### PR TITLE
Pr x2177 disable all uart dma

### PR DESCRIPTION
**Pull request by taileron**
**Describe problem solved by this pull request**
that´s still the only way to get auto flash of the IO gps and stable wifi log download working
**Describe your solution**
all u(s)arts only work correct as soon as dma is off

**Describe possible alternatives**
I have not yet been able to identify any other error in the board settings that could affect all UARTS at the same time.

### CODE REVIEW

**Comment by taileron** [comment]
a more recent AP bootloader solved it - now all rx and tx dma work on all u(s)arts

**Comment by dagar** [comment]
> a more recent AP bootloader solved it - now all rx and tx dma work on all u(s)arts

That's really bizarre, any idea what changed?

**Comment by taileron** [comment]
was not able to figure out what had changed but it was the opposite way the most recent one causes the fault.
That without fault is from october 2020 .... https://firmware.ardupilot.org/Tools/Bootloaders/

**Comment by dagar** [comment]
> was not able to figure out what had changed but it was the opposite way the most recent one causes the fault. That without fault is from october 2020 .... https://firmware.ardupilot.org/Tools/Bootloaders/

I'd be interested to know if the most recent bootloader combined with https://github.com/PX4/PX4-Autopilot/pull/18768 works. Otherwise I'll need to dig into it so that people buying new boars from mRo are directly flashable.

**Pull request closed without merging**
