### PR TITLE
ekf2-gnss-yaw: require "RTK fixed" fix type

### PR DESCRIPTION
**Pull request by bresch**
### Solved Problem
GNSS yaw data is really poor when the receiver is in "float" mode as the receiver is still converging.

We can see in the plot below that the vehicle isn't moving (integral of raw gyro is almost constant) and that the GNSS heading is moving while `fix_type < fixed`
gnss_yaw_fix_type

### Solution
Only use GNSS yaw data after convergence, when the receiver switches to "fix" mode.

### Test coverage
added unit test

### CODE REVIEW

**Comment by dagar** [comment]
This is likely the better thing to do when using dual ZED F9Ps and moving base, but is it correct for other units that can have dual antennas?

 - https://github.com/PX4/PX4-GPSDrivers/blob/261480cb78a3ba60cdda2dcc95b874ebc2c9312c/src/ashtech.cpp#L278-L302
 - https://github.com/PX4/PX4-GPSDrivers/blob/261480cb78a3ba60cdda2dcc95b874ebc2c9312c/src/unicore.cpp#L123-L160

@julianoes @vincentpoont2 do you know anything about heading requirements on the Unicore modules?

**Comment by julianoes** [comment]
I had used the Unicore heading without RTK, so I wouldn't think that's a requirement there.

**Comment by dagar** [comment]
> I had used the Unicore heading without RTK, so I wouldn't think that's a requirement there.

I suppose making it an optional requirement (EKF2 param) would be one way to handle it for now. Bigger picture it seems like inevitably we need to start capturing more of this as a function of sensor model. 

@bresch thoughts? 

A different approach that bypasses this problem (and that's way more work) could be to separately support "GNSS yaw" and GNSS relative position (what we actually get from dual ZED F9Ps). https://github.com/PX4/PX4-Autopilot/blob/main/msg/SensorGnssRelative.msg

**Comment by bresch** [comment]
I think I'll have to check with a more recent firmware because that log doesn't have the heading_accuracy field

**Comment by AlexKlimaj** [comment]
Also, I believe the GPS driver already only publishes a heading if the fix type is FIXED.

**Comment by ShiauweiZhao** [comment]
> This is likely the better thing to do when using dual ZED F9Ps and moving base, but is it correct for other units that can have dual antennas?
> 
> * https://github.com/PX4/PX4-GPSDrivers/blob/261480cb78a3ba60cdda2dcc95b874ebc2c9312c/src/ashtech.cpp#L278-L302
> * https://github.com/PX4/PX4-GPSDrivers/blob/261480cb78a3ba60cdda2dcc95b874ebc2c9312c/src/unicore.cpp#L123-L160
> 
> @julianoes @vincentpoont2 do you know anything about heading requirements on the Unicore modules?

I have UM982, and the dual antenna heading is still available in 3D fix mode

**Comment by bresch** [comment]
> I have UM982, and the dual antenna heading is still available in 3D fix mode

And does it report a heading accuracy too? Is the heading actually usable when in 3D fix mode?

**Pull request closed without merging**
