### PR TITLE
[DO NOT MERGE] testing nuttx sdmmc/sdio remove redundant GPIO config revert

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by davids5** [comment]
@dagar 
2 commits added px4-nuttx/pr-nuttx_sd_testing
you will need to repoint PX4 after your rebase

**Comment by davids5** [comment]
I just tested sd_stress locally with the error messages in - it fails with none of them firing. 

```
nsh> sd_stress
mkdir /fs/microsd/stress failed, ret: -1, errno: 17 -> File exists
iteration 0 took 003780 us: FAIL
```
 I forced the errors and proved they fire:
 ```

sd_stress
WARN  [ekf2] primary EKF changed 0 (timeout) -> 2
WARN  [ekf2] primary EKF changed 2 (timeout) -> 0
WARN  [ekf2] primary EKF changed 0 (timeout) -> 2
ERROR: mmcsd_get_r1 failed: 1
MMCSD ERROR mmcsd_removed!!!WARN  [ekf2] primary EKF changed 2 (timeout) -> 0
open /fs/microsd/stress/tmp000 failed, errno: 20 -> Not a directory
iteration 0 took 426842 us: FAIL

```
and 
```
sd_stress
ERROR: wkupevent has ERROR: 20
mkdir /fs/microsd/stress failed, ret: -1, errno: 5 -> I/O error
iteration 0 took 073360 us: FAIL
```

**Comment by davids5** [comment]
@dagar - This has new nuttx code I would like to test. The fix is deferring the dcache invalidate until after the DMA completion

**Comment by dagar** [comment]
Continued in https://github.com/PX4/PX4-Autopilot/pull/18687.

**Pull request closed without merging**
