### PR TITLE
posix shutdown investigation/hacks [take 2]

### PR DESCRIPTION
**Pull request by julianoes**
This PR is on top of #11525.

For me Ctrl+C and `shutdown` work on both Linux and Windows. Please cross-test and review.

I tried to get rid of all `pthread_cancel` so that one workaround in the lockstep scheduler can removed:
https://github.com/PX4/Firmware/blob/2ebb9d2ab52bce56a74d34d3b36c7130422577c2/platforms/posix/src/lockstep_scheduler/include/lockstep_scheduler/lockstep_scheduler.h#L24-L34

### CODE REVIEW

**Comment by julianoes** [comment]
@dagar I don't understand the path for this `dyn` test. It now works locally but still seems to fail for appveyor! :disappointed:

**Comment by MaEtUgR** [comment]
Nice, thanks @julianoes! and @dagar for starting out 👍
- The shutdown command now works again on Windows.
- Just wanted to mention it prints two times `Shutting down`:
```
pxh> shutdown
Shutting down
pxh> Shutting down

$
```
which is no problem at all.

- Note that Ctrl+C still hangs on Windows and waits for an enter before exiting with the SIGINT callback attached
https://github.com/PX4/Firmware/blob/b54ca67de9b5900c7ed11bef323c7b4e5a0339b6/platforms/posix/src/main.cpp#L410-L416

So we cannot get rid of that one yet.

**Comment by julianoes** [comment]
@MaEtUgR hm, so why did Ctrl+C work for me on Windows (Cygwin)?

**Comment by MaEtUgR** [comment]
> @MaEtUgR hm, so why did Ctrl+C work for me on Windows (Cygwin)?

Ctrl+C still works because of the lines I added in https://github.com/PX4/Firmware/pull/11305 and referenced above. This pr is fine but just does not yet allow to remove the hotfix.

**Comment by MaEtUgR** [comment]
We should have got this in before it had that many conflicts... @julianoes any plans to rebase (without any pressure)?

**Comment by julianoes** [comment]
@MaEtUgR yes we should get this in :smile: but it's far down my list.

**Comment by julianoes** [comment]
Impossible to rebase, closing.

**Pull request closed without merging**
