### PR TITLE
VTOL: direct MC throttle control during transition in not-altitude controlled modes

### PR DESCRIPTION
**Pull request by sfuhrer**
Potential replace for https://github.com/PX4/PX4-Autopilot/pull/16091.

@xdwgood @RicardoM17 fyi.

### CODE REVIEW

**Comment by sfuhrer** [comment]
> Sounds good to me @sfuhrer . Any idea what could be causing the spike? It seems that the FW setpoint isn't being updated during the transition and so it starts from zero or something like that. I'll try to look at the code and see if I can find something but if you already have any ideas that could be the reason it would make it easier.

No, no other ideas, yours or something similar sounds likely. If you don't find it let me know!

**Review by RicardoM17 — APPROVED** [review]
> > Sounds good to me @sfuhrer . Any idea what could be causing the spike? It seems that the FW setpoint isn't being updated during the transition and so it starts from zero or something like that. I'll try to look at the code and see if I can find something but if you already have any ideas that could be the reason it would make it easier.
> 
> No, no other ideas, yours or something similar sounds likely. If you don't find it let me know!

No worries @sfuhrer. I don't know if I will have the bandwidth to look at this, this week so I propose that we go ahead and merge this and I'll create the issue for the transition problem so we can at least keep it tracked and work on that when we do have the time.

This is also so that I can cherry-pick this PR into our repo and move from there :)

Let me know if that's ok, and also you @xdwgood .

**Comment by xdwgood** [comment]
@RicardoM17  I didn't encounter that spike problem in my flight test.So sorry, I did not continue to study it.I support the merging of this pr, but I don’t have time to see if the changes in standard vtol and tiltrotor vtol are correct. 

but......@sfuhrer is an expert, he will merge it at the right time :smiley:

**Comment by RicardoM17** [comment]
I haven't had time to have a look at this but I wonder if it has something to do with the (lack of) airspeed sensor.

**Comment by xdwgood** [comment]
Don't forget this

**Comment by dagar** [comment]
Needs to be rebased to resolve a small conflict, but otherwise good to go.

**Comment by sfuhrer** [comment]
I would have given this a quick testflight before merging. Plan on doing so on Thursday.

**Comment by RicardoM17** [comment]
> I would have given this a quick testflight before merging. Plan on doing so on Thursday.

I did flight test it but yea, not on current master

**Review by xdwgood — DISMISSED** [review]

**Comment by sfuhrer** [comment]
>I did flight test it but yea, not on current master

I meant on tiltrotor and standard VTOL frames. But unfortunately didn't get to it till now.

**Comment by sfuhrer** [comment]
Finally got to flight testing it. 
Standard VTOL: https://review.px4.io/plot_app?log=f3f624f6-1a83-4c14-9dd2-a9c98c5af851
Tiltrotor: https://review.px4.io/plot_app?log=45bef3bf-5ab1-4889-b8ea-58d458740f6b
No issues noted, it feels intuitive to have MC throttle control during transition when flying in stabilized.

**Review by xdwgood — APPROVED** [review]

**Review by LorenzMeier — APPROVED** [review]

**Pull request merged**
