### PR TITLE
Add support for CubeOrange+ into PX4

### PR DESCRIPTION
**Pull request by bugobliterator**
This PR adds support for STM32H757 based CubePilot CubeOrange+.

Requires these PR to be merged before:
~https://github.com/PX4/NuttX/pull/195~
https://github.com/apache/nuttx/pull/8124
https://github.com/PX4/NuttX/pull/214

### CODE REVIEW

**Comment by dagar** [comment]
Is there any publically available pinout or schematic for reference?

**Comment by julianoes** [comment]
Nice! I gave this a test and for me there are only 2 accel/gyros available.

```
ms5611 #0 on SPI bus 4
ERROR [SPI_I2C] icm42688p: no instance started (no device on bus?)
icm20948 #0 on SPI bus 4 rotation 10
ms5611 #1 on SPI bus 1
icm20649 #0 on SPI bus 1
```

So it looks like `icm42688p` fails to start.

And I was not able to get the console to show up, even though I added
```
CONFIG_DEV_CONSOLE=y
CONFIG_UART7_SERIAL_CONSOLE=y
```

Has the UART changed?

**Comment by julianoes** [comment]
> Has the UART changed?

No, it's all fine. Just the pins on the top of the case are no longer to be used as console. Instead the debug connector at the bottom of the baseboard (inside the case) still work.

**Comment by dagar** [comment]
Converting to draft until the NuttX side is in.

**Comment by YairTevel** [comment]
Nice work. I tested it with version 1.12 and needed several modifications in order to be able to burn and use it properly using Qgroundcontorl. 
1. board.h - After using the PLL values from the pull request the software didn't load after reboot. I had to use the cubeOrange values.
2. init.c - I had to add this section: 
// clear all existing MPU configuration from bootloader
	for (int region = 0; region < CONFIG_ARM_MPU_NREGIONS; region++) {
		putreg32(region, MPU_RNR);
@@ -129,6 +130,7 @@ __EXPORT void stm32_boardinitialize(void)
		// save
		putreg32(0, MPU_CTRL);
	}
	to stm32_boardinitialize function
3.   board_config.h - I had to add the next line: #define BOARD_HAS_PWM  DIRECT_PWM_OUTPUT_CHANNELS
4. rc.board_defaults - remove arch_io_pins

**Comment by davids5** [comment]
> Nice work. I tested it with version 1.12 and needed several modifications in order to be able to burn and use it properly using Qgroundcontorl.
> 
> 1. board.h - After using the PLL values from the pull request the software didn't load after reboot. I had to use the cubeOrange values.
> 2. init.c - I had to add this section:
>    // clear all existing MPU configuration from bootloader
>    for (int region = 0; region < CONFIG_ARM_MPU_NREGIONS; region++) {
>    putreg32(region, MPU_RNR);
>    @@ -129,6 +130,7 @@ __EXPORT void stm32_boardinitialize(void)
>    // save
>    putreg32(0, MPU_CTRL);
>    }
>    to stm32_boardinitialize function
> 3. board_config.h - I had to add the next line: #define BOARD_HAS_PWM  DIRECT_PWM_OUTPUT_CHANNELS
> 4. rc.board_defaults - remove arch_io_pins

Is this a matter of setting CONFIG_ARM_MPU_EARLY_RESET in the defconfig?

**Comment by YairTevel** [comment]
> > Nice work. I tested it with version 1.12 and needed several modifications in order to be able to burn and use it properly using Qgroundcontorl.
> > 
> > 1. board.h - After using the PLL values from the pull request the software didn't load after reboot. I had to use the cubeOrange values.
> > 2. init.c - I had to add this section:
> >    // clear all existing MPU configuration from bootloader
> >    for (int region = 0; region < CONFIG_ARM_MPU_NREGIONS; region++) {
> >    putreg32(region, MPU_RNR);
> >    @@ -129,6 +130,7 @@ __EXPORT void stm32_boardinitialize(void)
> >    // save
> >    putreg32(0, MPU_CTRL);
> >    }
> >    to stm32_boardinitialize function
> > 3. board_config.h - I had to add the next line: #define BOARD_HAS_PWM  DIRECT_PWM_OUTPUT_CHANNELS
> > 4. rc.board_defaults - remove arch_io_pins
> 
> Is this a matter of setting CONFIG_ARM_MPU_EARLY_RESET in the defconfig?

I don't really know, I'm open for suggestions. I'm planning to fly with the version tomorrow, but I don't know if it wiil be an optimal configuration. Do you think that setting the CONFIG_ARM_MPU_EARLY_RESET to another value will solve the problem?

**Comment by davids5** [comment]
@julianoes  Please https://github.com/PX4/NuttX/pull/214 merged. Please repoint this PR.

**Review by dagar — APPROVED** [review]

**Comment by junwoo091400** [comment]
> 

That's a qgc board I'd mismatch problem. Was this board not added in QGC?

**Comment by julianoes** [comment]
Orange+ is not released in a stable release yet. You need to build from source to get latest main, or wait just a little bit longer until we release v1.14.

**Comment by gitsr-sys** [comment]
@julianoes Thank for the explanation.
Regarding building from source, I git cloned PX4-Autopilot. Then which command should I use to build?
For example, `make px4_fmu-v5_default`
Instead of `px4-fmu-v5_default`, I am not sure what I should run for **Cube Orange+**.
Any advice is welcome!

**Pull request merged**
