### PR TITLE
Add Gazebo plane HITL setup

### PR DESCRIPTION
**Pull request by julianoes**
This allows to fly fixedwing in Gazebo HITL. However, the rudder doesn't seem hooked up correctly and this likely breaks X-Plane HITL because the throttle channel is changed in the mavlink module.

The right fix is probably to change the actuator ordering/mixing on the Gazebo side.

Related to #13595.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I think you should definitely fix it in Gazebo and adjust the mixer such that it works for existing QGC-based simulations.

**Comment by lee-shun** [comment]
Hello, have you finished the  Gazebo fixed_wing plane HITL setup? if you have, I want to learn about that cause I encountered the same questions these days. Thank you so much, here is my email: 2015097272@qq.com

**Comment by hamishwillee** [comment]
@julianoes This is obviously of interest. Any chance you might have time to work on it in the coming 3 months?

**Comment by julianoes** [comment]
I'm sure this has all changed too much in the meantime and I'd have to start over anyway. Therefore, closing this.

**Pull request closed without merging**
