### PR TITLE
boards: Add THE Peach K1/R1 code

### PR DESCRIPTION
**Pull request by ThePeach-kr**
Hi,

We developed a Flight Controller.
I would like to add our K1/R1 Flight Controller code to the PX4-Autopilot.

Docs: https://github.com/PX4/PX4-user_guide/pull/2034
Bootloader: https://github.com/PX4/PX4-Bootloader/pull/219

Thanks

### CODE REVIEW

**Comment by dagar** [comment]
The bootloader bin naming needs to be `${PX4_BOARD_VENDOR}_${PX4_BOARD_MODEL}_bootloader.bin` if you want the `SYS_BL_UPDATE` param and other command line helpers in the build system to automatically work.

**Comment by ThePeach-kr** [comment]
I modified it
Thanks !

**Review by dagar — APPROVED** [review]

**Comment by ThePeach-kr** [comment]
I mean, How long will it take to merge not only qgc, but also PX4-Autopilot and bootloader so that they can be used by users?
Is there anything else I need to do to merge?
Thanks

**Comment by ThePeach-kr** [comment]
> > I modified it !
> > Is there any additional process to register our board? I wonder how long it takes to register
> > Thanks.
> 
> Do you mean in QGC? At the moment flashing through QGC still needs to be added manually.

I mean, How long will it take to merge not only qgc, but also PX4-Autopilot and bootloader so that they can be used by users?
Is there anything else I need to do to merge?
Thanks

**Comment by ThePeach-kr** [comment]
@dagar 

Is there anything else to do merge or are you not able to merge?

**Comment by hamishwillee** [comment]
@dagar Can this merge?

**Comment by dagar** [comment]
The diff shows no change?

**Comment by ThePeach-kr** [comment]
> The diff shows no change?

Sorry, I created a new PR.
https://github.com/PX4/PX4-Autopilot/pull/20664

**Pull request closed without merging**
