### PR TITLE
init.d-posix: make all simulation airframes simulator specific

### PR DESCRIPTION
**Pull request by dagar**
- all posix simulation airframes are now specific to a simulator and model and now named `${SIMULATOR}_${MODEL}`
 - added cmake warnings for all SITL target helpers that the relevant airframe exists (this caught a few leftovers)
 - jmavsim launched directly from px4 binary now (you can debug directly, etc)

``` Console
ROMFS/px4fmu_common/init.d-posix/airframes/
├── 10016_gazebo_iris
├── 10017_jmavsim_iris
├── 10018_gazebo_iris_foggy_lidar
├── 10019_gazebo_omnicopter
├── 10030_gazebo_px4vision
├── 10040_sihsim_quadx
├── 10041_sihsim_airplane
├── 10042_sihsim_xvert
├── 1010_gazebo_iris_opt_flow
├── 1010_gazebo_iris_opt_flow.post
├── 1011_gazebo_iris_irlock
├── 1012_gazebo_iris_rplidar
├── 1013_gazebo_iris_vision
├── 1013_gazebo_iris_vision.post
├── 1015_gazebo_iris_obs_avoid
├── 1015_gazebo_iris_obs_avoid.post
├── 1017_gazebo_iris_opt_flow_mockup
├── 1019_gazebo_iris_dual_gps
├── 1021_gazebo_uuv_hippocampus
├── 1022_gazebo_uuv_bluerov2_heavy
├── 1030_gazebo_plane
├── 1031_gazebo_plane_cam
├── 1032_gazebo_plane_catapult
├── 1033_jsbsim_rascal
├── 1034_flightgear_rascal-electric
├── 1035_gazebo_techpod
├── 1036_jsbsim_malolo
├── 1037_gazebo_believer
├── 1038_gazebo_glider
├── 1039_flightgear_rascal
├── 1040_gazebo_standard_vtol
├── 1041_gazebo_tailsitter
├── 1042_gazebo_tiltrotor
├── 1043_gazebo_standard_vtol_drop
├── 1044_gazebo_plane_lidar
├── 1060_gazebo_rover
├── 1061_gazebo_r1_rover
├── 1062_flightgear_tf-r1
├── 1070_gazebo_boat
├── 17001_flightgear_tf-g1
├── 17002_flightgear_tf-g2
├── 2507_gazebo_cloudship
├── 3010_jsbsim_quadrotor_x
├── 3011_jsbsim_hexarotor_x
├── 4001_ign_x500
├── 6001_ign_x4
├── 6011_gazebo_typhoon_h480
├── 6011_gazebo_typhoon_h480.post
└── CMakeLists.txt

0 directories, 49 files
```

We should probably do another pass later to try and sort these and commit to a numbering scheme.

### CODE REVIEW

**Review by Jaeyoung-Lim — DISMISSED** [review]
Awesome! Thanks!

**Comment by Jaeyoung-Lim** [comment]
> We should probably do another pass later to try and sort these and commit to a numbering scheme.

@dagar Does this mean that we can have duplicate numbers as long as they don't coincide within each simulation?

**Comment by dagar** [comment]
> > We should probably do another pass later to try and sort these and commit to a numbering scheme.
> 
> @dagar Does this mean that we can have duplicate numbers as long as they don't coincide within each simulation?

I'm not sure what you mean, but let's discuss later. I'd like to get the multi-vehicle sim settled for new Gazebo in the near future.

**Comment by dagar** [comment]
Continued in https://github.com/PX4/PX4-Autopilot/pull/20867.

**Pull request closed without merging**
