### PR TITLE
Prevent spam warnings from adsb traffic conflicts

### PR DESCRIPTION
**Pull request by akkawimo**
**Problem**
- Multiple conflicts breaks down the current buffering logic and leads to spamming of conflict msgs

**How this PR solves the problem**

- The time needed to traverse the 3d distance between the uav and incoming traffic at their relative speed is now also checked against a collision time threshold.
- check traffic is refactored for clarification and it's deprecated code has been removed.
- The conflict detection and buffering logic are now moved into lib/adsb for unit testing.
- unit tests are created based on traffic with a random heading, position, speed etc. which is generated using a helper script in lib/adsb
- conflicts are now buffered up to 10 aircraft. While in the buffer, warnings are sent out at 1 hz. Once a msg from the same traffic shows that it is no longer in conflict, it is removed from the buffer, and the PIC is notified that it is no longer in conflict.
- When the buffer is full, a px4_warn msg will be logged and the msgs will start to spam.
- There are now two parameters that can independently set the thresholds for the horizontal cross-track separation and the vertical separation and a new parameter for the collision time threshold.  

Cross track distance is sin(theta)

image

### CODE REVIEW

**Comment by junwoo091400** [comment]
Cool feature! Could you fix the title "Upstream/tone down traffic warnings" to more intuitive one? Right now with this title I wasn't sure what this PR was actually about

**Comment by akkawimo** [comment]
> Cool feature! Could you fix the title "Upstream/tone down traffic warnings" to more intuitive one? Right now with this title I wasn't sure what this PR was actually about

Better?

**Comment by bkueng** [comment]
CI failure: https://github.com/PX4/PX4-Autopilot/actions/runs/4406381219/jobs/7718552393

**Comment by akkawimo** [comment]
@bkueng I think I fixed the make tests error by adding adsb to cmakelists of navigator 
are the other target fails related to this pr?

**Review by bkueng — APPROVED** [review]
Flash usage got reduced on main. Let's get this in then.

**Comment by hamishwillee** [comment]
@akkawimo @bkueng 
- Is this going into PX4 v1.14?
- Can you provide a PR for the docs impact?

 I ask because it deletes a few parameters that appear in docs: NAV_TRAFF_A_RADM, NAV_TRAFF_A_RADU
http://docs.px4.io/main/en/advanced_features/traffic_avoidance_adsb.html#configure-traffic-avoidance
http://docs.px4.io/main/en/advanced_features/traffic_avoidance_utm.html#configure-traffic-avoidance

@bkueng FYI we're getting that challenging point where mainline and px4 v1.14 docs have to split.

**Comment by bkueng** [comment]
> Is this going into PX4 v1.14?

Yes

> Can you provide a PR for the docs impact?

@akkawimo ?

> @bkueng FYI we're getting that challenging point where mainline and px4 v1.14 docs have to split.

Yes, we did not branch out on the px4 side yet.

**Comment by hamishwillee** [comment]
Cool. But we still need docs ....

**Comment by junwoo091400** [comment]
> I ask because it deletes a few parameters that appear in docs: NAV_TRAFF_A_RADM, NAV_TRAFF_A_RADU
> http://docs.px4.io/main/en/advanced_features/traffic_avoidance_adsb.html#configure-traffic-avoidance
> http://docs.px4.io/main/en/advanced_features/traffic_avoidance_utm.html#configure-traffic-avoidance

@akkawimo could you check on removing these parameters from the docs?

**Comment by akkawimo** [comment]
@junwoo091400 @hamishwillee opened pr for docs

**Pull request merged**
