### PR TITLE
Add vendor version exstension

### PR DESCRIPTION
**Pull request by dgeorge83616**
**Describe problem solved by this pull request**
The version script was rejecting correctly formatted tag constructed with PX4 version and derivative vendor, or forked, version. 

**Describe your solution**
Simple fix to allow vendor version, if present in tag, as documented in the error message of the [validate block](https://github.com/PX4/PX4-Autopilot/blob/f65781025ebb776fb5c406d96fbbfa52360f8a30/src/lib/version/px_update_git_header.py#L74).

**Describe possible alternatives**
Perhaps someone decided to replace, rather than append, and in that case the desired fix would be to the change the error text, instead.

**Test data / coverage**
Verified correct version string in absence of extended tag:
```
dan@ubuntu:~/projects/aidev$ make px4_sitl
-- PX4 version: v1.11.0-rc3-2081-gd2f9736a24
```

Verified extended form:
```
dan@ubuntu:~/projects/aidev$ git tag v1.11.0-rc3-1.0.0-dev
dan@ubuntu:~/projects/aidev$ make clean
dan@ubuntu:~/projects/aidev$ make px4_sitl
-- PX4 version: v1.11.0-rc3-1.0.0-dev
```

**Additional context**
Seemed appropriate to retain the PX4 version for sake of acknowledgement.

### CODE REVIEW

**Comment by dgeorge83616** [comment]
Looks like the only place vendor version is accessed is in a [test](https://github.com/PX4/PX4-Autopilot/blob/f65781025ebb776fb5c406d96fbbfa52360f8a30/src/systemcmds/tests/test_versioning.cpp#L162-L163) that basically verifies that it doesn't work...
If I get to it, I'll fix the parsing and add to log and also `ver` system command.

**Comment by dgeorge83616** [comment]
These changes didn't go far enough. For example, v1.12.0-0.0.4 fails validation. Even with the example from the description, above, the custom version doesn't show up in the `ver all` command, nor is it displayed correctly in QGC Vehicle Setup Summary. The `dev` suffix does show, but at the end of the Firmware Version field, not in the Custom Fw. Ver. field.

**Comment by ryanjAA** [comment]
@dgeorge83616 do you have a fix for this working?

**Comment by danduril** [comment]
@ryanjAA, I might end up adding support for <PX4 version>-<custom version>, as documented in the comments, but not high priority, ATM. The issue came up in our fork and I realized this PR was inadequate. For our purposes, we'll more likely add our custom component version string as is done for NuttX, ECL, and MAVLink.

I would not mind fixing it up on my own, and submitting another PR, but doesn't look as if anyone else in the community particularly cares.

**Pull request closed without merging**
