### PR TITLE
uXRCE-DDS Client: Expose custom participant and localhost-only flags

### PR DESCRIPTION
**Pull request by DanMesh**
### Solved Problem

The `uxrce_dds_client` can be started with flags to enable using a custom participant (`-c`) or localhost-only on the agent side (`-l`), but these were only available when starting the client by hand in the console.

### Solution

Remove the CLI flags and instead a parameter for selecting the participant configuration, `UXRCE_DDS_PTCFG`.

This allows for selecting either the custom participant or localhost-only configuration, or neither (the default).

#### To Do
- [ ] Update docs: https://github.com/PX4/PX4-user_guide/blob/main/en/middleware/uxrce_dds.md

#### Additionally

- Improve other parameter descriptions for the `uxrce_dds_client`.
- Improve formatting of `uxrce_dds_client status`. For example:
```bash
INFO  [uxrce_dds_client] Running, connected
INFO  [uxrce_dds_client] Using transport:    udp
INFO  [uxrce_dds_client] Agent IP:           192.168.0.5
INFO  [uxrce_dds_client] Agent port:         8888
INFO  [uxrce_dds_client] Custom participant: no
INFO  [uxrce_dds_client] Localhost only:     yes
INFO  [uxrce_dds_client] Payload tx:         47811 B/s
INFO  [uxrce_dds_client] Payload rx:         0 B/s
```

### Changelog Entry
For release notes:
```
uXRCE-DDS Client: expose custom participant and localhost-only flags as parameters
New parameters: UXRCE_DDS_PTCFG
```

### Test coverage
- Tested on n FMU v5x. Enabled the parameter in various combinations to verify the behaviour.

### CODE REVIEW

**Review by dagar — APPROVED** [review]
Having these as both command line arguments and parameters seems like more trouble than it's worth, but otherwise looks good.

**Review by bkueng — COMMENTED** [review]
At this point you could remove the CLI flags and make the param tri-state.

Can you also set it as default for v5x and v6x skynode?
In this file: https://github.com/PX4/PX4-Autopilot/blob/main/boards/px4/fmu-v5x/init/rc.board_defaults
Skynode detection: https://github.com/PX4/PX4-Autopilot/blob/main/boards/px4/fmu-v5x/init/rc.board_sensors#L52

**Comment by beniaminopozzan** [comment]
On the other hand, as the CLI is already there, what about using the same approach of the mavlink module?
https://github.com/PX4/PX4-Autopilot/blob/be56f74c1d0a03809fa370804f6dc114a4e4223b/src/modules/mavlink/module.yaml#L5-L35

I mean, tri state param, and the CLI flags are set in the command part of `UXRCE_DDS_CFG`

@bkueng , do you want v5x and v6x skynode to use `-l` or `-c`?

**Comment by DanMesh** [comment]
@beniaminopozzan Keeping the CLI and using it in the `command` section as you suggest is a nice idea. That way one can still stop and start the client from the console for testing, which is faster than always changing parameters and restarting.

For the defaults, I think we'd keep it that neither `-l` nor `-c` is used, as it is now.

**Comment by DanMesh** [comment]
On further thought, having both the CLI flags and a parameter for these configurations seems somewhat unnecessary.
It means there could be two "sources of truth" for what the user intends to use, and could make the setup unpredictable for someone not familiar with the way we choose between the CLI and params.

So: I have now removed the CLI flags and only have the single tri-state "participant configuration" parameter, `UXRCE_DDS_PTCFG`.

**Comment by bkueng** [comment]
Looks good, can you still add the skynode defaults?

**Review by bkueng — APPROVED** [review]

**Pull request merged**
