### PR TITLE
Close BDMA

### PR DESCRIPTION
**Pull request by CUAVcaijie**
After BDMA is turned on, spi6 uses BDMA to enter hardware interrupt

### CODE REVIEW

**Comment by davids5** [comment]
@CUAVcaijie What is the issue? Would you please describe it in detail and how to reproduce it,.

**Comment by CUAVcaijie** [comment]
reproduce：
    Burning master firmware directly
phenomenon：
    After all sensors are initialized, the system crashes
@davids5

**Comment by CUAVcaijie** [comment]
> I'll take a look, I'd like to see if we can fix BDMA rather than simply disable it. The cpu usage of the IMU drivers is enormous without it (9 kHz raw data from the ICM20649).

Yes, can enter the interrupt of BMDA, but I don't know where it died

**Comment by dagar** [comment]
Sorry, haven't had time to debug this. Let's merge for now and revert later once it's fixed.

**Review by dagar — APPROVED** [review]

**Pull request merged**
