### PR TITLE
rc/dsm: remove system field check, add new validity checks

### PR DESCRIPTION
**Pull request by dagar**
Here's a quick DSM parser fix take 2.

 - unfortunately we can't depend on the system field due to potential external binding and non-genuine Spektrum equipment
 - reject any DSM frame with duplicate channels
 - add 16 channel mask
 - tighten valid PWM range 990-2010us (±100% travel is 1102-1898µs)
 - update RCTest rejected frame count and 2nd data set which actually has 16 valid channels

Checking the DSM system field was added in https://github.com/PX4/PX4-Autopilot/pull/15430 when @mcsauder discovered sporadic invalid RC data with a Spektrum quad race serial receiver (visible once the filtering was removed). We should verify that this change accomplish the same improvement without the problematic system field dependency.

### CODE REVIEW

**Comment by dagar** [comment]
I'll give this a test on real hardware next year.

**Comment by mcsauder** [comment]
> I'll give this a test on real hardware next year.

I will too! ;) asap

**Comment by LorenzMeier** [comment]
I've reverted the changes from fall last year and it is now back to working. That baseline state is now here (still WIP): https://github.com/PX4/PX4-Autopilot/pull/16469

I'm going to test this one now.

**Comment by LorenzMeier** [comment]
This now works fine on hardware

**Review by LorenzMeier — APPROVED** [review]

**Comment by mcsauder** [comment]
Hardware tested with a spektrum DX8 G2 and multiple spektrum satellite serial receivers. Nice work @LorenzMeier !

**Comment by ilNonn0** [comment]
It works with my hardware: transmitter spektrum DX8G2, remote satellite SPM9645 and DSMX 22ms as binding protocol.

**Pull request merged**
