### PR TITLE
Auxiliary flight control actuator handling rework

### PR DESCRIPTION
**Pull request by sfuhrer**
[description WIP]
### Solved Problem
- split up controller further, e.g. enables us to easily replace fixed-wing rate controller with alternative controller (related: https://github.com/PX4/PX4-Autopilot/pull/20237)
- cleanly handle automatic landing_gear/flaps/spoiler setpoints vs. manually triggered gear/spoiler/flaps
- enable flaperons (deflect ailerons down to act as flaps) and spoilerons (deflect ailerons up to act as spoilers) with control allocation (Fixes https://github.com/PX4/PX4-Autopilot/issues/20694)
- 

### Solution
- add new module "Auxiliary actuator controller" that controls landing gear, flaps, spoilers, landing gear wheel. Not intended for payload control
- input into this module are "auto" setpoints and "manual" setpoints, which then are listened to depending on the flight mode and recency
- output are dedicated topics that are sent to the control allocation: 
```
landing_gear_setpoint.msg
flaps_setpoint.msg
spoilers_setpoint.msg
landing_gear_wheel_setpoint.msg
```
- remove legacy indexes in actuator_controls 
- use dedicated topic `tiltrotor_extra_controls` to pass collective thrust and tilt from controller to allocation.
image

image

[Link to video benchtesting flaps/spoilers](https://discord.com/channels/1022170275984457759/1022186266957201480/1050083696075620443)

 TODOs:
 
- [ ] get feedback for architecture (e.g. single module or separate ones for flaps, spoilers, landing_gear, landing_gear_wheel) 
- [ ] get feedback for new topic names
- [ ] get feedback for how to link flaps/spoilers with actuators in the allocation
- [ ] port wheel controller also to auxiliary actuator controller
- [ ] rename parameters that are now in the AAC
- [ ] enable flaps and spoilers both for dedicated actuators where the flaps should move it from -1..1 to have full range, and also on ailerons where flaps should only move it from 0..1
- [ ] airbrakes, do we want to enable it, do we need it?
- [ ] remove FW_DTRIM_R_FLPS and FW_DTRIM_P_SPOIL as that functionality now lives in the allocator
- [ ] update control surfaces saturation handling to take into account the flaps/spoiler configuration on the control surfaces
- [ ] remove actuator_controls completely (currently still needed between the rate controllers and the vtol module, at least for tiltrotor that needs collective thrust)
- [ ] add option (via param?) to block landing gear from being retracted when on the ground
- [ ] check VTOL landing gear logic -> should the vtol module publish landing_gear_auto_setpoint?
- [ ] add VTOL flaps/spoiler logic

### CODE REVIEW

**Comment by ryanjAA** [comment]
Thanks @sfuhrer - this is great!!

Changes aside that you want to make above, is this good to test fly?

**Comment by ryanjAA** [comment]
Bench tested as well - works as intended on first few passes. Thanks! Going to compare against commanded µs in with mixer to ensure the same but looks good so far!


(Later date probably want a slew param on just the deployment of spoilers since the flap time can be chosen but it is not in unison with the spoilers)

**Comment by sfuhrer** [comment]
> (Later date probably want a slew param on just the deployment of spoilers since the flap time can be chosen but it is not in unison with the spoilers)

It's currently hard coded to be 1s from min to max (kSpoilerSlewRate). Plus on dedicated spoilers you could set the actuator slew rate.

**Comment by sfuhrer** [comment]
> Thanks @sfuhrer - this is great!!
> 
> Changes aside that you want to make above, is this good to test fly?

I bench tested further and didn't run into any issues. I guess it's safe to fly, unless somebody spots something off in this log: https://review.px4.io/plot_app?log=35380007-1f75-4e04-933b-982882deb774

**Comment by sfuhrer** [comment]
> Testing this today. FYI

If you haven't already flashed and bench tested it, could you instead go for testing https://github.com/PX4/PX4-Autopilot/pull/20815? The behavior should be the same/very similar, and that one is more up to date and currently the more likely way we go forward.

**Comment by ryanjAA** [comment]
Will do new bench testing and then testing on https://github.com/PX4/PX4-Autopilot/pull/20815?. Thanks for pointing to that one.

**Comment by sfuhrer** [comment]
Closing this PR, https://github.com/PX4/PX4-Autopilot/pull/20815 replaces it.

**Pull request closed without merging**
