### PR TITLE
Battery: add average consumption parameters for multicopter and fixedwing 

### PR DESCRIPTION
**Pull request by sfuhrer**
This PR adds two new, vehicle-specific parameters: BAT_AVG_I_MC and BAT_AVG_I_FW. They are intended to reflect the average current needed for hover and fixed-wing flight, respectively. While with this PR they are not yet consumed anywhere, having them would allow:
- to calculate remaining flight time while in-air
- to calculate remaining flight distance --> could be used to make battery RTL "smarter" by returning early enough when far away
- to use at the planning stage, to indicate if a mission is feasible or not (plus for VTOL, it could be used to indicate if vehicle can reach home/land/safe points in hover mode from every location on the mission, after a quadchute for example)
- simulate battery drainage more precisely in SITL

For most applications these new params make only sense when you have an accurate current measurement on the vehicle and BAT_CAPACITY set. Or a smart battery that automatically gives you back remaining capacity.

### CODE REVIEW

**Comment by ThomasRigi** [comment]
Cool! These parameters will be useful for us for SITL flight route testing where we need a more accurate battery level estimation. 

I will create a PR with our SITL battery estimation improvements when this is merged

**Comment by ThomasRigi** [comment]
How are the chances that this will be merged soon? I need to have my battery simulations running by the end of next week and I would have preferred to start development on a clean master branch.

**Comment by sfuhrer** [comment]
@dagar what do you think? I know that it's not the perfect way to merge it before it's used anywhere in the PX4 flight stack, but it would unblock development on the simulation and mission planning part (even though we slightly abuse the PX4 params for these applications outside of the flight stack).
Any concrete flight stack application with these params (in RTL/battery estimation) is still very interesting in my opinion, but without having started the development of those we can't say for sure if we then really need those exact params.

**Review by moreba1 — APPROVED** [review]

**Comment by sfuhrer** [comment]
I'm gonna close this one. Let's resume discussion once https://github.com/PX4/PX4-Autopilot/pull/16399 is in (as this will be the first real consumer of these consumption/total flight time parameters).

**Pull request closed without merging**
