### PR TITLE
imxrt1170 bootloader

### PR DESCRIPTION
**Pull request by davids5**
Adds imxrt bootloader

N.B. This changes the load address of the application to 0x30020000. The bootloader load address is 0x30000000

FYI: @igalloway @dk7xe

### CODE REVIEW

**Comment by dk7xe** [comment]
nxp_fmurt1170-v1_bootloader has been successful build

**Comment by davids5** [comment]
@dk7xe you can only use the .px4 file in this PR.

**Comment by dk7xe** [comment]
flashed bootloader and PX4 from this PR
`SEGGER J-Link Commander V7.92k (Compiled Oct 18 2023 15:06:13)
DLL version V7.92k, compiled Oct 18 2023 15:04:26

Connecting to J-Link via USB...O.K.
Firmware: J-Link EDU Mini V1 compiled Jul 31 2023 12:03:29
Hardware version: V1.00
J-Link uptime (since boot): 0d 00h 11m 58s
S/N: 801006359
License(s): FlashBP, GDB
USB speed mode: Full speed (12 MBit/s)
VTref=3.299V


Type "connect" to establish a target connection, '?' for help
J-Link>connect
Please specify device / core. <Default>: MIMXRT1176XXXA_M7
Type '?' for selection dialog
Device>
Please specify target interface:
  J) JTAG (Default)
  S) SWD
  T) cJTAG
TIF>s
Specify target interface speed [kHz]. <Default>: 4000 kHz
Speed>1000
Device "MIMXRT1176XXXA_M7" selected.


Connecting to target via SWD
Found SW-DP with ID 0x6BA02477
DPIDR: 0x6BA02477
CoreSight SoC-400 or earlier
Scanning AP map to find all available APs
AP[3]: Stopped AP scan as end of AP map has been reached
AP[0]: AHB-AP (IDR: 0x84770001)
AP[1]: AHB-AP (IDR: 0x24770011)
AP[2]: APB-AP (IDR: 0x54770002)
Iterating through AP map to find AHB-AP to use
AP[0]: Core found
AP[0]: AHB-AP ROM base: 0xE00FD000
CPUID register: 0x411FC272. Implementer code: 0x41 (ARM)
Cache: L1 I/D-cache present
Found Cortex-M7 r1p2, Little endian.
FPUnit: 8 code (BP) slots and 0 literal slots
CoreSight components:
ROMTbl[0] @ E00FD000
[0][0]: E00FE000 CID B105100D PID 000BB4C8 ROM Table
ROMTbl[1] @ E00FE000
[1][0]: E00FF000 CID B105100D PID 000BB4C7 ROM Table
ROMTbl[2] @ E00FF000
[2][0]: E000E000 CID B105E00D PID 000BB00C SCS-M7
[2][1]: E0001000 CID B105E00D PID 000BB002 DWT
[2][2]: E0002000 CID B105E00D PID 000BB00E FPB-M7
[2][3]: E0000000 CID B105E00D PID 000BB001 ITM
[1][1]: E0041000 CID B105900D PID 001BB975 ETM-M7
[1][2]: E0042000 CID B105900D PID 004BB906 CTI
[0][1]: E0043000 CID B105900D PID 001BB908 CSTF
I-Cache L1: 32 KB, 512 Sets, 32 Bytes/Line, 2-Way
D-Cache L1: 32 KB, 256 Sets, 32 Bytes/Line, 4-Way
Memory zones:
  Zone: "Default" Description: Default access mode
Cortex-M7 identified.
J-Link>reset
Reset delay: 0 ms
Reset type NORMAL: Resets core & peripherals via SYSRESETREQ & VECTRESET bit.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via AIRCR.SYSRESETREQ.
Core did not halt after reset, halting it manually.
AfterResetTarget() start
Valid application detected. Setting PC / SP manually.
Booting from FlexSPI1.
  PC = 0x300023A9
  SP = 0x202447BC
Clean & invalidate cached CPU registers
AfterResetTarget() end - Took 62.4ms
J-Link>halt
PC = 300023A8, CycleCnt = 00000000
R0 = 40CAC0B0, R1 = 0A000000, R2 = 80000000, R3 = FFFFFFFF
R4 = E000ED00, R5 = 2024AEEC, R6 = 001632A3, R7 = 2024AEEC
R8 = 3C6A9559, R9 = 202447BC, R10= 0000C35A, R11= 30002000
R12= 2024AE80
SP(R13)= 202447BC, MSP= 202447BC, PSP= 00000000, R14(LR) = 002014B9
XPSR = 81000000: APSR = Nzcvq, EPSR = 01000000, IPSR = 000 (NoException)
CFBP = 00000000, CONTROL = 00, FAULTMASK = 00, BASEPRI = 00, PRIMASK = 00

FPS0 = 00000000, FPS1 = 00000000, FPS2 = 00000000, FPS3 = 00000000
FPS4 = 00000000, FPS5 = 00000000, FPS6 = 00000000, FPS7 = 00000000
FPS8 = 00000000, FPS9 = 00000000, FPS10= 00000000, FPS11= 00000000
FPS12= 00000000, FPS13= 00000000, FPS14= 00000000, FPS15= FFFFFFFF
FPS16= 00000000, FPS17= 00000000, FPS18= 00000000, FPS19= 00000000
FPS20= 00000000, FPS21= 00000000, FPS22= 00000000, FPS23= 00000000
FPS24= 00000000, FPS25= 00000000, FPS26= 00000000, FPS27= 00000000
FPS28= 00000000, FPS29= 00000000, FPS30= 00000000, FPS31= FFFFFFFF
FPSCR= 00000000
J-Link>loadbin C:\Temp\MR-FMURT7\20231020_fmurt7_bootloader\nxp_fmurt1170-v1_bootloader.bin 0x30000000
'loadbin': Performing implicit reset & halt of MCU.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via AIRCR.SYSRESETREQ.
Core did not halt after reset, halting it manually.
AfterResetTarget() start
Valid application detected. Setting PC / SP manually.
Booting from FlexSPI1.
  PC = 0x300023A9
  SP = 0x202447BC
Clean & invalidate cached CPU registers
AfterResetTarget() end - Took 63.0ms
Downloading file [C:\Temp\MR-FMURT7\20231020_fmurt7_bootloader\nxp_fmurt1170-v1_bootloader.bin]...
J-Link: Flash download: Bank 0 @ 0x30000000: Skipped. Contents already match
O.K.
J-Link>loadbin C:\Temp\MR-FMURT7\20231020_fmurt7_bootloader_wo_assortion\nxp_fmurt1170-v1_default.bin 0x30020000
'loadbin': Performing implicit reset & halt of MCU.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via AIRCR.SYSRESETREQ.
Core did not halt after reset, halting it manually.
AfterResetTarget() start
Valid application detected. Setting PC / SP manually.
Booting from FlexSPI1.
  PC = 0x300023A9
  SP = 0x202447BC
Clean & invalidate cached CPU registers
AfterResetTarget() end - Took 64.5ms
Downloading file [C:\Temp\MR-FMURT7\20231020_fmurt7_bootloader_wo_assortion\nxp_fmurt1170-v1_default.bin]...
J-Link: Flash download: Bank 0 @ 0x30000000: Skipped. Contents already match
O.K.
J-Link>reset
Reset delay: 0 ms
Reset type NORMAL: Resets core & peripherals via SYSRESETREQ & VECTRESET bit.
Reset: Halt core after reset via DEMCR.VC_CORERESET.
Reset: Reset device via AIRCR.SYSRESETREQ.
Core did not halt after reset, halting it manually.
AfterResetTarget() start
Valid application detected. Setting PC / SP manually.
Booting from FlexSPI1.
  PC = 0x300023A9
  SP = 0x202447BC
Clean & invalidate cached CPU registers
AfterResetTarget() end - Took 59.7ms
J-Link>go
Memory map 'after startup completion point' is active
J-Link>`

**Comment by dk7xe** [comment]
**bootup of FMU**

`B[boot] Rev 0x0 : Ver 0x0 RT1176V6X000000
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
reset done, 10 ms
Successfully bound SDHC to the MMC/SD driver
nsh: sysinit: fopen failed: No such file or directory
HW arch: NXP_FMURT1170_V1
HW type: RT1176V6X000000
HW version: 0x000
HW revision: 0x000
PX4 git-hash: 4b40e19e20a53350f8ede71c3393959b93f63fdb
PX4 version: 1.14.0 0 (17694720)
PX4 git-branch: pr-imxrt1170-imxrt1062-bootloader
OS: NuttX
OS version: Release 11.0.0 (184549631)
OS git-hash: 9592b4696fc251c738f360939c98a8[hardfault_log] Fault Log info File N                                                                                                                                                             o 4 Length 8205 flags:0x00 state:1
[hardfault_log] Fault Log is Armed
52b565c800
Build datetime: Oct 20 2023 10:12:02
Build uri: localhost
Build variant: default
Toolchain: GNU GCC, 9.3.1 20200408 (release)
PX4GUID: 00090000000000000000829297443224180e
MCU: i.MX RT1170 rB0, rev. 0
INFO  [param] selected parameter default file /fs/microsd/params
INFO  [param] importing from '/fs/microsd/params'
INFO  [parameters] BSON document size 723 bytes, decoded 723 bytes (INT32:16, FL                                                                                                                                                             OAT:18)
INFO  [param] selected parameter backup file /fs/microsd/parameters_backup.bson
Board architecture defaults: /etc/init.d/rc.board_arch_defaults
Board defaults: /etc/init.d/rc.board_defaults
ifup can0...OK
ifup can1...OK
ifup can2...OK
Loading airframe: /etc/init.d/airframes/4017_nxp_hovergames
INFO  [dataman] data manager file '/fs/microsd/dataman' size is 62600 bytes
INFO  [px4io] IO FW CRC match
Board sensors: /etc/init.d/rc.board_sensors
INFO  [ina226] Failed to init INA226 on bus 1, but will try again periodically.
ina226 #0 on I2C bus 1 (external) address 0x41
INFO  [ina226] Failed to init INA226 on bus 2, but will try again periodically.
ina226 #1 on I2C bus 2 (external) address 0x41
ERROR [SPI_I2C] icm42688p: no instance started (no device on bus?)
bmi088_accel #0 on SPI bus 3 rotation 4
bmi088_gyro #0 on SPI bus 3 rotation 4
icm42688p #0 on SPI bus 2 rotation 6
bmm150 #0 on I2C bus 3 address 0x10
WARN  [SPI_I2C] ist8310: no instance started (no device on bus?)
bmp388 #0 on I2C bus 3 address 0x77
bmp388 #1 on I2C bus 2 (external) address 0x76
nsh: icm20948_i2c_passthrough: command not found
nsh: ist8308: command not found
nsh: lis2mdl: command not found
nsh: lis3mdl: command not found
nsh: lis3mdl: command not found
nsh: qmc5883l: command not found
nsh: rm3100: command not found
nsh: ak09916: command not found
nsh: dshot: command not found
ekf2 [498:237]
Board mavlink: /etc/init.d/rc.board_mavlink
INFO  [mavlink] mode: OnboardLowBandwidth, data rate: 290000 B/s on /dev/ttyS5 @                                                                                                                                                              3000000B
Starting Main GPS on /dev/ttyS1
Starting Ultrawideband position sensor driver on /dev/ttyS3
Starting MAVLink on /dev/ttyS2
INFO  [mavlink] mode: Onboard, data rate: 2880 B/s on /dev/ttyS2 @ 57600B
Starting MAVLink on ethernet
INFO  [mavlink] mode: Normal, data rate: 100000 B/s on udp port 14550 remote por                                                                                                                                                             t 14550
Addons script: /fs/microsd/etc/extras.txt
WARN  [mavlink] no broadcasting address found
WARN  [health_and_arming_checks] Preflight Fail: Crash dumps present on SD, vehi                                                                                                                                                             cle needs service
WARN  [health_and_arming_checks] Preflight Fail: Crash dumps present on SD, vehi                                                                                                                                                             cle needs service
WARN  [uwb_sr150] UWB module is not responding.
INFO  [logger] logger started (mode=all)
INFO  [uavcan] Node ID 1, bitrate 1000000

NuttShell (NSH) NuttX-11.0.0
nsh> W
`

**Comment by dk7xe** [comment]
hardfault file could have been there before. stupid me has not checked that
[fault_2023_10_19_05_46_13.log](https://github.com/PX4/PX4-Autopilot/files/13059072/fault_2023_10_19_05_46_13.log)

**Comment by dk7xe** [comment]
@davids5 @PetervdPerk-NXP i call it a success

**Review by dagar — APPROVED** [review]

**Pull request merged**
