### PR TITLE
update all px4board kconfig

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
@PetervdPerk-NXP @muramura should we add some sorting here as well (like in https://github.com/PX4/PX4-Autopilot/pull/20850)?

**Comment by PetervdPerk-NXP** [comment]
The ordering in the px4board follows the order of definitions in the main Kconfig in the root directory.
Every rsource will add relative paths in alphabetical order, running the updateconfig command will make sure that the output file follow this scheme hence re-ordering isn't required.

Some reference
https://pypi.org/project/kconfiglib/
https://www.kernel.org/doc/Documentation/kbuild/kconfig-language.txt

**Comment by dagar** [comment]
TODO: fix v6x EXT2 before merging this so we don't lose track of the change.

Screenshot from 2023-01-06 09-35-22

**Comment by dagar** [comment]
CONFIG_BOARD_SERIAL_EXT2 fixed in https://github.com/PX4/PX4-Autopilot/pull/20884

**Pull request merged**
