### PR TITLE
TECS: Add feedforward gains for energy rates

### PR DESCRIPTION
**Pull request by RomanBapst**
Will add motivation, description and testing data in a bit.

### CODE REVIEW

**Comment by sanderux** [comment]
test flight 1: https://logs.px4.io/plot_app?log=2c9c93ec-1b0a-49f7-beeb-ce98f10700d9

**Comment by RomanBapst** [comment]
I don't think that the feedforward gain in the throttle loop is actually needed, since usually the climb rates and min/max throttle are chosen such that a unity feedforward gain should be achieved.
I need to analyze a few logs to see if this could still be beneficial to improve the response. It should definitely NOT be used to compensate for bad attitude tracking or the lack of TECS parameter tuning (such as climbrate constraints, ...)

**Comment by sfuhrer** [comment]
> I don't think that the feedforward gain in the throttle loop is actually needed, since usually the climb rates and min/max throttle are chosen such that a unity feedforward gain should be achieved.
> I need to analyze a few logs to see if this could still be beneficial to improve the response. It should definitely NOT be used to compensate for bad attitude tracking or the lack of TECS parameter tuning (such as climbrate constraints, ...)

Agree that FW_T_SEB_R_FF can be handy to make the pitch loop tighter, I was wondering about that before as well when tuning it. 
For FW_T_STE_R_FF I'm not convinced atm that we need it, and would rather limit this PR on adding FW_T_SEB_R_FF (that actually added improvements to @sanderux , whereas I see from the log that FW_T_STE_R_FF was left at 1 (which means current behavior).

**Review by sfuhrer — CHANGES_REQUESTED** [review]
Also test flown it, and increasing FW_T_SEB_R_FF helped also in our case.

I would though not add FW_T_STE_R_FF for now, until we got confirmation that it can really improve the tracking performance in ways that no other settings can (e.g. a correctly set throttle min/cruise/max values).

**Comment by sfuhrer** [comment]
@RomanBapst , as discussed I removed the STE FF param for now. I've also slightly adjusted the param min/max to safer regions and rebased on master.

**Review by dagar — APPROVED** [review]

**Comment by CarlOlsson** [comment]
> Will add motivation, description and testing data in a bit.

:)

**Pull request merged**
