### PR TITLE
[gz] X500 mono_cam_down and aruco world

### PR DESCRIPTION
**Pull request by dakejahl**
- airframe x500_mono_cam_down
- gz world with aruco tag

### CODE REVIEW

**Comment by hamishwillee** [comment]
@dakejahl FMI what can you do with this? I ask because we have this other monocular camera https://docs.px4.io/main/en/sim_gazebo_gz/vehicles.html#x500-quadrotor-with-monocular-camera which has the note:

image

So a camera that does nothing ...

**Comment by dakejahl** [comment]
@hamishwillee it provides a gazebo topic /camera. All of the models with cameras do. While the gz sim is running you can type "gz topic --list" to see all the published gz topics. Very similar to ros2 in that way. There's the ros2 gz bridge which can bridge topics and that's how I test my ros2 vision applications with sim. I am working on adding camera support directly to the GZBridge.cpp so that I can add optical flow to sim to make it easier to test. I'll add gstreamer in there while I'm at it and then the cameras will finally be useful by default.

**Review by dagar — APPROVED** [review]

**Comment by dagar** [comment]
Minor merge conflicts. 
Screenshot 2024-07-25 at 10 32 28 PM

**Comment by dirksavage88** [comment]
> @dakejahl FMI what can you do with this? I ask because we have this other monocular camera https://docs.px4.io/main/en/sim_gazebo_gz/vehicles.html#x500-quadrotor-with-monocular-camera which has the note:
> 
> image
> 
> So a camera that does nothing ...

Unpopular opinion here: I think we need to get away from the classic gazebo plugin mentality that PX4 has to have a plugin for everything in simulation.

 **The downward cam is not in PX4 (at least not merged yet)** and really is needed since there is no precision land in simulation without it (or optical flow, despite the dev team's reluctance to integrate it in sim or test it IRL). Nothing personal @hamishwillee as there are others who feel the same way about the downward monocular camera. I get it, it's ingrained that it has to be useful out of the box and be batteries included...but IMO it is better to give people the building blocks and sit back, watch them build great things.

This plugin architecture really just needs to die and people should move on to the new gz and learn how to bridge gz topics to ROS to make something. Give people the building blocks instead of holding their hand

**Comment by hamishwillee** [comment]
@dirksavage88 
1. There are many useful things that you can do with PX4 that do not involve ROS or Gazebo but you still want to test. Such as collision prevention , terrain following, improved position hold, QGC Camera handling via MAVLink API and so on. Making developers have to understand Gz and ROS to test their PX4 software is not a good use of time.
2. Either the building blocks aren't there, or no one uses them - because we get questions all the time about X, Y, Z. IF those exist then perhaps better entry points are needed for them, but if won't solve point 1.

**Comment by hamishwillee** [comment]
>  I'll add gstreamer in there while I'm at it and then the cameras will finally be useful by default.

When you're done let me know and we can add some docs.

**Comment by dakejahl** [comment]
Can we just merge this? @patrikpordi is trying to make a tutorial for implementing precision landing with PX4

**Comment by patrikpordi** [comment]
Could it be merged sometimes soon?

**Comment by Jaeyoung-Lim** [comment]
@dakejahl What is missing from this PR?

**Comment by dakejahl** [comment]
@Jaeyoung-Lim I don't think anything is missing. This is the necessary files to launch the x500 model with downward camera in the aruco world

**Pull request merged**
