### PR TITLE
few cyphal fixes for fmu-v5

### PR DESCRIPTION
**Pull request by PonomarevDA**
### Solved Problem

I've started with Cyphal build for cuav v5+. This PR solved few found bugs. I did each fix as a separate commit.

### Solution
1. It was not possible to even build cyphal for fmu-v5 `make px4_fmu-v5_cyphal` because of the floating-point comparing. The first commit fixed the following error:
```
../../src/drivers/cyphal/Subscribers/udral/Battery.hpp:113:25: error: comparing floating-point with '==' or '!=' is unsafe [-Werror=float-equal]
  113 |    if (_nominal_voltage != NAN) {
```

2. Setpoint serialization didn't work due to incorrect payload size. Fixed.

3. Port ID couldn't be configured because of the wrong comparison of param name and dynamic pub/sub name. It also created a new publisher every time when his port identifier changes. I'm not sure do we really need a prefix, so I just removed a prefix as a minimal fix to make it work. Alternatively, I can expand the register names.

4. UavcanEscController didn't work correctly. There was one instance inside CyphalNode that could call `update_outputs` (to publish setpoint) and there was another instance inside PublicationManager that could call `update` (to publish readiness). It was said in comment to integrate UavcanEscController with PublicationManager, so I did it. After the fix the autopilot started to publish setpoint and readiness.

5. But it still had a problem with readiness. The autopilot published it only after arm status changing that was not correct. According to [UDRAL](https://github.com/OpenCyphal/public_regulated_data_types/blob/master/reg/udral/service/actuator/esc/_.0.1.dsdl) it should publish readiness at least with some certain frequency called CONTROL_TIMEOUT. I set the minimal frequency as 10 Hz.

6. After all these fixes the setpoint publish frequency was ~75 Hz, but I expected ~100 Hz. I found out that EscClient called PX4_INFO every publication. The cyphal work item was significantly loaded. I removed it and also increased the pub rate to 200 Hz and decreased schedule interval. I can set any rate or even add a new parameter that will define it if you need.

I also have some things to discuss:
1. Right now the setpoint is within the range [0; 8192]. [UDRAL](https://github.com/OpenCyphal/public_regulated_data_types/blob/master/reg/udral/service/actuator/esc/_.0.1.dsdl) describes Ratiometric control [-1, +1] and speed control in rad/sec. But the standard says nothing about this range. Probably, it is related to DroneCAN RawCommand. But if so, the range should be up to 8191. Should we fix it?
2. I like that new QGC has `Actuator Testing` feature that allows to rotate a particular motor like in `gui tool`. But in this mode the vehicle is disarmed, and readiness is not ENGAGED. So we should either change the cyphal readiness logic or arm the vehicle in this mode.
3. Right now the readiness port id = setpoint port id + 1. Is not it is better to make a separate parameter for readiness? Btw, the readiness implementation is defined in 2 places: [Publishers/udral/Readiness.hpp](https://github.com/PX4/PX4-Autopilot/blob/main/src/drivers/cyphal/Publishers/udral/Readiness.hpp) and [Actuators/EscClient.hpp](https://github.com/PX4/PX4-Autopilot/blob/79c55614d860d2f3e8ce775741dd96ef062c998f/src/drivers/cyphal/Actuators/EscClient.hpp#L76). Probably, we should merge them in a single one.

### Test coverage

I tried it only with `yakut` and some devices such as cyphal to pwm for ESC adapters. I will write here if I have flight tests.

Below you can see screenshots from `yakut`:
image

and from mavlink console:
image

Here port id 2000 corresponds to setpoint and 2001 to readiness.

Beside this branch I'm going to extend the cyphal drivers with additional sensors such as gps, mag, baro. But it will be about next PR.

### CODE REVIEW

**Comment by PetervdPerk-NXP** [comment]
Hi PonomarevDA

Nice improvements.

Regarding point "3. prefix" we've introduced the notion of prefix to split out the uORB over UAVCAN/Cyphal messages. Now it could be that this was a bit broken since I didn't had the chance to fully test it, but I think removing the whole prefix probably breaks the uORB_over_UAVCAN publishers/subscribers.
https://github.com/PX4/PX4-Autopilot/blob/aac05d7bcdfbbe51f76e18c2becb4237a44b965b/src/drivers/cyphal/Subscribers/uORB/uorb_subscriber.hpp#L57

**Comment by PonomarevDA** [comment]
I've restored the prefix and added udral prefixes for all non uorb pub/sub.

**Comment by PonomarevDA** [comment]
I've added 3 more commits:
1. I found and fixed one more prefix related bug in SubscriptionManager.
2. I also fixed updateParam() logic for DynamicPortSubscriber. For a dynamic subscriber with multiple subscriptions (right now as an example it might be UavcanBmsSubscriber, but I performed tests with similarly implemented extends for GPS subscriber) it is necessary to initially update all port identifiers and only after that call the subscription. Otherwise it will call subscribe() when some port identifiers are not updated yet.
3. It was useful for me to fix `Actuator testing` feature, so I came up with a simple fix. I added a subscriber on `actuator_test` uorb topic that makes it possible to test motors from QGC without sniffers or other devices.

We also made a flight test based on this branch with our custom cyphal can-pwm adapter for esc: [video](https://youtu.be/ZxDxgamdh6E), [log104](https://review.px4.io/plot_app?log=a6af11d9-5b7f-4e57-b378-009caf09e8eb).

@PetervdPerk-NXP please, check it.

**Comment by pavel-kirienko** [comment]
@PetervdPerk-NXP not to push you, but a review would be greatly appreciated!

**Comment by PetervdPerk-NXP** [comment]
@pavel-kirienko  @PonomarevDA 
I don't have access to a FMU-V5 if you could rebase on master I would be able to test it.

**Comment by PetervdPerk-NXP** [comment]
Had a problem that DynamicPortSubscriber was only unsubscribing but not subscribing I've modified that and tested with MR-CANHUBK3 and BMS-772 and it seems to be working fine.

Here are my changes
https://github.com/PetervdPerk-NXP/Firmware/commit/7d513d8bb416852c2c4fcfa038f4d415a8bdc2af

**Comment by PonomarevDA** [comment]
Thanks. I've merged your commit and checked it with cuav v5+.
At this point it is possible to fly on PX4 with Cyphal ESC or pwm-adapters on fmu-v5.

I still have some ideas for implementation from improving standard compatibility (adding `port.List` and `*type` registers - these features greatly simplify the configuration process with Yukon) to extending supported Cyphal sensors (gps, mag, baro, etc). I also need to clarify about setpoint scaling by 8192. As I understand it should be from 0.0 to 1.0. But perhaps all these new features should be in future PRs.

**Comment by PetervdPerk-NXP** [comment]
I think it's fine to iteratively improve things. The Cyphal implementation in PX4 was made before Yukon was a thing so some things will need some refactoring.

Overall it looks good to me I think we can merge this PR.

**Review by PetervdPerk-NXP — APPROVED** [review]

**Pull request merged**
