### PR TITLE
zenoh-pico: update to correct dev/1.0.0-px4 branch which is advertised by GitHub

### PR DESCRIPTION
**Pull request by MaEtUgR**
### Solved Problem
https://github.com/PX4/PX4-Autopilot/pull/23462#issuecomment-2268958438

### Solution
Switch `zenoh-pico` submodule from
https://github.com/PX4/zenoh-pico/commits/fff1a8c168e10d4ed9cbf2aa7d67ede07f239c52
to
https://github.com/PX4/zenoh-pico/tree/dev/1.0.0-px4 (https://github.com/PX4/zenoh-pico/commit/f093aa7955bb24dfa3e626de084583711e3bac5c)

### Alternatives
Please check the versions in review. I'm only guessing that's what you wanted. FYI @AlexisTM

### Test coverage
This submodule commit was advertised by GitHub and hence is available for me locally.

### CODE REVIEW

**Comment by PetervdPerk-NXP** [comment]
The PX4 fork of Zenoh-pico is now up to date with Zenoh pico `dev/1.0.0` which contains the socket fix.

I would propose to point it to https://github.com/PX4/zenoh-pico/commit/e6cdbf71a0ed3f601d8a958c27b2bddb437a2a80
https://github.com/PX4/zenoh-pico/tree/dev/1.0.0

**Comment by AlexisTM** [comment]
That is indeed, sorry for the mess up.

**Comment by MaEtUgR** [comment]
ok, I'll do that 👍

**Comment by MaEtUgR** [comment]
CI failure that's related 😬
image

**Comment by MaEtUgR** [comment]
Because of the build error with https://github.com/PX4/zenoh-pico/tree/dev/1.0.0 caught by CI that's related to https://github.com/eclipse-zenoh/zenoh-pico/pull/563 and type casting I went back to my original suggestion referring to https://github.com/PX4/zenoh-pico/tree/dev/1.0.0-px4 instead. That will get main successfully fetch submodules again and you can look into the build issue and update to the latest 1.0.0 with more context than I have.

**Pull request merged**
