### PR TITLE
Split PAB ID and FMUM

### PR DESCRIPTION
**Pull request by davids5**
This is a Work in progress on VxX to split the version and revision into BASE ID and FMUM ID.

The purpose is to reduce the permutations of FMUM/BASE combinations needed in the SPI configuration, scripting and boards.

The manifest has been moved to be a common pab_manifest and the manifest components expanded.

The MFT query has been completed to include a queries to identify a base component existence or non-existence. 

to-dos:

- [x] Ripple to all Arch
- [x] Build test and verify all Non-Split and simple versioned boards still report correctly
- [x] Ripple to all V5X and V6X HW.

### CODE REVIEW

**Comment by davids5** [comment]
FMI @AlexKlimaj 

@vincentpoont2 - Can you please test this branch on all the HB base with all the versions of FMUM (sensor sets), comparing main boot output to this version and note any missing sensors or incorrect rotations?

**Comment by vincentpoont2** [comment]
> FMI @AlexKlimaj
> 
> @vincentpoont2 - Can you please test this branch on all the HB base with all the versions of FMUM (sensor sets), comparing main boot output to this version and note any missing sensors or incorrect rotations?

Will test and report back

**Comment by dagar** [comment]
FYI @AlexKlimaj

**Comment by davids5** [comment]
@dagar I have migrated the px4_fmu-v5x - Please have a look

**Comment by vincentpoont2** [comment]
> FMI @AlexKlimaj 
> 
> @vincentpoont2 - Can you please test this branch on all the HB base with all the versions of FMUM (sensor sets), comparing main boot output to this version and note any missing sensors or incorrect rotations?

We have tested it with all the Rev and Ver we have. No issue found.

**Comment by davids5** [comment]
> > FMI @AlexKlimaj
> > @vincentpoont2 - Can you please test this branch on all the HB base with all the versions of FMUM (sensor sets), comparing main boot output to this version and note any missing sensors or incorrect rotations?
> 
> We have tested it with all the Rev and Ver we have. No issue found.

Thanks @vincentpoont2 - can you please list the FMUM (V5X, V6X - and sensor sets) and base types tested with each

**Comment by davids5** [comment]
@dagar Can we bring this in?

**Comment by niklaut** [comment]
I'm testing on FMUv6x  and Skynode Baseboard 010 and the MAVLINK connection does not start, because the config file has not been updated in this PR:
- https://github.com/PX4/PX4-Autopilot/blob/main/boards/px4/fmu-v6x/init/rc.board_mavlink#L7

I'll test some more.

**Comment by davids5** [comment]
> I'm testing on FMUv6x and Skynode Baseboard 010 and the MAVLINK connection does not start, because the config file has not been updated in this PR:
> 
> * https://github.com/PX4/PX4-Autopilot/blob/main/boards/px4/fmu-v6x/init/rc.board_mavlink#L7
> 
> I'll test some more.

@niklaut - good catch - sorry about that - I will add that change.

**Comment by niklaut** [comment]
Hm, I don't know if this is really backward compatible: Running on the same hardware shows different sensor rotations in the boot output, which is a little sus:

```diff
-[boot] Rev 0x1 : Ver 0x9 V5X009001
-HW type: V5X009001
-HW version: 0x009
-HW revision: 0x001
-bmi088_accel #0 on SPI bus 3 rotation 2
-bmi088_gyro #0 on SPI bus 3 rotation 2
-icm42688p #0 on SPI bus 2 rotation 4
-icm20602 #0 on SPI bus 1 rotation 8
-bmm150 #0 on I2C bus 4 (external) address 0x10 rotation 6
+[boot] Rev 0x1 : Ver 0x9 V5X001
+HW type: V5X
+HW FMUM ID: 0x001
+HW BASE ID: 0x009
+bmi088_accel #0 on SPI bus 3 rotation 4
+bmi088_gyro #0 on SPI bus 3 rotation 4
+icm42688p #0 on SPI bus 2 rotation 6
+icm20602 #0 on SPI bus 1 rotation 10
+bmm150 #0 on I2C bus 4 (external) address 0x10
```

<details>
<summary>FMUv5x before change</summary>

```
[boot] Rev 0x1 : Ver 0x9 V5X009001
reset done, 10 ms
[boot] Fault Log info File No 4 Length 3177 flags:0x01 state:1
[boot] Fault Log is Armed
nsh: sysinit: fopen failed: No such file or directory
HW arch: PX4_FMU_V5X
HW type: V5X009001
HW version: 0x009
HW revision: 0x001
PX4 git-hash: 24db1cecb44d2f6d36c3903735663388faf89f84
PX4 version: 1.14.0 0 (17694720)
PX4 git-branch: develop
Vendor version: 3.0.0 0 (50331648)
OS: NuttX
OS version: Release 11.0.0 (184549631)
OS git-hash: b25bc43cd81e257c5e63ac17c7c4331510584af6
Build datetime: Jan 26 2024 16:02:54
Build uri: localhost
Build variant: default
Toolchain: GNU GCC, 9.3.1 20200408 (release)
PX4GUID: 000200000000203234414256500600250034
MCU: STM32F76xxx, rev. Z
nsh: [: syntax error
ERROR [parameters] BSON document size (0) doesn't match bytes decoded (536)
ERROR [parameters] BSON document size (0) doesn't match bytes decoded (536)
ERROR [parameters] BSON document size (0) doesn't match bytes decoded (536)
ERROR [param] importing from '/fs/mtd_caldata' failed (-1)
INFO  [param] selected parameter default file /fs/mtd_params
INFO  [param] importing from '/fs/mtd_params'
INFO  [parameters] BSON document size 754 bytes, decoded 754 bytes (INT32:16, FLOAT:19)
INFO  [param] selected parameter backup file /fs/microsd/parameters_backup.bson
Board architecture defaults: /etc/init.d/rc.board_arch_defaults
Board defaults: /etc/init.d/rc.board_defaults
mcp23009 #0 on I2C bus 3 (external) address 0x25
Loading airframe: /fs/microsd/ext_autostart/airframes/1230010_x500
ERROR [param] Parameter SYS_USE_IO not found.
ERROR [param] Parameter SYS_CTRL_ALLOC not found.
INFO  [dataman] data manager file '/fs/microsd/dataman' size is 64312 bytes
INFO  [px4io] IO FW CRC match
Board sensors: /etc/init.d/rc.board_sensors
bmi088_accel #0 on SPI bus 3 rotation 2
bmi088_gyro #0 on SPI bus 3 rotation 2
icm42688p #0 on SPI bus 2 rotation 4
icm20602 #0 on SPI bus 1 rotation 8
bmm150 #0 on I2C bus 4 (external) address 0x10 rotation 6
WARN  [SPI_I2C] ist8310: no instance started (no device on bus?)
ina226 #0 on I2C bus 1 (external) address 0x41
bmp388 #0 on I2C bus 4 (external) address 0x77
bmp388 #1 on I2C bus 2 (external) address 0x76
WARN  [SPI_I2C] lightware_laser_i2c: no instance started (no device on bus?)
WARN  [vehicle_angular_velocity] no gyro selected, using sensor_gyro_fifo:0 2490386
ekf2 [680:237]
Board mavlink: /etc/init.d/rc.board_mavlink
INFO  [mavlink] mode: OnboardLowBandwidth, data rate: 290000 B/s on /dev/ttyS4 @ 3000000B
Starting DShot Driver on /dev/ttyS6
Starting Main GPS on /dev/ttyS0
Conflicting config for /dev/ttyS6
Starting MAVLink on /dev/ttyS3
INFO  [mavlink] mode: Normal, data rate: 2880 B/s on /dev/ttyS3 @ 57600B
Starting UXRCE-DDS Client on ethernet
INFO  [logger] logger started (mode=all)

NuttShell (NSH) NuttX-11.0.0
nsh>
```

</details>

<details>
<summary>FMUv5x after change</summary>

```
[boot] Rev 0x1 : Ver 0x9 V5X001
reset done, 10 ms
[boot] Fault Log info File No 4 Length 3177 flags:0x01 state:1
[boot] Fault Log is Armed
nsh: sysinit: fopen failed: No such file or directory
HW arch: PX4_FMU_V5X
HW type: V5X
HW FMUM ID: 0x001
HW BASE ID: 0x009
PX4 git-hash: 0feea9ffb142a181b5321e330f1d3955fa20f013
PX4 version: 1.14.0 0 (17694720)
PX4 git-branch: pr-ver-rev-ids-private
Vendor version: 3.0.0 0 (50331648)
OS: NuttX
OS version: Release 11.0.0 (184549631)
OS git-hash: b25bc43cd81e257c5e63ac17c7c4331510584af6
Build datetime: Jan 26 2024 15:57:06
Build uri: localhost
Build variant: default
Toolchain: GNU GCC, 9.3.1 20200408 (release)
PX4GUID: 000200000000203234414256500600250034
MCU: STM32F76xxx, rev. Z
nsh: [: syntax error
ERROR [parameters] BSON document size (0) doesn't match bytes decoded (536)
ERROR [parameters] BSON document size (0) doesn't match bytes decoded (536)
ERROR [parameters] BSON document size (0) doesn't match bytes decoded (536)
ERROR [param] importing from '/fs/mtd_caldata' failed (-1)
INFO  [param] selected parameter default file /fs/mtd_params
INFO  [param] importing from '/fs/mtd_params'
INFO  [parameters] BSON document size 754 bytes, decoded 754 bytes (INT32:16, FLOAT:19)
INFO  [param] selected parameter backup file /fs/microsd/parameters_backup.bson
Board architecture defaults: /etc/init.d/rc.board_arch_defaults
Board defaults: /etc/init.d/rc.board_defaults
mcp23009 #0 on I2C bus 3 (external) address 0x25
Loading airframe: /fs/microsd/ext_autostart/airframes/1230010_x500
ERROR [param] Parameter SYS_USE_IO not found.
ERROR [param] Parameter SYS_CTRL_ALLOC not found.
INFO  [dataman] data manager file '/fs/microsd/dataman' size is 64312 bytes
INFO  [px4io] IO FW CRC match
Board sensors: /etc/init.d/rc.board_sensors
bmi088_accel #0 on SPI bus 3 rotation 4
bmi088_gyro #0 on SPI bus 3 rotation 4
icm42688p #0 on SPI bus 2 rotation 6
icm20602 #0 on SPI bus 1 rotation 10
bmm150 #0 on I2C bus 4 (external) address 0x10
WARN  [SPI_I2C] ist8310: no instance started (no device on bus?)
bmp388 #0 on I2C bus 4 (external) address 0x77
bmp388 #1 on I2C bus 2 (external) address 0x76
WARN  [SPI_I2C] lightware_laser_i2c: no instance started (no device on bus?)
WARN  [vehicle_angular_velocity] no gyro selected, using sensor_gyro_fifo:0 2490386
ekf2 [662:237]
Board mavlink: /etc/init.d/rc.board_mavlink
INFO  [mavlink] mode: OnboardLowBandwidth, data rate: 290000 B/s on /dev/ttyS4 @ 3000000B
Starting DShot Driver on /dev/ttyS6
Starting Main GPS on /dev/ttyS0
Conflicting config for /dev/ttyS6
Starting MAVLink on /dev/ttyS3
INFO  [mavlink] mode: Normal, data rate: 2880 B/s on /dev/ttyS3 @ 57600B
Starting UXRCE-DDS Client on ethernet
INFO  [logger] logger started (mode=all)

NuttShell (NSH) NuttX-11.0.0
nsh>
```

</details>

FMUv6x rev 0x10 ver 0x10 doesn't show this issue.

**Comment by davids5** [comment]
> Hm, I don't know if this is really backward compatible: Running on the same hardware shows different sensor rotations in the boot output, which is a little sus:
> 
> ```diff
> -[boot] Rev 0x1 : Ver 0x9 V5X009001
> -HW type: V5X009001
> -HW version: 0x009
> -HW revision: 0x001
> -bmi088_accel #0 on SPI bus 3 rotation 2
> -bmi088_gyro #0 on SPI bus 3 rotation 2
> -icm42688p #0 on SPI bus 2 rotation 4
> -icm20602 #0 on SPI bus 1 rotation 8
> -bmm150 #0 on I2C bus 4 (external) address 0x10 rotation 6
> +[boot] Rev 0x1 : Ver 0x9 V5X001
> +HW type: V5X
> +HW FMUM ID: 0x001
> +HW BASE ID: 0x009
> +bmi088_accel #0 on SPI bus 3 rotation 4
> +bmi088_gyro #0 on SPI bus 3 rotation 4
> +icm42688p #0 on SPI bus 2 rotation 6
> +icm20602 #0 on SPI bus 1 rotation 10
> +bmm150 #0 on I2C bus 4 (external) address 0x10
> ```
> 
> FMUv5x before change
> FMUv5x after change
> FMUv6x rev 0x10 ver 0x10 doesn't show this issue.

I wonder if I translated the "if then" logic wrong

**Comment by niklaut** [comment]
Same issue with FMU rev 0x1 ver 0x10, so not related to the base version.

| | Base 009 | Base 010 |
|---|---|---|
| FMU 001 | ❌ | ❌ |
| FMU 010 | ✔️ | ✔️ |

**Comment by davids5** [comment]
@niklaut - I have fixed ( and restructured) the V5X files. I messed up the selection logic for the skynode but also V5X001000 and V5X005000 were broken on main.

Both have been fixed.

```diff
58c58
< Run:V5X001000 fmum=000 base=001 Used
---
> Run:V5X000 fmum=000 base=001 Used
66c66,67
< icm20649 -s -R 6 start
---
> bmi088 -A -R 4 -s start
> bmi088 -G -R 4 -s start
82c83
< Run:V5X004000 fmum=000 base=004 Used
---
> Run:V5X000 fmum=000 base=004 Used
97c98
< bmp388 -X -b 2 start
---
> bmp388 -I start
138c139
< Run:V5X005000 fmum=000 base=005 Used
---
> Run:V5X000 fmum=000 base=005 Used
146,150c147,151
< icm20649 -s -R 4 start
< icm42688p -R 4 -s start
< icm20602 -R 8 -s start
< bmm150 -I -R 6 start
< pm_selector_auterion start
---
> bmi088 -A -R 4 -s start
> bmi088 -G -R 4 -s start
> icm42688p -R 6 -s start
> icm20602 -R 10 -s start
> bmm150 -I start
153c154
< bmp388 -X -b 2 start
---
> bmp388 -I start
```

**Comment by AlexKlimaj** [comment]
Migrated the arkv6x, I still need to test it.

**Review by niklaut — APPROVED** [review]
Thanks, it works now!

| | Base 009 | Base 010 |
|---|---|---|
| FMU 001 | ✔️ | ✔️ |
| FMU 010 | ✔️ | ✔️ |

**Comment by davids5** [comment]
@niklaut - thanks for testing. Did you by chance test this on the the other bases (QS (8,0xa) etc)? [See 
image
](https://github.com/pixhawk/Pixhawk-Standards/blob/master/DS-019%20Pixhawk%20versions%20and%20revisions.md#base-board-versions)

**Comment by davids5** [comment]
@AlexKlimaj Can you post you test results so we can merge.

**Comment by AlexKlimaj** [comment]
Looks like it is working.

ARKV6X FMUM ID: 0x000 with the ARK PAB Carrier BASE ID 0x001
```
[boot] Rev 0x0 : Ver 0x1 ARKV6X000
reset done, 10 ms
[boot] Fault Log info File No 4 Length 3177 flags:0x01 state:1
[boot] Fault Log is Armed
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
nsh: sysinit: fopen failed: No such file or di[hardfault_log] Fault Log is Armed
rectory
HW arch: ARK_FMU_V6X
HW type: ARKV6X
HW FMUM ID: 0x000
HW BASE ID: 0x001
PX4 git-hash: ae0dcbfa23e503e72a02ab2b1e08f3d718ec8a42
PX4 version: 1.15.0 40 (17760320)
PX4 git-branch: pr-ver-rev-ids
OS: NuttX
OS version: Release 11.0.0 (184549631)
OS git-hash: 6fdb755a5d776de3017aa874a5e204dd1903054e
Build datetime: Jan 29 2024 11:47:53
Build uri: localhost
Build variant: default
Toolchain: GNU GCC, 10.2.1 20201103 (release)
PX4GUID: 000600000000333138313033511000470028
MCU: STM32H7[4|5]xxx, rev. V
INFO  [param] selected parameter default file /fs/mtd_params
INFO  [param] importing from '/fs/mtd_params'
INFO  [parameters] BSON document size 464 bytes, decoded 464 bytes (INT32:9, FLOAT:12)
INFO  [param] selected parameter backup file /fs/microsd/parameters_backup.bson
Board architecture defaults: /etc/init.d/rc.board_arch_defaults
Board defaults: /etc/init.d/rc.board_defaults
INFO  [dataman] data manager file '/fs/microsd/dataman' size is 64312 bytes
INFO  [px4io] PX4IO Not Supported
Board sensors: /etc/init.d/rc.board_sensors
INFO  [ina226] Failed to init INA226 on bus 1, but will try again periodically.
ina226 #0 on I2C bus 1 (external) address 0x41
INFO  [ina226] Failed to init INA226 on bus 2, but will try again periodically.
ina226 #1 on I2C bus 2 (external) address 0x41
INFO  [ina226] Failed to init INA226 on bus 3, but will try again periodically.
ina226 #2 on I2C bus 3 (external) address 0x41
iim42652 #0 on SPI bus 1 rotation 3
icm42688p #0 on SPI bus 2 rotation 9
icm42688p #1 on SPI bus 3 rotation 6
bmm150 #0 on I2C bus 4 (external) address 0x10
bmp388 #0 on I2C bus 4 (external) address 0x76
nsh: icm20948_i2c_passthrough: command not found
nsh: battery_status: command not found
WARN  [vehicle_angular_velocity] no gyro selected, using sensor_gyro_fifo:0 2818058
No autostart ID found
ekf2 [343:237]
Starting Main GPS on /dev/ttyS0
Starting MAVLink on /dev/ttyS6
INFO  [mavlink] mode: Normal, data rate: 1200 B/s on /dev/ttyS6 @ 57600B
Starting MAVLink on ethernet
INFO  [mavlink] mode: Normal, data rate: 100000 B/s on udp port 14550 remote port 14550
INFO  [logger] logger started (mode=all)
INFO  [uavcan] Node ID 1, bitrate 1000000
```

ARKV6X FMUM ID: 0x000 with the Holybro Mini Carrier BASE ID 0x005
```
[boot] Rev 0x0 : Ver 0x5 ARKV6X000
reset done, 10 ms
[boot] Fault Log info File No 4 Length 3177 flags:0x01 state:1
[boot] Fault Log is Armed
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
nsh: sysinit: fopen failed: No such file or dir[hardfault_log] Fault Log is Armed
ectory
HW arch: ARK_FMU_V6X
HW type: ARKV6X
HW FMUM ID: 0x000
HW BASE ID: 0x005
PX4 git-hash: ae0dcbfa23e503e72a02ab2b1e08f3d718ec8a42
PX4 version: 1.15.0 40 (17760320)
PX4 git-branch: pr-ver-rev-ids
OS: NuttX
OS version: Release 11.0.0 (184549631)
OS git-hash: 6fdb755a5d776de3017aa874a5e204dd1903054e
Build datetime: Jan 29 2024 11:47:53
Build uri: localhost
Build variant: default
Toolchain: GNU GCC, 10.2.1 20201103 (release)
PX4GUID: 000600000000333138313033511000470028
MCU: STM32H7[4|5]xxx, rev. V
INFO  [param] selected parameter default file /fs/mtd_params
INFO  [param] importing from '/fs/mtd_params'
INFO  [parameters] BSON document size 464 bytes, decoded 464 bytes (INT32:9, FLOAT:12)
INFO  [param] selected parameter backup file /fs/microsd/parameters_backup.bson
Board architecture defaults: /etc/init.d/rc.board_arch_defaults
Board defaults: /etc/init.d/rc.board_defaults
INFO  [dataman] data manager file '/fs/microsd/dataman' size is 64312 bytes
INFO  [px4io] IO FW CRC match
Board sensors: /etc/init.d/rc.board_sensors
INFO  [ina226] Failed to init INA226 on bus 1, but will try again periodically.
ina226 #0 on I2C bus 1 (external) address 0x41
iim42652 #0 on SPI bus 1 rotation 3
icm42688p #0 on SPI bus 2 rotation 9
icm42688p #1 on SPI bus 3 rotation 6
bmm150 #0 on I2C bus 4 (external) address 0x10
bmp388 #0 on I2C bus 4 (external) address 0x76
nsh: icm20948_i2c_passthrough: command not found
nsh: battery_status: command not found
WARN  [vehicle_angular_velocity] no gyro selected, using sensor_gyro_fifo:0 2818058
No autostart ID found
ekf2 [376:237]
Starting Main GPS on /dev/ttyS0
Starting MAVLink on /dev/ttyS6
INFO  [mavlink] mode: Normal, data rate: 1200 B/s on /dev/ttyS6 @ 57600B
Starting MAVLink on ethernet
INFO  [mavlink] mode: Normal, data rate: 100000 B/s on udp port 14550 remote port 14550
INFO  [logger] logger started (mode=all)
INFO  [uavcan] Node ID 1, bitrate 1000000
```

ARKV6X FMUM ID: 0x001 with the ARK PAB Carrier BASE ID 0x001
```
nsh> [boot] Rev 0x1 : Ver 0x1 ARKV6X001
reset done, 10 ms
[boot] Fault Log info File No 4 Length 3177 flags:0x01 state:1
[boot] Fault Log is Armed
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
nsh: sysinit: fopen failed: No such file or dire[hardfault_log] Fault Log is Armed
ctory
HW arch: ARK_FMU_V6X
HW type: ARKV6X
HW FMUM ID: 0x001
HW BASE ID: 0x001
PX4 git-hash: ae0dcbfa23e503e72a02ab2b1e08f3d718ec8a42
PX4 version: 1.15.0 40 (17760320)
PX4 git-branch: pr-ver-rev-ids
OS: NuttX
OS version: Release 11.0.0 (184549631)
OS git-hash: 6fdb755a5d776de3017aa874a5e204dd1903054e
Build datetime: Jan 29 2024 11:47:53
Build uri: localhost
Build variant: default
Toolchain: GNU GCC, 10.2.1 20201103 (release)
PX4GUID: 00060000000033313831303351100043002b
MCU: STM32H7[4|5]xxx, rev. V
INFO  [param] selected parameter default file /fs/mtd_params
INFO  [param] importing from '/fs/mtd_params'
INFO  [parameters] BSON document size 464 bytes, decoded 464 bytes (INT32:9, FLOAT:12)
INFO  [param] selected parameter backup file /fs/microsd/parameters_backup.bson
Board architecture defaults: /etc/init.d/rc.board_arch_defaults
Board defaults: /etc/init.d/rc.board_defaults
INFO  [dataman] data manager file '/fs/microsd/dataman' size is 64312 bytes
INFO  [px4io] PX4IO Not Supported
Board sensors: /etc/init.d/rc.board_sensors
INFO  [ina226] Failed to init INA226 on bus 1, but will try again periodically.
ina226 #0 on I2C bus 1 (external) address 0x41
INFO  [ina226] Failed to init INA226 on bus 2, but will try again periodically.
ina226 #1 on I2C bus 2 (external) address 0x41
INFO  [ina226] Failed to init INA226 on bus 3, but will try again periodically.
ina226 #2 on I2C bus 3 (external) address 0x41
iim42653 #0 on SPI bus 1 rotation 3
iim42653 #1 on SPI bus 2 rotation 9
iim42653 #2 on SPI bus 3 rotation 6
bmm150 #0 on I2C bus 4 (external) address 0x10
bmp388 #0 on I2C bus 4 (external) address 0x76
nsh: icm20948_i2c_passthrough: command not found
nsh: battery_status: command not found
WARN  [vehicle_angular_velocity] no gyro selected, using sensor_gyro_fifo:0 3014666
No autostart ID found
ekf2 [343:237]
Starting Main GPS on /dev/ttyS0
Starting MAVLink on /dev/ttyS6
INFO  [mavlink] mode: Normal, data rate: 1200 B/s on /dev/ttyS6 @ 57600B
Starting MAVLink on ethernet
INFO  [mavlink] mode: Normal, data rate: 100000 B/s on udp port 14550 remote port 14550
INFO  [logger] logger started (mode=all)
INFO  [uavcan] Node ID 1, bitrate 1000000
```

ARKV6X FMUM ID: 0x001 with the Holybro Mini Carrier BASE ID 0x005
```
nsh> [boot] Rev 0x1 : Ver 0x5 ARKV6X001
reset done, 10 ms
[boot] Fault Log info File No 4 Length 3177 flags:0x01 state:1
[boot] Fault Log is Armed
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
nsh: sysinit: fopen failed: No such file or dire[hardfault_log] Fault Log is Armed
ctory
HW arch: ARK_FMU_V6X
HW type: ARKV6X
HW FMUM ID: 0x001
HW BASE ID: 0x005
PX4 git-hash: ae0dcbfa23e503e72a02ab2b1e08f3d718ec8a42
PX4 version: 1.15.0 40 (17760320)
PX4 git-branch: pr-ver-rev-ids
OS: NuttX
OS version: Release 11.0.0 (184549631)
OS git-hash: 6fdb755a5d776de3017aa874a5e204dd1903054e
Build datetime: Jan 29 2024 11:47:53
Build uri: localhost
Build variant: default
Toolchain: GNU GCC, 10.2.1 20201103 (release)
PX4GUID: 00060000000033313831303351100043002b
MCU: STM32H7[4|5]xxx, rev. V
INFO  [param] selected parameter default file /fs/mtd_params
INFO  [param] importing from '/fs/mtd_params'
INFO  [parameters] BSON document size 464 bytes, decoded 464 bytes (INT32:9, FLOAT:12)
INFO  [param] selected parameter backup file /fs/microsd/parameters_backup.bson
Board architecture defaults: /etc/init.d/rc.board_arch_defaults
Board defaults: /etc/init.d/rc.board_defaults
INFO  [dataman] data manager file '/fs/microsd/dataman' size is 64312 bytes
INFO  [px4io] IO FW CRC match
Board sensors: /etc/init.d/rc.board_sensors
INFO  [ina226] Failed to init INA226 on bus 1, but will try again periodically.
ina226 #0 on I2C bus 1 (external) address 0x41
iim42653 #0 on SPI bus 1 rotation 3
iim42653 #1 on SPI bus 2 rotation 9
iim42653 #2 on SPI bus 3 rotation 6
bmm150 #0 on I2C bus 4 (external) address 0x10
bmp388 #0 on I2C bus 4 (external) address 0x76
nsh: icm20948_i2c_passthrough: command not found
nsh: battery_status: command not found
WARN  [vehicle_angular_velocity] no gyro selected, using sensor_gyro_fifo:0 3014666
No autostart ID found
ekf2 [375:237]
Starting Main GPS on /dev/ttyS0
Starting MAVLink on /dev/ttyS6
INFO  [mavlink] mode: Normal, data rate: 1200 B/s on /dev/ttyS6 @ 57600B
Starting MAVLink on ethernet
INFO  [mavlink] mode: Normal, data rate: 100000 B/s on udp port 14550 remote port 14550
INFO  [logger] logger started (mode=all)
INFO  [uavcan] Node ID 1, bitrate 1000000
```

**Review by AlexKlimaj — APPROVED** [review]

**Review by dagar — APPROVED** [review]

**Pull request merged**
