### PR TITLE
Qurt qshell implementation

### PR DESCRIPTION
**Pull request by ZacharyLowell**
### Solved Problem
This code gets individual modules and drivers and such running on the DSP. Qshell takes a string from px4 shell and passes to the dsp where it will ingest this uorb and run the command that the string is stating to do.

### Solution
This code packages a msg in a uorb to be sent from apps to dsp. Dsp ingest this uorb, runs the necessary command, and sends an ack back to the apps.

### Alternatives
Currently no alternatives

### Test coverage
Tested on the voxl2

### CODE REVIEW

**Comment by dagar** [comment]
Where is qurt side qshell server started?

**Review by katzfey — APPROVED** [review]

**Comment by dagar** [comment]
This seems fine for now, just a few notes for later.

 - the qshell service could just become a generic shell thing (I'm going something similar for UAVCAN and other platforms)
 - qshell could be a voxl2 linux specific systemcmd
 - qshell service could be baked into qurt platform init if that's the only way to interact with it?
 - later it might make sense to use the `shell` service for things like the mavlink shell access (instead of spawning nsh like we do now)

**Comment by katzfey** [comment]
Yes, all good suggestions.

**Comment by katzfey** [comment]
If you hit approve I will merge it

**Review by katzfey — APPROVED** [review]

**Review by dagar — APPROVED** [review]

**Pull request merged**
