### PR TITLE
ekf2: migrate mag 3D fusion to SymForce

### PR DESCRIPTION
**Pull request by bresch**
TODO:
- [x] evaluate the CPU load and flash space difference
- [x] compare result using unit test
- [x] remove previous derivation

Tested on a Pixhawk4 (fmu-v5), mag 3D active:
main:
```
 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE FD
1434 wq:INS0                      4588  6.816  4380/ 6000 241 (241)  w:sem  4
1435 wq:INS1                      4089  6.091  4380/ 6000 240 (240)  w:sem  4
```

PR:
```
 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE FD
1434 wq:INS0                      1314  6.853  4380/ 6000 241 (241)  w:sem  4
1435 wq:INS1                      1180  6.218  4380/ 6000 240 (240)  w:sem  4
```
flash space on fmu-v5:
- main: 1962573 B
- PR: 1968029 B (when generating K using symforce) and 1962053 B (by computing K = PH'/innov_var in the code)

Flash size difference can be explained by the unrolled loops in the computation of the K vectors (before we were manually turning those lines into `for` loops, e.g.: [here](https://github.com/PX4/PX4-Autopilot/pull/20403/files#diff-0dc1c6930bc06279369ba79a8f0651d32823be3fc38b6708a9f6f4634f46234cL222-L224)).

If I wrap manually those equations into for loops (just for the sake of comparison, this isn't a solution, we would need to make it auto-generated) the flash space goes down to 1963885 B

### CODE REVIEW

**Comment by dagar** [comment]
px4_fmu-v5_test flash overflow

Screenshot from 2022-10-13 09-06-19

**Comment by bresch** [comment]
Not pre-computing K brings the flash usage down to `1962053 B`. Looking at `top`, I'm not able to see a significant change in CPU load

**Review by dagar — APPROVED** [review]

**Comment by bresch** [comment]
Need to update the innovation calculation between the fusion of each axis (use the new state vector to compute the innovation but use the initial one to compute the jacobians)

**Comment by bresch** [comment]
> Need to update the innovation calculation between the fusion of each axis (use the new state vector to compute the innovation but use the initial one to compute the jacobians)

Done and rebased on `main`

**Review by dagar — APPROVED** [review]

**Pull request merged**
