### PR TITLE
New TF-B1 helium gas balloon airframe

### PR DESCRIPTION
**Pull request by kaklik**
We would like to add our gas balloon [ThunderFly TF-B1](https://github.com/ThunderFly-aerospace/TF-B1) airframe.
The airframe settings were improved in two high-altitude-balloon flights FIK-5 and FIK-6. 

FIK-6 flight gondola containing ThunderFly TF-B1 technology

The PX4 was in use the previous flight [FIK-5](https://review.px4.io/plot_app?log=a35a59d1-8a3e-4181-a114-b2d6a319d2ec), but unfortunately, the EKF2 estimator seems to be suboptimal to balloon dynamics. Therefore we switched to the estimator Q for now. The modification brings some troubles with log analysis and [flight_review needs to be modified](https://github.com/ThunderFly-aerospace/flight_review/tree/estimator_q). 
The flight where the system was successfully used was the [FIK-6 scientific experiment](https://github.com/ODZ-UJF-AV-CR/FIK-6). Unfortunately, the log recorded is quite huge (around 800 MB) which cannot be uploaded to standard review.px4.io. Therefore I add the following screenshots from our modified flight_review and in-flight photos. 

TF-B1/FIK-6 altitude plot

The recorded barometric altitude is a little underestimated, probably by improper use of the troposphere atmospheric model used up to the stratosphere. :) 

Snapshot from FIK-6 on-board camera

The airframe itself expects the parachute recovery method for now, but in the future, we hope the PX4 stack will be used for controlled flight and return recovery.

FIK-6 flight trajectory

[Flight-review video from balloon burst](https://youtu.be/E5B5rW-Sako).

The real-flight firmware was improved in redundant telemetry and Payload data handling. This resulted in the SiK modem on the TELEM port and LoRa transceiver directly connected to Pixhawk SPI port and controlled by PX4, which gives us a more reliable control of telemetry transmission.  

Both telemetry links  (SiK and LoRa) were used to [real-time upload](https://github.com/ODZ-UJF-AV-CR/FIK-6/tree/FIK-6/sw/Telemetry_receiver) the telemetry data on https://tracker.habhub.org/, which allows accurate prediction of the landing site and fast experiment recovery after gondola touchdown.

TF-B1 airframe FIK-6 flight on habhub tracker

Therefore some more pull-requests will follow.

### CODE REVIEW

**Comment by CarlOlsson** [comment]
cool work!

> but unfortunately, the EKF2 estimator seems to be suboptimal to balloon dynamics.

Can you please elaborate on what the problem was with EKF2?

**Comment by kaklik** [comment]
> cool work!
> 
> > but unfortunately, the EKF2 estimator seems to be suboptimal to balloon dynamics.
> 
> Can you please elaborate on what the problem was with EKF2?

The behavior can be seen in the [FIK-5](https://review.px4.io/plot_app?log=a35a59d1-8a3e-4181-a114-b2d6a319d2ec) flight log.  The balloon has many sharp "unpredictable" movements which cause EKF to reset to GPS.  In the results, there is almost no estimated trajectory.  Maybe there could be a possibility to improve this by proper EKF parameters tunning, but generally, the LEP or Q estimator has a better performance compared to system complexity in that application.  There are many GPS measured points along the balloon flight path, therefore the estimator is primarily required to estimate the attitude and optionally the velocities.

**Comment by CarlOlsson** [comment]
> The balloon has many sharp "unpredictable" movements which cause EKF to reset to GPS.

In the linked logfile it seems like the EKF is diverging due to diverging delta velocity states and very bad magnetometer data. I would start with temperature calibrate the IMU and make sure the quality of magnetometer data is improved, if you want to use EKF2 in the future.

**Comment by dagar** [comment]
> > The balloon has many sharp "unpredictable" movements which cause EKF to reset to GPS.
> 
> In the linked logfile it seems like the EKF is diverging due to diverging delta velocity states and very bad magnetometer data. I would start with temperature calibrate the IMU and make sure the quality of magnetometer data is improved, if you want to use EKF2 in the future.

That might have benefited from multi-EKF with an instance of ekf2 for each IMU. On fmu-v5 the Invensense IMU was historical the higher priority default, but it also has a Bosch BMI055 which is much more stable over temperature change. https://github.com/PX4/PX4-Autopilot/pull/15640#issuecomment-683114631

**Comment by kaklik** [comment]
Yes, the airframe setup could be iteratively improved in the future. The current tested and working solution is a result of two non-trivial experiments, which do not cover every configuration possibilities. 
In this case, multi-EKF could improve the situation, but multi-estimator  (eg. EKF, LPE, and Q) could be even better. I think that a sophisticated - observer-based estimator alone like an EKF, will fail. It needs precise tunning of the physics model, which is unfortunately unknown for high-altitude-balloon until the real flight. Therefore some backup estimators working with different algorithms could cover this situation better.

**Comment by CarlOlsson** [comment]
> It needs precise tunning of the physics model, which is unfortunately unknown for high-altitude-balloon until the real flight

I don't understand what you mean by this. The EKF uses an IMU model which regards the gyro and accel data as time varying parameters. So the "physics model" is trivial. I don't know of any reason it would not work as good as LPE so if it doesn't I am very interested in understanding where it comes from.

**Comment by kaklik** [comment]
> > It needs precise tunning of the physics model, which is unfortunately unknown for high-altitude-balloon until the real flight
> 
> I don't understand what you mean by this. The EKF uses an IMU model which regards the gyro and accel data as time varying parameters. So the "physics model" is trivial. I don't know of any reason it would not work as good as LPE so if it doesn't I am very interested in understanding where it comes from.

Ok, I think this should be displayed by a simple experiment.  Take a Pixhawk  (FMUv5 for example) mount it in the box on a long rope  (around 30meters) under a multi-copter.    And fly the multi-copter randomly above a terrain.  The result probably would be a common reset of EKF estimator.  The cause of this situation is sharp moves at some parts of the trajectory.   A similar situation occasionally arises in case of hand transport of an airframe with running PX4 - this is a common situation preventing the arming which everyone knows.

**Comment by CarlOlsson** [comment]
Ah okey thanks for clarifying!
I never really looked into LPE before but I see now that for you application it makes sense, cool!

**Review by LorenzMeier — APPROVED** [review]
Thanks!

**Pull request merged**
