### PR TITLE
uORB_tests: add uORB::SubscriptionMultiArray tests

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
@bkueng what did you hit in https://github.com/PX4/PX4-Autopilot/pull/16092?

**Comment by dagar** [comment]
This also uncovers a small bug with `uORB::DeviceNode::get_initial_generation()` and topics that were previously published then unadvertised. @ShawnFeng0 FYI

Screenshot from 2020-10-30 10-48-23

Possibly already resolved by https://github.com/PX4/PX4-Autopilot/pull/16084.

**Comment by ShawnFeng0** [comment]
It may be because test_single() has used orb_test instance 0 to publish data once, but after you subscribe to test_SubscriptionMulti, orb_test instance 0 has a piece of data waiting to be read, but it has not been read yet, there is a new publication, resulting in the instance 0 produced two unread data, so the test failed.

**Comment by ShawnFeng0** [comment]
That should be it. I turned off test_single() first and did the test, and it passed.

I see that in order to maintain independence, each unit test basically uses a different message. Maybe a new one should be used here. Or use copy several times in advance to read all the messages before executing the test.

**Comment by dagar** [comment]
> That should be it. I turned off test_single() first and did the test, and it passed.
> 
> I see that in order to maintain independence, each unit test basically uses a different message. Maybe a new one should be used here. Or use copy several times in advance to read all the messages before executing the test.

That's all true, but I still don't see why this isn't technically a real bug. The first subscription subscribes and reports the last generation as 1 (should be 2 from the earlier test_single()), then after it does the first copy the generation jumps to 3 (actual generation + 1).

**Comment by ShawnFeng0** [comment]
Oh, `test_single()` was published twice, `orb_advertise(ORB_ID(orb_test), &t)` and `orb_publish(ORB_ID(orb_test), ptopic, &t)`.

Then `test_SubscriptionMulti()` was published once and it became 3, and that's it.

The generation is the total number of releases externally, but it is used as an index starting from 0 inside the `uORB::DeviceNode`. When I first saw it, I found it very strange. It was a small trick.

**Review by bkueng — APPROVED** [review]

**Comment by ShawnFeng0** [comment]
The test failed because of this:
https://github.com/PX4/PX4-Autopilot/blob/99833eb001d657f10125fafc9993abd333d442f6/src/modules/uORB/uORBDeviceNode.cpp#L552
If there is valid data before, we will reduce the initial value by 1 to get the latest data. Then it was released again in test_SubscriptionMulti(), our _last_generation = generation-2. In addition, there is no queue for the orb_test topic, so it was skipped twice when copying.

My modification in https://github.com/PX4/PX4-Autopilot/pull/16084 cannot fix this problem.

For this problem, we should use a copy before the start of this test case to point _last_generation to the latest data. Or it should be tested on a new topic.

**Pull request merged**
