### PR TITLE
fw_pos_control_l1: OFFBOARD fully populate position_setpoint_triplet

### PR DESCRIPTION
**Pull request by dagar**
Possible fix for https://github.com/PX4/PX4-Autopilot/issues/17122#issuecomment-799554102.

@AndreRigi @Jaeyoung-Lim

### CODE REVIEW

**Comment by mrpollo** [comment]
That was fast, thanks @dagar 🐢

**Review by Jaeyoung-Lim — APPROVED** [review]
Thanks!

**Comment by AndreRigi** [comment]
@dagar Thank you for the quick fix, it's now functional again. 

I don't know if I should raise a new issue for what follows or not, so I will just write it here for now. 

From my understanding, both the flight_mode_manager and mavlink  publish on `trajectory_setpoint` during the FW transition.
For some reason, flight_mode_manager publishes NaN values that are overwriting the ones from mavlink. This raises a critical warning [here](https://github.com/PX4/PX4-Autopilot/blob/master/src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp#L1704). 
Despite this, the drone still flies properly as it seems that `_pos_sp_triplet.current` is not updated while the values on `trajectory_setpoint` are not valid and as soon as the transition is done, flight_mode_manager stops publishing.

**Comment by dagar** [comment]
@AndreRigi maybe start a fresh issue with a log? I wasn't aware that OFFBOARD was being used to command a VTOL transitions.

If you could also share a previous "good" log that couldn't hurt.

**Pull request merged**
