### PR TITLE
GPS: add velocity fields to Unicore

### PR DESCRIPTION
**Pull request by julianoes**
It looks like vertical velocity as well as velocity accuracy are not available using NMEA, so we extract all velocities from the Unicore ACRICA message instead.

~Depends on https://github.com/PX4/PX4-GPSDrivers/pull/171 getting merged first.~

### CODE REVIEW

**Comment by julianoes** [comment]
@mrpollo I'm very confused why CI fails here. Any idea?
https://github.com/PX4/PX4-Autopilot/actions/runs/10608117827/job/29401718081?pr=23614

**Comment by mrpollo** [comment]
A fluke maybe? I've never seen it fail like this. I'll take a deeper look tomorrow morning. I'll add a failed step to upload the logs so we can take a deeper look whenever something like this happens. For now, after a restart of the failed jobs, it's all green ✅

**Comment by julianoes** [comment]
Thanks for checking @mrpollo.

We'll have to wait for @vincentpoont2 to test fly this and then merge the GPS repo first.

**Comment by julianoes** [comment]
Flight tested, good to be merged.

**Pull request merged**
