### PR TITLE
[WIP] boards: add new mRo Pixracer Pro (M10064C)

### PR DESCRIPTION
**Pull request by dagar**
This is a new STM32H7 board with 3 IMUs and 8 PWM outputs from mRo (https://store.mrobotics.io/mRo-PixRacer-Pro-p/m10064c.htm) that's a successor the Pixracer.

Screenshot from 2020-10-10 20-48-38
Screenshot from 2020-10-10 20-49-01

### CODE REVIEW

**Comment by bresch** [comment]
Nice, except I'm not sure if it's a good idea to have dampened sensors :rofl: 

Screen Capture_select-area_20201014104053

_As nouns the difference between **damping** and **dampening** is that **damping** is the reduction in the magnitude of oscillations by the dissipation of energy while **dampening** is the act of making or becoming damp (= slightly wet)._

**Comment by pkocmoud** [comment]
You may have failed to note the other definitions of “dampen” such as:

“to check or diminish the activity or vigor of”

but if you prefer your sensors wet, we can accommodate that too 😊

**Comment by LorenzMeier** [comment]
@pkocmoud Could you give this a go to verify on hardware? We would love to merge, but it needs a flight test. A flight review link would be appreciated.

**Comment by LorenzMeier** [comment]
@dagar Could you attach a binary for Phil? Here is a reminder how to flash custom binaries: https://docs.px4.io/master/en/config/firmware.html#installing-px4-master-beta-or-custom-firmware

**Comment by berndpfrommer** [comment]
I checked out the pr-mro_pixracer_pro branch and tried to build it.
I got several warnings of the form below which I answered by 'y' and Enter, figuring it was due to the changes made  to the master branch.
```
 *******************************************************************************
 *   IF YOU DID NOT CHANGE THIS FILE (OR YOU DON'T KNOW WHAT A SUBMODULE IS):  *
 *   Hit 'u' and <ENTER> to update ALL submodules and resolve this.            *
 *   (performs git submodule sync --recursive                                  *
 *    and git submodule update --init --recursive )                            *
 *******************************************************************************


   Only for EXPERTS:
   src/drivers/gps/devices submodule is not in the recommended version.
   Hit 'y' and <ENTER> to continue the build with this version. Hit <ENTER> to resolve manually.
   Use git add src/drivers/gps/devices && git commit -m 'Updated src/drivers/gps/devices' to choose this version (careful!)

```
However, the build later failed with this error message:
```

In file included from ../../src/lib/ecl/EKF/../ecl.h:100:0,
                 from ../../src/lib/ecl/EKF/control.cpp:42:
/usr/include/newlib/math.h:18:3: error: '__ULong' does not name a type
   __ULong i[2];
   ^~~~~~~
compilation terminated due to -Wfatal-errors.
[354/1407] Generating uORB topic sources
ninja: build stopped: subcommand failed.
Makefile:217: recipe for target 'px4_fmu-v4_default' failed

```
Did I pick the right target (px4_fmu-v4_default)?

If you provide a binary I can test against that as well, but having a source tree to work with is more satisfying. In particular if it compiles :)

**Comment by dagar** [comment]
> Did I pick the right target (px4_fmu-v4_default)?

It's `mro_pixracerpro_default`. I'll give this a rebase tomorrow.

**Comment by berndpfrommer** [comment]
I tried a simple rebase but alas got the same build errors, for target mro_pixracerpro_default

**Comment by berndpfrommer** [comment]
Tested it on the master branch.
1) It builds
2) It uploads to the mro pixracer pro
3) Afterwards, QGroundcontrol no longer can connect to the board. I also couldn't get a mavlink shell response. The status light is solid green.

Note that the hardware works fine under ardupilot. Here's the log from the upload.

```
make mro_pixracerpro_default upload
[0/4] Performing build step for 'bootloader_firmware'
ninja: no work to do.
[3/4] uploading px4make mro_pixracerpro_default upload
[0/4] Performing build step for 'bootloader_firmware'
ninja: no work to do.
[3/4] uploading px4
Loaded firmware for board id: 1017,0 size: 1803853 bytes (91.75%), waiting for the bootloader...


Found board id: 1017,0 bootloader version: 5 on /dev/serial/by-id/usb-mRo_mRoPixracerPro-BL_190034000D51393132343030-if00
sn: 003400193139510d30303432
chip: 20036450
family: b'STM32H743/753'
revision: b'V'
flash: 1966080 bytes
Windowed mode: False

Erase  : [====================] 100.0%
Program: [====================] 100.0%
Verify : [====================] 100.0%
Rebooting. Elapsed Time 31.386


Loaded firmware for board id: 1017,0 size: 1803853 bytes (91.75%), waiting for the bootloader...


Found board id: 1017,0 bootloader version: 5 on /dev/serial/by-id/usb-mRo_mRoPixracerPro-BL_190034000D51393132343030-if00
sn: 003400193139510d30303432
chip: 20036450
family: b'STM32H743/753'
revision: b'V'
flash: 1966080 bytes
Windowed mode: False

Erase  : [====================] 100.0%
Program: [====================] 100.0%
Verify : [====================] 100.0%
Rebooting. Elapsed Time 31.386


```

**Comment by berndpfrommer** [comment]
probably some issue with the bootloader. Is there a way to update the bootloader from Ardupilot to PX4? I can't install any px4 firmware from qgroundcontrol. Is there a way to update the bootloader without the JTAG cable?

**Comment by dagar** [comment]
> probably some issue with the bootloader. Is there a way to update the bootloader from Ardupilot to PX4? I can't install any px4 firmware from qgroundcontrol. Is there a way to update the bootloader without the JTAG cable?

It might be the USB string changing (and QGC not updated yet). I'll take a look.

**Comment by berndpfrommer** [comment]
Today I tried using the latest QGroundControl (QGC) and indeed I can flash the firmware now by selecting Developer Build (Master), but the symptoms are ultimately the same: the device doesn't boot after flash.
Below are the messages I'm getting on the QGC console when flashing. Note that it lists the device as "ArduPilot ChibiOS".
```
QGroundControl Daily can upgrade the firmware on Pixhawk devices, SiK Radios and PX4 Flow Smart Cameras.
Plug in your device via USB to start firmware upgrade.
Found device: ArduPilot ChibiOS
Connected to bootloader:
Version: 5
Board ID: 1017
Flash size: 1966080
Downloading firmware...
From: http://px4-travis.s3.amazonaws.com/Firmware/master/mro_pixracerpro_default.px4
Download complete
MAV_AUTOPILOT = 12
Successfully decompressed parameter_xml
Successfully decompressed airframe_xml
Successfully decompressed image
Erasing previous program...
Erase complete
Programming new version...
Program complete
Verifying program...
Verify complete
Rebooting board
Upgrade complete
------------------------------------------

```

**Comment by berndpfrommer** [comment]
Tested again today: I can install the firmware (using latest from master) all from within QGroundControl. Device comes up, I can connect and configure, progress!

But the SBUS signal from my FrSky X4R-SB receiver is not working. The radio is sending the signal (identical hardware setup works for the pixracer (non-pro)), but QGroundControl does not get input signal.
Could this be related to #16871?

https://github.com/PX4/PX4-Autopilot/commit/acaf219c0f84f80b1b56c1a9d0b03a1cce3f9cf1

According to the hardware documentation, the RC input pin happens to be USART6, which is mentioned in the above commit.

**Comment by dagar** [comment]
> Tested again today: I can install the firmware (using latest from master) all from within QGroundControl. Device comes up, I can connect and configure, progress!
> 
> But the SBUS signal from my FrSky X4R-SB receiver is not working. The radio is sending the signal (identical hardware setup works for the pixracer (non-pro)), but QGroundControl does not get input signal.
> Could this be related to #16871?
> 
> [acaf219](https://github.com/PX4/PX4-Autopilot/commit/acaf219c0f84f80b1b56c1a9d0b03a1cce3f9cf1)
> 
> According to the hardware documentation, the RC input pin happens to be USART6, which is mentioned in the above commit.

@berndpfrommer I think you're right. I'm not sure what the intent is with SPI6 overlapping, but let's get it sorted out. I'll open a PR where we can continue the discussion and test.

**Comment by berndpfrommer** [comment]
More testing today, for airframe "generic ground vehicle. The tests went very well:
1. mavlink streaming on Telem2 to rosbridge worked
2. triggering external camera on ports 5 + 6 for regular time intervals worked (GPIO, signal is sent on both pins).
3. steering and throttle works the same way as on the pixracer (ports 2 and ports 4)
4. FRSKY S-port telemetry is transmitted
5. GPS seems to be detected, but could not test because robot was indoors
6. FRSKY s-bus receiver works

I have seen one strange reboot when connecting via mavlink that I don't understand where it came from. Not sure if it was poor power connection or other hardware issue. Will keep an eye on it.

**Comment by StephenCarlson** [comment]
To provide a datapoint for this WIP: I've been able to compile in Ubuntu 18.04 and upload using QGC. Using https://mrobotics.io/docs/pixracer-pro/ as the reference for the following: 
- 101/TELEM1/ttyS0 is binding to the SERIAL 5 | SERIAL 6 8-pin header.
- 102/TELEM2/ttyS1 is binding to the SERIAL 1 header.
- 201/GPS1/ttyS2 is binding to the SERIAL2 header.
- 202/GPS2/ttyS3 is binding to the GPS header, but the GPS driver isn't actually communicating properly on this header.

I'm using a mRo u-Blox Neo-M8N GPS+Compass; the compass and I2C bus seems to be working, but GPS is not being identified. Things crash when I try `gps stop` and `gps start` on the Mavlink console. Am I missing something for getting the GPS to work?

**Pull request merged**
