### PR TITLE
add uavcan imu

### PR DESCRIPTION
**Pull request by PonomarevDA**
**Describe problem solved by this pull request**
At this moment, if you need to perform hardware in the loop simulation there is only way to do it via mavlink. It's easy, but it doesn't cover hardware sensors modules such as UAVCAN sensors.

**Describe your solution**
We suggest an alternative way by using uavcan HITL simulation.
It is supposed to connect your PC with autopilot via CAN-sniffer, create one or few UAVCAN nodes on it and perform communication between the flight stack and your simulator.
The only thing we need for UAVCAN v0 is to additionally implement accelerometer and gyroscope sensors, and this pr did it.

**Test data / coverage**
We implemented dynamics simulator, uavcan communicator, connected PC and cuav v5+ via can-sniffer and perform uavcan HITL simulation as test.
Example of flight you can see here: https://youtu.be/n0GiNYDw2V4
Corresponded log file: https://review.px4.io/plot_app?log=460d59a4-c320-4de2-96e8-35f9545b672b
Another flight log: https://review.px4.io/plot_app?log=12abc158-4b12-4650-8cd9-661e458f24ea
Note: in all tests I used a little bit different version from this PR, because I added our airframe and comment internal sensors [in rc.board_sensors](https://github.com/PX4/PX4-Autopilot/blob/master/boards/px4/fmu-v5/init/rc.board_sensors) to prevent starting them by default.

### CODE REVIEW

**Review by LorenzMeier — APPROVED** [review]

**Comment by LorenzMeier** [comment]
Last question: Could you please provide the output of `top` and `free` before and after the PR?

**Comment by PonomarevDA** [comment]
I tested it without any sensors input, uavcan_mode=3.

Before PR (9f6c882d2a2f6f0f41b8f17a0c99bea39da7b21c)
master

After PR (be7f7039e2a0ff494edc750238d6d38606ad60c7)
pr

**Comment by AlexKlimaj** [comment]
I can help test this on my ARK Flow if you are interested.

**Review by JacobCrabill — APPROVED** [review]
Looks good.  Having the output of `top` while actively using these bridges would be good, though.  Also good to check - stack usage (almost every time a new SensorBridge is added, we seem to need to increase the stack size of the UAVCAN WorkQueue).

**Comment by AlexKlimaj** [comment]
Also, since my flow board has a paw3902 and a bmi088 but the paw3902 driver doesn't populate the gyro integral data, is it more useful to publish the bmi088 data as an IMU cannode message, or add it to the optical flow message?

**Comment by dagar** [comment]
> Also, since my flow board has a paw3902 and a bmi088 but the paw3902 driver doesn't populate the gyro integral data, is it more useful to publish the bmi088 data as an IMU cannode message, or add it to the optical flow message?

I'm extending the `sensors` module to process raw optical, including handling synchronization with gyro, then downsampling to publish a single message that can be consumed by the estimator or published by the CAN flow node.

Something like `sensor_optical_flow (full rate) + sensor_gyro_fifo => vehicle_optical_flow` (final naming TBD).

**Review by dagar — APPROVED** [review]

**Comment by dagar** [comment]
I think we'll need a bit more work to fully utilize IMUs on UAVCAN, but this is a great start.

**Comment by PonomarevDA** [comment]
@JacobCrabill I've captured `top` while flying in the simulator. According to it the stack usage seems to be ok, doesn't it?
Flight: [video with `top`](https://youtu.be/JmElAwgAoSc) and [corresponding flight log](https://review.px4.io/plot_app?log=7e9a0040-7dd8-4145-a556-a5f1613f5067) (Here I've turned off all internal imu, so it reduced the whole cpu usage relative to typical flight with internal imu because in my case uavcan imu has a lower rate than internal via i2c/spi).

**Pull request merged**
