### PR TITLE
commander: calibration add additional time for message reporting

### PR DESCRIPTION
**Pull request by dagar**
This is attempting to improve/fix QGC calibration status reporting. If these calibration status messages are dropped then QGC can get "stuck".

@nrogelio

### CODE REVIEW

**Comment by nrogelio** [comment]
Gyroscope calibration successful (complete in UI).
https://review.px4.io/plot_app?log=934e8457-5230-449e-816c-f389b8d32c9d

Other sensors calibration worked too.

**Comment by bkueng** [comment]
Did you really mean 600ms? Seems quite a lot.

**Comment by dagar** [comment]
> Did you really mean 600ms? Seems quite a lot.

Yes it is quite a lot, but arbitrarily copied from the existing magic mavlink propagation/padding delays.

I think we can restructure this to hold off on the param notification until after the finished message (and delay), but need to verify with mag. An actual mavlink interface for interactive calibration would be nice...

**Comment by dagar** [comment]
I've updated the branch to only do the parameter notification after the final done or failed message has been sent + delay. This seems to be still working on a random setup + okay radio. 

@nrogelio could you try again in a somewhat realistic scenario (typical radio connection)? If gyro calibration is still working we should double check a real mag cal as well.

**Comment by nrogelio** [comment]
@dagar 

Gyroscope calibration didn't work as before
https://review.px4.io/plot_app?log=9df4a939-12cf-4701-b836-a8b560fb9592

Used holybro telemetry radios 433Mhz 100mW, ground radio connected to a tablet.
Checked with QGroundControl daily and stable versions.

600ms might be a lot, but when I calibrated before, it didn't feel it was taking too long to calibrate (performed all calibrations).

**Comment by dagar** [comment]
We need to decide if this is still worth doing pre-events interface.

**Comment by dagar** [comment]
No longer needed with events.

**Pull request closed without merging**
