### PR TITLE
FW conditions for loitering for standard VTOLs

### PR DESCRIPTION
**Pull request by GaspardBesacier**
### Solved Problem
We found out that there was a problem with the loitering conditions of the drone in FW mode. Indeed, in the handle_setpoint_type function of the FixedWingPositionControl.cpp file, a part of the code is dedicated to check the position of the drone relative to the current waypoint and assess if it is possible to reach the target in FW mode. If not, the setpoint type is changed to LOITER and the drone climbs in spirals to the waypoint.
However, during our tests, we witnessed that the drone sometimes performed these transitions to LOITER mode even if the required climbs/descents were pretty slow.

### Solution
After looking at the code in detail, we found out that this switch into LOITER mode was supposed to happen when "close to waypoint, but altitude error greater than twice acceptance" (commentary in the code). However, in the code the conditions were inversed, that is not too close to the waypoint (inside two times the acceptance radius) and an altitude error greater that just one time the acceptance. We thus figured that there might be a mistake in the position of the multiplicator and moved it to correspond to the description.
As a result, we don't have the undesired LOITER phases anymore.

### Test coverage
This was tested in simulation but not on real drones (it shouldn't be a problem since the modification is pretty minor).

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
@GaspardBesacier Fixed in https://github.com/PX4/PX4-Autopilot/pull/21012 ?

**Comment by sfuhrer** [comment]
@GaspardBesacier @ThomasRigi With https://github.com/PX4/PX4-Autopilot/pull/21012 I mitigated the problem already quite a bit, but you're right, there are still cases where the switch from FOH to LOITER is happening without need. 
I though don't like these arbitrary magic factors like the "2" here. What we really want to achieve is: _Stay in FOH as long as going towards the waypoint, and leave FOH (to LOITER) only if past the waypoint._ That would be a clear geometrical condition to check, and works with any NAV_FW_ALT_RAD and horizontal acceptance radius.

**Comment by ThomasRigi** [comment]
I like the idea of a clear geometrical condition, but on first thought I would prefer to have something that can act in advance if it's already clear that you're not going to reach the WP's altitude before actually getting there. Maybe we can find a criterion that projects the current trajectory ?

**Comment by sfuhrer** [comment]
> I like the idea of a clear geometrical condition, but on first thought I would prefer to have something that can act in advance if it's already clear that you're not going to reach the WP's altitude before actually getting there. Maybe we can find a criterion that projects the current trajectory ?

Please feel free to propose something, just keep it as simple as possible.
Concerning your concern about not acting in advance of being at the WP position: I'm not sure if that's really an issue, in the end it just changes how the loiter is joined (flying through the center first). It doesn't result in the vehicle being somewhere outside of the loiter radius around the WP, so the area it flies in stays the same, independently from how it joins the loiter.

**Comment by ThomasRigi** [comment]
Wouldn't you risk something like this if you wait ? Where the first turn goes outside because of the loiter circle ? (This already happens on every hold that we trigger)
DSC_0143


Tentative (simplified) pseudo-code snippet for my idea:

```
if (dist_xy < acc_rad) {
    time_to_WP = dist_xy / groundspeed;
    projected_altitude = altitude + time_to_WP * climb_rate;
    if (abs(altitude-projected_altitude) > NAV_FW_ALT_RAD) {
        position_sp_type = position_setpoint_s::SETPOINT_TYPE_LOITER;
    }
}
```
Then stay in SETPOINT_TYPE_LOITER until you're within NAV_FW_ALT_RAD of the WP altitude.


I'm a little worried about instantaneous changes in the height rate (e.g. wind gusts) that make this statement somewhat unreliable, but for the rest I quite like it. You still have the dependency on both the L1 distance and NAV_FW_ALT_RAD, but IMO in a way that makes sense without arbitrary factors.

**Comment by sfuhrer** [comment]
> Wouldn't you risk something like this if you wait ? Where the first turn goes outside because of the loiter circle ? (This already happens on every hold that we trigger)

True, when you have the default loiter radius rather low that would happen. Valid concern.

> projected_altitude = altitude + time_to_WP * climb_rate;

What's your `climb_rate` in this case? In a perfect world this makes a lot of sense, I just worry about this kind of model (or estimator feedback) based logical conditions. Need to carefully think about the worst case scenario.

> edit: is there a way to scale down the size of images ?

Haha the real question now, no clue!


Another smaller iteration may be to just remove the loiter radius from the check, as proposed by @tstastny [here](https://github.com/PX4/PX4-Autopilot/pull/21012#discussion_r1097682996). That would keep the logic very simple but reduce the chance of unnecessarily doing a LOITER by a quite substantial factor.

**Comment by ThomasRigi** [comment]
The climb_rate is the weak spot in my condition. Just taking local_pos.vz or something is probably not reliable enough, we'd most likely have to add a filter to it to be less dependent on instantaneous disturbances. My gut feeling would be a time constant of around 1s for the filter.

And I think @tstastny has a good point in removing the loiter radius from the condition.

**Comment by sfuhrer** [comment]
Closing this as https://github.com/PX4/PX4-Autopilot/pull/21168 should be enough. Please reopen if you see evidence that that's not the case.

**Pull request closed without merging**
