### PR TITLE
Offset antenna of secondary GPS

### PR DESCRIPTION
**Pull request by JonasPerolini**
**Describe problem solved by this pull request**
EKF2_GPS_POS_X, EKF2_GPS_POS_Y and EKF2_GPS_POS_Z allow to offset the position of the main GPS antenna in the body frame but there is no variable for the secondary GPS. This might be an issue when using RTK.

**Describe your solution**
Add the same parameters for the second GPS: EKF2_GPS2_POS_X, EKF2_GPS2_POS_Y and EKF2_GPS2_POS_Z and use the correct offset depending on the GPS currently used.

**Additional Note**
In the case of GPS blending, more work would have to be done but from the comment in gps_blending.cpp, it appears that it's planned: // TODO read parameters for individual GPS antenna positions and blend

In px4-firmware/src/modules/sensors/vehicle_gps_position/gps_blending.hpp we set GPS_MAX_RECEIVERS_BLEND = 2;
In px4-firmware/src/modules/sensors/vehicle_gps_position/gps_blending.cpp blend_gps_data() if we blend the GPS, we set _selected_gps = GPS_MAX_RECEIVERS_BLEND;
Therefore shouldn't the description https://github.com/PX4/PX4-Autopilot/blob/master/msg/vehicle_gps_position.msg
"GPS selection: 0: GPS1, 1: GPS2. 2: GPS3. 3. Blending multiple receivers" be changed to "GPS selection: 0: GPS1, 1: GPS2. 2: Blending multiple receivers"

### CODE REVIEW

**Comment by dagar** [comment]
This looks correct, but there's one major issue is that we have no mechanism to enforce persistent GPS instance numbering. It will be stable when everything is working perfectly, but it fails if anything goes wrong in the field (eg GPS1 starts late or isn't working at all). The startup race condition is even worse with UAVCAN GPS units. 

To address this I was planning to introduce per sensor instance configuration parameters similar to the way we do it now for calibration.

Something like
 - SENS_GPSx_ID (device id)
 - SENS_GPSx_POS_{X,Y,Z}

This would be handled by `sensors/vehicle_gps_position` and the position offsets could be properly factored into GPS blending. We'd pass along the GPS offsets in `vehicle_gps_position.msg` for EKF2 consumption and completely remove EKF2_GPS_POS_{X,Y,Z}.

If you're interested I believe we could get the proper solution implemented and working very quickly.

**Comment by JonasPerolini** [comment]
Thank you @dagar for your reply. I was unaware of this issue.

I agree with you, passing the GPS offsets in the vehicle_gps_position.msg would be best as it allows to tackle the GPS blending offsets properly using the weights. 

How do you want to proceed?

**Comment by dagar** [comment]
> Thank you @dagar for your reply. I was unaware of this issue.
> 
> I agree with you, passing the GPS offsets in the vehicle_gps_position.msg would be best as it allows to tackle the GPS blending offsets properly using the weights.
> 
> How do you want to proceed?

Ping me on PX4 slack to discuss? I can help hack together the right solution pretty quickly if you're in a position to validate with a working setup.

**Comment by dagar** [comment]
Work in progress per GNSS instance configuration parameters. https://github.com/PX4/PX4-Autopilot/pull/19402

**Comment by dagar** [comment]
Closing in favor of https://github.com/PX4/PX4-Autopilot/pull/19402.

**Pull request closed without merging**
