### PR TITLE
Add fixed wing rate control module

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
## Describe problem solved by this pull request
The `fw_att_control` module were controlling both attitude and body rate setpoints. While this has been working great, this makes it hard to integrate other control methods on either side of the cascasded loop.

Therefore, this PR proposes adding a separate `fw_rate_control` module that pulls out the rate control functionality from the `fw_att_control` module.

## Describe your solution
This PR adds a fixed wing rate control module, where we can potentially swap out the controller to other controllers(out of tree modules)

Adding the rate controller as a separate module has the following advantages
- We can run the rate controller at a faster rate, that is appropriate for attitude control
- makes the control framework more modular, for example we can now switch the rate controller to different rate control methods (e.g. indi @kimnerd FYI)
- Cleaner interface between rate control and attitude control so that the interface for each cascaded control is clearly defined
- This moves us closer to a unified rate controller for VTOLs

This is still a WIP, and I have noticed a few things that needs to be resolved before we can actually merge this approach
- [x] This PR breaks the wheel controller - We need to decide on how to handle wheel controller (https://github.com/PX4/PX4-Autopilot/pull/20537)
  - A lot of information is just getting passed to the attitude controller just for the wheel controller
- [x] Decide on how to handle flap controls (Currently being passed through attitude setpoints)
  - Why are flaps part of the attitude setpoint?
- [x] The `fw_rate_control` still needs to subscribe to `vehicle_attitude_setpoint` message since the reset rate integral is included in the `vehicle_attitude_setpoint` (https://github.com/PX4/PX4-Autopilot/pull/20502)

## Test data / coverage
Tested in SITL

## Additional context
- This is a continuation of https://github.com/PX4/PX4-Autopilot/pull/20080

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
Backported https://github.com/PX4/PX4-Autopilot/pull/20286

**Comment by Jaeyoung-Lim** [comment]
Rebased

**Comment by Jaeyoung-Lim** [comment]
Rebased on top of https://github.com/PX4/PX4-Autopilot/pull/20502

**Comment by Jaeyoung-Lim** [comment]
@tstastny @sfuhrer This should be ready for review, since the dependency to the wheel controller has been removed.

**Comment by Jaeyoung-Lim** [comment]
@dagar @tstastny @sfuhrer Rebased as per discussion of the FW Dev call

**Comment by Jaeyoung-Lim** [comment]
Had to backport https://github.com/PX4/PX4-Autopilot/pull/15949 since the manual control setpoint message definition changed between a rebase

**Comment by dagar** [comment]
The build failures are due to parameter usage (eg FW_AIRSPD_MAX) that's stripped from the build (excluded modules).

Screenshot from 2022-12-07 12-44-02

After that's been addressed please rebase on current `main`, I've also freed up a little flash.

**Comment by Jaeyoung-Lim** [comment]
> The build failures are due to parameter usage (eg FW_AIRSPD_MAX) that's stripped from the build (excluded modules).

@dagar I see... should we separate the parameters for the rate control module?

**Comment by Jaeyoung-Lim** [comment]
@dagar I am not sure the ci failure jere is real.

The usb controller seems to have returned an error

**Comment by Jaeyoung-Lim** [comment]
@dagar There seems to be a flash shortage when building all fmuv5 variants

**Comment by Jaeyoung-Lim** [comment]
@dagar Jenkins seems to be failing now

**Comment by sfuhrer** [comment]
I flight tested it today on a small tiltrotor VTOL: https://review.px4.io/plot_app?log=ac92bb1e-befe-4afe-9240-198dfdfacd2b. Didn't notice anything extraordinary so far, looks all good!

**Comment by Jaeyoung-Lim** [comment]
@dagar @tstastny Any outstanding issues before we can get this in?

**Comment by Jaeyoung-Lim** [comment]
Rebased

**Review by dagar — APPROVED** [review]

**Pull request merged**
