### PR TITLE
Update submodule NuttX apps to latest Wed Feb  3 18:41:44 UTC 2021

### PR DESCRIPTION
**Pull request by dagar**
- NuttX apps in PX4/Firmware (e52fcdf26175f6fc0ff2c407d563ecb4d365763a): https://github.com/PX4/NuttX-apps/commit/af732cdf24d81cfbb51f7ef6189a83c2687df7c2
    - NuttX apps current upstream: https://github.com/PX4/NuttX-apps/commit/909eff540d8004371d5838b9c0764cc753d665cf
    - Changes: https://github.com/PX4/NuttX-apps/compare/af732cdf24d81cfbb51f7ef6189a83c2687df7c2...909eff540d8004371d5838b9c0764cc753d665cf

### CODE REVIEW

**Comment by dagar** [comment]
@davids5 can you verify what you'd like NuttX apps pointed at?

**Comment by davids5** [comment]
@dagar @mrpollo - It should point to the 10.0.0 commit - that was in place when we branched nuttx. It would not be a good thing to have a newer apps all is not compatible.

**Comment by dagar** [comment]
The submodule is currently pointing at `px4_firmware_nuttx-10.0.0+-bp-rejected-netmon` which isn't the default branch in https://github.com/PX4/NuttX-apps or the branch referenced in .gitmodules. Can we get it back in sync all on the same branch (px4_firmware_nuttx-10.0.0+)?

https://github.com/PX4/PX4-Autopilot/blob/3f1ca4dfc9cd3e88a61f4bef0538ecf6d651b310/.gitmodules#L44

**Comment by davids5** [comment]
Right. Yes I forgot about that.  I did not know that the Firmware PR was merged. It need to be ee36c714bff4521322532ff75b45df21ecf389a1 so that needs to be merged into apps. I will do it now,

**Comment by davids5** [comment]
@dagar, @mrpollo  PR is pending here https://github.com/PX4/NuttX-apps/pull/8

FYI: We will need to do an NuttX uptake or backport (lower risk) some useful tools. Iperf, slcan etc.

**Comment by davids5** [comment]
Please merege https://github.com/PX4/PX4-Autopilot/pull/16754

**Pull request closed without merging**
