### PR TITLE
Update mavlink submodule

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
**Describe problem solved by this pull request**
It was not possible to update the mavlink submodule(https://github.com/PX4/PX4-Autopilot/pull/16081), since sitl_gazebo required updates on the mavlink implementation

**Describe your solution**
This PR updates the mavlink submodule and in order to resolve mavlink depencencies, updates sitl_gazebo submodule

**Additional context**
- From the discussion in the PX4 dev call on 18/Nov/2020, we decided that mavlink c libraries should not be installed as part of the px4 simulation containers. Removed in https://github.com/PX4/PX4-containers/pull/287
- This PR replaces https://github.com/PX4/PX4-Autopilot/pull/16081

### CODE REVIEW

**Comment by igorsgcampos** [comment]
Dear @Jaeyoung-Lim, 

This update stops just short of https://github.com/mavlink/mavlink/tree/59467b88519393ccce841278d407967c22cb30b6, which is needed for PR https://github.com/PX4/PX4-Autopilot/pull/15882, can you kindly update the mavlink submodule to track this newer commit in order to have this PR unblocked?

Thanks for your attention!

Regards,

Igor

**Comment by igorsgcampos** [comment]
The commit from the build bot for this version is: bcff0cf5de2cd2e50bc610b4dae5d4ba9fa5ad60

**Comment by dagar** [comment]
@igorsgcampos this unblocks the ability to update mavlink again, you can use the desired submodule version in your PR.

**Review by dagar — APPROVED** [review]
Thanks for fixing this @Jaeyoung-Lim

**Comment by igorsgcampos** [comment]
> @igorsgcampos this unblocks the ability to update mavlink again, you can use the desired submodule version in your PR.

I just tried that, but now it says that there are conflicts that need to be resolved, but I only updated the submodule. I don't understand what went wrong.

**Pull request merged**
