### PR TITLE
NuttX disable priority inheritance and adjust default priorities

### PR DESCRIPTION
**Pull request by dagar**
Do we actually need priority inheritance? Do we have any potential issues with priority inversion? How do we identify potential issues both now and in the future?

#### Possible sources of thread interaction to review in detail
 - [x] param save (commit)
     - there's actually very little param writing from modules (param_set), perhaps a non-blocking param_tryset() would make sense?
 - [x] dataman
 - [x] cdev
    - significantly reduced in the system, but still the core of uORB
 - [x] ~~differentiate usage with pthread mutex vs semaphores?~~ (enabled/disabled system wide with CONFIG_PRIORITY_INHERITANCE)

#### Benefits
 - memory savings (~ 8kB)
 - flash savings (~ 4.5kB)
 - cpu savings (~ 3-5%)
 - improved worst case interrupt latency
 - appeal to authority
> "Friends don't let friends use priority inheritance".
> 
> Just don't do it. If you really need it, your system is broken anyway.
> 
>   Linus

### CODE REVIEW

**Comment by dagar** [comment]
Idea: create a special instrumented build variant to detect and log possible cases of priority inversion to review.

**Comment by bkueng** [comment]
I can imagine that in certain situations (e.g. bootup or computation after calibration) the latency of high-prio tasks is a bit higher, but as we generally don't have long-running tasks (and avoid running at very high cpu load) I don't think disabling it is an issue.

However there's a safety aspect to it as well: it means that a lower-prio task running busy might block a high-prio task from running.

**Comment by dagar** [comment]
I'm not sure I'm thinking about this the right way, but overall it actually doesn't seem that bad given the focus on short WorkItem cycles running to completion and threads for resource access.

The concerning case that comes to mind is param autosave performed from LPWORK with the possibility of the highest priority flight critical modules (eg mc_rate_control) blocking on a param get. At a minimum we could consider bumping that up to `wq:hp_default` that's running just beneath the controllers to minimize the impact of any priority inversion (kept within the "flight critical" region above mavlink, logger, vmount, etc).

If necessary we could also insert temporary priority boosts in things like the locked portion of param_set_internal().

Beyond that potential issues around dataman (mavlink/navigator), logger, etc seem like a wash.

Does anything else scary come to mind?

**Comment by dagar** [comment]
While debugging something else I casually took a look at the semaphore holder activity under normal usage, and so far I haven't even hit a case where we've had to boost the priority of other threads holding counts on a semaphore.

https://github.com/PX4/NuttX/blob/863ed53e3fb1cebbb0832ec28fbc11e16566e89e/sched/semaphore/sem_holder.c#L1015-L1025

https://github.com/PX4/NuttX/blob/863ed53e3fb1cebbb0832ec28fbc11e16566e89e/sched/semaphore/sem_holder.c#L328

**Comment by LorenzMeier** [comment]
Closing as stale.

**Pull request closed without merging**
