### PR TITLE
Standalone extension to PX4 to launch it independently of Gazebo

### PR DESCRIPTION
**Pull request by frede791**
### Solved Problem
When launching PX4 using `make px4_sitl` you will always launch Gazebo as well. However, in some cases, for example when the host running Gazebo and the host running PX4 are not on the same machine, it is undesireable to launch both with one command. By setting the `STANDALONE` environmental variable, you can launch PX4 independently of Gazebo sim. PX4 will launch and look for a node running gazebo until it is found. Gazebo can be started independently using `gz sim --r /path/to/world.sdf`. Once both services are launched, the PX4 model will pop into existence in Gazebo. 

In order to make this work, several amends had to be made:
1. In the sdf file of the model, webserver paths to Gazebo fuel are provided rather than the local paths to the meshes. This increases flexibility when working on multiple devices. This also means that local mesh directories can be removed entirely as all meshes are now hosted on Gazebo fuel.
2. In `GZBridge.cpp`, rather than using the `set_sdf_filename` method that links to a file in the repository (which is then read by Gazebo), the `sdf_file` function is used to read out the file in its entirety and send that over to the simulation. 

### Changelog Entry
For release notes: Ability to launch Gazebo independently of PX4.

```
New parameter: STANDALONE
```

image
Warning that is thrown by PX4 when STANDALONE env variable has been set but no gazebo simulation has been found. This warning disappears once Gazebo has been started.

### CODE REVIEW

**Comment by dagar** [comment]
FYI the intent with the new (Ignition) Gazebo interface was that PX4 should be a completely independent piece that connects into the sim, and only directly launches the server if necessary. We may have let this slip a bit as the lazy default of launching within a px4 build took hold.

Then for the models I wanted to make sure we have at least a simple quadcopter in tree, but beyond that I wanted to keep them separate so we don't bloat the git repo. Ideally I was thinking we put them in https://github.com/PX4/PX4-gazebo-models, but keep it completely in sync with PX4 on fuel. https://app.gazebosim.org/PX4

**Comment by frede791** [comment]
The main issue I've encountered is that I cannot run the models when the meshes are stored on Github. I think this is because Gazebo limits the search path to the fuel webserver and local directories. So storing it in fuel and copying it over to: https://github.com/PX4/PX4-gazebo-models is probably the best way. 
Do you know who runs the PX4 Gazebo fuel account? I currently have the mesh paths linked to my own fuel account but it would obviously be nicer to have them link to the PX4 account.

**Comment by dagar** [comment]
> Do you know who runs the PX4 Gazebo fuel account?

I created it.

> @dagar I think uploading the models to fuel and linking them in the sdf file is probably the cleanest and most size-efficient way. As a backup we could also save them in the https://github.com/PX4/PX4-gazebo-models repo, but we shouldn't primarily rely on that.

I'd like everything to be on fuel for discovery, drag and drop world building, etc, but ultimately shouldn't the repo (https://github.com/PX4/PX4-gazebo-models) be the original source for collaboration? Then keep everything in sync via gz fuel upload/update.

I'd love to see more collaboration (hopefully via Fuel) beyond the PX4 ecosystem, as much as possible our models and worlds shouldn't be PX4 specific. We also have to keep in mind there will be many companies that use this in private, so whatever we do let's make sure it's as easy (or obvious) as possible for people to also add and maintain models directly in tree (or on the side) without ever going to fuel.

**Comment by frede791** [comment]
Makes sense. Do you want to upload the meshes to the PX4 fuel account and set the paths in sdf to that account? I can start uploading models to https://github.com/PX4/PX4-gazebo-models. Perhaps there is a way to set a github action that uploads/updates a mesh to fuel whenever a new version of the mesh is uploaded in Gazebo uising the gz fuel library? 

Do you still want to continue to keep the meshes in the PX4-Autopilot tree even if they are already in https://github.com/PX4/PX4-gazebo-models? It feels unnecessary to me.

**Comment by dagar** [comment]
> Makes sense. Do you want to upload the meshes to the PX4 fuel account and set the paths in sdf to that account? I can start uploading models to https://github.com/PX4/PX4-gazebo-models. Perhaps there is a way to set a github action that uploads/updates a mesh to fuel whenever a new version of the mesh is uploaded in Gazebo uising the gz fuel library?


> Do you still want to continue to keep the meshes in the PX4-Autopilot tree even if they are already in https://github.com/PX4/PX4-gazebo-models? It feels unnecessary to me.

I don't really want to keep anything in PX4-Autopilot, other than the bare minimum basic quadcopter simulation so that if someone clones PX4 before boarding a long flight they at least have something to play with.

**Comment by frede791** [comment]
Modified paths to point to PX4 fuel server.

**Pull request closed without merging**
