### PR TITLE
NuttX with Backport of stm32h755II missing changes

### PR DESCRIPTION
**Pull request by davids5**
Changes that were need but not included.

Also brings in https://github.com/PX4/NuttX/pull/314 - [BACKPORT] stm32h7: allow Ethernet MAC without PHY

### CODE REVIEW

**Comment by davids5** [comment]
@julianoes  @bugobliterator Would you please test this again.

**Comment by bugobliterator** [comment]
> @julianoes @bugobliterator Would you please test this again.

Tested working for CubeOrangePlus and CubeOrange

**Comment by jfbblue0922** [comment]
@davids5 
I have confirmed that it works correctly.
Thank you for your BACKPORT.

**Comment by davids5** [comment]
@dagar 
 https://github.com/PX4/NuttX/pull/313 was merged. 

This PR is ready. - Tested and repointed.

**Comment by davids5** [comment]
Merged in https://github.com/PX4/PX4-Autopilot/pull/23311

**Pull request closed without merging**
