### PR TITLE
create hovergames airframe

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
Is the Hovergames config locked down or is it going to evolve over time?

**Comment by dagar** [comment]
https://github.com/PX4/Firmware/issues/12037

**Comment by igalloway** [comment]
@dagar the airframe and hardware is locked down. I don't know what the best tuning parameters are to use. Most people that build it i notice it is quite twitchy - are the racing copter parameters still the default?

**Comment by TSC21** [comment]
@dagar @igalloway are we missing something here?

**Comment by jarivanewijk** [comment]
@dagar, do you have time to help us revive this? HoverGames challenge 2 will start soon and it would be great to have our own airframe.

I believe the settings in this PR were copied from the generic S500 config, which is probably a good starting point. We have been using those settings for a while and they give decent results, though it seems to be very sensitive to vibrations. Note that we just used the S500 settings, we do not actually have an S500 frame. I believe we use almost the same frame as what Holybro now sells as X500.

We may need a little help with tuning, which we have little experience with. However, we have a few guys with different setups that can maybe help with testing. @PetervdPerk-NXP @dk7xe @igalloway (Landon is not on GitHub it seems?)

Most participants will use our drone kit with a 4000-5000mAh 3S or 4S battery, so the tuning has to be appropriate for such setups. However, as more add-on components become available the total weight, weight distribution and vibration levels of the drone may change as well.

**Comment by jarivanewijk** [comment]
@dagar @igalloway - Would it be possible to get this merged in the current state? The current PID tuning values have been used for almost two years without any major issues, I think.

(Only thing that would need to change is the airframe ID, 4016 has already been used for the Holybro PX4 Vision devkit).

**Comment by dagar** [comment]
> @dagar @igalloway - Would it be possible to get this merged in the current state? The current PID tuning values have been used for almost two years without any major issues, I think.
> 
> (Only thing that would need to change is the airframe ID, 4016 has already been used for the Holybro PX4 Vision devkit).

I'll rebase it.

**Comment by dagar** [comment]
I've rebased this branch on current master.

@jarivanewijk if you or @igalloway could share one or more representative good logs then I can do a quick pass and incorporate that tuning.

**Comment by igalloway** [comment]
Here is a log of my second last flight. The tuning parameters are good
https://logs.px4.io/plot_app?log=83b6a525-f1f3-4947-98c1-9507ec7b801b
Note there is a separate problem with the battery gage that I'm checking - i think there may be a code or parameter problem. The battery may be reporting 100% all the time.

Here's a second log - flight characteristics ok ,but we had some odd problem at the end while hovering before landing
https://logs.px4.io/plot_app?log=f53dabf1-a0fb-433e-8ba8-f09c569db684

**Comment by jarivanewijk** [comment]
@dagar Are the flight logs provided by @igalloway good enough? Iain mentions some problems, but the flight itself was OK. Do you need any more flight logs to confirm? (Doesn't the flight test team have a HoverGames drone with FMUK66 as well?)

**Review by igalloway — COMMENTED** [review]
@dagar 
Could you change the code be '4017_nxp_hovergames' and name be 'NXP HoverGames'
After that can we get it merged?
Thanks

**Review by igalloway — CHANGES_REQUESTED** [review]
@dagar 
Could you change the code be '4017_nxp_hovergames' and name be 'NXP HoverGames'
After that can we get it merged?
Thanks

**Review by igalloway — CHANGES_REQUESTED** [review]
@dagar i updated the two files mentioned. Not sure if we can still use 4017 as the NXP HoverGames drone id?

**Pull request merged**
