### PR TITLE
UAVCANv1 menuconfig proposal

### PR DESCRIPTION
**Pull request by PetervdPerk-NXP**
Regarding the unification attempt for FMU's and Node's of the UAVCANv1 implementation we want to create compile time configurations, to do this using manual CMake defines can be a bit tedious.

This PR proposes the use of menuconfig to configure a UAVCANv1 node, using make <target> uavcanconfig, the configuration will be saved in boards/<board>/uavcanconfig and can be easily be modified. Furthermore this helps with boards that are multipurpose e.g. the UCANS32K146 can act as a GNSS node but also as an IMU node. Thus you can create seperate UAVCAN configurations for that.

uavcan_menuconfig

### CODE REVIEW

**Comment by dagar** [comment]
This is interesting, just be aware that a lot of people don't have menuconfig installed.

We carry a python version in tree. https://github.com/PX4/PX4-Autopilot/blob/master/platforms/nuttx/NuttX/tools/menuconfig.py

**Comment by PetervdPerk-NXP** [comment]
> We carry a python version in tree

Okay thanks didn't knew about that, added a check for kconfig and created a fallback to the python implementation if kconfig isn't installed.

**Review by JacobCrabill — APPROVED** [review]
Very cool - hope to try this out later this week, but if it doesn't really touch anything outside of UAVCAN v1, let's bring it in.  Looks like a really nice way to configure CAN peripherals.

**Comment by PetervdPerk-NXP** [comment]
Actually it doesn't do anything yet, except providing a GUI for menuconfig and defining the Kconfig defines when set in the uavcan_v1 driver. 

If this is correct way to work out compile time configuration in PX4 should still be discussed I think. Since this approach doesn't scale to other applications. @davids5 suggested that we can turn it around and move the menuconfig into the board BSP folder which allows to change non-UAVCAN configuration as well, however does this usecase exist and furthermore it will complicate the whole PX4 CMake configuration.

@mrpollo would it be something to discuss this during the devcall tomorrow?

**Comment by davids5** [comment]
Look at it from an OOD perspective. The Board "is a {FB,BX,FLEX}CAN device (has a Soc that has a CAN ctrl) and "has n" CAN interfaces" "has a" RGB LED, "has a PWM" .... The xxxxx.cmake make the composite (adds the modules).  in this case adds "uavcanxxx" What better place for the "many boards" to one module" relationship to control it? 

A factory pattern would work well here the messy ifdefs can be hidden in one place. The sexier approaches like static construction (included add your self to the list) is nice, but relies on the C++ run before `main` or other linker magic). But the bottom line is that board has to enable the modules it supports for it's HW.

**Comment by dagar** [comment]
> to do this using manual CMake defines can be a bit tedious

I agree, I just want to be careful before introducing special mechanisms for individual modules/drivers that are solving the same type of problem we have all over the place.

**Comment by PetervdPerk-NXP** [comment]
https://github.com/PX4/PX4-Autopilot/blob/a03b02313c1301534d95293e6e6ced2853e58a12/src/drivers/uavcan_v1/CMakeLists.txt#L34

So UAVCANv1 configs that are generated are unique for each board + label combination.

Regarding the question on the dev call today if there are better alternatives to kconfig/menuconfig. I've actually no idea, but I'm open to suggestions if someone knows a better config system can be integrated with CMake.

**Comment by PetervdPerk-NXP** [comment]
Replaced by #17100

**Pull request closed without merging**
