### PR TITLE
[WIP] WindEstimator: use SymForce auto-generated function for airspeed fusion

### PR DESCRIPTION
**Pull request by bresch**
Opening for discussions.

## Describe problem solved by this pull request
Our python scripts generating c++ code for the estimators requires quite some additional copy/paste and manual modification work. This always takes time and is prone to human errors.

## Describe your solution
This PR shows that we could automate much more by using the recently open-sourced [SymForce](https://github.com/symforce-org/symforce) code generator.

~NOTE: I had to slightly modify the source code of SymForce in order to produce this auto-generated code using our `Matrix` library instead of `Eigen` and `std`; I still need to find a way to implement it nicely in order to have it accepted in the official SymForce.~
Edit: code generation now uses an unmodified SymForce build and applies search-replace at the end to translate the cstdlib and Eigen into PX4-compatible code

## Describe possible alternatives
Continue to maintain and improve our own code generator

## Test data / coverage
SITL tested

### CODE REVIEW

**Comment by RomanBapst** [comment]
@bresch Good idea!

**Comment by dagar** [comment]
Updated to use cmath std::pow (https://github.com/PX4/PX4-Autopilot/pull/19893).

**Comment by bresch** [comment]
Added a unit test to verify the singularity handling using `epsilon` works properly.

**Comment by bresch** [comment]
Flight test showed good results (`airspeed_wind.01` is this estimator using airspeed fusion to get the scale factor too; `wind.00` is this estimator with sideslip fusion only; `wind` is from EKF2):

DeepinScreenshot_select-area_20220727101937

**Review by dagar — APPROVED** [review]

**Comment by RomanBapst** [comment]
@bresch Why does the estimate from the ekf look so unstable? Not related to this PR but still wondering what's up there.

**Comment by sfuhrer** [comment]
> @bresch Why does the estimate from the ekf look so unstable? Not related to this PR but still wondering what's up there.

Maybe because of the airspeed scale that the EKF used was still quite off? 
https://github.com/PX4/PX4-Autopilot/pull/19978 would accelerate this.

**Comment by bresch** [comment]
@RomanBapst Yes, it's because it has the wrong scale factor. Thanks for the PR @sfuhrer

**Pull request merged**
