### PR TITLE
RTL fixes and improvements for VTOL vehicles

### PR DESCRIPTION
**Pull request by kibidev**
**Update 2023-02-01**
This PR does not longer include the original MC descend alterations in RTL, but instead just fixes the addtional issues found int the process. This PR now:
- Fixes VTOL FW landing bug
- RTL_STATE_HEAD_TO_CENTER is not longer dependent on whether loiter is used or not.
- MC will use descend state, independent of whether loiter is used or not.
- Fix acceptance radius for mission item prior to VTOL transition by setting _mission_item.vtol_back_transition

**Describe problem solved by this pull request**
The main problem I set out to solve was that a VTOL RTL is too slow/consumes to much battery when landing at rally points with altitude different than home altitude. This is because MPC_LAND_ALT1/MPC_LAND_ALT2 do not consider rally point altitude, and it is therefor not possible to tune the land and descend speeds so that you get both a soft landing and a fast descent until you are close to the ground. For VTOLs we can not use RTL_DESCEND_ALT for this wither, since it must be set high enough for a safe FW loiter, which can be too high to do a slow MC descend from.

During this process, I found other issues with RTL that I have addressed as well:
  - If RTL_LAND_DELAY > 0, VTOLs will do a FW landing, this bug was introduces in https://github.com/PX4/PX4-Autopilot/pull/16582
  - RTL_STATE_HEAD_TO_CENTER is dependent on whether to loiter or not. It would be desired to have same functionality for  VTOL transition/movement no matter if loiter is used or not.
  - MC and VTOL in MC will skip descend state if there is no loiter. I under stand the rationale that in most cases the behavior will be almost the same if MPC_LAND_ALT1/MPC_LAND_ALT2 is set correctly, but as described above this is not possible for rally points with altitude different than home.
  - Acceptance radius for VTOL landing in RTL is different than normal VTOL landing, since state prior to VTOL transition do not set _mission_item.vtol_back_transition. This can cause some overshoot and possible unnecessarily aggressive maneuvering.

**Describe your solution**
The main issue is fixed by introducing a new parameter RTL_DESCEND_MC and a new RTL state RTL_STATE_MC_DESCEND. RTL_DESCEND_MC gives an altitude for a MC (or VTOL in MC) to descend to (at speed MPC_Z_V_AUTO_DN) before starting the landing (at a slower speed). For VTOL in FW, this state will be entered after first descending to RTL_DESCEND_ALT and loiter and transition to MC. For MC and VTOL in MC, this state will be entered after return. That means that RTL_DESCEND_ALT and RTL_LAND_DELAY will not be used at all for MC.

**Describe possible alternatives**
MPC_LAND_ALT1/MPC_LAND_ALT2 could be fixed to account for rally point altitude, which may solve some, but not all RTL VTOL issues.

**Test data / coverage**
Tested in simulator with standard VTOL.
Could use some help to test pure MC and FW behavior.

**Additional context**
RTL time prediction is not changed. The prediction seems to be fairly rough for VTOL anyway, so I consider it safe to ignore the these changes and they will not make the RTL time worse.

### CODE REVIEW

**Comment by kibidev** [comment]
Here is state diagrams before/after:

rtl1
rtl3

I also pushed a small update to handling of MC from DESCEND state. Normally, we should not longer be in DESCEND state for a MC, but it might be a good idea to handle it from completeness.

**Comment by ThomasRigi** [comment]
I totally agree that the slow landing on rally points below home is an issue.  (Or hard landing, if the rally point is above home.) But it's not only an RTL issue. The same issue occurs when you have a land WP below home altitude. So rather than fixing it only for RTL by introducing a new state, I'd rather have it fixed in all cases by reworking https://github.com/PX4/PX4-Autopilot/blob/main/src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.cpp#L176 to take into account the known ground altitudes. I don't have the full overview if you could just take the `vehicle_local_position_setpoint.z` or `_sub_triplet_setpoint.get().current.alt`.

If that for some reason doesn't work, I'm ok with adding the new state. It's basically the same as I do to work my way around mission land WPs that are below home : I just set a normal WP 10-15m above the Land WP to have a fast descent until the lidar picks up. But I wouldn't introduce a new parameter. Why not just use MPC_LAND_ALT1 instead ?

**Comment by kibidev** [comment]
Thanks for your feedback @ThomasRigi 

I would prefer not to mix MPC_LAND_ALT1 into RTL.
It do not logically make sense to me to use it in the RTL module at all, and also MPC_LAND_ALT1 is used during landing, while the proposed new RTL_DESCEND_MC would be relevant before landing.

We use the same approch as you for WP landing at different altitude, minus lidar at the current setup. I think this works OK.
As a part of this we have set MPC_LAND_ALT1/MPC_LAND_ALT2 to 9999/9998 to disable them, and use a fixed landing speed during the entire landing phase.

Fixing MPC_LAND_ALT1/MPC_LAND_ALT2 to account for RP and WP altitude would be very good, but it still will not account for all landing scenarios, for example an landing away from any RP/WP. For that reason, I think it still would make sense to have a fast MC descend state in RTL, so that you can use a conservative landing speed from all altitude as a default, and then speed it up whenever you have altitude data available.

I have tried to find alternative without adding a new parameter to RTL, but I find that while the current parameter set is good for both MC and FW vehicles, it does not cover all VTOL use cases.

**Comment by KonradRudin** [comment]
Hey, as far is a can see, we have the altitude above ground available for a safe point here:
https://github.com/PX4/PX4-Autopilot/blob/main/src/modules/navigator/rtl.cpp#L212
And it gets written into the mission item here:
https://github.com/PX4/PX4-Autopilot/blob/main/src/modules/navigator/rtl.cpp#L546
and thus is also written in the position setpoint. So the flight task should use this altitude instead of the home position altitude in the Flight task as suggested by @ThomasRigi . I don't know why this is not used already (probably because the land mode set the altitude to absolute zero, so we would need to make sure to only use valid altitudes from the position setpoint). With that, you would be able to use the normal MPC_LAND_ALT1/MPC_LAND_ALT2 to land. I know this does not work for the general case, where the landing altitude is not known or in case of the land mode, where the altitude is set to 0, but RTL always tries to land at a known position with known altitude so a fix for this should be in the flightTask directly, i guess. 
Your other addressed issues in the RTL seems to be fine.

**Comment by kibidev** [comment]
Thanks you for feedback, @KonradRudin.

I see your points regarding MPC_LAND_ALT1/MPC_LAND_ALT2, and I agree that they should account for RTL altitude. Unless someone else is working on it, I might have a look at it later. However, this will also mean that we either do not use MPC_LAND_ALT* when ground level is unknown (which is not desired if you just want to land manually a short distance from home on a level field), use MPC_LAND_ALT* with e.g. home altitude when ground level is unknown (which is not desired when you e.g. need to directly command landing at a long flight. It might be an edge case, but I have a feeling that solving land altitude in general calls for much broader discussion to capture all scenarios.

And having a separate MC descend in RTL does not block or impacts solving of MPC_LAND_ALT* for other altitudes than home, so it is possible to do both.

But should I not be able to convince you, is it a state flow like this we can use as a basis?
rtl5

**Comment by ThomasRigi** [comment]
Thanks @KonradRudin for looking into it. So we have established:
1.  For RTL we can easily use the rally point altitude in the flight task, we just need the flight task to consider the altitude that's already there in the position_setpoint_triplet.current.
2. For a mission landing we can do exactly the same. (As per https://mavlink.io/en/messages/common.html#MAV_CMD_NAV_LAND, the altitude is the ground level)
3. If you land at a random spot, the altitude of the position_setpoint_triplet.current is set to 0 AMSL. 

For 3., I would argue that this is ok (or put it to -500m AMSL, to rule out all of https://en.wikipedia.org/wiki/List_of_places_on_land_with_elevations_below_sea_level). It means that you would descend fast until the lidar says that you're close to ground. Without lidar you'd experience a hard landing, but that's IMO the less bad option compared to defaulting to a slow descend. But I might be biased here from our usecase (BVLOS deliveries), where if we need to trigger an unplanned Land in the middle of a flight it means that we're in deep trouble and need to get to the ground asap. Independently of our use case, I've never liked the dependency on home altitude. In general the earth is not flat. If I can't convince you here on my argumentation, we can surely build an if-statement to treat this case separately.

On the implementation: So far `_evaluateDistanceToGround()` lives in the parent class FlightTask, which has no notion of the position setpoint triplets. I reckon it's best to override this function in FlightTaskAuto to do explicitly what we want there without potentially affecting other flight tasks.

**Comment by ThomasRigi** [comment]
@kibidev I'm probably not the best reference for the RTL state machine because I never really checked all the details in it, but your latest outline looks sensible to me.

**Comment by KonradRudin** [comment]
@kibidev maybe i missed a point but why do you want to explicitly want a descend before land in the MC RTL case. They both should be doing the same by descending at the same speed when the landing flight task would use the correct altitude (unless for landing when we are close to the ground). On the other hand, it won't hurt so i would be fine with the proposed state machine.

**Comment by KonradRudin** [comment]
> Thanks @KonradRudin for looking into it. So we have established:
> 
> 1. For RTL we can easily use the rally point altitude in the flight task, we just need the flight task to consider the altitude that's already there in the position_setpoint_triplet.current.
> 2. For a mission landing we can do exactly the same. (As per https://mavlink.io/en/messages/common.html#MAV_CMD_NAV_LAND, the altitude is the ground level)
> 3. If you land at a random spot, the altitude of the position_setpoint_triplet.current is set to 0 AMSL.
> 
> For 3., I would argue that this is ok (or put it to -500m AMSL, to rule out all of https://en.wikipedia.org/wiki/List_of_places_on_land_with_elevations_below_sea_level). It means that you would descend fast until the lidar says that you're close to ground. Without lidar you'd experience a hard landing, but that's IMO the less bad option compared to defaulting to a slow descend. But I might be biased here from our usecase (BVLOS deliveries), where if we need to trigger an unplanned Land in the middle of a flight it means that we're in deep trouble and need to get to the ground asap. Independently of our use case, I've never liked the dependency on home altitude. In general the earth is not flat. If I can't convince you here on my argumentation, we can surely build an if-statement to treat this case separately.
> 
> On the implementation: So far `_evaluateDistanceToGround()` lives in the parent class FlightTask, which has no notion of the position setpoint triplets. I reckon it's best to override this function in FlightTaskAuto to do explicitly what we want there without potentially affecting other flight tasks.

To 3.: Maybe it would be better to use a NaN value there, to explicitly state, that we do not know the ground altitude at this place. 
To the implementation: there is also the `_prepareLandSetpoints()` function in the flighttaskauto, where you may set the correct landing ground altitude if it is known. Then set in `_evaluateDistanceToGround()` the distance from the sensor, if available, else, the landing ground altitude if available, else either home or a default altitude. I guess the home altitude is still a remnant of the early days, when the use case was mostly VLOS flights close in range to the pilot.

**Comment by kibidev** [comment]
> @kibidev maybe i missed a point but why do you want to explicitly want a descend before land in the MC RTL case. They both should be doing the same by descending at the same speed when the landing flight task would use the correct altitude (unless for landing when we are close to the ground). On the other hand, it won't hurt so i would be fine with the proposed state machine.

I think the outlined solutions to the other modules probably would be fine for us as well. If we are able to fix this and have it in the same release as the RTL fixes, I will be great. For now we will run our own branch where we use the MC descend state, and the just discard this state when we move to 1.14 or whatever this fix will be included in.

I can remove the relevant commit, and then just check that I have not missed anything in the state machine and test a bit.
Do you have any preference to how to implement suggestions from reviews? Is a rewritten history and a force-commit OK, or would you prefer new commits (in this case a revert commit)? I am partial to rewritten history myself, as I find the resulting main branch easier to follow.

**Comment by KonradRudin** [comment]
> I can remove the relevant commit, and then just check that I have not missed anything in the state machine and test a bit.
> Do you have any preference to how to implement suggestions from reviews? Is a rewritten history and a force-commit OK, or would you prefer new commits (in this case a revert commit)? I am partial to rewritten history myself, as I find the resulting main branch easier to follow.

A rebase and force commit is fine for me, especially at this early level in the design decision. Also like your visualization of the state machine btw.

**Comment by kibidev** [comment]
Great, I have updated the PR now.

**Comment by kibidev** [comment]
@KonradRudin will you need anything else from me to complete the review?

**Review by KonradRudin — COMMENTED** [review]
Hey, sorry, i missed, that you already updated the PR. The changes look good, but you missed the formatting. Just do a make format and squash this into the last commit.

**Comment by kibidev** [comment]
> Hey, sorry, i missed, that you already updated the PR. The changes look good, but you missed the formatting. Just do a make format and squash this into the last commit.

Ah, sorry, I didn't catch that error. Fixed now @KonradRudin.

**Review by KonradRudin — APPROVED** [review]

**Comment by KonradRudin** [comment]
Hey @kibidev i have created an issue for the rally point landing at different altitude. Can you check if this is correct and fill in the additional details (More explanation, logs etc. if available)? I just don't want it to get forgotten when this PR gets closed.

**Pull request merged**
