### PR TITLE
Navigator: Geofence improvements

### PR DESCRIPTION
**Pull request by sfuhrer**
### Solved Problem

Fixes: 
1) listen to GF_SOURCE (fixes https://github.com/PX4/PX4-Autopilot/issues/20677)
2) do not constantly send new reposition waypoints when GF is breached as a fixed-wing

New features:
3) if armed, do not allow to upload GF that would immediately trigger
4) do not allow to upload GF if it doesn't contain Home (to not break RTL)

Functional changes (neither new features nor fixes):
5) has to be in all inclusion GF 
6) remove GF_ALTMODE (with the big baro offset usually present this is quite unusable)
7) remove GF_COUNT (don't see need, don't find it intuitive)
8) change messaging
9) some code cleanup

### Solution
1) correctly listen to it.
2) if GF_ACTION is HOLD, and GF is breached: stay in the "GF breached mode" until the current loiter is changed (through new reposition or change of mode) --> see https://github.com/PX4/PX4-Autopilot/commit/66ca5c294952689e0775c5136ad0d7f6604a2d17
3) check GF breach in update function, and stop updating the current GF if it would immediately get breached --> see https://github.com/PX4/PX4-Autopilot/commit/83f3665d9576b453142196c2e4725e46728d1f46
4) check GF breach in update function, and stop updating the current GF if it doesn't contain Home --> see https://github.com/PX4/PX4-Autopilot/commit/83f3665d9576b453142196c2e4725e46728d1f46
5) Change logic that all GF action already gets triggered when the GF leaves one inclusion GF, not only when outside of all inclusion GF. 
I'm not entirely sure what we want, but for me it seems cleaner that way.
6) remove it.
7) remote it.
8) see https://github.com/PX4/PX4-Autopilot/commit/8e1c3e8093e3da0dbe9a276eb01d2672d7cd190b:
 - geofence_result.cpp contains to contain separate fields for the 3 geofence types
 -  remote "primary" from messages, as we don't distinguish primary vs secondary etc
 - do all user notification due to GF breach from Commander
9) various 

### Changelog Entry
For release notes:
```
Bugfix: Geofence: correctly listen to GF_SOURCE
Bugfix: Geofence: do not constantly send new reposition waypoints when GF is breached as a fixed-wing
Feature: Geofence: if armed, do not allow to upload GF that would immediately trigger
Feature: Geofence: do not allow to upload GF if it doesn't contain Home (to not break RTL)
Documentation: TODO
```

### Alternatives
We should also fix the pre-emptive geofence triggering (GF_PREDICT=1). I haven't touched that in this PR, and even split it up further (without GF_PREDICT=1 it will now always set the Hold point at the position it is currently at).

### Test coverage
SITL tested

### Context
Screen recording with current main, where issues 4) and 2) are visible:

https://github.com/PX4/PX4-Autopilot/assets/26798987/87cd8a30-1768-493f-afa6-9ce8dc84ac27

Screen recording of this PR, where the new features 3) and 4) are shown, plus fixed 2):

https://github.com/PX4/PX4-Autopilot/assets/26798987/2469124f-63e4-4f1e-9ac4-5315b2d020da

### CODE REVIEW

**Comment by MaEtUgR** [comment]
Maintainers call: Would be nice to have an automated test for this e.g. MAVSDK test using https://github.com/mavlink/MAVSDK/blob/main/examples/geofence/geofence.cpp

**Review by mcsauder — APPROVED** [review]
This is a nice simplification and improvement.  Thanks @sfuhrer !

**Review by dagar — APPROVED** [review]

**Review by Drone-Lab — COMMENTED** [review]
Hello @sfuhrer  ! It appears there might be a potential issue with the invocation of the checkMissionAgainstGeofence() function when only the geofence undergoes an update.  The problem is related to the state machine and asynchronous message reading in geofence.cpp.I'm here to assist further if needed.

**Comment by sfuhrer** [comment]
> Hello @sfuhrer ! It appears there might be a potential issue with the invocation of the checkMissionAgainstGeofence() function when only the geofence undergoes an update [484a44e](https://github.com/PX4/PX4-Autopilot/commit/484a44e5e97c24ef74d108d26725d38f73db5e39) . The problem is related to the state machine and asynchronous message reading in geofence.cpp.I'm here to assist further if needed.

Hi! Do you mean that when you update the geofence, you would want the mission feasibility checks to be run again it, and then
- reject the geofence update if the mission feasibility check then would fail
- make the mission invalid

?

**Comment by Drone-Lab** [comment]
> Hi! Do you mean that when you update the geofence, you would want the mission feasibility checks to be run immediately against it, and then
> 
> * reject the geofence update if the mission feasibility check then would fail
> * make the mission invalid

Yes.

Currently, the same upload button doesn't trigger a check when updating only the fence, only updating the mission triggers a check, which I think is patently unreasonable.

For example, a scenario like this: a user plans a task in advance and passes the check, is ready to execute it some time later, but doesn't get a notification that the task is not compliant until just before execution.

**Comment by sfuhrer** [comment]
>Yes.

It wasn't a yes/no question :sweat_smile: 
Which of the two options would you prefer? A or B? Before we decide on that we cannot implement anything.

**Comment by Drone-Lab** [comment]
> It wasn't a yes/no question 😅 Which of the two options would you prefer? A or B? Before we decide on that we cannot implement anything.

when I update the geofence, I need the mission feasibility checks to be run immediately.
Since the geofence and mission updates are under the same button "upload", we just need to reject this update(include geofence and mission if they have been updated) and leave it as it was before we clicked upload.So,it is a yes/no question.😀


Since now there is already a feasibility check in the module of the mission, when a new upload of a new mission is not available, it will be rejected.
We can accomplish the above by simply adding the same check to the geofence.Like this:https://github.com/PX4/PX4-Autopilot/pull/22531

**Comment by sfuhrer** [comment]
> > It wasn't a yes/no question 😅 Which of the two options would you prefer? A or B? Before we decide on that we cannot implement anything.
> 
> when I update the geofence, I need the mission feasibility checks to be run immediately. Since the geofence and mission updates are under the same button "upload", we just need to reject this update(include geofence and mission if they have been updated) and leave it as it was before we clicked upload.So,it is a yes/no question.😀
> 
> Since now there is already a feasibility check in the module of the mission, when a new upload of a new mission is not available, it will be rejected. We can accomplish the above by simply adding the same check to the geofence.Like this:#22531

But isn't that exactly option A? You propose to reject the GF if it's not compatible with the mission.

**Comment by Drone-Lab** [comment]
> But isn't that exactly option A? You propose to reject the GF if it's not compatible with the mission.

Yes,you are right!
I want to reject a whole round of uploads that aren't feasible, and if the upload only updates the geofence, it's case A.

**Pull request merged**
