### PR TITLE
EKF2: move implementation of updateAidSrcStatus to cpp file, saves flash

### PR DESCRIPTION
**Pull request by haumarco**
saves 3.7 kB flash (v6x).
2.2 kB only from updateAidSourceStatus

### CODE REVIEW

**Comment by haumarco** [comment]
let me know if you think that the performance loss of not having the compiler inline the functions of the [second commit](https://github.com/PX4/PX4-Autopilot/pull/23709/commits/9b35ec1b149bf15d188521260c64288e85950b2f) is worth the 1.5 kB flash.

**Comment by AlexisTM** [comment]
We could gate it behind a config and add `__attribute__ ((noinline))` for a "low flash build"?

**Comment by haumarco** [comment]
I thought forcing noinline for these simple functions would be too radical. I don't know what linker optimisations we're running, but it could still be the case that these functions are inlined for performance reasons, right? As these are not the typical single-line functions, I don't think it's "overkill". If you think gating is the best way to go, then let me know. I'm far from an expert on the subject.

---
I planned to force noinline in a follow-up for the template function of _updateAidSourceStatus_ since we're only using 3 different variations. But first I want to get this and https://github.com/PX4/PX4-Autopilot/pull/23701 merged...

**Review by dagar — APPROVED** [review]

**Comment by dagar** [comment]
There's a minor merge conflict now, but otherwise looks good.

**Review by dagar — APPROVED** [review]

**Pull request merged**
