### PR TITLE
Pusher slew rate in MC mode for standard VTOL

### PR DESCRIPTION
**Pull request by GaspardBesacier**
### Solved Problem
We found out that sometimes the pusher throttle had a tends to change pretty abruptly, which can cause oscillatory behaviors but also may reduce the engine durability.

### Solution
To solve this problem, we implemented a slew rate limiting the evolution of the pusher throttle when its value is high enough (above FLT_EPSILON): it maintains the throttle in an interval around its previous value, which range is defined by the new slew_rate parameter and the time step. When the throttle is already low (below FLT_EPSILON), it isn't affected by the slew rate to be able to brake fast (may be safer in some situations).

### Alternatives
We could also apply another kind of filter (maybe moving average, or other kind of lowpass filter) to the pusher actuator commands but this method is already pretty efficient.

### Test coverage
It was tested on simulation multiple times and worked fine, and there shouldn't be any corner cases that could cause problems.

### Context
Before modification:
Capture d’écran du 2022-12-20 17-26-52
After modification:
Capture d’écran du 2022-12-20 17-27-17

### CODE REVIEW

**Comment by GaspardBesacier** [comment]
This is a follow-up to the previous PR https://github.com/PX4/PX4-Autopilot/pull/20394 (@sfuhrer and @ThomasRigi)

**Comment by sfuhrer** [comment]
Do we understand where these oscillations come from? And did you try out the motor slew rate limiting in the control allocation? (CA_RX_SLEW, it's also exposed in the Allocation UI in advanced).

**Comment by ThomasRigi** [comment]
I didn't know there was a slew-rate built in to control allocation. I think that makes this PR mostly superfluous. Maybe the only thing is that here it's a slewrate in place for as long as the pusher is in use, but stopping the pusher it is still immediate if _pusher_throttle == 0 (to not have remaining throttle when pitching up for braking). Is that also possible with CA ?

The oscillations come from a reasonably aggressive MC controller and a much slower response time of the pusher motor to actually move the whole drone forward.

I'm fine if the slew rate of CA is good enough, we can close this PR in that case.

**Comment by sfuhrer** [comment]
>The oscillations come from a reasonably aggressive MC controller

Define reasonable :sweat_smile:  . Do you want to share the MPC parameters that lead to them, or even a log? I think they are quite concerning, and simply adding a slew rate on the pusher won't fix the root cause (it will then have an even slower response time). 

>Maybe the only thing is that here it's a slewrate in place for as long as the pusher is in use, but stopping the pusher it is still immediate if _pusher_throttle == 0 (to not have remaining throttle when pitching up for braking). Is that also possible with CA ?

No it's a symmetric slewrate by all that I know.

**Comment by ThomasRigi** [comment]
Actually, never mind :sweat_smile: We recently lowered the MPC_ACC_HOR_MAX and MPC_JERK_AUTO, and I don't see the problem anymore as much as on older flights (of which I couldn't find a good log just like that in our database).

Closing as it was just bad params on our side and there is the symmetric CA slewrate for those who want to use it.

**Pull request closed without merging**
