### PR TITLE
boards: mRo pixracer pro restore USART6, but RX only

### PR DESCRIPTION
**Pull request by dagar**
@berndpfrommer can you try this?

### CODE REVIEW

**Comment by berndpfrommer** [comment]
- was able to check out the pr-pixracerpro_rc branch and build + install it successfully. Made sure I had the most recent relevant commit.
- still some problem: sticks in QGroundControl do not move
- this time also tested the frsky s-port, that one is also not working.
Note that I have this configured and working on a pixracer (non-pro version), so I just unplug the standard pixracer, plug in the pixracer pro. So the wiring should be correct, but there is always a chance that a firmware parameter setting is wrong. Everything is pretty much set to the defaults though.

**Comment by dagar** [comment]
I believe RC was on the wrong port (/dev/ttyS3 instead of /dev/ttyS4) and frsky wasn't started automatically.

**Comment by berndpfrommer** [comment]
Tested this today with the latest master branch (last commit ending in 6484c)
- the pixracer pro boots up but goes into a sequence of persistent and annoying beeps the moment I connect with QGroundControl.
- I can see the gyro providing data in QGroundControl, I can configure etc
- The beeping is unbearable
- The SBus RC input still is not working
- In QGroundControl the input channel monitoring shows no input channels

**Comment by berndpfrommer** [comment]
Note: as I was testing related to #17483 I discovered that I was using the wrong port on my SBUS receiver. So the last report above is invalid: it may or may not have worked, my setup was faulty.
See #17483 for more.

**Pull request merged**
