### PR TITLE
sih in sitl test

### PR DESCRIPTION
**Pull request by romain-chiap**
This is a draft pull request in an attempt to bring the SIH into the SITL. The benefit will be to have a quadrotor simulator coded in C++ in the PX4 flight stack (SIH) that can be run on a laptop or computer. The SIH can currently only be run on a dedicated hardware (Pixhawk for example), I'm trying to make it run in SITL.

I believe the minimal steps to start the SIH in SITL are
1. compile the SIH module. I called sih in `boards/px4/sitl/nolockstep.cmake`
2. do not start the module `simulator` (sending/receiving Mavlink messages with jMAVSim), and start the module `sih` instead. I implemented this modification in `ROMFS/px4fmu_common/init.d-posix/rcS`.

I compile and start the simulation with `make px4_sitl_nolockstep none` with QGC open to monitor the behaviour.
The SIH is running (checked with `sih status`), but the EKF does not seem to fuse the IMU. The topic `vehicle_attitude` is never published, but the topic `vehicle_gps_position` is published at regular interval.

My initial guess was that the multi-EKF does not like the SIH simulating one IMU only, but it works in SIH-HITL. So, this is not the problem.

I then realized the SIH was updated and calls the IMU, mag and baro drivers `#include <lib/drivers/accelerometer/PX4Accelerometer.hpp>` and they seem to be commented from compilation in `boards/px4/sitl/nolockstep.cmake`. Does that ring a bell?
I'm also mentioning that the topics `sensor_combined`, `sensor_accel`, `sensor_gyro`, `sensor_mag`, `sensor_baro` are being published at regular interval during SIH in SITL runtime. Yes they do, but they are somewhat not consumed by the EKF.

Interestingly, I tried to create a logfile by doing `logger on` followed by `logger off` and they EKF aligned itself! and then lost its fix soon after.
```
pxh> logger on
pxh> logger off
pxh> INFO  [ecl/EKF] reset position to last known position
INFO  [ecl/EKF] reset velocity to zero
INFO  [ecl/EKF] GPS checks passed
INFO  [logger] closed logfile, bytes written: 13640874
INFO  [ecl/EKF] 1622145937251161: EKF aligned, (baro hgt, IMU buf: 12, OBS buf: 9)
WARN  [ecl/EKF] baro hgt timeout - reset to gps
WARN  [ecl/EKF] gps hgt timeout - reset to gps
```

Any hint?

### CODE REVIEW

**Comment by dagar** [comment]
Can you check `uorb top -1` and `sensors status`?

**Comment by dagar** [comment]
I think it's the `simulator` module taking the first sensor_accel and sensor_gyro instances, but not publishing data. For initial testing try commenting out "simulator" in no lockstep.cmake
https://github.com/PX4/PX4-Autopilot/blob/e1df73999d01035f181eb27cdd5fb09f1149c1b7/boards/px4/sitl/nolockstep.cmake#L56

**Comment by romain-chiap** [comment]
These are after commenting `simulator` in cmake.
```
pxh> uorb top -1

update: 1s, num topics: 70
TOPIC NAME                         INST #SUB RATE #Q SIZE
actuator_armed                        0   10    2  1   16 
actuator_controls_0                   0    9  800  1   48 
actuator_outputs                      0    5  800  1   80 
commander_state                       0    1    2  1   16 
cpuload                               0    5    2  1   16 
distance_sensor                       0    6   49  1   56 
ekf2_timestamps                       0    2  267  1   24 
logger_status                         0    1    1  1   40 
multirotor_motor_limits               0    2  800  1   16 
rate_ctrl_status                      0    1  800  1   24 
sensor_accel                          0    5  800  8   48 
sensor_baro                           0    2   20  1   32 
sensor_combined                       0    2  267  1   48 
sensor_gps                            0    5   20  1  112 
sensor_gyro                           0    6  800  8   48 
sensor_mag                            0    2   49  4   48 
sensor_preflight_mag                  0    1   77  1   16 
sensors_status_imu                    0    2  267  1   88 
telemetry_status                      0    2    2  1   88 
telemetry_status                      1    2    1  1   88 
telemetry_status                      2    2    1  1   88 
telemetry_status                      3    2    1  1   88 
vehicle_acceleration                  0    2  267  1   32 
vehicle_air_data                      0   14   19  1   40 
vehicle_angular_acceleration          0    2  800  1   32 
vehicle_angular_velocity              0   10  800  1   32 
vehicle_attitude_groundtruth          0    1   24  1   56 
vehicle_control_mode                  0   18    2  1   24 
vehicle_global_position_groundtruth   0    1   24  1   64 
vehicle_gps_position                  0    3   20  1  104 
vehicle_imu                           0    5  267  1   56 
vehicle_imu_status                    0    6   10  1   96 
vehicle_land_detected                 0   11    1  1   24 
vehicle_magnetometer                  0    4   44  1   40 
vehicle_status                        0   34    2  1   80 
vehicle_status_flags                  0    6    2  1   48 
```

```
pxh> sensors status
INFO  [sensors] selected gyro: 1310988 (0)
INFO  [data_validator] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [data_validator] sensor #0, prio: 50, state: OK
INFO  [data_validator] 	val:   0.0921, lp:   0.0063 mean dev:   0.0003 RMS:   0.0741 conf:   1.0000
INFO  [data_validator] 	val:   0.0074, lp:   0.0007 mean dev:  -0.0000 RMS:   0.0371 conf:   1.0000
INFO  [data_validator] 	val:  -0.0006, lp:   0.0020 mean dev:   0.0000 RMS:   0.0159 conf:   1.0000

INFO  [sensors] selected accel: 1310988 (0)
INFO  [data_validator] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [data_validator] sensor #0, prio: 50, state: OK
INFO  [data_validator] 	val:   0.0983, lp:   0.0108 mean dev:  -0.0001 RMS:   0.3208 conf:   1.0000
INFO  [data_validator] 	val:   1.1478, lp:  -0.0657 mean dev:  -0.0013 RMS:   1.0747 conf:   1.0000
INFO  [data_validator] 	val: -10.0011, lp:  -9.7688 mean dev:   0.0002 RMS:   0.8957 conf:   1.0000

INFO  [vehicle_magnetometer] selected magnetometer: 197388 (0)
INFO  [data_validator] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [data_validator] sensor #0, prio: 50, state: OK
INFO  [data_validator] 	val:   0.1845, lp:   0.1785 mean dev:  -0.0001 RMS:   0.0202 conf:   1.0000
INFO  [data_validator] 	val:  -0.0202, lp:  -0.0452 mean dev:   0.0000 RMS:   0.0203 conf:   1.0000
INFO  [data_validator] 	val:   0.4623, lp:   0.5009 mean dev:   0.0004 RMS:   0.0301 conf:   1.0000
INFO  [sensor_calibration] MAG 197388 EN: 1, offset: [ 0.000  0.000  0.000], scale: [ 1.000  1.000  1.000], Internal

INFO  [vehicle_air_data] selected barometer: 6620172 (0)
INFO  [data_validator] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [data_validator] sensor #0, prio: 0, state: OK
INFO  [data_validator] 	val: 100936.7266, lp: 100937.3906 mean dev:   0.0228 RMS:   1.7037 conf:   1.0000
INFO  [data_validator] 	val:  14.7895, lp:  14.7899 mean dev:   0.0000 RMS:   0.0009 conf:   1.0000
INFO  [data_validator] 	val:   0.0000, lp:   0.0000 mean dev:   0.0000 RMS:   0.0000 conf:   1.0000

INFO  [sensors] Airspeed status:
INFO  [data_validator] 	no data

INFO  [vehicle_acceleration] selected sensor: 1310988, rate: 800.5 Hz, estimated bias: [0.0000 0.0000 0.0000]
INFO  [sensor_calibration] ACC 1310988 EN: 1, offset: [0.0000 0.0000 0.0000] scale: [1.0000 1.0000 1.0000]

INFO  [vehicle_angular_velocity] selected sensor: 1310988, rate: 800.5 Hz 
INFO  [vehicle_angular_velocity] estimated bias: [0.0000 0.0000 0.0000]
INFO  [sensor_calibration] GYRO 1310988 EN: 1, offset: [0.0000 0.0000 0.0000]

INFO  [vehicle_imu] 0 - IMU ID: 1310988, accel interval: 1249.1 us, gyro interval: 1249.1 us
vehicle_imu: accel data gap: 13268 events
vehicle_imu: gyro data gap: 0 events
vehicle_imu: accel update interval: 145947 events, 1363.62us avg, min 997us max 2738us 365.618us rms
vehicle_imu: gyro update interval: 159213 events, 1249.99us avg, min 997us max 1507us 65.742us rms
INFO  [sensor_calibration] ACC 1310988 EN: 1, offset: [0.0000 0.0000 0.0000] scale: [1.0000 1.0000 1.0000]
INFO  [sensor_calibration] GYRO 1310988 EN: 1, offset: [0.0000 0.0000 0.0000]
```

The EKF eventually got a fix after about 3min. I tried again with `simulator` uncommented in cmake.
The EKF eventually got a fix after a while. The yaw estimate seemed a bit unstable and finally got fixed. The altitude estimate never fixed, but I was able to fly in Manual mode. The vehicle estimated position seemed to be updated at a very low rate and sometime blocked. I was able to get a [log](https://review.px4.io/plot_app?log=17db0ede-e336-49d5-8c4d-5359ad58b1dc).

**Comment by romain-chiap** [comment]
is it possible that PX4 is overloaded? I imagine the RAM and CPU are limited by my laptop hardware which is huge compared to a Pixhawk hardware. However, maybe the non-realtime OS is not able to satisfy to the SIH?
```
sih: cycle interval: 1009192 events, 1250.00us avg, min 981us max 1505us 64.806us rms
sih: cycle: 1009192 events, 6085155us elapsed, 6.03us avg, min 1us max 124us 4.898us rms
```

**Comment by romain-chiap** [comment]
in the logs, the baro altitude and GPS altitude are very reasonable but the fused altitude is garbage, which I have trouble explaining.

**Comment by dagar** [comment]
You could also skip this (or force back to 200) for SIH where the IMU data is at 800 Hz. 

https://github.com/PX4/PX4-Autopilot/blob/1da4e2f4413d3a3709501b413ed2ddca4b9c25ca/ROMFS/px4fmu_common/init.d-posix/rcS#L208-L209

**Comment by romain-chiap** [comment]
I tried `param set IMU_INTEG_RATE 200` without success. 

Yes, the accelerometer is pretty bad. The interesting thing is that with the same configuration in SIH-HITL, the accelerometer is much cleaner:
bokeh_plot-2

Still trying to figure out why...

**Comment by dagar** [comment]
The IMU integration is missing a lot of accel samples for some reason.

Screen Shot 2021-05-28 at 5 11 04 PM

**Comment by dagar** [comment]
We should try SITL SIH with these changes to the sensors module. https://github.com/PX4/PX4-Autopilot/pull/17640
It does a better job of continuously monitoring the accel & gyro publication rates.

**Comment by dagar** [comment]
I think I've found the problem. In regular SITL running without real time scheduling (eg Linux + root) the scheduling jitter is quite large and this is messing with the IMU integration.

I'll update sensors/vehicle_imu to be more resilient.

Later we can update SITL with SIH to use lockstep internally and the time internally will increment cleanly even on a heavily loaded non-realtime system.

**Comment by romain-chiap** [comment]
I just tried SIH-SITL with [PR-17640](https://github.com/PX4/PX4-Autopilot/pull/17640), sensors status reported 0 accelerometer gaps
```
INFO  [vehicle_imu] 0 - Accel ID: 1310988, interval: 1250.1 us (SD 65.4 us), Gyro ID: 1310988, interval: 1250.1 us (SD 65.4 us)
vehicle_imu: accel data gap: 0 events
vehicle_imu: gyro data gap: 0 events
```
but the behaviour remained the same:
1. I took a long time for the EKF to converge the attitude and altitude
2. the heading estimate is offset by about 30 deg
3. the altitude estimate is offset by about 200m

I got a log [here](https://review.px4.io/plot_app?log=ed42d59a-791a-4757-9ee4-ea3e16ba6b7e), the accelerometer looks better, the gyro is clean too.
Screen Shot 2021-05-30 at 7 08 53 PM

**Comment by dagar** [comment]
Weird, it doesn't even tilt align for 30 seconds.

I wonder if there's something related to the timestamps that start at significantly larger values than in typical usage.

**Comment by romain-chiap** [comment]
@priseborough any idea why the EKF takes about 3 min to converge in SITL?
It takes about 10 sec on the Pixhawk4 hardware.

**Comment by priseborough** [comment]
@romain-chiap Do you mean SIH? When I run SITL using either the gazebo or jmavsim simulator, there is no delay aligning

**Comment by romain-chiap** [comment]
Yes, I mean SIH, we are trying to run the SIH in SITL: without hardware, directly on a laptop but using the SIH module as the simulator. `ekf2 status` looks like that
```
INFO  [ekf2] available instances: 0
WARN  [ekf2] selected instance: None
ekf2:0 attitude: 0, local position: 0, global position: 0
ekf2: ECL update: 11807 events, 3548us elapsed, 0.30us avg, min 0us max 33us 1.401us rms
ekf2: ECL full update: 0 events, 0us elapsed, 0.00us avg, min 0us max 0us 0.000us rms
ekf2: IMU message missed: 0 events
ekf2: mag message missed: 0 events
```
What is the difference between ekf update and full update?

@dagar what would it take to implement the lockstep? and do you think that will solve our problem? I imagine yes, but I'm not sure what the problem is given we have no accelerometer and gyro gaps now with [PR-17640](https://github.com/PX4/PX4-Autopilot/pull/17640).

**Comment by dagar** [comment]
Done!

**Pull request closed without merging**
