### PR TITLE
[BACKPORT] px4_fmu-v6c:Add Mini & fix Rev 1

### PR DESCRIPTION
**Pull request by davids5**

### CODE REVIEW

**Comment by davids5** [comment]
@mrpollo @vincentpoont2  will test this in the AM tomorrow.  Then it can be merged

**Comment by vincentpoont2** [comment]
Tested on 

- Pixhawk 6C (VER0 REV 0)
- Pixhawk 6C (VER0 REV 1)
- Pixhawk 6C Mini (VER2, REV1)

The sensor calibration, receiver, and LOG functions are all normal

Boot Logs
[6c-mini_boot-print.txt](https://github.com/PX4/PX4-Autopilot/files/10872110/6c-mini_boot-print.txt)
[Pixhawk 6C_REV0_20230301 release1.13-pr-backport-HB-6C-Mini0.txt](https://github.com/PX4/PX4-Autopilot/files/10872111/Pixhawk.6C_REV0_20230301.release1.13-pr-backport-HB-6C-Mini0.txt)
[Pixhawk 6C_REV1_20230301 release1.13-pr-backport-HB-6C-Mini0.txt](https://github.com/PX4/PX4-Autopilot/files/10872113/Pixhawk.6C_REV1_20230301.release1.13-pr-backport-HB-6C-Mini0.txt)

**Review by vincentpoont2 — APPROVED** [review]

**Comment by junwoo091400** [comment]
@davids5 note, if you create a branch in release/* format, it automatically triggers the metadata deployment to S3 webserver: https://github.com/PX4/PX4-Autopilot/blob/7edce94b939f98a708b4ce96557120509d2adce1/.github/workflows/deploy_all.yml#L7

Therefore, it will modify the target metadata before even it gets merged. Could you not use the release/* format for the branch name?

**Comment by davids5** [comment]
> @davids5 note, if you create a branch in release/* format, it automatically triggers the metadata deployment to S3 webserver:
> 
> https://github.com/PX4/PX4-Autopilot/blob/7edce94b939f98a708b4ce96557120509d2adce1/.github/workflows/deploy_all.yml#L7
> 
> Therefore, it will modify the target metadata before even it gets merged. Could you not use the release/* format for the branch name?
> 
> Note: left a comment in discord as well: https://discord.com/channels/1022170275984457759/1045343300850290778/1081108778956619847

@junwoo091400 Good to know - thank you.  with the exception of `main` I use the base name in my branches to keep rebasing and PR on the correct target. I am curious how others keep it straight. How do you do it.

**Review by mrpollo — APPROVED** [review]

**Comment by mrpollo** [comment]
Thanks @davids5

**Pull request merged**
