### PR TITLE
navigator: remove deprecated mavlink_log*

### PR DESCRIPTION
**Pull request by bkueng**
Reduces flash usage by 6.4KB

### CODE REVIEW

**Review by sfuhrer — APPROVED** [review]
This will give us some breathing space again :+1:

**Comment by dagar** [comment]
I hate that this is the case, but I have concerns we may be quietly hurting ourselves by making this switch. There are private QGC forks, QGC SRR, and other custom GCS software without events support. You could rightly say there's been enough time to upgrade and it's their problem, but the reality will be various PX4 projects entrenched on old versions and we'll quietly miss out on bug reports, fixes, and other little contributions.

Options
1. keep the mavlink_log*, but behind ifdefs and new kconfig
2. System wide option to send out all events as mavlink (off by default).

Presumably option 2 would negate most of the flash savings here? This behaviour could also be build time disabled via kconfig.

**Comment by sfuhrer** [comment]
Shorter term fix for immediate flash issues on v5 and v5x: https://github.com/PX4/PX4-Autopilot/pull/20811

**Comment by bkueng** [comment]
Certainly a valid concern. Then how long do you want to drag this along? In the past we agreed on +-1 version compat to QGC. That is given here.

We could send out a message to update the GCS if it does not query the metadata upon connection.

**Comment by dagar** [comment]
> Certainly a valid concern. Then how long do you want to drag this along? In the past we agreed on +-1 version compat to QGC. That is given here.
> 

It's not that I want to drag this along, I'm just aware of a lot of 3rd party development we benefit from indirectly and this is a much different kind of break from the typical minor version issues of the past.

If something like option 2 is viable I think we should go all in with events, but keep the runtime configurable mavlink fallback "escape hatch" (that can be completely disabled via kconfig as needed). Wouldn't that work for everyone?

**Comment by bkueng** [comment]
> If something like option 2 is viable I think we should go all in with events, but keep the runtime configurable mavlink fallback "escape hatch" (that can be completely disabled via kconfig as needed). Wouldn't that work for everyone?

I'm just not convinced by that. You'll have some boards/configs compatible while others are not. And it's a bit of work to do it properly as the print format differs.

**Comment by dagar** [comment]
> > If something like option 2 is viable I think we should go all in with events, but keep the runtime configurable mavlink fallback "escape hatch" (that can be completely disabled via kconfig as needed). Wouldn't that work for everyone?
> 
> I'm just not convinced by that. You'll have some boards/configs compatible while others are not. And it's a bit of work to do it properly as the print format differs.

Yes it's not my first choice, but we already have that now with flash constrained boards not including the events package and all the other modules that gradually become optional and disabled by default as things get tight.

It's really two issues that I see here.
 1. There are a lot of things outside of our control that aren't ready for this (but hopefully will be eventually). In addition to many private projects the more public examples would be things like the Herelink (ships with customized QGC that predates events) or UgCS.
2. Regardless of the current compatibility I think as a project we'd be in a better position supporting (even in some minimal capacity without the duplication). I think it will be a different story if/when the Linux side can be more tightly integrated.
 
So in terms of cost benefit here I don't really know how to quantify the downside, but I know it's non-zero. 

If people feel they're getting stuck due to flash shortages there are still quite a few other avenues I can start pursuing more aggressively.

**Pull request closed without merging**
