### PR TITLE
Layered, lock-free param system

### PR DESCRIPTION
**Pull request by ThomasDebrunner**
This PR refactores the param system. 

### Layers
The (implicit) layers of the param system are now explicit. Specifically, there are the following layers in the system:

```
User config
--------------------------------------------------
Airframe (runtime) defaults
--------------------------------------------------
Firmware (compile time) defaults
```

More layers could be added in the future, e.g. a "temporary overlay" layer for flight modes etc.

The layers follow the following rules:

- Getting a param goes down the layer stack, until the first layer gets hit that "contains" the param.
- Set / Reset are layer local operations. "Set" makes a layer "contain" a param, "reset" makes a layer not contain a param.

Therefore, when getting a param, the first layer that contains it will return it. E.g. if an airframe default exists, a reset of a user config will make the next get return the airframe default, if not, it will fall back to the firmware default.

### Storage implementation

All layers inherit from `ParamLayer` interface. The actual implementations can have data storage backends. 
The following are provided:

**ConstLayer:** Base layer for the firmware contained, compile time const param set

**DynamicSparseLayer:** Implements current behaviour. Dynamic, runtime memory allocation, contains only the necessary (changed) values. Stored as a sorted array in memory. Look-up is via binary search.

**StaticSparseLayer:** Implements a static, fixed size array. Has a fixed number of "slots" to store changed values. Contains only the necessary (changed) values. Stored as a sorted array in memory. Look-up is via binary search. Storing more values than slots will result in an error

**ExhaustiveLayer:** Implements an array the size of all params. Contains a copy of the full param set in memory. Access is direct memory access.

### Example storage configs

The storage class for the layers can be chosen to fit the needs. E.g:

**Memory constrained system**

(Same behaviour as we have now)
```
User config: DynamicSparseLayer
Airframe defaults: DynamicSparseLayer
Firmware defaults: ConstLayer
```

**Memory constrained, static memory**

(Restricted number of params can be changed)
```
User config: StaticSparseLayer
Airframe defaults: StaticSparseLayer
Firmware defaults: ConstLayer
```

**O(1) param get / set assured, static memory**

(Restricted number of params can be changed)
```
User config: ExhaustiveLayer
Airframe defaults: StaticSparseLayer
Firmware defaults: ConstLayer
```

### Locking
All layers should be implemented without locking, but the use of critical sections instead.

**TODO:** There is still the file access semaphore. Not entierly clear how we'd get rid of that one (if at all). 

**TODO:** I hacked in this `atomic_transaction` primitive, to have recursive critical section entering / leaving. I believe that's wrong and should be done differently.

### Current state

Compiles, seems to work mostly. Still quite a bit of work to be done if persued. 
I believe the `parameters.cpp` could even be reduced more with the new class structure.

### CODE REVIEW

**Comment by dagar** [comment]
Just off the top of my head I worry about making it even harder to transition to finally support additional parameter types that aren't 4 bytes. 

 - 64 bit integers
 - double precision floating point
 - strings (maybe fixed length)
 - actual booleans
 - possibly 1 or 2 byte integers (might not matter)

Thoughts?

**Review by bkueng — COMMENTED** [review]
Looks pretty good.

I'm just a bit concerned with having multiple implementations for different boards, with potentially slightly different behaviors. At least initially I'd use the same layers everywhere.

**Comment by ThomasDebrunner** [comment]
Thanks for the review @bkueng ! I addressed your comments with more commits. 
@dagar I don't think it makes it makes it harder to support different sized data types. The only thing that may get more complicated is to retain the O(1) access time in the exhaustive layer, but I am pretty sure that it also should not be a problem, as long as all params are known at compile time and have fixed length. 

I believe there is a case for a fully dynamic param system with runtime params etc. but I'd rather have that on the mission computer than on the FMU tbh. I am quite content with the simplicity of the float / int32 params that we have, I believe it saves us some headaches.

**Comment by bkueng** [comment]
I did some testing (also flash params)

Pixhawk 4:
PR:
```
INFO  [parameters] summary: 1126/1971 (used/total)
INFO  [parameters] file: /fs/mtd_params
INFO  [parameters] backup file: /fs/microsd/parameters_backup.bson
INFO  [parameters] storage array: 155/1971 elements (1248 bytes total)
INFO  [parameters] storage array (custom defaults): 31/1971 elements (256 bytes total)
INFO  [parameters] auto save: on
INFO  [parameters] last auto save: 2.646 seconds ago
param: export: 4 events, 160660us elapsed, 40165.00us avg, min 39774us max 40465us 293.633us rms
param: find: 9407 events
param: get: 152156 events
param: get: 152156 events, 257316us elapsed, 1.69us avg, min 1us max 4us 0.577us rms
param: set: 159 events, 6147us elapsed, 38.66us avg, min 5us max 79us 18.735us rms
```
main:
```
INFO  [parameters] summary: 1124/1976 (used/total)
INFO  [parameters] file: /fs/mtd_params
INFO  [parameters] backup file: /fs/microsd/parameters_backup.bson
INFO  [parameters] storage array: 155/256 elements (4096 bytes total)
INFO  [parameters] storage array (custom defaults): 31/32 elements (512 bytes total)
INFO  [parameters] auto save: on
INFO  [parameters] last auto save: 4.117 seconds ago
param: export: 5 events, 188847us elapsed, 37769.40us avg, min 34094us max 39743us 2668.137us rms
param: find: 10555 events
param: get: 161365 events
param: set: 160 events, 6092us elapsed, 38.08us avg, min 4us max 74us 20.252us rms
```

TODO: `lp_work low on stack 276` -> switch export to the px4 wq.

**Comment by dagar** [comment]
> @dagar @bkueng Can we get this in?

If everyone is comfortable with it let's bring it in first thing after we branch for v1.14.

Can you rebase to see if the remaining CI failures are resolved?

**Comment by bkueng** [comment]
Rebased. This is good to go from my side.

**Comment by ThomasDebrunner** [comment]
Can we get this in?

**Comment by ThomasDebrunner** [comment]
Just rebased

**Comment by bkueng** [comment]
Let's finally get this in then.

**Comment by dagar** [comment]
Test rack is failing intermittently when doing an explicit param save after setting some parameters. The command `param save` should probably be scheduling the worker instead of doing it directly, but regardless we should still review what's going on here.

Screenshot from 2023-06-07 17-11-36

**Pull request merged**
