### PR TITLE
uavcanode: refactor publishers and subscribers

### PR DESCRIPTION
**Pull request by dagar**
@davids5 first pass at refactoring uavcannode to split the subscribers and publishers out. Next we can make it trivial to configure the subset to include at runtime or build time.

``` Console
nsh> uavcannode status
Pool allocator status:
        Capacity hard/soft: 500/250 blocks
        Reserved:  17 blocks
        Allocated: 7 blocks

UAVCAN node status:
        Internal failures: 0
        Transfer errors:   0
        RX transfers:      2395
        TX transfers:      20337

CAN1 status:
        HW errors: 0
        IO errors: 0
        RX frames: 3190
        TX frames: 25386

Publishers:
        battery_status -> uavcan.equipment.power.BatteryInfo:1092
        optical_flow -> com.hex.equipment.flow.Measurement:20200
        sensor_gps -> uavcan.equipment.gnss.Fix2:1063
        sensor_mag -> uavcan.equipment.ahrs.MagneticFieldStrength2:1002
        distance_sensor -> uavcan.equipment.range_sensor.Measurement:1050
        differential_pressure -> uavcan.equipment.air_data.RawAirData:1027
        sensor_baro -> uavcan.equipment.air_data.StaticPressure:1028
        sensor_baro -> uavcan.equipment.air_data.StaticTemperature:1029

Subscribers:
        uavcan.equipment.indication.BeepCommand:1080 -> tune_control
        uavcan.equipment.indication.LightsCommand:1081 -> led_control

uavcannode: cycle time: 50853 events, 4383797us elapsed, 86.21us avg, min 54us max 861us 58.739us rms
uavcannode: cycle interval: 50853 events, 2247.86us avg, min 71us max 10028us 2883.902us rms
```

### CODE REVIEW

**Review by LorenzMeier — APPROVED** [review]
Nice, this is a big step forward! I've reviewed the architecture, but I will leave the line-by-line review to David as he is much more familiar with the implementation in this module.

**Review by davids5 — DISMISSED** [review]
@dagar Nice! 

What is the plan for build time Adds. Do you use a Kconfig or do you have a more elegant solution in mind??

**Comment by dagar** [comment]
> @dagar Nice!
> 
> What is the plan for build time Adds. Do you use a Kconfig or do you have a more elegant solution in mind??

Nothing specific in mind yet, but it occurred to me we could do it at the level of the messages themselves. A mechanism where you specify the specific DSDL you want to include in a specialized build (eg uavcan::equipment::power::BatteryInfo), and then all the other "handlers" wouldn't even be in the build. This could probably exist for uORB as well.

**Comment by JacobCrabill** [comment]
Looks much cleaner than the original implementation!  I was about to refactor some internal developments on top of `master`; I'll use this refactor instead.

**Pull request merged**
