### PR TITLE
Fix MC thrust spike

### PR DESCRIPTION
**Pull request by bresch**
### Solved Problem
replaces #21380

### CODE REVIEW

**Comment by hendjoshsr71** [comment]
I approve.  (Though I can't formally approve it.)

But this was my original commit before adding on another commit so that there was only one path to change `_hover_thrust`

**Comment by bresch** [comment]
> I approve. (Though I can't formally approve it.)

Thanks!

> But this was my original commit before adding on another commit so that there was only one path to change _hover_thrust

Yes (and I kept you as the author of the commit). I didn't add the 2nd commit because I just don't think that merging 2 functions and separating the logic internally using a boolean argument is better than 2 functions with a proper name (might just be my opinion).

**Review by MaEtUgR — APPROVED** [review]
@hendjoshsr71 Thanks a lot for looking into it and suggesting a solution!
Additional sanity checks to prevent the hover thrust update make the controller go nuts sound useful. I know I'm a bit late to the party but still added a commit to suggest some improvements 😇 They are mostly reordering and renaming and I'd expect no multicopter with more than 20:1 thrust to weight ratio. Please correct me ifg I'm wrong.

I also thought about how to cover this case in a unit test but since it's internal states the controller has to be ran multiple times to find e.g. the integrator being off. Maybe I find a simple test case.

If you're ok with this I'd merge it for the 1.14 release.

**Review by MaEtUgR — APPROVED** [review]
Done

**Review by hendjoshsr71 — APPROVED** [review]
@MaEtUgR looks fine for a refactor that is much clearer than my original changes 

Feel free to squash it all together if that is preferred.

**Review by dagar — APPROVED** [review]

**Pull request merged**
