### PR TITLE
Crazyflie v 21

### PR DESCRIPTION
**Pull request by LorenzMeier**
This is a continuation of https://github.com/PX4/PX4-Autopilot/pull/16433, rebased on master and with submodules fixed.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@TheLegendaryJedi Could you look into the CI build failure here? I have rebased you branch, you can take this one over and send a new PR if you prefer. It looks like you have named the target in some locations crazyflie and in others crazyflie21 and the CI system can't find the resulting binary.

I also saw that you copied the complete syslink code from the Crazyflie v1 - is this stricly necessary? Can't this be shared?

**Comment by TheLegendaryJedi** [comment]
Thanks a lot @LorenzMeier for the submodules fix and all the help. I can take this one. But if you want I can reorganize the crazyflie 2.1 code to remove the duplicated one and submit a new PR. 

I separated everything because I didn't knew if it was good practice to import files from another board folder. I considered this one like a total different board. What do you suggest in this case?

I still need to understand how QGC detects the board and downloads the firmware for that specific one.

**Comment by mrpollo** [comment]
@dagar I tried restarting the Hardware Test and made things worst, the last failed test was uORB, now it won't even start the build, can you advice how to move forward?

**Comment by mrpollo** [comment]
@TheLegendaryJedi do you have an update on the PR?

**Comment by TheLegendaryJedi** [comment]
> @TheLegendaryJedi do you have an update on the PR?

Hi @mrpollo, I can't understand why is failing the Jenkins Hardware Test. Is this test using real boards to test the binary flash?

**Comment by mrpollo** [comment]
I'm replaying the branch again on Jenkins, hopefully, it gives us a better view into what's going on.

**Comment by TheLegendaryJedi** [comment]
> I'm replaying the branch again on Jenkins, hopefully, it gives us a better view into what's going on.

It's still failing. I checked the log but I can't understand what is wrong.

**Comment by TSC21** [comment]
> > I'm replaying the branch again on Jenkins, hopefully, it gives us a better view into what's going on.
> 
> It's still failing. I checked the log but I can't understand what is wrong.

This can be ignored as it has nothing to do with this PR.

**Comment by MaEtUgR** [comment]
This pr pulled in some ancient submodules, see https://github.com/PX4/PX4-Autopilot/pull/16609

**Pull request merged**
