### PR TITLE
Fix DSM2/DSMX guessing routine and DSM range checking

### PR DESCRIPTION
**Pull request by chris1seto**
I noticed several issues with the DSM parser. 
* Inappropriate range checks in both channel indexes and channel values
* DSMX/2 guessing routine does not correctly identify otherwise valid DSM2/X from an RX which has a channel payload which does not align with the predefined channel layouts
* A bug in the generation of the `cs10` and `cs11` channel layout word
* Improperly set maximum DSMX/2 channels definition
* Improper handling of channel counts and channel values for channel counts larger than 7

This PR references the following document from Spektrum: https://www.spektrumrc.com/ProdInfo/Files/Remote%20Receiver%20Interfacing%20Rev%20A.pdf

This PR fixes those issues and should probably also serve as a starting point for a more comprehensive discussion about how to correctly detect DSMX/2. The DSM protocol is extremely flexible and also poorly adhered to (even by Spektrum themselves!), and as a result, it's difficult to detect with 100% confidence if a frame (or small collection of frames) is for certain DSMX or DSM2. This PR implements several new heuristics to uphold the previous behavior of automatically guessing whether a stream is either DSMX or DSM2. It is my opinion, however, that given the extreme protocol flexibility allowed within the protocol, and the wide range of implementations in both Spektrum and non-Spektrum RXes, that there should be a param which allows the user to statically set whether to use DSMX or DSM2 parsing. 

Notes on range checking:
* For DSMX, at a minimum, channel index bitfield values up to, and including decimal 12 as well as decimal 15 are valid.  It's not entirely clear to me from the Spektrum satellite spec document how channel indexes up to 20 are obtained, and there appears to be an implementation of this in the original driver. I don't know if that is correct. A channel index value of 15 means that the channel word is a placeholder and should not be parsed. In this case, the entire word is 0xffff, but channel values covering the entire range should be valid, so I am assuming that it's simply a don't care if the channel index is 15 and that a channel value of all bits set DOES NOT specifically mean that the channel value is invalid.

* DSM can still have a max channel count range check, since it has a larger bitfield for channel index

* I do not believe that range checking is safe on channel values. It's not impossible of for the entire stick range to be legitimately used, and enforcing arbitrary range checks of "reasonable values" could be a time bomb in flight if a slider/stick is moved to a range that wasn't seen in ground testing or in radio calibration. Spektrum implies in their specification document that the entire range of the channel value bitfield is valid.

For the above reasons, there is very limited data to determine that a DSM channel is for sure DSMX or DSM2. The majority of the previous guessing routine utilized range checks such as those. 

In this new PR, I introduce several new guessing heuristics. For each DSM2 or DSMX, 
1. In all frames seen over the sample period, there must be no channel index gaps
2. Channels must start at 0 and a minimum channel count of 5 is required
3. For each channel seen, it must be seen nearly as often as every other channel seen in the sample period
4. A, individual frame is only valid if it does not contain duplicate channel indexes. Each good frame is counted during the sample period. After 15 frame samples are counted, there must be at least 10 good frames of either DSMX or DSM2

For background, the "system byte" is available to differentiate between DSMX and DSM2 streams, however, it has been the case that the system byte has apparently been reported as incorrectly set in some genuine Spektrum RXes. This means that we cannot use it alone to determine a DSMX or DSM2 stream. One alternative option is to use this byte as it was intended and not guess at all, but also present a param to override the use of the system byte and specifically parse as DSMX or DSM2.

This PR should considerably improve DSM2/DSMX guessing performance, however as a result of the limited information available for determining a valid DSM2/DSMX stream, I would highly recommend the alternative solution mentioned above involving the system byte and the param to override it. 

Thanks for @dagar for his help in answering questions about the existing DSM parser and his feedback on a new solution!

### CODE REVIEW

**Comment by chris1seto** [comment]
I think I'm basically done with this for now. I reworked the dropped frame counter such that only frames which failed parsing after sampling was done are counted. This makes for a more valid representation of how many frames were dropped due to real issues in steady state. This number should be 0, or nearly 0 in any normal flying environment unless range is being exceeded.

**Comment by mcsauder** [comment]
@chris1seto , could you rebase against current master?

**Comment by dagar** [comment]
Looks good so far with testing what I have on hand.

**Review by mcsauder — APPROVED** [review]
Bench tested latest commits on the bench with a dx9 and an SPM4647, no issues.

**Review by dagar — APPROVED** [review]
Thanks @chris1seto, nice work.

**Comment by mcsauder** [comment]
Flight test with Pixhawk4 mini, Spektrum DX9, SPM4647: https://review.px4.io/plot_app?log=6b6b2cff-4e32-43e7-b4b7-8d0016bf653f

**Comment by mcsauder** [comment]
Thanks @chris1seto and @dagar !  Nice work!

**Pull request merged**
