### PR TITLE
MC_Pos_Control: takeoff bug constrain hover_thrust_estimate

### PR DESCRIPTION
**Pull request by hendjoshsr71**
This is the version of [PR](https://github.com/PX4/PX4-Autopilot/pull/21372)  that points to main instead of 1.13

### CODE REVIEW

**Comment by junwoo091400** [comment]
@hendjoshsr71 Could you do `make format` and commit results to fix the format checker CI that is failing?

**Comment by junwoo091400** [comment]
Tailsitter SITL is falining again: https://github.com/PX4/PX4-Autopilot/actions/runs/4544468878/jobs/8011289156?pr=21380

However, the previous commit in the `main` branch didn't have a failure. Therefore it could be an introduced behavior from this PR? The log shown however is more related to airspeed selector / battery :thinking: 

image

**Comment by hendjoshsr71** [comment]
> @hendjoshsr71 Could you do `make format` and commit results to fix the format checker CI that is failing?

Done! Though I had fix up how  the auto formatter "fixed" things. It looked pretty weird.

**Review by bresch — CHANGES_REQUESTED** [review]
I'm not a big fan of merging 2 functions in one and split it internally using a boolean parameter. Especially when reading the function call, I think it would be nicer to have something like `setHoverThrustAndUpdateIntegral()' than 'setHoverThrust(true)`.

**Comment by hendjoshsr71** [comment]
> I'm not a big fan of merging 2 functions in one and split it internally using a boolean parameter. Especially when reading the function call, I think it would be nicer to have something like `setHoverThrustAndUpdateIntegral()` than `setHoverThrust(true)`.

Agree. I was trying to acheive what @dagar wanted in terms of only one path for these constraints. 

If either you or Daniel would like to push my repo your prefence to achieve that goal feel free. That would probably be easier than me going back and forth.?

**Comment by bresch** [comment]
replaced by https://github.com/PX4/PX4-Autopilot/pull/21512 . Thanks @hendjoshsr71 for the fix. I rebased, made some minor changes and did another PR with it

**Pull request closed without merging**
