### PR TITLE
Drivers: icm42688p iim42652 iim42653 disable AFSR

### PR DESCRIPTION
**Pull request by AlexKlimaj**
See
https://github.com/ArduPilot/ardupilot/issues/25025#issuecomment-1773910280

Needs testing.

### CODE REVIEW

**Comment by AlexKlimaj** [comment]
I confirmed on main that it is present in the Fifo data. But it doesn't appear in the sensor_gyro version of the same data. 
image

**Review by dagar — APPROVED** [review]

**Comment by AlexKlimaj** [comment]
Just tested this PR appears to fix the gryo but I got an accel filter fault during it.

https://review.px4.io/plot_app?log=d543e92b-f80b-409d-822f-099fa1f1053d

**Comment by AlexKlimaj** [comment]
Running main back on the iim42653 without the clock enabled, it doesn't look like it has the gyro stuck issue.

https://review.px4.io/plot_app?log=533f414f-8e87-4382-9b60-495c6abe437d
image

**Review by dagar — APPROVED** [review]

**Comment by AlexKlimaj** [comment]
https://review.px4.io/plot_app?log=0608d0e9-6592-4029-936e-9d196d114946

**Pull request merged**
