### PR TITLE
Testing of NuttX 10.0.0+ - as baseline for Net param Changes

### PR DESCRIPTION
**Pull request by davids5**
Replaces https://github.com/PX4/Firmware/pull/15905

This will track nuttx master, hence the name NuttX Next

### CODE REVIEW

**Comment by davids5** [comment]
@dagar  this is the cause of the assertion fail on the test rack for FMUv5 debug.

NuttX 10 is very broken by this careless PR https://github.com/apache/incubator-nuttx/pull/1767#issuecomment-712434684 , the fix is forthcoming but it will be a while while all the CS issues are resolved.

**Comment by dagar** [comment]
Thanks @davids5. FYI bootloader update seems to be bricking the Holybro Durandal again (periodically?). The test rack is now per board setup is now flashing bootloaders.

**Comment by davids5** [comment]
> Thanks @davids5. FYI bootloader update seems to be bricking the Holybro Durandal again (periodically?). The test rack is now per board setup is now flashing bootloaders.

Let's how the test rack feels about theses changes.  Boot loader was hard faulting due to dynamic streams causing an OOO issues.  I fixed it with our dev/null fix.

**Comment by dagar** [comment]
At a glance things look good on the test rack. The only difference I'm seeing is a small memory savings depending on the board (maybe 3-4 kB).

**Review by dagar — APPROVED** [review]

**Comment by dagar** [comment]
Looks good to me, onward and upward!

**Pull request merged**
