### PR TITLE
[WIP] purge legacy mixers (switch to control allocation)

### PR DESCRIPTION
**Pull request by dagar**
This is still a bit premature, but lack of flash space is becoming a serious roadblock.

I'm opening this now so we can start to identify everything that will be needed to fully purge the old mixing system and replace it with control allocation.

#### Questions
 - how do we want to handle somewhat generic airframe defaults?
     - certain boards default to usable PWM_MAIN settings?

#### TODO
 - [ ] review and update all airframes
   - [ ] fixedwing
   - [ ] multicopter
   - [ ] vtol
     - [ ] standard
     - [ ] tailsitter
     - [ ] tiltrotor
   - [ ] rover
   - [ ] others
   - [ ] what can we delete?
 - [ ] dshot
 - [ ] pwm_out
    - [ ] crazyflie special case
 - [ ] px4io
 - [ ] pwm_out_sim
 - [ ] tap_esc (mantis)
 - [ ] review rev (PWM_MAIN_REV) and trim
 - [ ] introduce mechanism to limit airframes to specific boards or classes of board

### CODE REVIEW

**Comment by dagar** [comment]
Saves about 50 kB of flash on px4_fmu-v5x and around 30 kB on px4_fmu-v2_default.

**Comment by dagar** [comment]
Given the scale of this I think we should start incrementally converting airframes in master entirely to control allocation.

@sfuhrer @bkueng @MaEtUgR

**Comment by dagar** [comment]
Thanks @sfuhrer, I think we're in agreement. You probably didn't see it in the noise, but I already started dropping some of the nearly empty airframes.

 - generic airframes for each category
 - specific airframes that correspond to widely available RTF models and kits
     - we need to be careful here that the airframe doesn't capture more than it should (eg don't set the board rotation if it doesn't come with a flight controller)
     - we probably shouldn't even bother carrying frames that don't come with specific motors, ESCs, props, etc unless it's some non-trivial geometry
 - airframes for one specific board (like the crazyflie)


One area we should talk about is handling the transition for things like the VTOL setups where many users expected to use MAIN + AUX in a specific way. Are we ready to pull all of that away and have them rely on the GUI to assign actuators to physical outputs or should we carry a few specific transition airframes where we have something like a standard VTOL with PWM MAIN and PWM AUX configured all the way through as it is now?

**Comment by taileron** [comment]
> Thanks @sfuhrer, I think we're in agreement. You probably didn't see it in the noise, but I already started dropping some of the nearly empty airframes.
> 
> * generic airframes for each category
> * specific airframes that correspond to widely available RTF models and kits
>   
>   * we need to be careful here that the airframe doesn't capture more than it should (eg don't set the board rotation if it doesn't come with a flight controller)
>   * we probably shouldn't even bother carrying frames that don't come with specific motors, ESCs, props, etc unless it's some non-trivial geometry
> * airframes for one specific board (like the crazyflie)
> 
> One area we should talk about is handling the transition for things like the VTOL setups where many users expected to use MAIN + AUX in a specific way. Are we ready to pull all of that away and have them rely on the GUI to assign actuators to physical outputs or should we carry a few specific transition airframes where we have something like a standard VTOL with PWM MAIN and PWM AUX configured all the way through as it is now?

Is it perhaps even possible with the redesign of the mixer structure to decouple middle positions from limits and only mix on a fixed percentage or per 1000 basis? Currently, changing the upper or lower PWM limit shifts both the center and the gain of the respective mix function.

**Comment by sfuhrer** [comment]
> Is it perhaps even possible with the redesign of the mixer structure to decouple middle positions from limits and only mix on a fixed percentage or per 1000 basis? Currently, changing the upper or lower PWM limit shifts both the center and the gain of the respective mix function.

Changing the PWM min/max still also has an effect on the middle position, but you can additionally set an "output trim" to get servos centered. Please try it out and provide feedback, though best in a separate issue report, as it's not directly linked to the purpose of this PR.

**Comment by sfuhrer** [comment]
>One area we should talk about is handling the transition for things like the VTOL setups where many users expected to use MAIN + AUX in a specific way. Are we ready to pull all of that away and have them rely on the GUI to assign actuators to physical outputs or should we carry a few specific transition airframes where we have something like a standard VTOL with PWM MAIN and PWM AUX configured all the way through as it is now?

**Comment by sfuhrer** [comment]
I

**Comment by dagar** [comment]
Done!

**Pull request closed without merging**
