### PR TITLE
Update submodule mavlink v2.0 to latest Thu Oct 29 00:38:59 UTC 2020

### PR DESCRIPTION
**Pull request by dagar**
- mavlink v2.0 in PX4/Firmware (4bbea026e72f9aab7a159483e86a1f99e476ebad): https://github.com/mavlink/c_library_v2/commit/1eff57ee1e54fbed0b24617b1d4452d26d8b2221
    - mavlink v2.0 current upstream: https://github.com/mavlink/c_library_v2/commit/431cc688ca8484d0402e0ee8a73559f72cbc2750
    - Changes: https://github.com/mavlink/c_library_v2/compare/1eff57ee1e54fbed0b24617b1d4452d26d8b2221...431cc688ca8484d0402e0ee8a73559f72cbc2750

    431cc688 2020-10-28 PX4BuildBot - autogenerated headers for rev https://github.com/mavlink/mavlink/tree/b63eaf283c30c14fb075fa3d8092e71ed86f579d

### CODE REVIEW

**Comment by dagar** [comment]
FYI @Jaeyoung-Lim @TSC21 @bperseghetti looks like we need to update mavlink within the containers?
Screen Shot 2020-11-02 at 1 54 13 PM

Better yet, can we reconsider if a copy of mavlink is actually needed within the containers?

**Comment by Jaeyoung-Lim** [comment]
@dagar mavlink libraries are used in simulation submodules to build test without the firmware. Probably it can be removed and we can add it as part of the test setup phase

**Comment by Jaeyoung-Lim** [comment]
Ah, its sitl_gazebo that is outdated

**Comment by Jaeyoung-Lim** [comment]
@dagar Fixed in https://github.com/PX4/PX4-SITL_gazebo/pull/657

**Comment by Jaeyoung-Lim** [comment]
Replaced by https://github.com/PX4/PX4-Autopilot/pull/16233

**Pull request closed without merging**
