### PR TITLE
enable safetybutton of  cuav neov2pro can gps

### PR DESCRIPTION
**Pull request by gitfishup**
enable safetybutton of  cuav neov2pro can gps

### CODE REVIEW

**Comment by gitfishup** [comment]
@dagar Could you please provide quick feedback here?

**Comment by dagar** [comment]
Sorry, I missed this. https://github.com/PX4/PX4-Autopilot/pull/16292 contains the safety button specific feedback. https://github.com/PX4/PX4-Autopilot/pull/16292

In particular we need to untangle the `ORB_ID(safety)` usage so that modules aren't both publishing and subscribing to the same topic. https://github.com/PX4/PX4-Autopilot/pull/16292#issuecomment-735409388

**Comment by LorenzMeier** [comment]
Continuation of GPS PR is here: https://github.com/PX4/PX4-Autopilot/pull/16598

**Comment by LorenzMeier** [comment]
This is something we are now working on together in the other branch.

**Pull request closed without merging**
