### PR TITLE
Add support for stabilized mode on rovers

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
**Describe problem solved by this pull request**
Currently rovers only support manual mode and mission modes. However, manual mode can result in the heading constantly being changed when traversing in rough terrain. Therefore, it is better to be able to keep a constant heading while navigating rough terrain.

**Describe your solution**
This PR adds support for stabilized flight mode for rovers. In stabilized, the rover will try to keep a constant heading that can be moved using a manual stick input.

Since we already support attitude control in offboard mode, simply re-wiring this controller to the manual stick inputs allows support for stabilized mode. 

Additional cleanups along the way are the following
- updated the uORB API
- Changed the module to use the px4 work que in order to remove the while loop it was using previously. 
- Removed all the loops that were running in different frequencies with `fds`. Now the controller runs every time there is an attitude update

The cleanup and feature for stabilized are separated in different commits

**Test data / coverage**
- [x] SITL Testing
```
make px4_sitl gazebo_rover
```
Log: https://review.px4.io/plot_app?log=a43e5d2f-c3cf-4d47-b122-9059279955ed

- [ ] Real hardware testing

**Additional context**
- Next steps: This is something that is needed to prepare the `rover_pos_control` module to add the rate controller. This will probably happen by separating the attitude control functionality to a separate module. I believe that the poor performance of yaw tracking can be greatly improved by a rate controller.

### CODE REVIEW

**Comment by dagar** [comment]
Overall this looks much better. One area we should double check is the scheduling so that full manual control will still function without vehicle_attitude publishing. A simple conservative backup schedule is probably good enough (50 ms / 20 Hz). 

https://github.com/PX4/PX4-Autopilot/blob/ce552a33647daf83a21c2fd7313df7b3589e84b5/src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp#L437-L438

**Comment by Jaeyoung-Lim** [comment]
@dagar Thanks! That makes sense. But I think the same would also apply to the fixedwing attitude controller?

**Comment by dagar** [comment]
> @dagar Thanks! That makes sense. But I think the same would also apply to the fixedwing attitude controller?

Yes absolutely. This didn't matter originally because pure manual (with RC at least) is handled directly in the px4io, but that will soon not be the case at all.

A bit later this can become a simple standalone manual flight mode (outside of the controller) that does nothing but consume `manual_control_setpoint` and publish `actuator_controls_0`.

**Comment by Jaeyoung-Lim** [comment]
@dagar I added the timeout!

**Comment by LorenzMeier** [comment]
I've included your commits here: https://github.com/PX4/PX4-Autopilot/pull/16847

**Comment by LorenzMeier** [comment]
I tested this on real HW, works!

**Comment by Jaeyoung-Lim** [comment]
@LorenzMeier Thanks for testing!

**Pull request closed without merging**
