### PR TITLE
for testing ramtron

### PR DESCRIPTION
**Pull request by davids5**
Bringing in all the NuttX backorts for BCH and ramtron

ramtron: Remove errant code and definitions - was merged upstream

 - https://github.com/apache/incubator-nuttx/pull/4276
 - https://github.com/apache/incubator-nuttx/pull/4891 ()
 - https://github.com/apache/incubator-nuttx/pull/4299

### CODE REVIEW

**Comment by davids5** [comment]
@dagar Do you feel that the mtd for ramtron is sufficiently tested in HW CI? If so I will proceed with roundtripping the nuttx portion. 

FYI @jlaitine

**Comment by dagar** [comment]
> @dagar Do you feel that the mtd for ramtron is sufficiently tested in HW CI? If so I will proceed with roundtripping the nuttx portion.
> 
> FYI @jlaitine

It's not great, but it would catch blatant failures (parameters lost after a reboot, mtd rwtest, etc).

**Comment by davids5** [comment]
@dagar how's about adding an 'mtd rwtest'?

**Comment by dagar** [comment]
> @dagar how's about adding an 'mtd rwtest'?

Yes that's already done.

Screenshot from 2021-11-25 13-19-40

**Comment by davids5** [comment]
> > @dagar how's about adding an 'mtd rwtest'?
> 
> Yes that's already done.
> 
> Screenshot from 2021-11-25 13-19-40

I missed that. Ok then I would say it should go upstream....

**Comment by davids5** [comment]
NuttX changes unstreamed https://github.com/apache/incubator-nuttx/pull/4891

**Comment by davids5** [comment]
@dagar 
This has been reabased on master and repointed to Nuttx Backports https://github.com/PX4/NuttX/pull/172

**Comment by davids5** [comment]
@dagar Repointed to PX4 NuttX tip and rebased on master.

**Pull request merged**
