### PR TITLE
mavlink: STATUSTEXT increase stale message timeout

### PR DESCRIPTION
**Pull request by dagar**
RE: https://discuss.px4.io/t/looks-like-status-text-is-not-sent-if-heartbeat-from-gcs-is-lost/26118.

Likely needs more discussion.

### CODE REVIEW

**Comment by dagar** [comment]
I vaguely recall the original motivation was something like a user connecting to the system some time after boot and was greeted with a nasty mavlink critical that was badly out of date.

**Comment by dagar** [comment]
Additionally I've increased the mavlink level HEARTBEAT timeout condition from 1.5 -> 2 s.

**Comment by digitalw0lf** [comment]
> Additionally I've increased the mavlink level HEARTBEAT timeout condition from 1.5 -> 2 s.

IMHO 2.5 seconds would be better in this case, because with 2 seconds you will either detect a single heartbeat loss or no (50/50). Yes, this does not makes much difference currently, because heartbeat timeout does not triggers any immediate action, but just in case.
Otherwise, PR looks acceptable.

**Comment by dagar** [comment]
HEARTBEAT timeout increased to 2.5 seconds.

**Comment by dagar** [comment]
I suppose we could be treating any valid mavlink from a particular component/mavtype as a "HEARTBEAT" update.

**Pull request merged**
