### PR TITLE
delete rattitude flight mode

### PR DESCRIPTION
**Pull request by dagar**
Opening for discussion, but in my opinion we don't need this.

### CODE REVIEW

**Review by bresch — DISMISSED** [review]
I agree. And you can still map stabilized and acro on a mode switch

**Comment by bkueng** [comment]
Personally I don't mind, but as it's a somewhat common mode, why not keep it?

> And you can still map stabilized and acro on a mode switch

That is certainly not the same thing.

**Comment by dagar** [comment]
> Personally I don't mind, but as it's a somewhat common mode, why not keep it?

I'm happy to drop this if anyone is aware of any actual usage. I'm gradually trying to get to the point where the control mode flags set which controllers are actually running and rattitude is a weird case I don't want to work through first if it doesn't actually matter.

Ultimately I want to be able to carry arbitrary random modes like this, but completely self contained. The mode itself should be able to open/close the attitude loop if it wants to, but without special handling scattered in both controllers. We'll also be able to trivially add/remove it from builds similar to a module today.

**Comment by bkueng** [comment]
> Ultimately I want to be able to carry arbitrary random modes like this, but completely self contained. The mode itself should be able to open/close the attitude loop if it wants to, but without special handling scattered in both controllers. We'll also be able to trivially add/remove it from builds similar to a module today.

And we can't retain rattitude until we're there?

**Review by MaEtUgR — APPROVED** [review]
I agree with removing it since I don't know of anyone who uses it or any other possibility to use it other than flipping with constant speed.

> And we can't retain rattitude until we're there?

We could, do you see value? Do you use it? Do you know anyone using it? That would be valuable feedback.

**Comment by dagar** [comment]
> > Ultimately I want to be able to carry arbitrary random modes like this, but completely self contained. The mode itself should be able to open/close the attitude loop if it wants to, but without special handling scattered in both controllers. We'll also be able to trivially add/remove it from builds similar to a module today.
> 
> And we can't retain rattitude until we're there?

We can if there's any value at all. Otherwise dropping it for the time being makes it every so slightly easier to get to that new world.

**Comment by RomanBapst** [comment]
@bkueng I think the problem with this flightmode is that you made acro work so well nowdays that people don't need the "stabilized" mode anymore, they just keep the vehicle in acro mode and let go of the sticks, feels like stabilized ;-)

**Review by RomanBapst — DISMISSED** [review]

**Comment by bkueng** [comment]
> @bkueng I think the problem with this flightmode is that you made acro work so well nowdays that people don't need the "stabilized" mode anymore, they just keep the vehicle in acro mode and let go of the sticks, feels like stabilized ;-)

Haha, well then, even better.
I was just thinking that all a user sees here is a loss of functionality, so we should at least clarify in the release notes that we can easily re-add it if requested.

**Comment by bkueng** [comment]
@dagar can you update the docs, or ask @hamishwillee ?

**Pull request merged**
