### PR TITLE
Add SITL targets for Iris models with depth cameras

### PR DESCRIPTION
**Pull request by DanMesh**
### Solved Problem

Vehicle models with depth cameras were available, but the corresponding targets to run simulations with these models were missing.

Docs for the models were prematurely added in https://github.com/PX4/PX4-user_guide/pull/2264, but had to be hidden since these targets were not available.

- Fixes https://github.com/PX4/PX4-user_guide/issues/2283

### Solution

Add SITL targets for Iris with forward- and downward-facing depth cameras.

### Changelog Entry
For release notes:
```
Add SITL targets for Iris models with depth cameras
```

### Alternatives
Remove the depth camera models and not support simulations with depth cameras.

### Test coverage
Tested that the simulation could be launched with the new models.

### Context
N/A

### CODE REVIEW

**Comment by DanMesh** [comment]
If they're left out, what would the workflow look like for developers who want to use these and other ROS-related models?

As PX4 becomes more closely linked with ROS, I'd imagine we'll have more people wanting to work with models like these. So it would be beneficial to have suitable simulation targets already available.

I agree that adding the airframe configs is somewhat unnecessary, but is it possible to use a default config with a different model?

**Comment by hamishwillee** [comment]
> , but is it possible to use a default config with a different model?

This is the question. 

As a user I want to be able to use a depth camera. I'd actually prefer to be able to add the sensor to my preferred airframe (not iris). But if iris is the only way, then I'd rather that than nothing.

Similarly, it would make my life easier to be able to attach arbitrary video cameras to an iris (say) to test multi camera setups.

**Comment by Jaeyoung-Lim** [comment]
@DanMesh The make targets are only used when you build and run SITL through the `make` command. However, you will never do this when you are launching with ros correct?

In ROS, you normally select the model and airframe separately in the launchfile. For example, if you are trying to use the model for obstacle avoidance, adding a new airframe config makes sense since you need to configure the vehicle for this use case(which is already done for px4vision).

I am not against adding airframe configs when it makes sense. I just don't see why these particular models are useful to have an airframe config.

**Comment by DanMesh** [comment]
>The make targets are only used when you build and run SITL through the make command. However, you will never do this when you are launching with ros correct?

@Jaeyoung-Lim I use the `make` command to launch the simulation and don't use ROS for that. Separately, I have a ROS 2 node running which is subscribing to the depth camera images. This is the kind of use case I have in mind when wanting to add the models, where all that is needed for the PX4 sim is
```sh
make px4_sitl gazebo-classic_iris_depth_camera
```

I'm not entirely clear on what you mean by "launching with ROS". If there is a way to launch a PX4 simulation with customisable airframes (using ROS or not), that would fit my use case equally well - and that which @hamishwillee describes.

**Comment by Jaeyoung-Lim** [comment]
> If there is a way to launch a PX4 simulation with customisable airframes (using ROS or not), that would fit my use case equally well 

This is how it is already with the launchfile of ROS1.

With ROS2, this is also possible, but you would just need to write a launchfile in this way. The only problem is that px4 does not contain launchfiles for ros2 at the moment. @dagar FYI

**Comment by hamishwillee** [comment]
@Jaeyoung-Lim OK, so pretend ROS does not exist (as I like to). How do I:
- Launch a simulation with a depth camera
- Launch a simulated vehicle with three MAVLink cameras?

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee It doesn't make sense to launch a depth camera model without ROS, since the depth data is published to ROS.

For the camera, you just need to add multiple instances of the camera manager to different camera sensors in gazebo and configure the udp ports for it.

**Review by dagar — APPROVED** [review]

**Comment by hamishwillee** [comment]
> For the camera, you just need to add multiple instances of the camera manager to different camera sensors in gazebo and configure the udp ports for it.

@Jaeyoung-Lim That's awesome. I don't see any documentation on that? Am I missing something?

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee For me this is more of an integration problem. 

AFAIK QGC does not supports this usecase, so even if someone creates such a model they would only be able to test it with a proprietery ground station that has multicam support (e.g. Auterion Mission Control)

**Pull request merged**
