### PR TITLE
fmu-v5: move some test commands to test config

### PR DESCRIPTION
**Pull request by julianoes**
I would expect anyone using these test commands can just use the test config instead.

This should unblock the flash issue for main/v1.14, I'd hope.

### CODE REVIEW

**Comment by julianoes** [comment]
@dagar this should help with flash for main/v1.14, right?

**Comment by julianoes** [comment]
:wave: bump

**Comment by mrpollo** [comment]
Hey, @julianoes, we have seen users frequently perform SD bench tests whenever they realize they have a crappy SD card. Would it be possible to keep the test?

**Comment by julianoes** [comment]
Of course! This is just a suggestion. Can can change my PR as you wish.

**Comment by julianoes** [comment]
Done.

**Comment by junwoo091400** [comment]
Dang since the `v5_test` target is still overflowing, CI doesn't pass 😢

**Review by dagar — APPROVED** [review]

**Pull request merged**
