### PR TITLE
ekf2: verbose print status with Matrix improved print

### PR DESCRIPTION
**Pull request by dagar**
This is an experiment to see if we can pretty print the full covariance matrix on the command line (`ekf2 status`). Currently off by default unless you enable the DEBUG_BUILD define for ekf2 in CMakeLists.txt.

In the Matrix print helper I condensed the output (fixed width), added special handling for zero (so it's obvious) and also print the row/column.

``` Console
nsh> ekf2 status


ekf2:0 EKF dt: 0.0105s, IMU dt: 0.0052s, attitude: 1, local position: 0, global position: 0
ekf2: ECL update: 785 events, 4973us elapsed, 6.34us avg, min 1us max 203us 10.519us rms
ekf2: ECL full update: 553 events, 183481us elapsed, 331.79us avg, min 150us max 829us 131.936us rms
ekf2: IMU message missed: 3 events
ekf2: vehicle_air_data messages missed: 0 events
ekf2: vehicle_gps_position messages missed: 0 events
ekf2: vehicle_magnetometer messages missed: 0 events

Q: (0-3)
 0| 0.95657 
 1| 0.01003 
 2|-0.00255 
 3|-0.29130 
Velocity: (4-6)
 0| 0.02055 
 1| 0.01271 
 2| 0.00798 
Position: (7-9)
 0| 0.40394 
 1|-0.19808 
 2|-0.60134 
Delta Angle Bias: (10-12)
 0| 0       
 1| 0       
 2| 0       
Delta Velocity Bias: (13-15)
 0| 0       
 1|-0.00001 
 2| 0.00006 
Magnetic Field: (16-18)
 0| 0.18535 
 1|-0.01996 
 2| 0.50808 
Magnetic Bias: (19-21)
 0| 0       
 1| 0       
 2| 0       
Wind: (22-23)
 0| 0       
 1| 0       
P:
  | 0      | 1      | 2      | 3      | 4      | 5      | 6      | 7      | 8      | 9      |10      |11      |12      |13      |14      |15      |16      |17      |18      |19      |20      |21      |22      |23      
 0| 0        0        0        0.00002  0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0       
 1| 0        0.00007  0        0        0.00005  0.00016  0        0.00004  0.00013  0        0        0        0        0        0.00001  0        0        0        0        0        0        0        0        0       
 2| 0        0        0.00007  0       -0.00017  0.00005  0       -0.00014  0.00004  0        0        0        0       -0.00001  0        0        0        0        0        0        0        0        0        0       
 3| 0.00002  0        0        0.00009  0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0       
 4| 0        0.00004 -0.00016  0        0.01471  0        0        0.02659  0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0       
 5| 0        0.00016  0.00004  0        0        0.01495 -0.00001  0        0.02711  0        0        0        0        0        0        0        0        0        0        0        0        0        0        0       
 6| 0        0        0        0        0       -0.00001  0.01486  0       -0.00001  0.04099  0        0        0        0        0       -0.00001  0        0        0        0        0        0        0        0       
 7| 0        0.00004 -0.00014  0        0.02856  0        0        0.19460  0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0       
 8| 0        0.00014  0.00004  0        0        0.02931 -0.00001  0        0.19693 -0.00001  0        0        0        0        0        0        0        0        0        0        0        0        0        0       
 9| 0        0        0        0        0        0        0.04069  0        0        0.25277  0        0        0        0        0       -0.00003  0        0        0        0        0        0        0        0       
10| 0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0       
11| 0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0       
12| 0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0       
13| 0        0       -0.00001  0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0       
14| 0        0.00001  0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0       
15| 0        0        0        0        0        0       -0.00001  0        0       -0.00003  0        0        0        0        0        0        0        0        0        0        0        0        0        0       
16| 0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0       
17| 0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0       
18| 0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0       
19| 0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0       
20| 0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0       
21| 0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0       
22| 0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0       
23| 0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0        0       

```

### CODE REVIEW

**Review by bresch — DISMISSED** [review]
nice

**Review by bresch — APPROVED** [review]
Any reason not to merge that now?

**Comment by dagar** [comment]
> Any reason not to merge that now?

No, just the minor conflicts. Let's get it through CI cleanly then merge immediately.

**Comment by dagar** [comment]
Strange, unit-MatrixAssignment still failing for some reason even though it's not hitting any asserts.

image

**Comment by bresch** [comment]
> Strange, unit-MatrixAssignment still failing for some reason even though it's not hitting any asserts.

If was hitting an assert, but the stdout stream is still redirected for some reason, this is why the error message and printf don't show up. I fixed the test case but I wasn't able to redirect the stream back to the console.

**Review by bresch — APPROVED** [review]

**Pull request merged**
