### PR TITLE
add board definition and imu sensor for JFB110

### PR DESCRIPTION
**Pull request by jfbblue0922**
we are developing JAE flight controllers to be compatible with PX4.
we would like to continue development in the future, so we have created a PR.

JFB-110 Flight Controller
https://www.jae.com/Motion_Sensor_Control/eVTOL/FlightController/

Added JFB-110 board control function
・add JFB-110 board definition（boards/jfb）
・add external watchdog clear signal output（boards/jfb/jfb110/src）
・add imu sensor SCHA63T（src/drivers/imu/murata）

thank you.

### CODE REVIEW

**Comment by dagar** [comment]
The board support looks good, but could you please explain the io_timer/io_pins change?

There's also a minor merge conflict to resolve.
image

**Comment by dagar** [comment]
Minor code style failures in CI. https://github.com/PX4/PX4-Autopilot/actions/runs/9126759801/job/25095670689

image

**Comment by jfbblue0922** [comment]
@dagar

Thank you for your advice.

Regarding the PWM IO pin assignment of the JFB110 board, the timer was not continuous, so I changed it.

**Comment by jfbblue0922** [comment]
I pulled from the latest master and tried to run it on the JFB board,
but it became unstable.

Once I can confirm that it works properly, I will make a new PR.
This PR will be close.
Thank you.

**Pull request closed without merging**
