### PR TITLE
use github CI to deploy metadata to S3

### PR DESCRIPTION
**Pull request by bkueng**
- enumerate all existing build targets & variants automatically (with some excludes, like qurt or sitl replay)
  - pushes parameter metadata to S3. This can be extended to other metadata & binaries as well (replacing Jenkins)
  - directory structure is as below
  - there's some inconsistency with container naming (some add `-focal` while others do not) that should be fixed
- ignores `ext/*` git tags, to allow for external/extra git tags

### S3 directory structure
- general metadata, containing all modules (e.g. for flight review): `Firmware/<version>/_general/`
- per-board: `Firmware/<version>/<board>/`
  - `version`: if on a git tag, it's the git tag, if on a `release/x.y` branch, it's `release-x.y`, otherwise it's `master`. This could also be made more granular (e.g. commits on master) if needed.
  - `board`: this is the build target, e.g. `px4_fmu-v4_uavcanv1`

### CODE REVIEW

**Review by LorenzMeier — CHANGES_REQUESTED** [review]
@bkueng The list of checks (with 185) gets a bit unmanageable - can we have metadata as a single check instead? It's impossible to find a failed check in this pile now.

**Comment by dagar** [comment]
The vast majority of the work overlaps with the regular builds, can we combine them?

Even for the existing builds I was looking at options to better group them to try and minimize the scrolling.

**Comment by bkueng** [comment]
This will only run on `master`, `release/*`and `pr-metadata-test` branches so it does not apply to normal PR's.

**Comment by dagar** [comment]
> This will only run on `master`, `release/*`and `pr-metadata-test` branches so it does not apply to normal PR's.

Is there not an easy way put a conditional on only the s3-sync-action? This is also something that needs to be done for the existing compile jobs to fully kill off Jenkins.

**Comment by dagar** [comment]
I'll unify this later if possible.

**Comment by bkueng** [comment]
>  Is there not an easy way put a conditional on only the s3-sync-action?

Yes: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#example-expression-in-an-if-conditional

**Pull request merged**
