### PR TITLE
platforms: nuttx: SerialImpl: fix poll timeout and integer underflow

### PR DESCRIPTION
**Pull request by dakejahl**
A microsecond time was being passed to `poll()`, which takes a millisecond timeout. Also if the elapsed time was already greater than the timeout an integer underflow would occur which causes poll to block forever.

- fix poll timeout
- fix integer underflow

### CODE REVIEW

**Review by katzfey — CHANGES_REQUESTED** [review]
Looks like this would need to be done for the Posix platform as well.

**Review by katzfey — APPROVED** [review]

**Comment by MaEtUgR** [comment]
FYI I don't exactly understand why but this change possibly in combination with others creates issues on main:
1. https://github.com/PX4/PX4-Autopilot/issues/23289
1. The MAVLink communication the companion computer on Skynode has multiple seconds round trip which times out almost all protocols (credits to @chfriedrich98 for finding and bisecting this issue)

**Comment by katzfey** [comment]
I think it would be better to change readAtLeast timeout to milliseconds instead of microseconds because users of this call seem to be using it will millisecond values.

**Comment by katzfey** [comment]
I'll create a new PR that changes the timeout to milliseconds.

**Comment by katzfey** [comment]
See https://github.com/PX4/PX4-Autopilot/pull/23296

**Pull request merged**
