### PR TITLE
Decouple filepaths from rcS/MTD using Kconfig

### PR DESCRIPTION
**Pull request by PetervdPerk-NXP**
As an alternative to #20805 and discussed in today's dev call.

File path configuration through Kconfig.

For now we only introduce symbols for param and logger.
- BOARD_LOG_DIR
- BOARD_PARAM_FILE

Furthermore we generate a ROMFS `rc.filepaths` that takes `BOARD_PARAM_FILE`

### CODE REVIEW

**Comment by PetervdPerk-NXP** [comment]
@dagar  I've changed the mechanism a bit could you take a look it?

@Igor-Misic  I've added a second commit here as well to use LittleFS on the fmu-v6xrt. I saw you were working on LittleFS before would you be able to test this on your hardware and share your thoughts?

**Comment by PetervdPerk-NXP** [comment]
Moved the LittleFS commit to #22749
Overall I think it's ready for review.
Also this PR poses a potential fix for #22590 because one simply has to format the QSPI with a filesystem and then define `BOARD_LOG_DIR` to point to the mount point of the filesystem.

**Comment by davids5** [comment]
@PetervdPerk-NXP I am looking at the notion of replacing the persistent storage location `/fs/microsd` across  the system. This path is hardcoded in a lot of places, UAVCAN, NetMan, DataMan etc. The approach I was considering was to create `#if !defined(PX4_ROOT_STOAGE)` and set it in board_comon.h to the current default.. Then any board can override it by setting it in board_config.h.  Now that you have this mechanism; What would you suggest should be done?

**Comment by PetervdPerk-NXP** [comment]
Superseded by #23003

**Pull request closed without merging**
