### PR TITLE
fix ROMFS: run camera trigger, capture and PPS before pwm_out

### PR DESCRIPTION
**Pull request by bkueng**
As they might need to reserve the pwm pins.

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
@bkueng Thanks for the quick fix!

I tried this PR with `CAM_CAP_FBACK` enabled, but the capture still doesn't seem to be enabled
```
INFO  [camera_capture] Capture enabled : NO
INFO  [camera_capture] Frame sequence : 0
INFO  [camera_capture] No trigger yet
INFO  [camera_capture] Number of overflows : 0
INFO  [camera_capture] Status chan: 5 edges: 0 last time: 0 last state: 0 overflows: 0 latency: 0
```
Is this expected?

**Comment by Jaeyoung-Lim** [comment]
@bkueng Thank you so much for the quick fix!

This fixed the problem with camera capture being disabled:
```
INFO  [camera_capture] Capture enabled : YES
INFO  [camera_capture] Frame sequence : 0
INFO  [camera_capture] No trigger yet
INFO  [camera_capture] Number of overflows : 0
INFO  [camera_capture] Status chan: 5 edges: 0 last time: 0 last state: 0 overflows: 0 latency: 0
```
I will report back with the full camera trigger workflow :smile:

**Comment by Jaeyoung-Lim** [comment]
Hmm I think it might not be reliable

Reflashing the pixhawk with the same PR results in a different result
```
camera_capture status
INFO  [camera_capture] Capture enabled : NO
INFO  [camera_capture] Frame sequence : 0
INFO  [camera_capture] No trigger yet
INFO  [camera_capture] Number of overflows : 0
INFO  [camera_capture] Status chan: 1 edges: 0 last time: 0 last state: 0 overflows: 0 latency: 0
```

**Review by dagar — APPROVED** [review]

**Comment by dagar** [comment]
@Jaeyoung-Lim try explicitly advertising the camera_capture publication in the module's constructor.

**Comment by dagar** [comment]
Regression from https://github.com/PX4/PX4-Autopilot/pull/20108.

**Comment by Jaeyoung-Lim** [comment]
I think now the camera capture status is always disabled even though I cycled the power a few times.

**Pull request merged**
