### PR TITLE
boards: mro ctrl-zero-h7 pin fixes

### PR DESCRIPTION
**Pull request by dagar**
The larger diff is from syncing this up with the pixracer pro.

### CODE REVIEW

**Comment by ryanjAA** [comment]
I’ll give this a try when back.

**Comment by dagar** [comment]
These were obviously wrong. @ryanjAA ping me when you're back and we'll give these boards another quick pass to see if anything else is missing.

**Comment by ryanjAA** [comment]
Back so can test as needed. @dagar

**Comment by dagar** [comment]
> Back so can test as needed. @dagar

Thanks @ryanjAA. For the boards you care about could you do a quick pass with master and see if anything is missing at this point? 

I was also going to reduce the speed a bit to lower the temperature. https://github.com/PX4/PX4-Autopilot/pull/19036

**Pull request merged**
