### PR TITLE
NuttX with SDMMC Backport

### PR DESCRIPTION
**Pull request by davids5**
For testing of  https://github.com/PX4/NuttX/pull/146

Once the NuttX PR is merged, this will be repointed.

### CODE REVIEW

**Comment by davids5** [comment]
@dagar - did this run on the test rack?

**Comment by davids5** [comment]
> @dagar - did this run on the test rack?

Sorry I see it now... http://ci.px4.io/blue/organizations/jenkins/PX4_misc%2FFirmware-hardware/detail/pr-NuttX-sdmmc-bp-test/1/pipeline

Do you see any issues with it?

**Comment by dagar** [comment]
> @dagar - did this run on the test rack?

Yes - http://ci.px4.io/blue/organizations/jenkins/PX4_misc%2FFirmware-hardware/detail/pr-NuttX-sdmmc-bp-test/1/pipeline/685

Screen Shot 2021-04-08 at 10 53 22 AM

Screen Shot 2021-04-08 at 10 54 20 AM

**Comment by dagar** [comment]
Rebased with updated NuttX.

**Review by dagar — APPROVED** [review]

**Comment by BazookaJoe1900** [comment]
@davids5, @dagar it seems that the write speed been increased by factor of 5. is that right? and that what the pr should been done?

**Comment by davids5** [comment]
@BazookaJoe1900 - on what HW? Something with a dcache?  Is that just this change (there was a previous sd_bench change)? 
The last change to sd_bench has an option to use unaligned (usually the default prior to the sd_bench change) but defaults to aligned buffers now. This enables DMA transfers.

Please confirm log files are AOK on your craft after this change.

**Comment by BazookaJoe1900** [comment]
the HW is stm32f7 based.
I am not sure on which versions the print screen were done. so not sure if there were other changes

**Comment by dagar** [comment]
In retrospect I see that comment might be a bit misleading. As a quick verification of this change I checked all the boards on the test rack and those screenshots are from 2 randoms.

There's actually quite a huge difference in SD performance across both different cards and different boards (SDMMC domain). For example Cube Orange (stm32h7) with the cheapo SD card it ships with is surprisingly slow (sdbench ~ 60 kB/s) compared to fmu-v5 (stm32f7) with a slightly better U3 replacement card (~ 1500 kB/s). The actual state of the card (write cycles) is probably a big factor we're oblivious to.

**Comment by davids5** [comment]
> In retrospect I see that comment might be a bit misleading. As a quick verification of this change I checked all the boards on the test rack and those screenshots are from 2 randoms.
> 

Yeah I had not clue what you were showing - and why there were only 2 lines. 

> There's actually quite a huge difference in SD performance across both different cards and different boards (SDMMC domain). For example Cube Orange (stm32h7) with the cheapo SD card it ships with is surprisingly slow (sdbench ~ 60 kB/s) compared to fmu-v5 (stm32f7) with a slightly better U3 replacement card (~ 1500 kB/s). The actual state of the card (write cycles) is probably a big factor we're oblivious to.

A better comparison is H7 to H7 and same card. With the same config running. Comparing Cube Orange (stm32h7)  to a FMUv6 using the same card 2 times each in both units. would be meaningful.

**Pull request merged**
