### PR TITLE
add windy default world

### PR DESCRIPTION
**Pull request by frede791**
Adds a windy default world to Gazebo. Changing the wind velocity only requires to modify the `linear_velocity` parameter near the bottom of the sdf file. 

To run the world use: `make px4_sitl gz_x500_windy` in the PX4-Autopilot repo. You may run into an `unknown target` error. In this case first run `make clean && make distclean` before running the command. 

### Solved Problem
Adds a windy default world to Gazebo. Changing the wind velocity only requires to modify the `linear_velocity` parameter near the bottom of the sdf file. 

### Test coverage
https://review.px4.io/plot_app?log=b0969110-5339-4e60-8c22-30bb36020d4b

### CODE REVIEW

**Review by Jaeyoung-Lim — COMMENTED** [review]
Awesome!

Two questions
- Is this already part of the available make targets?
- Have you tried out vehicles in wind and checked if they actually influence the flight? Wind should influence the thrust of the motors, lift/drag of aerodynamics and the airspeed sensor values
- Probably worth checking if the advanced liftdrag plugin also uses wind information?

**Comment by Jaeyoung-Lim** [comment]
> No, not currently, but I wasn't aware that there is a Cmake file for Gazebo worlds (if so, can you point me to its location?)

If so, how is someone expected to run the windy world? Could you include this in the PR description? It would be great if you can keep the PR template and fill in the relevant information.

> Yes, i have tried the x500, noticing a significant slant in the position of the vehicle in mid-air (to make it even more pronounced set the linear velocity value to 100 100 100 and you will see the vehicle getting blown off the map)

I am more curious the actual behavior -> whether if it is close to what we expect on the real vehicle, or if it is just applying some wrench force on the joints to look like some force is being applied.

Please also check with the airspeed sensors and liftdrag plugins. 

> Advanced Lift Drag currently does not use it, but I already have it on my todo list once the regular plugin gets merged.

Awesome!

**Comment by frede791** [comment]
Updated the description to explain how to run the world and also provided a flightreview. I am not sure how to interpret the data to see whether the model behaves as we want it to.

**Comment by frede791** [comment]
The way I understand wind, it can be enabled for individual links or the whole model, depending on what parameters are set. By only setting the `enable_wind` flag for the world and not disabling it for any of the individual links, I believe that wind affects all necessary links. The way in which they are affected depends on the respective plugins. In the x500 for example, wind only affects the motormodel plugins, as this is where the wind velocity gets factored into the calculation of the moments and forces. Since these moments and forces are applied for each rotor individually (rather than in one central point like the advanced lift drag plugin), I would think that the wind affects each component individually.

**Comment by beniaminopozzan** [comment]
Thanks @frede791 !
FYI, you can also start a `gz_x500` simulation with the new world with
```sh
make px4_sitl gz_x500_windy_default
```

**Comment by frede791** [comment]
@beniaminopozzan i have tried this but I get  an "unknown target" error

**Comment by beniaminopozzan** [comment]
> @beniaminopozzan i have tried this but I get an "unknown target" error

@frede791 , do a clean build calling `make distclean` first

**Comment by frede791** [comment]
yes this works. I will update the PR and also make a PR to the px4 user guide.

**Comment by Jaeyoung-Lim** [comment]
@frede791 One more thing -> could we remove the default and just name in `windy.world`?

**Comment by frede791** [comment]
@Jaeyoung-Lim @beniaminopozzan Addition to the PX4 user guide. Feel free to add if you think there is something missing/lacking.
https://github.com/PX4/PX4-user_guide/pull/2817

**Comment by frede791** [comment]
@Jaeyoung-Lim https://github.com/PX4/PX4-user_guide/pull/2817 has been merged into the user guide. Should we look to merge this as  well?

**Review by Jaeyoung-Lim — APPROVED** [review]

**Pull request merged**
