### PR TITLE
uORB Service feature

### PR DESCRIPTION
**Pull request by junwoo091400**
## Describe problem solved by this pull request
Currently uORB has no concept of a [Service](https://docs.ros.org/en/foxy/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Services/Understanding-ROS2-Services.html) or an Action, but rather has modules publishing / subscribing to topics in global context.

This is like having people talking loudly to each other in a open space, and we want to make that more into a civilized, one-to-one conversation based architecture where you don't need to hear / interpret what everyone is saying in the room :tea: 

### ROS 2
image
Source: [ROS2 Foxy Documentation](https://docs.ros.org/en/foxy/_images/Service-MultipleServiceClient.gif)

In **ROS2**, Service and Action is used for defining a clear request / response structure between two entities where the messages are guaranteed to be delivered back & doesn't interfere with other modules sending messages in the same topic.

### Current status of PX4
This is useful for example when a certain module wants to do a `vehicle_command` to the Commander, and make sure that it receives the result of that command to know whether it was accepted / rejected / pending, etc.

Currently, PX4 has two separate topics such as `vehicle_command` and `vehicle_command_ack`, which basically implements the Service architecture (one is for sending the command & the other for receiving the result of it), but it never ties those two messages together, with two dedicated entities (e.g. Navigator & Commander) and it is just not so usable.

### Google Doc
In [this document](https://docs.google.com/document/d/1Wzh4lwDiQ7evSyO_0ElSq_qMpU89nu0VJ1kMkNyrX2Y/edit#), you can find the architecture proposal.

### Pseudocode
A service has an argument & response.
Pseudocode (does not have to look exactly like this, just as an inspiration):
On **provider**
```
uORB::ServiceProvider<ORB_ID(argument_type), ORB_ID(response_type)> service(SERVICE_INSTANCE_XXX)

run() {
...
  while (service.called()) {
    argument_type arg;
    service.get_call_arg(arg);
    response_type response;
    // DO PROCESSING
    service.handle_call(response);
  }
...
}
```

On **caller** 
 ```
uORB::Service<ORB_ID(argument_type), ORB_ID(response_type)> service(SERVICE_INSTANCE_XXX)


// Invoke the service
future<response_type> future = service.call(argument, TIMEOUT);

// check if future is done or timeout 
  if (future.done() || future.timeout()) {
    if (future.done()) {
      response_type response = future.get()
    } else {
      // handle timeout error
    }
  }
```

## Questions
1. Can we do interoperability with ROS2?
2. What if there are multiple providers of the same service? Could we dynamically add new providers of a service, how would the other modules know which provider to call? -> E.g. multiple flight modes offering a “has_activated“ service

## Resources
- ROS2 Service Internals: https://docs.ros.org/en/foxy/Concepts/About-Internal-Interfaces.html
- https://github.com/ros2/rclcpp
-

### CODE REVIEW

**Comment by dagar** [comment]
For reference you might want to take a look at XRCE-DDS Requester and Replier to see how we could almost immediately have ROS2 interoperability. https://micro-xrce-dds.docs.eprosima.com/en/latest/introduction.html

**Comment by dirksavage88** [comment]
@junwoo091400 nxp has their embedded RPC implementation, [eRPC](https://github.com/EmbeddedRPC/erpc) might be worth a look-see for reference?

**Comment by junwoo091400** [comment]
> @junwoo091400 nxp has their embedded RPC implementation, [eRPC](https://github.com/EmbeddedRPC/erpc) might be worth a look-see for reference?

Thanks for the reference, will check it out!

**Comment by swimmingseeds** [comment]
This pull request has been mentioned on **Discussion Forum for PX4, Pixhawk, QGroundControl, MAVSDK, MAVLink**. There might be relevant details there:

https://discuss.px4.io/t/px4-community-q-a-march-01-2023/30941/1

**Pull request closed without merging**
