### PR TITLE
boards: NuttX disable CONFIG_RAMTRON_WRITEWAIT

### PR DESCRIPTION
**Pull request by dagar**
I don't think we actually benefit from this period, but more specifically it's causing an initial read failure due to the status register write protect enable bit (WPEN). 

https://github.com/PX4/NuttX/blob/ec8f6f56050033cc46a099f084f82137e08fa619/drivers/mtd/ramtron.c#L887-L902
Screenshot from 2021-11-13 13-53-01

Screenshot from 2021-11-13 13-52-38

Given we aren't setting any protected blocks, don't have boards with control of the write protect pin, and never write to the statue register, I don't see why this check even matters.

Additionally with CONFIG_RAMTRON_WRITEWAIT disabled we still check for in progress writes before any new reads or writes.

### CODE REVIEW

**Comment by davids5** [comment]
@dagar Had a look at this. I never see the failure from reset or fresh power on. In fact status is always a 0xff 

The enable give better performance, we do not wait on write and can get some || ism

**Comment by davids5** [comment]
@dagar - you must be working on a different branch of nuttx.  We are missing https://github.com/apache/incubator-nuttx/pull/4276 and hence the FF.

**Comment by davids5** [comment]
@daga I was going to close as replaced by PR #18720 but b435f93 looks to be of value

**Comment by dagar** [comment]
> @dagar I was going to close as replaced by PR #18720 but [b435f93](https://github.com/PX4/PX4-Autopilot/commit/b435f93c5a7c6b814089688f83cb6611eb8b6dbb) looks to be of value

Continued in https://github.com/PX4/PX4-Autopilot/pull/18678.

**Pull request closed without merging**
