### PR TITLE
drivers/distance_sensor/broadcom/afbrs50: minimize IRQ_LOCK()/IRQ_UNLOCK() calls

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by AlexKlimaj** [comment]
Looks like it has the same behavior with the icm-42688p. But without the 42688p turned on, it performs like I would except.
image

**Review by AlexKlimaj — DISMISSED** [review]
Doesn't fix the issue with the 42688p, but performs the same as before.

**Comment by AlexKlimaj** [comment]
Maybe we don't want interrupts locked for each spi transfer?

**Comment by dagar** [comment]
> Maybe we don't want interrupts locked for each spi transfer?

We definitely don't. The confusion here is deciphering what they're actually doing (what's actually needed) with the locking internally. Using SPI_LOCK might be more appropriate if the lock/unlock is called outside of an interrupt context.

**Comment by AlexKlimaj** [comment]
@goetzfrv Here is the issue. We are trying to understand how and why the IRQ lock is needed so often and why it is getting stuck in it when there are other high priority tasks running.

**Pull request merged**
