### PR TITLE
mavlink: support receiving multi-chunk statustexts

### PR DESCRIPTION
**Pull request by julianoes**
This adds support for mavlink statustext messages arriving in multiple chunks.

### CODE REVIEW

**Comment by dagar** [comment]
I suppose it probably doesn't matter, but it might be nice to completely clear out anything old in log_message.text so it's not distracting if looking directly at the raw published data.

**Review by dagar — DISMISSED** [review]

**Comment by julianoes** [comment]
@dagar I'm sorry, don't understand what you mean exactly. Happy to adapt it though.

**Comment by dagar** [comment]
> @dagar I'm sorry, don't understand what you mean exactly. Happy to adapt it though.

When reusing the same `log_message_s` buffer the new text is NULL terminated, but previous longer messages could still be in the text after the NULL. This doesn't really matter, but it could be nice to clear out the full text field so that previous garbage isn't actually present in the publication. For example imagine it going out to ROS2 and debugging what's actually on the wire.

**Comment by julianoes** [comment]
Ok, got it. I will fix it.

**Comment by julianoes** [comment]
@dagar I've added a test and it turns out it's already correct because we're using `strncpy`, and it turns out `strncpy` does it for you.

>  Copies the first num characters of source to destination. If the end of the source C string (which is signaled by a null-character) is found before num characters have been copied, destination is padded with zeros until a total of num characters have been written to it.
https://www.cplusplus.com/reference/cstring/strncpy/

**Review by dagar — APPROVED** [review]

**Pull request merged**
