### PR TITLE
Fixed micro hal from dshot and added  allocation alignment

### PR DESCRIPTION
**Pull request by davids5**
The first part is //Fix me! REMOVE this The DSHOT added this and needs to be fixed

F7 alignment is unchanged.
```
Before

080140f8 0000001c T dq_rem
081740b8 00000010 t drives
08156694 00000020 T drv_led_start
20028094 00000014 b dshot_burst_buffer
200280c0 000005a0 b dshot_burst_buffer_array
0810b500 00000050 T dshot_dmar_data_prepare
20028660 0000003c b dshot_handler
080352f0 00000008 T dshot_main

After

80140f8 0000001c T dq_rem
081740c0 00000010 t drives
0815669c 00000020 T drv_led_start
20028094 00000014 b dshot_burst_buffer
200280c0 000005a0 b dshot_burst_buffer_array
0810b508 00000050 T dshot_dmar_data_prepare
20028660 0000003c b dshot_handler
080352f0 00000008 T dshot_main

```
 @Igor-Misic Would you please test this on the F4 and (it had [this hack](https://github.com/PX4/PX4-Autopilot/compare/pr-align-buffers?expand=1#diff-2154e4c275fb40cf926306138c70e5b614b0e093d0272e752f65dd34fd857460L49) and I want to insure it did not hide a need for word alignment.  

The second part adds an abstraction to get aligned allocated buffers on HW that it matters on.
I have added it to the logger and sd_bench (you can force un alignment with -u)

N.B.  The memory on the heap is is from SRAM123 and the NuttX SDMMC driver only supports IDMA* therefor H7 boards Using SDMMC1 and Not SDMMC2 will not benefit from the alignment.

*For SDMMC1, IDMA cannot access SRAM123 or SRAM4. Refer to ST AN5200 for
details. 

For FMU V6x (uses SDMMC2) the results are significant
```
nsh> sd_bench (aligned)
INFO  [sd_bench] Using block size = 4096 bytes, sync=0
INFO  [sd_bench]
INFO  [sd_bench] Testing Sequential Write Speed...
INFO  [sd_bench]   Run  0:  3384.12 KB/s, max write time: 10 ms (= 400.00 KB/s), fsync: 4 ms
INFO  [sd_bench]   Run  1:  3341.56 KB/s, max write time: 10 ms (= 400.00 KB/s), fsync: 3 ms
INFO  [sd_bench]   Run  2:  3359.11 KB/s, max write time: 9 ms (= 444.44 KB/s), fsync: 3 ms
INFO  [sd_bench]   Run  3:  3367.90 KB/s, max write time: 9 ms (= 444.44 KB/s), fsync: 3 ms
INFO  [sd_bench]   Run  4:  3360.94 KB/s, max write time: 9 ms (= 444.44 KB/s), fsync: 3 ms
INFO  [sd_bench]   Avg   :  3362.73 KB/s

nsh> sd_bench -u (unaligned)
INFO  [sd_bench] Using block size = 4096 bytes, sync=0
INFO  [sd_bench]
INFO  [sd_bench] Testing Sequential Write Speed...
INFO  [sd_bench]   Run  0:   646.92 KB/s, max write time: 15 ms (= 266.67 KB/s), fsync: 4 ms
INFO  [sd_bench]   Run  1:   649.44 KB/s, max write time: 14 ms (= 285.71 KB/s), fsync: 3 ms
INFO  [sd_bench]   Run  2:   648.18 KB/s, max write time: 12 ms (= 333.33 KB/s), fsync: 5 ms
INFO  [sd_bench]   Run  3:   635.08 KB/s, max write time: 42 ms (=  95.24 KB/s), fsync: 5 ms
INFO  [sd_bench]   Run  4:   649.23 KB/s, max write time: 13 ms (= 307.69 KB/s), fsync: 3 ms
INFO  [sd_bench]   Avg   :   645.77 KB/s
```

### CODE REVIEW

**Comment by davids5** [comment]
This had been rebased on todays master  and today's master appears to have killed the console input on V6X. 28681405ae works 

 Drafting this until master is is updated. FYI @Igor-Misic , @dagar

**Comment by dagar** [comment]
> This had been rebased on todays master and today's master appears to have killed the console input on V6X. [2868140](https://github.com/PX4/PX4-Autopilot/commit/28681405aef2023972a633beb00205f618d1a5ae) works

Try again?

**Comment by dagar** [comment]
Build failing for Kinetis.

Screen Shot 2021-03-16 at 1 04 38 AM

**Comment by davids5** [comment]
> > This had been rebased on todays master and today's master appears to have killed the console input on V6X. [2868140](https://github.com/PX4/PX4-Autopilot/commit/28681405aef2023972a633beb00205f618d1a5ae) works
> 
> Try again?

I rebased and refactored the inclusion, it is cleaner now.

**Comment by Igor-Misic** [comment]
The motor is spinning and beeping over DShot. 
```
nsh> dshot beep4
nsh> dshot beep5
nsh> dshot beep1
nsh> ver all
HW arch: PX4_FMU_V4
FW git-hash: 269139289839be9d6d0976b0201a537e06a63990
FW version: 1.11.0 c0 (17498304)
FW git-branch: pr-align-buffers
OS: NuttX
OS version: Release 10.0.0 (167772415)
OS git-hash: 9e077c2f806acd5bda5550bd3231bfc7773e170f
Build datetime: Mar 16 2021 23:41:19
Build uri: localhost
Toolchain: GNU GCC, 7.2.1 20170904 (release) [ARM/embedded-7-branch revision 255204]
PX4GUID: 000100000000313236343435511700340045
MCU: STM32F42x, rev. 3
```

**Review by LorenzMeier — APPROVED** [review]

**Pull request merged**
