### PR TITLE
NuttX build in place

### PR DESCRIPTION
**Pull request by dagar**
~~@davids5 opening this so we don't lose track of the branch.~~

 - cmake NuttX build wrapper compile in place
    - slightly faster skipping necessary copying (depending on system)
    - allows debugging in place
    - easier to work directly in NuttX following official documentation
    - simplifies overall build which should make it easier to resolve any remaining NuttX dependency issues in the build system
 - the downside is switching back and forth between different builds always require rebuilding NuttX, but I think this is worth the improved developer experience
 - also no longer builds px4io and bootloader in every single build
     - for most users these rarely change and we're wasting a lot of build time

### CODE REVIEW

**Comment by davids5** [comment]
@dagar 16:32 Second `make check_nuttx` I think that is about 4 min savings. 

But it is not ready for real use.

build this branch then change the nuttx submodule

```
 *******************************************************************************
 *   [31mIF YOU DID NOT CHANGE THIS FILE (OR YOU DON'T KNOW WHAT A SUBMODULE IS):[0m  *
 *   [31mHit 'u' and <ENTER> to update ALL submodules and resolve this.[0m            *
 *   (performs [94mgit submodule sync --recursive[0m                                  *
 *    and [94mgit submodule update --init --recursive[0m )                            *
 *******************************************************************************


   Only for EXPERTS:
   platforms/nuttx/NuttX/nuttx submodule is not in the recommended version.
   Hit 'y' and <ENTER> to continue the build with this version. Hit <ENTER> to resolve manually.
   Use [94mgit add platforms/nuttx/NuttX/nuttx && git commit -m 'Updated platforms/nuttx/NuttX/nuttx'[0m to choose this version (careful!)

Build aborted.
FAILED: git_init__home_david_s5_src_PX4_repos_mainline_Firmware_platforms_nuttx_NuttX_nuttx.stamp 
cd /home/david_s5/src/PX4/repos/mainline/Firmware && /home/david_s5/src/PX4/repos/mainline/Firmware/Tools/check_submodules.sh platforms/nuttx/NuttX/nuttx && /usr/bin/cmake -E touch /home/david_s5/src/PX4/repos/mainline/Firmware/build/px4_fmu-v5_debug/git_init__home_david_s5_src_PX4_repos_mainline_Firmware_platforms_nuttx_NuttX_nuttx.stamp
ninja: build stopped: subcommand failed.
make: *** [Makefile:225: px4_fmu-v5_debug] Error 1
"make px4_fmu-v5_debug" terminated with exit code 2. Build might be incomplete.
```

Then rerun on command line and it builds but it does not rebuild Nuttx so I get the wrong code

then make clean
 and 
 
 ```
10:01:52 {pr-nuttx_in_place_build *$=} ~/src/PX4/repos/mainline/Firmware$ make px4_fmu-v5_debug 
ninja: error: '../../platforms/nuttx/NuttX/nuttx/defconfig', needed by '../../platforms/nuttx/NuttX/nuttx/.config', missing and no known rule to make it
make: *** [Makefile:225: px4_fmu-v5_debug] Error 1
```

**Review by davids5 — CHANGES_REQUESTED** [review]
See comments needs some work

**Comment by davids5** [comment]
I will say this: It is super nice to hit a breakpoint set in the file you expect it to be it!!

**Comment by dagar** [comment]
I believe this now has all functionality present in master. Let's continue testing.

**Comment by dagar** [comment]
Rebased on master.

**Comment by davids5** [comment]
@dagar - I had some time to test this again

It did not work. 

```
rm -rf build/
$ make px4_fmu-v5_default px4io_firmware_update
-- PX4 version: v1.13.0-alpha1-2998-g4c007cc3d2
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- PX4 config file: /home/david_s5/src/PX4/repos/mainline/Firmware/boards/px4/fmu-v5/default.px4board
-- PLATFORM nuttx
-- TOOLCHAIN arm-none-eabi
-- ARCHITECTURE cortex-m7
-- ROMFSROOT px4fmu_common
-- IO px4_io-v2_default
-- SERIAL_GPS1 /dev/ttyS0
-- SERIAL_TEL1 /dev/ttyS1
-- SERIAL_TEL2 /dev/ttyS2
-- SERIAL_TEL4 /dev/ttyS3
-- UAVCAN_INTERFACES 2
-- UAVCAN_TIMER_OVERRIDE 6
-- PX4 config: px4_fmu-v5_default
-- PX4 platform: nuttx
-- cmake build type: MinSizeRel
-- The CXX compiler identification is GNU 9.3.1
-- The C compiler identification is GNU 9.3.1
-- The ASM compiler identification is GNU
-- Found assembler: /usr/lib/ccache/arm-none-eabi-gcc
-- Check for working CXX compiler: /usr/lib/ccache/arm-none-eabi-g++
-- Check for working CXX compiler: /usr/lib/ccache/arm-none-eabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/lib/ccache/arm-none-eabi-gcc
-- Check for working C compiler: /usr/lib/ccache/arm-none-eabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Enabling double FP precision hardware instructions
-- ccache enabled via symlink (/usr/lib/ccache/arm-none-eabi-g++ -> /usr/bin/ccache)
-- drivers/px4io: ROMFS including px4_io-v2_default
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
-- Using C++11
-- Release build type: MinSizeRel
-- ROMFS: ROMFS/px4fmu_common
-- ROMFS:  Adding platforms/nuttx/init/stm32f7/rc.board_arch_defaults -> /etc/init.d/rc.board_arch_defaults
-- ROMFS:  Adding boards/px4/fmu-v5/init/rc.board_defaults -> /etc/init.d/rc.board_defaults
-- ROMFS:  Adding boards/px4/fmu-v5/init/rc.board_sensors -> /etc/init.d/rc.board_sensors
-- ROMFS:  Adding boards/px4/fmu-v5/extras/px4_fmu-v5_bootloader.bin -> /etc/extras/px4_fmu-v5_bootloader.bin
-- ROMFS:  Adding boards/px4/fmu-v5/extras/px4_io-v2_default.bin -> /etc/extras/px4_io-v2_default.bin
-- Found SVD: /home/david_s5/src/PX4/repos/mainline/Firmware/../cmsis-svd/data/STMicro/STM32F7x5.svd
-- Configuring done
-- Generating done
-- Build files have been written to: /home/david_s5/src/PX4/repos/mainline/Firmware/build/px4_fmu-v5_default
[2/9] Performing download step (git clone) for 'px4io_firmware_build'
Cloning into 'px4io_firmware_build'...
done.
Note: switching to 'v1.13.0-alpha1-2998-g4c007cc3d2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 4c007cc3d2 NuttX build in place
[5/9] Performing configure step for 'px4io_firmware_build'
FAILED: external/Stamp/px4io_firmware_build/px4io_firmware_build-configure 
cd /home/david_s5/src/PX4/repos/mainline/Firmware/build/px4_fmu-v5_default/external/Build/px4io_firmware_build && /usr/bin/cmake -DCONFIG=px4_io-v2_default -GNinja /home/david_s5/src/PX4/repos/mainline/Firmware/build/px4_fmu-v5_default/external/Source/px4io_firmware_build && /usr/bin/cmake -E touch /home/david_s5/src/PX4/repos/mainline/Firmware/build/px4_fmu-v5_default/external/Stamp/px4io_firmware_build/px4io_firmware_build-configure
-- PX4 version: v1.13.0-alpha1-2998-g4c007cc3d2
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- PX4 config file: /home/david_s5/src/PX4/repos/mainline/Firmware/build/px4_fmu-v5_default/external/Source/px4io_firmware_build/boards/px4/io-v2/default.px4board
-- PLATFORM nuttx
-- TOOLCHAIN arm-none-eabi
-- ARCHITECTURE cortex-m3
-- CONSTRAINED_FLASH y
-- PX4 config: px4_io-v2_default
-- PX4 platform: nuttx
make[1]: *** No rule to make target 'olddefconfig'.  Stop.
-- cmake build type: MinSizeRel
-- The CXX compiler identification is GNU 9.3.1
-- The C compiler identification is GNU 9.3.1
-- The ASM compiler identification is GNU
-- Found assembler: /usr/lib/ccache/arm-none-eabi-gcc
-- Check for working CXX compiler: /usr/lib/ccache/arm-none-eabi-g++
-- Check for working CXX compiler: /usr/lib/ccache/arm-none-eabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/lib/ccache/arm-none-eabi-gcc
-- Check for working C compiler: /usr/lib/ccache/arm-none-eabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- ccache enabled via symlink (/usr/lib/ccache/arm-none-eabi-g++ -> /usr/bin/ccache)
CMake Error at platforms/nuttx/cmake/px4_impl_os.cmake:138 (message):
  Could not determine chip architecture from NuttX config.  You may have to
  add it.
Call Stack (most recent call first):
  CMakeLists.txt:310 (px4_os_determine_build_chip)


-- Configuring incomplete, errors occurred!
See also "/home/david_s5/src/PX4/repos/mainline/Firmware/build/px4_fmu-v5_default/external/Build/px4io_firmware_build/CMakeFiles/CMakeOutput.log".
See also "/home/david_s5/src/PX4/repos/mainline/Firmware/build/px4_fmu-v5_default/external/Build/px4io_firmware_build/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.
make: *** [Makefile:225: px4_fmu-v5_default] Error 1
```

**Review by davids5 — DISMISSED** [review]
@dagar Still no joy

**Comment by dagar** [comment]
@davids5 the issue is your usage of GIT_SUBMODULES_ARE_EVIL preventing the submodules from being initialized in the encapsulated px4io build, which is why this wasn't reproducible locally or on any CI.

I'll figure out something.

**Comment by dagar** [comment]
Updated the px4io update to use rsync.

**Comment by dagar** [comment]
The problem was the copied px4io build had symlink still porting to the source directory. The nuttx clean was overreaching.

**Review by davids5 — APPROVED** [review]
@dagar - I have tested this and it is working with dual debug. So I would say it is good to go.

**Pull request merged**
