### PR TITLE
Pr 16292 Rebased

### PR DESCRIPTION
**Pull request by LorenzMeier**
This is a continuation of #16292 rebased.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@dagar The pending question was:

Does this mean that I need to subscribe to three safety instances in Commander.cpp, and modify the switch ((PrearmedMode)_param_com_prearm_mode.get()) { ----->src/modules/commander/Commander.cpp to support the setting of armed. prearmed according to different safety instances? If so ,how to obtain the UAVCAN GPS's safety button state in commander.cpp?

Using fmu-v5 board with IO and FMU : As I understand it, If I don't implement multiple instances, I can't change legacy GPS 's safety_off by using the uavcan GPS safety button. Am i right ?

And, if i add mutil instances, how to handle the "_safety" parameter of return TRANSITION_DENIED != arming_state_transition(&status, _safety, vehicle_status_s::ARMING_STATE_SHUTDOWN,,
if i pass through safeties[num_of_safeties],shoule I modify arming_state_transition function?
@dagar

**Comment by LorenzMeier** [comment]
@gitfishup Working hard on this now!

**Comment by gitfishup** [comment]
@LorenzMeier  OK，thanks

**Comment by LorenzMeier** [comment]
This functionality has been merged in parallel.

**Pull request closed without merging**
