### PR TITLE
nxp_fmuk66-x:Disable CONFIG_MMCSD_MULTIBLOCK (_DISABLE=y)

### PR DESCRIPTION
**Pull request by davids5**
The Write  operation on e HW fail without CONFIG_MMCSD_MULTIBLOCK_DISABLE=y.

Should resolve https://github.com/PX4/PX4-Autopilot/issues/17087

I am assuming this is true with some V3 HW as well. 

@mrpollo - Please test on your borked V3,

@dk7xe - Please test on your rev E

### CODE REVIEW

**Comment by landonh12** [comment]
Log pulled and uploaded to PX4 flight review successfully with this patch. https://review.px4.io/plot_app?log=1c03030b-a0b1-4326-ad0d-17f7d0386264

**Comment by mrpollo** [comment]
I had no GPS connected, but I was able to generate an ulog file, whereas before I couldn't access the SD card at all

https://logs.px4.io/plot_app?log=a363809d-8e4e-4ad3-9802-db64a051be82

**Comment by dk7xe** [comment]
Well done @davids5 
Works for me as well https://logs.px4.io/plot_app?log=196b9191-f025-4d95-838b-7292b2801d61

**Review by LorenzMeier — APPROVED** [review]

**Comment by dk7xe** [comment]
uhh.. that was fast ;)

**Comment by LorenzMeier** [comment]
Testing is everything! You made it possible!

**Pull request merged**
