### PR TITLE
fmu-v3: make optional sensor startup quiet

### PR DESCRIPTION
**Pull request by julianoes**
This fixes the errors showing up at startup for me with a Black Cube.

Should fix http://px4-jenkins.dagar.ca:8080/blue/organizations/jenkins/PX4-Autopilot/detail/pr-backport-20086/4/pipeline/

Backport of #20281

### CODE REVIEW

**Comment by dagar** [comment]
Waiting until we understand the root cause of the difference.

**Comment by julianoes** [comment]
Closing in favor of https://github.com/PX4/PX4-Autopilot/pull/20281

**Comment by julianoes** [comment]
I'll rebase this on `release/v1.13` now that #20281 is in.

**Comment by julianoes** [comment]
Doesn't need forwardporting as it's already in https://github.com/PX4/PX4-Autopilot/commit/355f184f066.

**Comment by dagar** [comment]
Can you keep fmu-v2 and fmu-v3 in sync?

**Pull request closed without merging**
