### PR TITLE
[WIP]: introduce PX4DifferentialPressure class and cleanup all drivers

### PR DESCRIPTION
**Pull request by dagar**
This is an old PR I never finished. Resurrecting it here to work through the few remaining issues and testing.

Review and test
 - [ ] analog differential pressure sensor (which boards?)
 - [ ] ms4515
 - [ ] ms4525
 - [ ] ms5525
 - [ ] sdp3x
 - [ ] ets

### CODE REVIEW

**Comment by dagar** [comment]
This looks like a lot of code churn, but it's actually not that scary. The structure of each driver is nearly identical.

**Comment by SalimTerryLi** [comment]
Hmm... Any follow up?

**Comment by SalimTerryLi** [comment]
May I ask why MS45x5 series were implemented as IIC device? They should be analog sensors typically. I also found PX4AIRSPEED design, but not much document can be found. I strongly suggest rename them as px4airspeed instead of ms45x5 to avoid ambiguity.

I suggest that we SHOULD NOT mess up these two different implements of dp sensor.

In this way, we should make a decision about whether we should keep the analog_diffpres or remove it and use the true name such as MS4515, MS4525 and MPXV7002 instead. This should be discussed when we are more familiar to the differences between those sensors. (TODO)

And, if possible, I want to gather more docs about PX4AIRSPEED design. Schematic seems helpless.

I'm willing and able to make some improvements about this part.

**Comment by LorenzMeier** [comment]
Without going further into detail, I think you're confusing different sensor types here. The fact that there are working I2C drivers here prove that these sensors are indeed I2C devices, so I'm not sure why you're questioning that.

What might confuse you is that the MS4525 is ratiometric in offset to its supply voltage, so the 5V rail is being measured to compensate for that change in offset. That doesn't mean that the sensor itself is analog.

I'm also not sure why couldn't find or read the schematics for the airspeed module. You can find it here and open the file with Eagle CAD: https://github.com/pixhawk/Hardware/tree/master/AIRSPEEDv1

That should very clearly show the part number and how it is wired up.

**Comment by SalimTerryLi** [comment]
> Without going further into detail, I think you're confusing different sensor types here. The fact that there are working I2C drivers here prove that these sensors are indeed I2C devices, so I'm not sure why you're questioning that.
> 
> What might confuse you is that the MS4525 is ratiometric in offset to its supply voltage, so the 5V rail is being measured to compensate for that change in offset. That doesn't mean that the sensor itself is analog.
> 
> I'm also not sure why couldn't find or read the schematics for the airspeed module. You can find it here and open the file with Eagle CAD: https://github.com/pixhawk/Hardware/tree/master/AIRSPEEDv1
> 
> That should very clearly show the part number and how it is wired up.

These are the documents that I found which describes those sensors.
https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Data+Sheet%7FMS4515%7FB2%7Fpdf%7FEnglish%7FENG_DS_MS4515_B2.pdf%7FCAT-BLPS0040
https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=MS4525&DocType=Data+Sheet&DocLang=English
https://www.nxp.com/docs/en/data-sheet/MPXV7002.pdf

Above is my discovery before your reply.
After I installed Eagle on my Ubuntu and opened that sch then I got the correct product ID. It is very annoying for that they both called ms45x5 but the one used in PX4AIRSPEED can be searched with "4525DO", not "MS4525". Sorry for my negligence.
Here is the corresponding docs:
https://www.te.com/usa-en/product-4525DO-DS5AI001DP.datasheet.pdf

Then the question should be:
1. find a correct name for existing dp sensors
2. discuss how to implement analog dp sensors
Right?

**Comment by dagar** [comment]
I'll be back...

**Pull request closed without merging**
