### PR TITLE
Update fmu-v6c rc.board_sensors

### PR DESCRIPTION
**Pull request by vincentpoont2**
Change so it will start MS5611 &  IST8310 properly.
fmuv6c I2C4 was changed to external here https://github.com/PX4/PX4-Autopilot/pull/19949

### CODE REVIEW

**Review by davids5 — DISMISSED** [review]

**Comment by vincentpoont2** [comment]
Tested, Please merge @davids5 @dagar.

**Comment by dagar** [comment]
So there are no fully internal I2C buses on this board? That's going to have minor repercussions like breaking mag cal auto rotation (for external mags).

**Comment by vincentpoont2** [comment]
> So there are no fully internal I2C buses on this board? That's going to have minor repercussions like breaking mag cal auto rotation (for external mags).

Mind explaining this "breaking mag Cal auto rotation for external mag"?

**Comment by ryanjAA** [comment]
If this does change on the hardware side there are still people in the wild with v1 hardware so it still needs to be supported somehow or hardware callback for them (or some way to differentiate - but it would still need to be supported).

**Comment by AlexKlimaj** [comment]
Is there a hw ver rev circuit on the 6c? That would be the only way.

**Comment by ryanjAA** [comment]
ADC 3 shows HW Rev and Ver so maybe it has it. Someone else will need to confirm.

**Comment by julianoes** [comment]
Replaced by #20200, closing.

**Pull request closed without merging**
