### PR TITLE
EKF2: avoid faulty reset by optical flow

### PR DESCRIPTION
**Pull request by haumarco**
### Solved Problem
Situation: Optical flow only external sensor, vehicle above MAXHGT (inertial dead reckoning)
It descends to z < MAXHGT and receives a faulty optical flow measurement, which is followed by hagl measurements > MAXHGT.

Now the velocity reset could be set to 40m/s (1.3 rad/s at 30m hagl) and the covariance of the velocity gets increased, but since the following OF measurements are rejected (hagl> MAXHGT again) the system continues flying in inertial dead reckoning but estimates a massive velocity.

I added a 95% threshold to the allowed range to trigger a reset, this increases the chance massively that following measurements are also within that range.

Flight where we I had this issue:
[log_105_2024-8-22-17-09-14.zip](https://github.com/user-attachments/files/16730755/log_105_2024-8-22-17-09-14.zip)
Screenshot from 2024-08-22 18-56-29

### CODE REVIEW

**Comment by dagar** [comment]
Somewhat related I was thinking it would be slightly safer to reset to a filtered value. https://github.com/PX4/PX4-Autopilot/pull/23399

**Comment by dagar** [comment]
Idea seems fine, but should we have a more unified approach for this magic limits? 

For example when relying on a range finder we limit the max height above ground (sent to the controllers) to 90% of the max. https://github.com/PX4/PX4-Autopilot/blob/17cc46cd54223a64f0c7ca17ee613ecd73c992ad/src/modules/ekf2/EKF/ekf_helper.cpp#L279-L280

When relying on optical flow we limit the max height above ground to 100% of the max. https://github.com/PX4/PX4-Autopilot/blob/17cc46cd54223a64f0c7ca17ee613ecd73c992ad/src/modules/ekf2/EKF/ekf_helper.cpp#L298

Perhaps all of these should be the same constant (90 or 95%)?

**Comment by dagar** [comment]
I've merged the minimal fix in https://github.com/PX4/PX4-Autopilot/pull/23618. Let me know if we still want to do anything with the sensor limits.

**Comment by bresch** [comment]
replaced by 
https://github.com/PX4/PX4-Autopilot/pull/23399
and
https://github.com/PX4/PX4-Autopilot/pull/23618

**Pull request closed without merging**
