### PR TITLE
sensors/vehicle_imu: use WelfordMean library to determine sensor sample rate average

### PR DESCRIPTION
**Pull request by dagar**
Determining the actual IMU (accel + gyro) sample rate is quite important for configuring integration and filtering throughout the system. This PR updates that measurement to use the relatively new WelfordMean class in mathlib, and updates the logic to continuously monitor the sample rate rather than stop after its first determined (or errors occur).

In general you'd expect the sensor sample rate to be a known statically based on configuration, but there are cases where we don't actually know (data coming in from Mavlink, UAVCAN, etc) or some sensors that can change at runtime based on actual usage (eg mpu9250 with or without mag).

With this update we now determine the sample rate initially much faster, but will continue to update it if things settle later.

### CODE REVIEW

**Comment by dagar** [comment]
Tested in SITL. Next I'll verify across the test rack.

**Comment by dagar** [comment]
Confirmed this fixes issues with SITL, SIH and extreme jitter (no lockstep or real time threads). 

@romain-chiap can you give this a try?

**Comment by romain-chiap** [comment]
I tried in SIH-SITL, it fixed the imu gaps (missed data) but it didn't solve the problem.

**Review by bresch — APPROVED** [review]

**Comment by dagar** [comment]
Verified across the test rack that the expected rates were determined and no change in cpu load.

**Pull request merged**
