### PR TITLE
Fixed px4vision model

### PR DESCRIPTION
**Pull request by frede791**
Copied over the model over from Gazebo fuel and fixed it up. Flies fine now. 
Fixes issue #22219 .

### CODE REVIEW

**Comment by frede791** [comment]
@Jaeyoung-Lim There were a bunch of wrong or deprecated parameters present in the model on gazebo fuel.

**Review by Jaeyoung-Lim — CHANGES_REQUESTED** [review]
Could we upload the model to fuel and link it here?

**Comment by frede791** [comment]
@Jaeyoung-Lim Sure we could do that. It's just the source file and the mesh files.

**Comment by Jaeyoung-Lim** [comment]
@frede791 Exactly, we want to minimize the number of meshes in the git tree. The px4vision model is also not run through the CI, so I would propose putting it up on fuel as it was before

**Comment by frede791** [comment]
@Jaeyoung-Lim I've uploaded the model to fuel, but I cannot seem to get it to work in the sdf file. https://app.gazebosim.org/frede791/fuel/models/px4_vision_fixed

**Pull request closed without merging**
