### PR TITLE
Update mavlink & adapt to pymavlink generator reporting failures by default

### PR DESCRIPTION
**Pull request by MaEtUgR**
### Solved Problem
As follow up to https://github.com/PX4/PX4-Autopilot/pull/23313 I went upstream and suggested https://github.com/ArduPilot/pymavlink/pull/952

### Solution
In review it turned out that everyone agrees that errors should always be reported and that's now the default. So I update MAVLink to the version containing the fix and remove the explicit `--exit-code` error flag again, it doesn't exist anymore.

### Changelog Entry
```
Improvement: Use new MAVLink version that reports errors by default without the build flag
```

### Test coverage
I tested a bunch of failure cases with PX4 for the pymavlink pr https://github.com/ArduPilot/pymavlink/pull/952

### CODE REVIEW

**Comment by MaEtUgR** [comment]
Something seems not good with the MAVLink update 😬
image

**Review by dagar — DISMISSED** [review]

**Comment by dagar** [comment]
A bit awkward, we have mavlink build failures happening within PX4-SITL_gazebo-classic. https://github.com/PX4/PX4-Autopilot/actions/runs/10245749629/job/28341436408?pr=23490

image

**Comment by MaEtUgR** [comment]
I tried to reproduce locally but first rebased on main and `make px4_sitl_default sitl_gazebo-classic` succeeds with all submodules checked out. Either it was already fixed or I did something wrong 👀

**Comment by MaEtUgR** [comment]
I did something wrong, now I get 
image
🤯

**Review by dagar — APPROVED** [review]

**Pull request merged**
