### PR TITLE
platforms/nuttx: cmake debug pass GDB path and set RTOS plugin file extension

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by AlexKlimaj** [comment]
It seems to be working. Although during testing my jlink-nuttx.so file somehow got renamed jlink-nuttx without the extension and cortex-debug couldn't find it again.

**Comment by AlexKlimaj** [comment]
Tested again. With a make distclean, make clean, then building again, I end up with a jlink-nuttx that does not have the file extension.

**Comment by AlexKlimaj** [comment]
The first build after a make distclean and git submodule update --init --recursive, it builds a jlink-nuttx without an extension. Then hitting build again, the only thing it builds is jlink-nuttx.so.

```
[main] Building folder: PX4-Autopilot 
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /home/alex/PX4-Autopilot/build/ark_fmu-v6x_default --config MinSizeRel --target all --
[build] [1/1 100% :: 0.111] Generating ../../../../platforms/nuttx/NuttX/nuttx/tools/jlink-nuttx.so
[build] Build finished with exit code 0
```

**Comment by dagar** [comment]
Still need to figure out if there's something odd with the NuttX host build, but from the PX4 cmake side I think this is fine.

**Pull request merged**
