### PR TITLE
Initial support for IMXRT FMUM

### PR DESCRIPTION
**Pull request by davids5**
This is not complete - but it builds :)

Todo:

- [ ] test on real HW
- [ ] add uavcan
- [ ] test PX4IO
- [ ] test Ethernet
- [ ] Power sequencing, check backfeeding

### CODE REVIEW

**Comment by davids5** [comment]
Rebased on master and px4io FW installed to extras with px4io_update.

**Comment by davids5** [comment]
> Log from real HW - https://logs.px4.io/plot_app?log=6b1553f3-734b-4800-a286-7f11eed45373
> 
> * All 4 motors are spinning.
> * RC input can not be detected from FrSky R-XSR receiver connected to RC IN.

@dk7xe Please retest the PR. RC is fixed  and I freed up memory (had to removed  gyro_fft ans esc_batt)
 
PX4 is growing faster the we can. We are going to have to have multiple configs  at some point one for MC, FW, ROVER

@dagar the px4io_update is a landmine! Please fix it to build as needed.

**Comment by dk7xe** [comment]
@davids5 i faced a hardfault after updating the FW.
[20221024_RT10602-v2_hardfault.txt](https://github.com/PX4/PX4-Autopilot/files/9849860/20221024_RT10602-v2_hardfault.txt)

**Comment by davids5** [comment]
> @davids5 i faced a hardfault after updating the FW. [20221024_RT10602-v2_hardfault.txt](https://github.com/PX4/PX4-Autopilot/files/9849860/20221024_RT10602-v2_hardfault.txt)

Did you power off and on again?
Did you use the reset button after programing?

**Comment by dk7xe** [comment]
Hmm, can't recall

**Comment by dk7xe** [comment]
> Hmm, can't recall But the FMU is rebooting now several times while connected via USB. Unfortunately my debug cable is already in one of the cases for traveling. Therefore i can only guess that it is a continuous hardfault.

Hi @davids5, i just checked again. there is no hardfault happening during this reboots. It occures only if the FMU is just powered from USB. Then i'm getting random reboots.
If the RT1062 FMU is powered from Power input i don't have seen any random reboot yet.

**Comment by dk7xe** [comment]
i did a clean build again resulting in crash when initializing GPS
[fmurt1062-v2_test_20221026.txt](https://github.com/PX4/PX4-Autopilot/files/9866433/fmurt1062-v2_test_20221026.txt)

**Comment by davids5** [comment]
> i did a clean build again resulting in crash when initializing GPS [fmurt1062-v2_test_20221026.txt](https://github.com/PX4/PX4-Autopilot/files/9866433/fmurt1062-v2_test_20221026.txt) I can not get a console prompt on the debug port. so it seems really stalled.

@dk7xe You will need RC04 HW. Or Drop the last commit to test with RC01 HW

**Comment by dk7xe** [comment]
Hi @davids5 , i had a succesful maiden flight of the fmurt1062 RC03 HW.
No tuning, just functional HW test.
Unfortunately no logs are written. Therefore just the video -> https://youtu.be/0tX7gSzxELQ
May you please look into the logging. i have enabled logging from boot. Files are created but not filled with any content.

**Comment by davids5** [comment]
> Hi @davids5 , i had a succesful maiden flight of the fmurt1062 RC03 HW. No tuning, just functional HW test. Unfortunately no logs are written. Therefore just the video -> https://youtu.be/0tX7gSzxELQ May you please look into the logging. i have enabled logging from boot. Files are created but not filled with any content.

I think you are going to have to wait to get working HW RC04.

**Comment by dk7xe** [comment]
Btw, Ethernet is working. I'm connecting my QGC Laptop via Ethernet at the moment.

**Comment by dk7xe** [comment]
First test with RC04 HW and baseboard with T1 ethernet done.
Flashing - OK
GPS port - OK
T1 ethernet port - OK
USB port - FAILED, not recogniced as device on windows and linux machine. 

[boot] Rev 0x0 : Ver 0x0 V5X000000
WARN  [drivers_board] reset done, 10 ms
Successfully bound SDHC to the MMC/SD driver
nsh: sysinit: fopen failed: No such file or directory
HW arch: NXP_FMURT1062_V2
HW type: V5X000000
HW version: 0x000
HW revision: 0x000
PX4 git-hash: 3cf731faa8404e7db0af7bf23cd50d6c6974c3c1
PX4 version: 1.14.0 0 (17694720)
PX4 git-branch: pr-fmu1062
OS: NuttX
OS version: Release 11.0.0 (184549631)
OS git-hash: fba2a48a7f745366cb16631fef843d38f2890f13
Build datetime: Dec 22 2022 07:51:44
Build uri: localhost
Build variant: default
Toolchain: GNU GCC, 9.3.1 20200408 (release)
PX4GUID: 00050000000000000000082e99d75d7586ec
MCU: i.MX RT1062 r1.1, rev. 1
nsh: hardfault_log: command not found
INFO  [param] selected parameter default file /fs/mtd_params
INFO  [param] importing from '/fs/mtd_params'
ERROR [tinybson] killed: unsupported node type
ERROR [parameters] param import failed (-1) attempt 1
ERROR [tinybson] killed: unsupported node type
ERROR [parameters] param import failed (-1) attempt 2
ERROR [tinybson] killed: unsupported node type
ERROR [parameters] param import failed (-1) attempt 3
ERROR [param] importing from '/fs/mtd_params' failed (-1)
ERROR [init] param import failed
[param] reading from /fs/mtd_params

BSON document size 539814648
ERROR [tinybson] killed: unsupported node type
ERROR [parameters] param dump failed (-1)
ERROR [param] reading from '/fs/mtd_params' failed (-1)
[init] importing from parameter backup
[param] reading from /fs/microsd/parameters_backup.bson

BSON document size 687
BSON_INT32:  CAL_ACC2_ID = 3670026
BSON_INT32:  CAL_ACC2_PRIO = 50
BSON_DOUBLE: CAL_ACC2_XOFF = 0.006501
BSON_DOUBLE: CAL_ACC2_YOFF = -0.002560
BSON_DOUBLE: CAL_ACC2_ZOFF = -0.077060
BSON_INT32:  CAL_GYRO0_ID = 6684698
BSON_INT32:  CAL_GYRO0_PRIO = 50
BSON_DOUBLE: CAL_GYRO0_XOFF = 0.002922
BSON_DOUBLE: CAL_GYRO0_YOFF = 0.000177
BSON_DOUBLE: CAL_GYRO0_ZOFF = 0.000035
BSON_INT32:  CAL_GYRO1_ID = 2490386
BSON_INT32:  CAL_GYRO1_PRIO = 50
BSON_DOUBLE: CAL_GYRO1_XOFF = -0.017792
BSON_DOUBLE: CAL_GYRO1_YOFF = -0.021495
BSON_DOUBLE: CAL_GYRO1_ZOFF = -0.006250
BSON_INT32:  CAL_GYRO2_ID = 3670026
BSON_INT32:  CAL_GYRO2_PRIO = 50
BSON_DOUBLE: CAL_GYRO2_XOFF = -0.010826
BSON_DOUBLE: CAL_GYRO2_YOFF = -0.002685
BSON_DOUBLE: CAL_GYRO2_ZOFF = -0.003396
BSON_INT32:  CAL_MAG0_ID = 4395041
BSON_INT32:  CAL_MAG0_PRIO = 50
BSON_DOUBLE: CAL_MAG0_XOFF = -0.011309
BSON_DOUBLE: CAL_MAG0_YOFF = 0.254842
BSON_DOUBLE: CAL_MAG0_ZOFF = -0.130266
BSON_INT32:  CAL_MAG1_ID = 396809
BSON_INT32:  CAL_MAG1_PRIO = 75
BSON_INT32:  CAL_MAG1_ROT = 0
BSON_DOUBLE: CAL_MAG1_XOFF = -0.028799
BSON_DOUBLE: CAL_MAG1_YOFF = -0.151358
BSON_DOUBLE: CAL_MAG1_ZOFF = -0.183945
BSON_INT32:  SYS_AUTOSTART = 50000
BSON_EOO
BSON decoded 687 bytes (double:18, string:0, bin:0, bool:0, int32:14, int64:0)
INFO  [param] importing from '/fs/microsd/parameters_backup.bson'
INFO  [parameters] BSON document size 687 bytes, decoded 687 bytes (INT32:14, FLOAT:18)
INFO  [parameters] summary: 0/1582 (used/total)
INFO  [parameters] file: /fs/mtd_params
INFO  [parameters] storage array: 32/32 elements (512 bytes total)
INFO  [parameters] auto save: on
param: export: 0 events, 0us elapsed, 0.00us avg, min 0us max 0us 0.000us rms
param: find: 32 events
param: get: 0 events
param: set: 32 events, 139us elapsed, 4.34us avg, min 1us max 9us 1.877us rms
dmesg [88:100]
INFO  [param] selected parameter backup file /fs/microsd/parameters_backup.bson
Board architecture defaults: /etc/init.d/rc.board_arch_defaults
Board defaults: /etc/init.d/rc.board_defaults
Loading airframe: /etc/init.d/airframes/50000_generic_ground_vehicle
INFO  [dataman] data manager file '/fs/microsd/dataman' size is 62560 bytes
rgbled_ncp5623c #0 on I2C bus 1 (external) address 0x39
INFO  [px4io] IO FW CRC match
Board sensors: /etc/init.d/rc.board_sensors
ina226 #0 on I2C bus 1 (external) address 0x41
INFO  [ina226] Failed to init INA226 on bus 2, but will try again periodically.
ina226 #1 on I2C bus 2 (external) address 0x41
bmi088_accel #0 on SPI bus 3 rotation 4
bmi088_gyro #0 on SPI bus 3 rotation 4
icm42688p #0 on SPI bus 2 rotation 6
icm20602 #0 on SPI bus 1 rotation 8
bmm150 #0 on I2C bus 4 (external) address 0x10
ist8310 #0 on I2C bus 1 (external) address 0xE rotation 10
bmp388 #0 on I2C bus 4 (external) address 0x77
bmp388 #1 on I2C bus 2 (external) address 0x76
nsh: icm20948_i2c_passthrough: command not found
nsh: ist8308: command not found
WARN  [SPI_I2C] Already running on bus 1
nsh: lis2mdl: command not found
nsh: lis3mdl: command not found
nsh: lis3mdl: command not found
nsh: qmc5883l: command not found
nsh: rm3100: command not found
nsh: ak09916: command not found
nsh: dshot: command not found
ekf2 [539:237]
Board mavlink: /etc/init.d/rc.board_mavlink
WARN  [mavlink] offboard mission init failed (-1)
INFO  [mavlink] mode: OnboardLowBandwidth, data rate: 290000 B/s on /dev/ttyS3 @ 3000000B
Starting Main GPS on /dev/ttyS1
Starting MAVLink on /dev/ttyS2
INFO  [mavlink] mode: Normal, data rate: 1200 B/s on /dev/ttyS2 @ 57600B
Starting MAVLink on ethernet
INFO  [mavlink] mode: Normal, data rate: 100000 B/s on udp port 14550 remote port 14550
INFO  [rc_input] valid device required
ERROR [rc_input] Task start failed (-1)
INFO  [logger] logger started (mode=all)

NuttShell (NSH) NuttX-11.0.0

**Comment by davids5** [comment]
@dk7xe Do you get the same results on Every boot?

**Comment by dk7xe** [comment]
Yes

**Comment by PetervdPerk-NXP** [comment]
For it's working but it's a bit delayed, it's empty when opening tty and then on debug tty I see the following
```
nsh> /dev/ttyACM0: launching nshterm
```

Furthermore memory is super tight
```
NuttShell (NSH) NuttX-10.4.0
nsh> ver all
nsh: ver: command not found
nsh> eth0: devup=1 PHY address=12 MSR=0082

nsh>
nsh> free
                   total       used       free    largest  nused  nfree
        Umem:     251104     249680       1424        464    990     57
nsh> ver all
HW arch: NXP_FMURT1062_V2
HW type: V5X000000
HW version: 0x000
HW revision: 0x000
PX4 git-hash: 3cf731faa8404e7db0af7bf23cd50d6c6974c3c1
PX4 version: 1.14.0 0 (17694720)
PX4 git-branch: pr-fmu1062
OS: NuttX
OS version: Release 12.0.0 (201326847)
OS git-hash: fba2a48a7f745366cb16631fef843d38f2890f13
Build datetime: Dec 27 2022 10:54:21
Build uri: localhost
Build variant: default
Toolchain: GNU GCC, 9.3.1 20200408 (release)
PX4GUID: 00050000000000000000062d99d75d7586ec
MCU: i.MX RT1062 r1.1, rev. 1
nsh>

```

**Comment by davids5** [comment]
We are out of memory. If the air frame is set and USB is plugged in you will see the out of memory message on the debug console. Time to optimism the config and memory usage....

**Comment by dk7xe** [comment]
Hen setting the Airframe to "NXP HoverGames" i'm getting this hardfault
 
[20230201_rt1060_hardfault.txt](https://github.com/PX4/PX4-Autopilot/files/10332367/20230201_rt1060_hardfault.txt)

**Comment by davids5** [comment]
continued here 
- https://github.com/PX4/PX4-Autopilot/pull/21321

**Comment by dk7xe** [comment]
@davids5 i have switched my build system to this branch now and will test drone and rover in the coming days.

**Pull request closed without merging**
