### PR TITLE
Rename 'control_mode' to 'vehicle_control_mode' in MulticopterPositionControl.cpp/hpp.

### PR DESCRIPTION
**Pull request by mcsauder**
Hello,

This PR renames instances of `control_mode` to `vehicle_control_mode` as they all pertain to the `vehicle_control_mode_s` type and related *.msg file.  This PR introduces no functional changes, just helps connect the dots between the messages and states with how/where they are used.  This PR also does a little bit of whitespace formatting and alphabetization for readability.

**Test data / coverage**
Test flown here, no issues or differences from current master branch: https://review.px4.io/plot_app?log=1e90cf5b-cc99-4d5f-a746-da8655a19a85

Please let me know if you have any questions or comments on this PR.

Thanks!

-Mark

### CODE REVIEW

**Comment by mcsauder** [comment]
No changes, just kicking the CI after rebasing with today's upstream merges

**Review by bkueng — APPROVED** [review]
Thanks @mcsauder. Personally I want to avoid/minimize such whitespace changes, as they lead to unnecessary rebase & merge conflicts (downstream adopters with changes/work in progress in particular).

**Comment by mcsauder** [comment]
> Thanks @mcsauder. Personally I want to avoid/minimize such whitespace changes, as they lead to unnecessary rebase & merge conflicts (downstream adopters with changes/work in progress in particular).

Thanks for your review @bkueng !  I agree with your reasoning, it just seems too easy to let code rot if it isn't cleaned up/formatted from time to time.  I'll keep whitespace changes as minimal as possible in the future.

**Comment by dagar** [comment]
Looks like there's a small conflict now. Rebase and then we'll get it merged immediately?

**Review by dagar — APPROVED** [review]

**Comment by mcsauder** [comment]
Thanks @dagar !

**Pull request merged**
