### PR TITLE
airframes: add standard_vtol_ctrlalloc model

### PR DESCRIPTION
**Pull request by julianoes**
Depends on https://github.com/PX4/PX4-SITL_gazebo/pull/819

### CODE REVIEW

**Comment by JacobCrabill** [comment]
FYI @julianoes / @dagar - This seems like everything is present and should be working, but there's some weirdness in the translation of position setpoints to attitude/velocity setpoints (this applies to the normal `standard_vtol` model as well) - I can't make a VTOL airframe move forward in Position mode.

**Comment by julianoes** [comment]
Do you still need this PR?

**Comment by JacobCrabill** [comment]
> Do you still need this PR?

I don't have the time to manage this; it's fine closing and coming back to some time later.

**Comment by julianoes** [comment]
Me neither. I'm going to close it.

**Comment by Jaeyoung-Lim** [comment]
@julianoes @JacobCrabill This PR https://github.com/PX4/PX4-SITL_gazebo/pull/819 was merged but seems to be stranded since the airframe configs were not merged.

Should I remove the model?

**Comment by julianoes** [comment]
Just saw these today actually. I think yes let's delete them.

https://github.com/PX4/PX4-SITL_gazebo/pull/857

**Pull request closed without merging**
