### PR TITLE
Pr tecs front trans

### PR DESCRIPTION
**Pull request by RomanBapst**
This PR brings makes use of [535](https://github.com/PX4/ecl/pull/535) in order to support altitude control via TECS during front transitions. This only applies for standard vtol and tiltrotors.

I also noticed that tailsitter transitions were broken on master (only in stabilized mode) and so i also included a fix for that (see diff in tailsitter.cpp).

I tested transitions in stabilized and position control for all three VTOL types in SITL.

### CODE REVIEW

**Comment by VTOLDavid** [comment]
Is safe to flight test in a tailsitter?

**Comment by RomanBapst** [comment]
@VTOLDavid Oh yes, sorry I forgot to tell you. This includes the fix you need for the tailsitter.

**Comment by VTOLDavid** [comment]
Thanks!

**Comment by dagar** [comment]
Looks good on first pass. Can you rebase?

**Comment by dagar** [comment]
> This though has the problem that then the aircraft is then no longer level, resulting in lift from the quadmotors in possibly backward direction, slowing the aircraft down.

Did you actually experience this? I was hoping we'd be able to get rid of the hard coded pitch setpoint handling and blending in VTOL transitions.

> The airspeed and altitude of the aircraft during a transition should rather be tuned correctly via the corresponding VTOL and TECS parameters. E.g. having a similar max throttle and airspeed setpoints for transitions and cruise to reduce an altitude over/undershoot right after the transition. With our planes (FunCub, BabyShark, SITLs) we have noticed no big altitude changes during the transition phases.

I think PX4 VTOL would be a lot more accessible (or at least less error prone) if many of these "tuning knobs" (VTOL parameters) were derived from existing parameters or dumped entirely.

**Comment by sfuhrer** [comment]
> Did you actually experience this? I was hoping we'd be able to get rid of the hard coded pitch setpoint handling and blending in VTOL transitions.
Well no, not directly experienced it so far, more like intuition based. The main reason I didn't push this further was that we usually had a very good altitude hold during transitions, and thus just didn't see the reason why to change that. To simplify the pitch sp handling (I assume you mean when the cruise pitch sp has a large offset from 0) would be a good reason, but I don't quite see how TECS is so helpful there..can you elaborate?

> I think PX4 VTOL would be a lot more accessible (or at least less error prone) if many of these "tuning knobs" (VTOL parameters) were derived from existing parameters or dumped entirely.
Totally agree with you on that. I will propose some changes for the VTOL parameters/transition logic soon (I want to solidify my understanding of the current status/behavior before that). 

One plan I had at some point was to start TECS when also the blending starts, as at this point we should have enough airflow. I will certainly keep that in the back of my head, but atm I think we can improve the user experience of VTOL transitions already a low without adding a new source of errors with the TECS.

**Comment by dagar** [comment]
> To simplify the pitch sp handling (I assume you mean when the cruise pitch sp has a large offset from 0) would be a good reason, but I don't quite see how TECS is so helpful there..can you elaborate?

The situation where the fixed pitch isn't appropriate for maintaining altitude either because it's slightly off, or wind conditions. Maintaining that fixed pitch with the multicopter controller can interfere with the lift motors naturally blending out.

> One plan I had at some point was to start TECS when also the blending starts, as at this point we should have enough airflow. 

Yes that should help with the nasty TECS initialization at transition. The other thing we can do in the TECS (and the FW position controller) is refactor the interface so that the state updates continue regardless of VTOL state and we send the command separately. We don't need to reset TECS completely.

https://github.com/PX4/Firmware/blob/f032d0d9fcc5ade4bf79bcd35fc0c930584e5118/src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp#L2017


https://github.com/PX4/Firmware/blob/f032d0d9fcc5ade4bf79bcd35fc0c930584e5118/src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp#L2041

**Comment by LorenzMeier** [comment]
Closing as stale.

**Pull request closed without merging**
