### PR TITLE
Update gz version to harmonic

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
### Solved Problem
The EOL is approaching for gz garden (Nov 2024)

https://gazebosim.org/docs/latest/releases/

### Solution
Update release to a LTS release of Gz (harmonic)

### Changelog Entry
For release notes:
```
Feature/Bugfix Bump default version of gz to harmonic
Documentation: Need to update the documentation to use gz harmonic
```

### Alternatives
No alternatives

### Test coverage
- Tested with gz
```
make px4_sitl gz_x500
```

### Context
- This might fix the airspeed sensor issue go away

### CODE REVIEW

**Comment by hamishwillee** [comment]
When this goes in, does that mean we will no longer support "Garden"? Does Harmonic work on Ubuntu 20.04?

We'll need some docs updates for this.

**Comment by Jaeyoung-Lim** [comment]
> When this goes in, does that mean we will no longer support "Garden"?

Yes, even if we do we cannot support it further than Nov 2024 since it would be EOL

**Review by dagar — APPROVED** [review]

**Comment by hamishwillee** [comment]
@Jaeyoung-Lim Should this backport to v1.15 too?

**Comment by bperseghetti** [comment]
> @Jaeyoung-Lim Should this backport to v1.15 too?
> 
> FYI, ROS docs call the humble/harmonic pairing risky: "- Possible, but use with caution. These combinations of ROS and Gazebo can be made to work together, but some effort is required."
> 
> Also, was macOS installer updated? In https://docs.px4.io/main/en/dev_setup/dev_env_mac.html#macos-development-environment it says `brew install px4-sim-gazebo`
> 
> Docs currently cover both Humble and Foxy. However no package exists for the Foxy/Harmonic combination. Should we just remove docs on Foxy in main (or stick with Gazebo there)? (@beniaminopozzan FYI)?

So, Foxy/Harmonic would not be a wise combination to use IMO. But we do have binary releases for supporting Humble/Harmonic and of course also Jazzy/Harmonic.

**Comment by bperseghetti** [comment]
Probably should fix this to avoid risk of confusion during install: https://github.com/PX4/PX4-Autopilot/pull/23632

**Comment by beniaminopozzan** [comment]
@hamishwillee the setup scripts (now) install

- Gazebo Classic 11 for Ubuntu 20.04
- Gazebo Garden for Ubuntu 21.3
- Gazebo Harmonic for Ubuntu 22.04

ROS 2 Foxy users will be using Ubuntu 20.04 and therefore Gazebo Classic 11 so there is no way they end up getting the ROS 2 Foxy / Gazebo Harmonic pair by just using the setup script.

ROS 2 Foxy is already EOL so keeping the documentation for it an for Gazebo Garden, as long as their EOL status is pointed out, is not that bad.

**Comment by hamishwillee** [comment]
Fixed by https://github.com/PX4/PX4-user_guide/pull/3367

I ignore Ubuntu 21.3 - only mad people use older non LTS variants :-).

The recommendation is upgrade to the "supported version" - Gazebo Harmonic for Ubuntu 22.04. Foxy/Gazebo Classic instructions remain in the docs, but I note that Foxy is EOL ... so upgrading makes sense.

**Pull request merged**
