### PR TITLE
AirspeedSelector, FailureDetector: Tailsitter attitude fixes

### PR DESCRIPTION
**Pull request by sfuhrer**
### Solved Problem
https://github.com/PX4/PX4-Autopilot/issues/21229
### Solution
Rotate attitude 90° in airspeed selector and failure detector.

Still have some `WARN  [ekf2] primary EKF changed 0 (filter fault) -> 3` that I'm looking into, which may have been the root issue for https://github.com/PX4/PX4-Autopilot/issues/21229.
It seems to be a EKF side slip fusion failure 
`# 6 - true if fusion of the synthetic sideslip constraint has encountered a numerical error`

### CODE REVIEW

**Comment by dagar** [comment]
Distributing even more tailsitter special cases everywhere is a bit concerning.

**Comment by sfuhrer** [comment]
> Distributing even more tailsitter special cases everywhere is a bit concerning.

Not nice but quite without alternative aren't we? And compared to other if(tailsitter) special cases the ones related to rotating the attitude are the easiest to justify no?

@dagar @bresch can we get this in and fix the remaining EKF fusion issue in https://github.com/PX4/PX4-Autopilot/pull/21328?

**Review by bresch — APPROVED** [review]

**Comment by sfuhrer** [comment]
@dagar @bresch please have a look at https://github.com/PX4/PX4-Autopilot/pull/21319/commits/29d934acf90366ff65a2ac1778c75a4af6722aeb

**Review by bresch — APPROVED** [review]
Perfect, thanks

**Comment by sfuhrer** [comment]
image
LGTM!

**Review by bresch — APPROVED** [review]

**Pull request merged**
