### PR TITLE
ekf2: generalized saving accel/gyro/mag in flight sensor calibration

### PR DESCRIPTION
**Pull request by dagar**
Opening to discuss additional changes and next steps for https://github.com/PX4/PX4-Autopilot/pull/18304.

 - add new estimator_sensor_calibration.msg
 - accel and gyro sensor calibration class add helper to convert estimated bias back to sensor calibration offset
 - sensors/vehicle_imu record in flight accel and gyro cal if available and adjust sensor calibration offsets on disarm

### CODE REVIEW

**Comment by dagar** [comment]
We should get the naming straight, should we call this "calibration" or "learned bias"?

**Comment by priseborough** [comment]
A few comments/questions, pending a more detailed review.

1) Do we need to publish the learned biases at the full rate? Once per second would probably suffice, 10Hz would be more than adequate.
2) Some biases have limits to how far the learned bias can swing. This tells the consumer how close we are to saturating the compensation. Should we include that information.
3) The term 'learned bias' is probably best for what the EKF produces. You subtract a bias, whereas an offset can be either sign. We would be better to limit the use of the term 'offset' to the  correction that is applied to the sensor data.

**Comment by priseborough** [comment]
@dagar I've merged the calibration and bias data into a single message here: https://github.com/priseborough/PX4-Autopilot/tree/pr-ekf2_sensor_calibration

**Comment by priseborough** [comment]
@dagar I did a quick flight test of the changes  pushed to https://github.com/priseborough/PX4-Autopilot/tree/pr-ekf2_sensor_calibration.

Single EFF operation:

https://logs.px4.io/plot_app?log=47f21124-85c8-4c39-acf2-cdb52e66c251

Four EKF operation, 2 IMU x 2 Mag with three consecutive flights.

https://logs.px4.io/plot_app?log=44d7d907-e267-4abf-9be7-6c8fa1ac1329
https://logs.px4.io/plot_app?log=3e073b7b-336f-43c9-9d13-06a1f14e2a7f
https://logs.px4.io/plot_app?log=579fa85f-d2ab-4158-b246-e6ec6b2b04c9

Screen Shot 2021-10-24 at 1 33 58 pm

**Comment by dagar** [comment]
Thanks Paul. I made a few small changes to make this fit in the flash constrained holybro kakute board, handle calibration count rollover, and make the PX4_INFO output a bit more consistent with the mag bias save, and specify accel/gyro.

Note there's still a hard coded requirement of the offset exceeding 0.05 m/s^2 for saving that we should probably revisit later.

Let's get this in and see how it goes.

**Pull request merged**
