### PR TITLE
Adding Batmon v4 support and refactoring Batt_smbus driver

### PR DESCRIPTION
**Pull request by nbelanger99**
The previous Batt_smbus implementation was a hard-coded BQ40z50/80 driver, not an actual SMBUS driver. In order to add support for more smart batteries, there should be an abstracted implementation of the SMBUS smart-battery spec, along with any more specific implementations on top of that. 

I've implemented the above structure; a generic SMBUS class which conforms to the SBS v1.1 spec, along with a BQ40z50/80 class, and a new class which introduces support for Rotoye Batmon smart batteries. 

Alternatively, the batt_smbus driver could continue to use a chain of if-else statements to offer support for multiple smart batteries, but that solution makes for increasingly difficult-to-read code and doesn't allow for good seperation of generic SMBUS capability from implementation-specific code. 

The Rotoye Batmon support has been tested-as-working with Batmon-equipt batteries. 

For more information on Rotoye Batmon, click [here](https://rotoye.com/)

### CODE REVIEW

**Comment by mrpollo** [comment]
@nbelanger99 Nick thanks for your contribution, it looks like we have some formatting and syntax errors that you need to address before we can review, can you please take a look at the failing CI?  if you browse through the CI logs you can see which commands it ran to get the output, for style and formatting you can refer to this guide https://docs.px4.io/master/en/contribute/code.html#code-style-formatting

**Comment by nbelanger99** [comment]
I'm having CI failures that don't seem to have to do with new code, such as Gazebo SITL tests, and issues regarding Post ccache cache files. I'm not sure exactly how to debug these issues, any help would be appreciated

**Comment by echoGee** [comment]
Any help with this ?

**Comment by mrpollo** [comment]
@echoGee it looks like some checks failed on their own unrelated to your changes, I'm restarting CI to verify, I'll get back to you shortly

**Comment by nbelanger99** [comment]
> @echoGee it looks like some checks failed on their own unrelated to your changes, I'm restarting CI to verify, I'll get back to you shortly

@mrpollo Thank you; it looks like we still have one Gazebo-related check failing. Is this a random thing or a real issue?

**Comment by mrpollo** [comment]
@nbelanger99 I think the issue is non-related to your changeset, I have pinged the dev team for their help reviewing!

**Comment by echoGee** [comment]
Any help on this ?

**Comment by mrpollo** [comment]
**Feedback from the BMS call**: Please add this as a modular standalone driver 

Let us know if you need help addressing this.

**Comment by echoGee** [comment]
We are trying to go down the path of making batmon a separate module, but end up with too much duplicated code. Lot of the underlying commonalities are tied to the I2C base classes. I worry that there would be fixes that make it to either branches and do not make it to the other. 

@dagar @mrpollo 
Is it worth putting this hacky architecture to a user to prevent regressions? I see another PR and some activity on https://github.com/PX4/PX4-Autopilot/pull/16872 . Maybe they would be able to test the changes on this PR and prevent regression? What do you think ?

**Comment by amikhalev** [comment]
Perhaps the `BATT_SMBUS` base class should be moved to `src/lib`. Then each specialization would just need to subclass `BATT_SMBUS` and implement the module entrypoint. So most of what is in `batt_smbus_main` could be moved to a static method on `BATT_SMBUS`

**Comment by dagar** [comment]
> Perhaps the `BATT_SMBUS` base class should be moved to `src/lib`. Then each specialization would just need to subclass `BATT_SMBUS` and implement the module entrypoint.

Yes that's what I think would be best architecturally (and for everyone).

SMBus should be only a base class for interfacing with a Smart Battery respecting what's in the [Smart Battery Data Specification](http://sbs-forum.org/specs/sbdat110.pdf) and nothing more.

**Comment by echoGee** [comment]
> Perhaps the `BATT_SMBUS` base class should be moved to `src/lib`. Then each specialization would just need to subclass `BATT_SMBUS` and implement the module entrypoint. So most of what is in `batt_smbus_main` could be moved to a static method on `BATT_SMBUS`

To move SBS stuff to BATT_SMBUS and keep most of the common code in there, it would need to be inherit I2CSPIDriver which automatically makes it a separate module. Isn't that right?

**Comment by amikhalev** [comment]
@echoGee Not sure if I understand correctly, but

A module is declared by `px4_add_module` in the CMake file, which allows it to be added under `DRIVERS`/`MODULES` in a board declaration.  `BATT_SMBUS` could exist as a class inheriting from `I2CSPIDriver` inside of a library (i.e. `px4_add_library`) without being a module, since there is no module entry point to call `module_start`.

I think what we want is:
 * A library in `src/lib/drivers` containing `class BATT_SMBUS`, a battery driver implementation for only functionality common to all SMBus batteries, as well as sufficient extension points via virtual methods to implement all BMS-specific functionality
 * Modules for each BMS-specific implementation, like `batt_smbus/bq40z80`, `batt_smbus/rotoye_batmon`, etc (following similar structure to IMU drivers). Each of these contains a subclass of `BATT_SMBUS` implementing specific functionality, as well as a module entry point which starts it. I could implement/test for bq40z80, @echoGee could for the Rotoye Batmon. I don't have a bq40z50, but I could implement it if someone else tests it
 * I suppose the generic SBS battery driver could also be exposed as a module (`batt_smbus/generic`?).
 * We could keep the parameter `BAT_SMBUS_MODEL` and add code to init scripts which launches the appropriate module. But this depends on whether all modules are even built by default.

@mhkabir @dagar thoughts?

**Comment by mrpollo** [comment]
Closed in favor of #16911

**Pull request closed without merging**
