### PR TITLE
Enable use of dedicated input capture pins

### PR DESCRIPTION
**Pull request by mhkabir**
**Describe problem solved by this pull request**
Enable use of the dedicated input capture pins on V5, V5X, V6X and Durandal through the IOTimer API.

**Describe your solution**
Added the input capture pins to the IO timer channel table so that they can be used by drivers later.

**Test data / coverage**
None yet, this is mostly for feedback. Will be testing thoroughly on available hardware.

### CODE REVIEW

**Comment by mhkabir** [comment]
@davids5 the order of the timer initialization in io_timers[MAX_IO_TIMERS] enforces the relative ordering of timers used in the timer_io_channels[MAX_TIMER_IO_CHANNELS] table through a static assert.

I agree that grouping the CH1-M and CAP1-N would be more readable, but that would mean needing to change the initIOTimer ordering in the io_timers table. I didn't want to change it since I didn't know if the ordering mattered.

**Comment by bkueng** [comment]
The grouping requirement comes from the `io_timers_channel_mapping_element_t` data structure, which can be lifted if we change that. IMO prefered as well.
Then we can also use them as additional pwm outputs if we want to.

**Comment by davids5** [comment]
>The grouping requirement comes from the io_timers_channel_mapping_element_t data structure, >which can be lifted if we change that. IMO preferred as well.

Am I ok to assume 'grouping' is not groups just the ordering in the file.  groups is a HW restriction and can not be changed.

> Then we can also use them as additional pwm outputs if we want to.

The reason for having them as dedicate capture was to allow the counting rate to not be 400 or 50hz.

**Comment by bkueng** [comment]
> Am I ok to assume 'grouping' is not groups just the ordering in the file. groups is a HW restriction and can not be changed.

Yes, I'm referring to the data structure.

**Comment by LorenzMeier** [comment]
Since there are no new commits addressing the review feedback, I'm closing this for now - please re-open with commits added, thanks!

**Pull request closed without merging**
