### PR TITLE
Add attitude and bodyrate control to RTPS

### PR DESCRIPTION
**Pull request by alvinsunyixiao**
## Describe problem solved by this pull request
`attitude` and `body rate` control in offboard mode was previously not possible with Fast-RTPS.

## Describe your solution
Generate the corresponding RTPS message for those two channels. The PX4 build bot should automatically update the [px4_ros_com](https://github.com/PX4/px4_ros_com) repo right?

## Describe possible alternatives
None

## Test data / coverage
Does not affect the flight controller

## Additional context
None

### CODE REVIEW

**Comment by alvinsunyixiao** [comment]
@dagar @TSC21

**Comment by Jaeyoung-Lim** [comment]
@alvinsunyixiao Could you rebase the branch to latest `main`?

**Comment by alvinsunyixiao** [comment]
@Jaeyoung-Lim Done.

**Review by Jaeyoung-Lim — APPROVED** [review]

**Comment by Jaeyoung-Lim** [comment]
@alvinsunyixiao Thanks!

**Pull request merged**
