### PR TITLE
when logger modules cant log, this is detected and new file open to log

### PR DESCRIPTION
**Pull request by avcuenes**
### Solved Problem
When I fly and logger is interrupted. 

### Solution
- I add some function to control logging and if logging stop after that I open new log file and continue to log.

### CODE REVIEW

**Comment by bkueng** [comment]
Can you describe the exact problem you're trying to solve? What errors do you see? On which hardware? And which SD card?

**Comment by avcuenes** [comment]
I am trying to solve logger problem. That problem have happened to me a few times. I fly and landed but  I see log file is interrupted. After that, I decided to solve. I assume logger thread didn't close but logger modules cant write to log file. I check logger module write to log file and If logger modules cant write to log file I open new file to write. 

Hardwares ,
Cubeorange and PX4 v1.12.3
Sandisk Ultra 32 gb

**Comment by bkueng** [comment]
I have nothing against hardening, but we need to fix the root cause. Can you provide the output of `dmesg` and `logger status` after it happened?

@davids5 fyi

**Comment by avcuenes** [comment]
I cant provide logger status because I realize this issue after flight.And, how to provide dmesg ?

**Comment by mnumanuyar** [comment]
any news on this ? 

As I understand this solves a problem that does not happen all of the time. And the main issue is 
1- for some reason log file is removed
2- there is no failsafe that activates when this has happen  (at least for this case) 

## a possibly related issue:
 when i do "erase all" in qground with sitl, new log file does not start. i am not sure this is intentional. in addition `logger status` report it is still writing. i traced this to 
```cpp
ssize_t LogWriterFile::LogFileBuffer::write_to_file(const void *buffer, size_t size, bool call_fsync) const
{
	perf_begin(_perf_write);
	ssize_t ret = ::write(_fd, buffer, size);
	std::cout<<ret<<'\n';                            // i added this for debug
	perf_end(_perf_write);

	if (call_fsync) {
		fsync();
	}

	return ret;
}
```

here altough the file does not exist, ret is not -1. which is probably is not intended.

I couldnt further debug into nuttx, because i dont know how 🥲  so any guidence there would be appriciated

**Comment by mnumanuyar** [comment]
i was able to repro with cube orange connected with usb to qground.
i was wotrking on a version slightly deviated from 1.12.3
everythin was ok, i left it open during lunch when i came back logging was stoppped

dmesg output:
```
INFO  [param] selected parameter default file /fs/mtd_params
INFO  [parameters] BSON document size 2571 bytes, decoded 2571 bytes
Board architecture defaults: /etc/init.d/rc.board_arch_defaults
Board defaults: /etc/init.d/rc.board_defaults
INFO  [uavcan] Node ID 1, bitrate 1000000
INFO  [px4io] IO FW CRC match
Board sensors: /etc/init.d/rc.board_sensors
ms5611 #0 on SPI bus 4
icm20602 #0 on SPI bus 4 rotation 12
icm20948 #0 on SPI bus 4 rotation 10
ms5611 #1 on SPI bus 1
icm20649 #0 on SPI bus 1
INFO  [commander] Mission #3 loaded, 36 WPs, curr: 30
Board extras: /etc/init.d/rc.board_mavlink
INFO  [mavlink] mode: Config, data rate: 800000 B/s on /dev/ttyACM0 @ 57600B
INFO  [mavlink] mode: Minimal, data rate: 2880 B/s on /dev/ttyS4 @ 57600B
Starting Main GPS on /dev/ttyS2
Starting MAVLink on /dev/ttyS0
INFO  [mavlink] mode: Normal, data rate: 1200 B/s on /dev/ttyS0 @ 115200B
INFO  [px4io] default PWM output device
INFO  [init] Mixer: /etc/mixers/AAERTWF.main.mix on /dev/pwm_output0
INFO  [pwm_out] instance: 0, max rate: 100, default: 50, alt: 50
INFO  [pwm_out] instance: 0, max rate: 100, default: 50, alt: 50
INFO  [init] Mixer: /etc/mixers/pass.aux.mix on /dev/pwm_output1
ERROR [px4io] failed setting PWM rate on IO
ERROR [pwm] PWM_SERVO_SET_SELECT_UPDATE_RATE
ekf2 [428:100]
INFO  [ekf2] starting instance 0, IMU:0 (3670050), MAG:0 (0)
INFO  [logger] logger started (mode=all)

NuttShell (NSH) NuttX-10.2.0
nsh> INFO  [logger] Start file log (type: full)
INFO  [logger] [logger] /fs/microsd/log/sess003/log001.ulg
INFO  [logger] Opened full log file: /fs/microsd/log/sess003/log001.ulg
uavcan_mag adding channel for topic sensor_mag node 25...
uavcan_mag channel 25 instance 1 ok
INFO  [ekf2] starting instance 1, IMU:1 (2621474), MAG:0 (589858)
INFO  [ekf2] starting instance 2, IMU:2 (2424842), MAG:0 (589858)
INFO  [ekf2] starting instance 3, IMU:0 (3670050), MAG:1 (8919299)
INFO  [ekf2] starting instance 4, IMU:1 (2621474), MAG:1 (8919299)
INFO  [ekf2] starting instance 5, IMU:2 (2424842), MAG:1 (8919299)
ERROR [uavcan] couldn't start parameter count: -2
uavcan_gnss adding channel for topic sensor_gps node 25...
uavcan_gnss node 25 instance 0 ok
uavcan_gnss node 25 topic sensor_gps instance 0 ok
WARN  [uavcan] GNSS Fix2 msg detected for ch 0; disabling Fix msg for this node
INFO  [commander] Connection to ground station lost
INFO  [commander] Data link regained
ERROR [uavcan] couldn't start parameter count: -2
INFO  [mavlink] Starting mavlink shell
ERROR [logger] write failed (28)
INFO  [logger] closed logfile, bytes written: 65884972
nsh> 
```

**Comment by mnumanuyar** [comment]
so i was checking the log and it says `ERROR [logger] write failed (28)`

I was curious about 28 I think it is: `#define	ENOSPC 28	/* No space left on device */` from `/opt/gcc-arm-none-eabi-9-2020-q2-update/arm-none-eabi/include/sys/errno.h`

but current logs are as such :

image

also when i try to check empty space i notice there is two partition. screenshot is from gparted:

 
partition

i am not very familiar with this technology i will try to format it and test it again

**Comment by davids5** [comment]
@mnumanuyar - it may be the format. You can reformat it on the FMU

**### !!! This will wipe all the data on the card. !!!**

On the console or via QGC console issues the commands
`echo > /fs/microsd/.format`
`reboot`

**Pull request closed without merging**
