### PR TITLE
Terrain following fix

### PR DESCRIPTION
**Pull request by joe-bfd**
### Solved Problem
When using jerk limited/acceleration based input position controllers I found that terrain following was not functional. Terrain following z position setpoints were ignored.

### Solution
Only set position setpoint to current position if z position setpoint is not already set

### CODE REVIEW

**Comment by dagar** [comment]
Trivial whitespace thing is making astyle angry. https://github.com/PX4/PX4-Autopilot/actions/runs/5674219445/job/15377357389?pr=21885
image

**Comment by joe-bfd** [comment]
Updated. Will check the output a little later to make sure It's all green lit

**Comment by joe-bfd** [comment]
Hey guys, any update on this PR? I can rebase it onto latest master if we want

**Comment by dagar** [comment]
It wasn't exactly clear to me why this is the right fix, could we do it more explicitly so it's obvious?

Are you interested in terrain hold or the full terrain following? Could it apply to only the current default manual position control mode or is it actually needed across all altitude and position control modes?

Ping me on slack if you want to discuss directly.

**Comment by julianoes** [comment]
Is this still work in progress or can we close it?

**Comment by bresch** [comment]
The issue with that patch is that FlightTaskAltitude is now producing the altitude setpoint in all cases, meaning that locking won't be as smooth as when done using the smooth vel variant.
For this, we might need to rewrite the terrain following/hold logic in `FlightTaskAltitudeSmoothVel`. It might be a good opportunity to review it and extract it in a class.

**Comment by AlexKlimaj** [comment]
@bresch maybe we want to make `_terrain_hold` a public variable of `FlightTaskManualAltitude`, then `FlightTaskManualAltitudeSmoothVel` can check before it does `_position_setpoint(2) = _smoothing.getCurrentPosition();`

**Comment by bresch** [comment]
replaced by https://github.com/PX4/PX4-Autopilot/pull/22294

**Pull request closed without merging**
