### PR TITLE
fix(kakuteh7.default.px4board): remove CONFIG_BOARD_SERIAL_TEL2

### PR DESCRIPTION
**Pull request by iftahnaf**
### Solved Problem
From the [documentation](https://docs.px4.io/main/en/flight_controller/kakuteh7.html), Kakute H7 does not have the TELEM2 option. It does appear in the default.px4board file: 
https://github.com/PX4/PX4-Autopilot/blob/f7e6e1354af1df0ab8ef3f0ad169518ad54d1989/boards/holybro/kakuteh7/default.px4board#L5

### Solution
The simple solution is to remove the line from the file so it won't appear as an option.

### Alternatives
We could also disable serial console and use `R3/T3` pins as TELEM2:
1. Disable the serial console:
https://github.com/PX4/PX4-Autopilot/blob/f7e6e1354af1df0ab8ef3f0ad169518ad54d1989/boards/holybro/kakuteh7/nuttx-config/nsh/defconfig#L240

2. Change the `CONFIG_BOARD_SERIAL_TEL2` in the default.px4board to the correct UART (from the documentation:
```
CONFIG_BOARD_SERIAL_TEL2="/dev/ttyS2"
```

@vincentpoont2 I would appreciate it if you could review this.

### CODE REVIEW

**Comment by beniaminopozzan** [comment]
side question: is `/dev/ttyS1` the one referred to as `UART 2` in the Holybro documentation?

**Comment by iftahnaf** [comment]
I'm not sure, but I guess so; I couldn't get a clear answer from Holybro's tech support.

**Comment by vincentpoont2** [comment]
@iftahnaf Thanks for the suggestion. 
KakuteH7's Telem2 is connected to the UART of the Bluetooth chip via a resistor inside the board, but it has no exposed solder pad.
image

Although it is not exposed by default. There are workaround, so I think it's better to keep this line of config.
The workaround is as follow:

image

There might a version in the future that doesn't have bluetooth and exposed the UART2.

**Comment by vincentpoont2** [comment]
> side question: is `/dev/ttyS1` the one referred to as `UART 2` in the Holybro documentation?

-----Yes, dev/ttys1 corresponds to UART2
-----The UART correspondence of PX4 is ttys0->UART1, ttys1->UART2, ttys2->UART3, and so on

**Comment by iftahnaf** [comment]
@vincentpoont2 Awesome, thanks for the clarification. 
I'll add this to the PX4 Kakute H7 docs.

**Pull request closed without merging**
