### PR TITLE
not run transition flight task when not enable altitude control

### PR DESCRIPTION
**Pull request by xdwgood**
.**Describe problem solved by this pull request**
To fix issue: https://github.com/PX4/PX4-Autopilot/issues/16057

**Describe your solution**
Do not run transition flight task when not enable altitude control

**Describe possible alternatives**
For all vtols, if altitude control is not enabled, the relevant thrust control information should not be published, but it is determined by the pilot's throttle stick

**Test data / coverage**
before this pr:
Screenshot from 2020-10-30 09-09-36

log link: https://review.px4.io/plot_app?log=31ecffd0-f99d-4169-99ab-f5fdc3778189

after this pr:
Screenshot from 2020-10-30 09-09-50

log link: https://review.px4.io/plot_app?log=39d29f3d-ab7a-4e43-bc9a-2d67d1d048bf

I also used simulation to verify that the drone state is normal after enabling altiude control.

**Additional context**
I also removed unused variables
`_transition_altitude` `_transition_yaw`

FYI @sfuhrer  @RicardoM17

### CODE REVIEW

**Review by sfuhrer — COMMENTED** [review]
For me it makes sense to not run the flight task for any VTOL, not just tailsitter, so I agree with this change here. As it is quite a big change though it would still be nice to get some flight testing on it on standard VTOL and tiltrotor. I can take care of that, hopefully this week.

**Comment by xdwgood** [comment]
@sfuhrer I completed the real flight test using the code containing the changes to this branch

**Comment by sfuhrer** [comment]
> @sfuhrer I completed the real flight test using the code containing the changes to this branch

@xdwgood did you check if you the throttle output follows the commands from the throttle stick during the transition phases? Because I don't think it does so for standard VTOL and tiltrotor.

**Comment by xdwgood** [comment]
> did you check if you the throttle output follows the commands from the throttle stick during the transition phases? 

@sfuhrer  yes,throttle output follows the commands from the throttle stick during the transition phases

**Comment by sfuhrer** [comment]
@RicardoM17 thanks for the testing on the tailsitter, looks promising. Let's tackle the spike though, agree.

@xdwgood @RicardoM17 I found the reason why it didn't work before with standard VTOL and tiltrotor, it's because there we're currently using the FW attitude controller during transition, and that one only publishes a thrust sp in horizontal direction --> need to map this to vertical thrust (on the MC motors). 
I've made the changes and pushed to https://github.com/PX4/PX4-Autopilot/pull/16244, if you agree I propose to move over to there (I somehow failed to push directly to the branch of this PR).

**Comment by RicardoM17** [comment]
Sounds good to me. Any idea what could be causing the spike? It seems that the FW setpoint isn't being updated during the transition and so it starts from zero or something like that. I'll try to look at the code and see if I can find something but if you already have any ideas that could be the reason it would make it easier.

**Comment by VTOLDavid** [comment]
I have experienced similar thust spikes in alt hold in FW mode with a tailsitter. I am trying to reproduce it in SITL

**Pull request closed without merging**
