### PR TITLE
microRTPS: fix setting UART communication flags

### PR DESCRIPTION
**Pull request by lukegluke**
bitwise not should be used instead of logical not

I don't use microR, just notice an issue, can't test.

### CODE REVIEW

**Comment by TSC21** [comment]
This makes sense. I will give a try, but I wonder if this was an actual problem the UART link wouldn't work (which it's not the case). Anyway, I will test it and merge it if it still works after the change.

**Comment by lukegluke** [comment]
> but I wonder if this was an actual problem the UART link wouldn't work (which it's not the case).

I think all bits were cleared at all (except 1). For example `uart_config.c_cflag &= !(CSIZE | CSTOPB | PARENB);` is equivalent to `uart_config.c_cflag &= 1` (or = 0), but all important flags are set after so I suppose it was not problem before.

**Comment by TSC21** [comment]
> > but I wonder if this was an actual problem the UART link wouldn't work (which it's not the case).
> 
> I think all bits were cleared at all (except 1). For example `uart_config.c_cflag &= !(CSIZE | CSTOPB | PARENB);` is equivalent to `uart_config.c_cflag &= 1` (or &= 0), but all important flags are set after so I suppose it was not problem before.

Yes that's correct. I guess this will still work, just need to confirm it first. Further than that, there are some optimizations that can be done on the config, but will leave it to a further PR. I will test and approve/merge if all good. Thanks for this!

**Review by TSC21 — APPROVED** [review]
all seems to be working correctly. Thank you!

**Pull request merged**
