### PR TITLE
flight_mode_manager: ManualAcceleration support weathervane yaw handler

### PR DESCRIPTION
**Pull request by dagar**
- fixes https://github.com/PX4/PX4-Autopilot/issues/17911

@taileron @VTOLDavid can you give this a try?

### CODE REVIEW

**Comment by dagar** [comment]
If this (or a minor variation) works then we can cleanly back port it for v1.12.2.

**Comment by VTOLDavid** [comment]
Thank you @dagar!  I will test it this week

**Comment by taileron** [comment]
> If this (or a minor variation) works then we can cleanly back port it for v1.12.2.

change into 1.12.1 wv now works perfect in position, rtl, mission: 
https://review.px4.io/plot_app?log=ed48f96c-5447-437c-8105-5df8e4c901a6

**Comment by VTOLDavid** [comment]
> 
> 
> > If this (or a minor variation) works then we can cleanly back port it for v1.12.2.
> 
> change into 1.12.1 wv now works perfect in position, rtl, mission much thanks @dagar:
> https://review.px4.io/plot_app?log=ed48f96c-5447-437c-8105-5df8e4c901a6

Same here, works perfect. Thanks @dagar!

**Comment by sfuhrer** [comment]
How about extending WV_EN to a bitmask with field one: enable in Auto, field two: enable in Position? As I can imagine users not wanting the WV in Position flight mode, but only in Auto modes.

**Comment by VTOLDavid** [comment]
> 
> 
> How about extending WV_EN to a bitmask with field one: enable in Auto, field two: enable in Position? As I can imagine users not wanting the WV in Position flight mode, but only in Auto modes.

Seems a good option, but why someone would like his VTOL to fight against wind?

**Review by sfuhrer — APPROVED** [review]

**Comment by dagar** [comment]
I'm going to merge this as is, then cherry-pick for v1.12.2. Then in master we can follow up with adding more granularity to WV_EN.

Thanks everyone.

**Pull request merged**
