### PR TITLE
FW position control add takeoff minimum pitch parameter

### PR DESCRIPTION
**Pull request by dagar**
This is currently passed through via mavlink, but I don't think it makes sense to set per mission. This is a vehicle parameter.

 - fixes https://github.com/PX4/Firmware/issues/6787

@antiheavy

### CODE REVIEW

**Comment by Antiheavy** [comment]
Agree.

Once this goes in place, then QGC could hide the takeoff pitch value in the waypoint editor which is a big flight safety improvement.  People fat figure the wrong pitch into that field and cause the vehicle to crash on launch -- i've done it a couple times and I've seen others do it too.

This also makes Takeoff mode actually useful for PX4 Fixed Wing since the pitch can be set appropriately for each vehicle, instead of some previously hard-coded value.

**Comment by Antiheavy** [comment]
original issue post here:  https://github.com/PX4/Firmware/issues/6787

**Comment by dagar** [comment]
Conflicts resolved and rebased on master.

**Comment by Antiheavy** [comment]
@dagar we can help with flight testing a branch that has this.  FYI @kjkinney

**Comment by Antiheavy** [comment]
we should make a scan for all launch mode features for both mission takeoff and QGC button takeoff behaviors.  e.g. how does this fit in  https://github.com/PX4/Firmware/pull/9858#event-1727111402

**Comment by Antiheavy** [comment]
@philipoe @tstastny your input would be appreciated for this fixed wing related PR.  original feature request here: https://github.com/PX4/Firmware/issues/6787

**Comment by Antiheavy** [comment]
can we add this to the Fixed Wing project board?
https://github.com/PX4/Firmware/projects/22

**Comment by philipoe** [comment]
I totally agree that this needed to be changed/fixed. I did a quick review and found no issues with the code changes related to the pitch min parameter. However, there is also a lot of variable name changes mixed into this one commit that i thus did not review...

**Comment by dagar** [comment]
Rebased on master (and simplified).

**Comment by dagar** [comment]
Simpler version of this PR without the other FW position controller changes. https://github.com/PX4/Firmware/pull/11373

**Comment by Antiheavy** [comment]
@dagar is this PR overcome by the newer https://github.com/PX4/Firmware/pull/11845  ?

**Comment by Antiheavy** [comment]
Hmmmm.  @dagar this is the version we’ve been flying for months. Works great.

**Comment by hamishwillee** [comment]
@RomanBapst This still looks sensible. Any reason why it hasn't gone in?

**Comment by RomanBapst** [comment]
@hamishwillee Yes, looks sensible. I'll have to rebase it and merge.

**Comment by ryanjAA** [comment]
This will be good to have. No reason to really ever change takeoff pitch per mission unless testing something. I have enjoyed an accidental 35 degree full flap takeoff instead of a 25 deg test (that should be essentially impossible unless very deliberate) which this will help users not do.

**Comment by hamishwillee** [comment]
Thanks @RomanBapst - I hope soon :-0

**Comment by Antiheavy** [comment]
>  I have enjoyed an accidental 35 degree full flap takeoff instead of a 25 deg test (that should be essentially impossible unless very deliberate) which this will help users not do.

guess what happens when someone thinks they are typing in their takeoff altitude into the pitch field!   yep, done it....   that is why we rolled in something nearly identical to this PR a year ago.

**Comment by hamishwillee** [comment]
Ping @RomanBapst - rebasing and merging reminder :-)

**Comment by Antiheavy** [comment]
This (or something similar) should really go into to upstream.  We’ve been running this PR for well over a year now. Many 1000’s of flights.   As both I and @ryanjAA  have pointed out there is a safety concern about the current requirement to type in a Takeoff pitch value into each mission.  Are there know users this would negatively impact? @dagar @RomanBapst

**Comment by ryanjAA** [comment]
I agree. Takeoff pitch really should be set either as a parameter or harder to access mission setting since it shouldn’t be easily accessible to the point of accidentally changing it. I never change it unless it’s a test but I do like knowing I see it when planning a mission as it validates the planning is correct (although I don’t need to see cruise speed and that’s a parameter so it’s just getting used to it I suppose). This does make sense to have as parameter or possibly viewable in qgc mission planning so if there are negative reasons not known maybe we approach this from the qgc side and make it simply harder to change than a simple text box but one way or another too easy of access isn’t ideal.

**Comment by LorenzMeier** [comment]
Closing as stale.

**Pull request closed without merging**
