### PR TITLE
Enable DO_SET_SPEED commands outside of missions in other AUTO modes

### PR DESCRIPTION
**Pull request by sfuhrer**
Replaces https://github.com/PX4/PX4-Autopilot/pull/18605.

**Describe problem solved by this pull request**
- no interface to change speed setpoint in auto flight if not in mission
- ~~flying in high wind with an airspeed setpoint close to stall is dangerous due to increased external disturbances, so the airspeed setpoint should ideally be increased in these situations~~

**Describe your solution**
*Speed setpoint slider:*
(Note: no PR yet for QGC side) Introduce a slider in the flyview of QGC to change the current speed setpoint. For MC this would be groundspeed, for FW/VTOLs in FW mode airspeed. After confirming the set value of the slider, QGC sends the MAVLink command [DO_CHANGE_SPEED](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_CHANGE_SPEED). Navigator stores the received value in _mission_cruising_speed_mc/_fw, and applies it from there on for every new AUTO action (e.g. GoTo, Loiter etc). For it to have immediate effect if vehicle is in AUTO_LOITER when receiving the change speed, apply it by doing a reposition without updating any other field than cruising_speed and cruising_throttle. 
DO_CHANGE_SPEED waypoints in mission have the same interface. They override the value set through the slider in the flyview.

When RTL is activated reset the cruising speed and throttle.
image

~~*Wind-based adaption:* (not sure if we need this anymore with https://github.com/PX4/PX4-Autopilot/pull/18810)
There is an offset added to the minimum airspeed setpoint: setpoint += `FW_WIND_ARSP_SC` * abs(wind). So if the scale is set to 0.2, then for 10m/s there are 2m/s added to the setpoint that help making the vehicle's attitude control more robust to disturbances caused by the high wind, plus reduces the chance of a groundspeed undershoot.~~

EDIT: removed the wind-based adaption from this PR, and also split out the airspeed setpoint handling in the FW position controller: https://github.com/PX4/PX4-Autopilot/pull/18841

**Describe possible alternatives**

**Test data / coverage**
SITL tested. 

**Additional context**

### CODE REVIEW

**Comment by sfuhrer** [comment]
This is an early draft on the groundstation side. 
https://user-images.githubusercontent.com/26798987/145609643-1066d775-03bf-487f-972d-9ebc3187a867.mp4

**Comment by Jaeyoung-Lim** [comment]
This is super cool!

**Review by RomanBapst — CHANGES_REQUESTED** [review]
@sfuhrer I just realized that when you set a speed in mc mode and then transition, the fw controller will use the same speed setpoint. Can you have a look at that?

**Comment by sfuhrer** [comment]
> @sfuhrer I just realized that when you set a speed in mc mode and then transition, the fw controller will use the same speed setpoint. Can you have a look at that?

Yes good point, I'd say we should always reset the speed and throttle setpoint when transitioning: https://github.com/PX4/PX4-Autopilot/pull/18834/commits/30179e1c679be13a3ad7ffeb95cd5d6e4f0dadf3

**Review by RomanBapst — APPROVED** [review]

**Comment by ryanjAA** [comment]
This is awesome @sfuhrer !

**Comment by sfuhrer** [comment]
Given that the QGC implementation is now there in a PR I go ahead and merge this.

**Comment by lichishubao** [comment]
But it doesn't work when the Fix-wing in offboard mode

**Comment by sfuhrer** [comment]
> But it doesn't work when the Fix-wing in offboard mode

Please open a new issue or ask on discord, as stated this PR wasn't about offboard but AUTO modes.

**Pull request merged**
