### PR TITLE
Pull request for issue #14350

### PR DESCRIPTION
**Pull request by mlaiacker**
This pr will fix issue #14350 
simulated with
px4_sitl gazebo_standard_vtol

log: https://logs.px4.io/plot_app?log=dfb7a07f-6a15-4744-93cc-94c9bae79882

bokeh_plot(1)

### CODE REVIEW

**Comment by mlaiacker** [comment]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/p/python-setuptools/python3-setuptools_39.0.1-2_all.deb  Could not connect to azure.archive.ubuntu.com:80 (52.177.174.250), connection timed out

maybe run the Python CI again?

**Comment by julianoes** [comment]
@mlaiacker I think this CI error is unrelated, don'w worry about it.

**Comment by MaEtUgR** [comment]
I think why this could be happening is: For multicopter we had the problem of navigator constantly resending the same waypoints just to update the altitude to track the 3D line which killed all useful trajectory flying in the FlightTaskAuto because the goal waypoint would constantly update. I'm quite sure the trajectory generation for multicopter already does the 3D line for the user and fixed-wing apparently not. I have to do some testing to figure out if I'm right.

**Comment by julianoes** [comment]
FYI @RomanBapst @sfuhrer

**Review by moreba1 — APPROVED** [review]

**Comment by mlaiacker** [comment]
Still alive, cool!

**Pull request closed without merging**
