### PR TITLE
RTL: VTOL: do the land delay loitering (RTL_LAND_DELAY) in fixed-wing flight

### PR DESCRIPTION
**Pull request by sfuhrer**
**Describe problem solved by this pull request**
https://github.com/PX4/PX4-Autopilot/issues/16500 --> for some VTOL applications it is desired if the land delay loitering is done while still in fixed-wing mode, instead of hover. I see these use-cases:
- if there should be a delay before landing, such that pilot could interfere (better do that in FW, as much more energy efficient)
- to estimate wind speed before triggering the backtransition, such that the distance to home can be optimized

**Describe your solution**
Change RTL state order 
old:   (CLIMB-->RETURN-->DESCEND-->TRANSITION-->MOVE_TO_LAND_HOVER-->LOITER-->LAND)
new: (CLIMB-->RETURN-->DESCEND-->LOITER-->TRANSITION-->MOVE_TO_LAND_HOVER-->LAND)

**Describe possible alternatives**
Some logic with NAV_FORCE_VT --> e.g. if NAV_FORCE_VT is set to false, then do not execute transition but directly go to loiter and then land in FW. Sounds dangerous to me, would have the advantage that if a user wants to have the loitering done in hover also for a VTOL, that could be set up.

**Test data / coverage**
SITL tested.

### CODE REVIEW

**Comment by MartinStokelj** [comment]
@sfuhrer If I understand this right it says "go to loiter and then land in FW". 
We don't want him to land and also not land him as FW, this would damage the drone.
If param RTL_LAND_DELAY is set to -1 he should loiter as FW above WP and not auto land or auto transition to MC...

**Comment by sfuhrer** [comment]
> it says "go to loiter and then land in FW". 

Where does it say that? That's certainly not the idea, but that after the loiter in FW it transitions and lands in hover.

**Comment by MartinStokelj** [comment]
sorry I misunderstood, it looks ok now with
RTL_LAND_DELAY -1
NAV_FORCE_VT 0
https://review.px4.io/plot_app?log=beb86924-b2a7-48f3-8e35-c1723e8b519d

**Review by RomanBapst — APPROVED** [review]

**Comment by RomanBapst** [comment]
@sfuhrer SITL tests are failing. Need to have a closer look if related. Otherwise, I agree with these changes.

**Review by RomanBapst — APPROVED** [review]

**Pull request merged**
