### PR TITLE
create a range of common quadcopter frame sizes and general ROMFS cleanup

### PR DESCRIPTION
**Pull request by dagar**
This was motivated by px4fmu-v2 flash space, but it's something I've wanted to improve for some time now.

One common source of confusion I see with new (and even experienced) users is not knowing where to start with airframe selection. We have a range of issues with the default airframes, including fairly generic configurations that are named specifically, or configurations that target a common frame that include many details specific to one particular users setup. The vast majority will never have the exact same setup, and users often end up playing a guessing game.

This PR attempts to start addressing some of these issues.

 
 - create a range of airframes for common quadcopter frame sizes
 - don't configure parameters that don't correspond to the actual airframe
    - an airframe for a frame kit shouldn't include PWM settings for particular ESCs unless they come with the kit
   - an airframe shouldn't include user preferences for things like frsky_telemetry
 - delete unnecessary airframes for things like vmount or CAN usage. These can easily be configured with a param change.

### CODE REVIEW

**Comment by dagar** [comment]
If there's concern over general churn or some of the airframes that have been added or removed I propose we set up a quick call to review this.

**Comment by dagar** [comment]
Here's what QGC airframe selection looks like with this PR.

screenshot from 2018-07-06 11-43-56

Compared to current master.
screenshot from 2018-07-06 11-45-22

**Comment by dagar** [comment]
TODO
 - review and consolidate
   - all VTOLs
   - Quadrotor Wide category
   - helicopters and coaxial helicopters (there should be generics)
   - flying wings (these could all be using the same mixer)
 - review generic options in all categories

**Comment by hamishwillee** [comment]
FWIW I think this is a hell of a lot better end user story - I would know what to select now (either a specific vehicle because that is RTF with no configuration, or a generic config for my frame size).

**Comment by bkueng** [comment]
This looks good except for the various SYS_AUTOSTART ID changes. I understand the intent but it unnecessarily breaks a lot of existing setups. E.g:
4010 -> 4330
4011 -> 4450
4050 -> 4251
1001 -> 4002

**Comment by dagar** [comment]
Suggestion from @MaEtUgR on the dev call to limit the quadcopter selection to small, medium, large.

**Comment by hamishwillee** [comment]
> Suggestion from @MaEtUgR on the dev call to limit the generic quadcopter selection to small, medium, large.

That is probably a good idea, but is there a good shared understanding of what those sizes mean, and if not, how would it be conveyed?

**Comment by dagar** [comment]
Example of how we're hurting users. https://github.com/PX4/Firmware/issues/10099

For a non-technical user getting out of this state is quite difficult.

**Comment by LorenzMeier** [comment]
Happy to review & help to get in if you rebase.

In terms of "bricking": We need support in the bootloader to trigger a complete system reset.

**Comment by mcsauder** [comment]
@dagar, I've deconflicted your work here: https://github.com/mcsauder/Firmware/tree/pr-airframe_cleanup

**Comment by mcsauder** [comment]
@dagar , here you go: https://github.com/PX4/Firmware/compare/master...mcsauder:pr-airframe_cleanup

**Comment by LorenzMeier** [comment]
Closing as stale.

**Pull request closed without merging**
