### PR TITLE
moved set_camera_zoom and do_set_servo to commander

### PR DESCRIPTION
**Pull request by dayjaby**
**Describe problem solved by this pull request**
SET_CAMERA_ZOOM was handled in mavlink_receiver before and DO_SET_SERVO only in mission_blocks. Moved both to the Commander.cpp. Also changed the formula for DO_SET_SERVO, as it probably required some very specific mixer before. Now it merely scales the 0-2000 input in the command to -1 to 1 and the rest is up to the mixer.

### CODE REVIEW

**Comment by julianoes** [comment]
I'm a bit confused here. What exactly does it fix? And why?

**Comment by dayjaby** [comment]
> I'm a bit confused here. What exactly does it fix? And why?

Both SET_CAMERA_ZOOM and DO_SET_SERVO can be mission items now *and* be performed if you send a COMMAND_LONG.

Before this PR, you could have DO_SET_SERVO as mission item, but not as command, and SET_CAMERA_ZOOM as command, but not as mission item.

**Comment by julianoes** [comment]
Right. And this actually works? :astonished:

**Comment by dayjaby** [comment]
> Right. And this actually works?

After reaching waypoint with SET_CAMERA_ZOOM, param1=2, param2=50:

```
~/Development/FirmwarePX4/build/px4_sitl_default/bin$ sudo ./px4-listener actuator_controls_2

TOPIC: actuator_controls_2
 actuator_controls_s
	timestamp: 414596000  (19.948000 seconds ago)
	timestamp_sample: 0
	control: [nan, nan, nan, nan, 0.0000, nan, nan, nan]
```

After reaching waypoint with SET_CAMERA_ZOOM, param1=2, param2=50:

```
~/Development/FirmwarePX4/build/px4_sitl_default/bin$ sudo ./px4-listener actuator_controls_2

TOPIC: actuator_controls_2
 actuator_controls_s
	timestamp: 436496000  (9.784000 seconds ago)
	timestamp_sample: 0
	control: [nan, nan, nan, nan, 1.0000, nan, nan, nan]
```

After reaching waypoint with DO_SET_SERVO, param1=1, param2=1500:

```
~/Development/FirmwarePX4/build/px4_sitl_default/bin$ sudo ./px4-listener actuator_controls_2

TOPIC: actuator_controls_2
 actuator_controls_s
	timestamp: 458816000  (18.656000 seconds ago)
	timestamp_sample: 0
	control: [nan, 0.5000, nan, nan, nan, nan, nan, nan]
```

A manual DO_SET_SERVO:
```
~/Development/FirmwarePX4/build/px4_sitl_default/bin$ rosservice call /mavros/cmd/command "{broadcast: false, command: 183, confirmation: 0, param1: 1, param2: 2000, param3: 0.0,
  param4: 0.0, param5: 0.0, param6: 0.0, param7: 0.0}" 
success: True
result: 0
~/Development/FirmwarePX4/build/px4_sitl_default/bin$ sudo ./px4-listener actuator_controls_2

TOPIC: actuator_controls_2
 actuator_controls_s
	timestamp: 539864000  (1.084000 seconds ago)
	timestamp_sample: 0
	control: [nan, 1.0000, nan, nan, nan, nan, nan, nan]
```

A manual SET_CAMERA_ZOOM:
```
~/Development/FirmwarePX4$ rosservice call /mavros/cmd/command "{broadcast: false, command: 531, confirmation: 0, param1: 2, param2: 100, param3: 0.0,
  param4: 0.0, param5: 0.0, param6: 0.0, param7: 0.0}" 
success: True
result: 0
simadm@10:~/Development/FirmwarePX4$ sudo ./build/px4_sitl_default/bin/px4-listener vehicle_command

TOPIC: vehicle_command
 vehicle_command_s
	timestamp: 847064000  (14.288000 seconds ago)
	param5: 0.000000
	param6: 0.000000
	param1: 2.0000
	param2: 100.0000
	param3: 0.0000
	param4: 0.0000
	param7: 0.0000
	command: 541
	target_system: 1
	target_component: 1
	source_system: 1
	source_component: 240
	confirmation: 0
	from_external: True
simadm@10:~/Development/FirmwarePX4$ sudo ./build/px4_sitl_default/bin/px4-listener actuator_controls_2

TOPIC: actuator_controls_2
 actuator_controls_s
	timestamp: 859448000  (5.292000 seconds ago)
	timestamp_sample: 0
	control: [nan, nan, nan, nan, 1.0000, nan, nan, nan]
```

**Comment by dayjaby** [comment]
@hamishwillee I think you are more on track on the DO_SET_SERVO requests on slack...is this a feasible solution for it? The only problem is the collision with actuator_controls_2 from the vmount module.

**Comment by bkueng** [comment]
I prefer to avoid the collision, and rather go for aux in control group `#3` as outlined in https://github.com/PX4/Firmware/pull/10320#issuecomment-561119536 with a new command. That way most existing setups can just use it w/o mixer changes and it is testable via RC as well.
Zoom should go through vmount. How are you using that currently, without vmount?

**Comment by dayjaby** [comment]
> I prefer to avoid the collision, and rather go for aux in control group `#3` as outlined in [#10320 (comment)](https://github.com/PX4/Firmware/pull/10320#issuecomment-561119536) with a new command. That way most existing setups can just use it w/o mixer changes and it is testable via RC as well.
> Zoom should go through vmount. How are you using that currently, without vmount?

The camera that we use is happy with getting the PWM signal just once for setting the zoom, so publishing actuator_controls_2 once was sufficient to get the zoom controlled, of course with a corresponding mixer file.

**Comment by coderkalyan** [comment]
It was just brought to my attention that my PR for DO_SET_SERVO (https://github.com/PX4/Firmware/pull/15281) conflicts with this. Not really sure what's going on here, or who should continue DO_SET_SERVO work? After talking with @bkueng, I am currently working on mapping DO_SET_SERVO to control group 3 RC aux 1-3. I am also adding support for the new MAV_CMD_DO_SET_ACTUATOR message.

**Pull request closed without merging**
