### PR TITLE
Fixes for kinetis k66 e & defconfig sync with V3

### PR DESCRIPTION
**Pull request by davids5**

### CODE REVIEW

**Comment by davids5** [comment]
Rebased on master with BUGFIX Hardfault Commander Calibration

**Comment by davids5** [comment]
@dagar - I think we should proceed with command line option on the icm42688p

**Comment by igalloway** [comment]
We have a couple of people reviewing and testing these updates. Will get back shortly.

**Review by dagar — APPROVED** [review]

**Comment by jarivanewijk** [comment]
Thank you, @davids5. Calibration works fine on FMUK66E, the sensors seem to have the correct rotation now. I think @igalloway will discuss with you what to do with the icm42688p and SPI DMA.

**Comment by davids5** [comment]
@jarivanewijk - thank you for testing!

**Pull request merged**
