### PR TITLE
NXP MR-CANHUBK3 Support

### PR DESCRIPTION
**Pull request by PetervdPerk-NXP**
Adds for support for the MR-CANHUBK3 board as presented on the PX4 Summit
https://www.youtube.com/watch?v=8Iw6FnZlbtM

MR-CANHUB-K3 Features
- Lockstep Cortex-M7 @ 160Mhz
- 512KB RAM
- 6x CAN-FD
- 8MB on-board non-volatile storage with LittleFS
- 100BASE-T1 Automotive Ethernet
- Onboard SBC FS26 supporting 5-40V input for supplying K3
- 8x PWM output
- (Optional) FMUV5X-IMU-RC03 IMU board support

MR-CANHUB-K3 has 2 targets

nxp_mr-canhubk3_default
Basic PX4 modules can be run as cannode

nxp_mr-canhubk3_fmu
All modules enabled to function as FMU but following add-ons are required to make it function fully
- FMUV5X-IMU-RC03 IMU board
- SD Card SPI breakout on port P1B for logging

Todo regarding software
- ADC input support
- LPUART DMA support

### CODE REVIEW

**Review by davids5 — APPROVED** [review]
LGTM

**Comment by dagar** [comment]
Test rack started failing, we're getting `mkfatfs failed: Bad address` consistently on some (but not all) boards.

Screenshot 2022-12-06 at 6 30 32 PM

**Comment by dagar** [comment]
Screenshot 2022-12-06 at 6 32 11 PM

**Comment by dagar** [comment]
Looks like we lost the NuttX-apps submodule change. https://github.com/PX4/PX4-Autopilot/pull/20717

**Pull request merged**
