### PR TITLE
Make DO_SET_SERVO work

### PR DESCRIPTION
**Pull request by kpetrykin**
Hello!

My goal was to make the mission command DO_SET_SERVO working with the possibility of triggering the servo with RC switch.

First, I have found that "vmount" module (when enabled) publishes its values to actuator_controls_2 topic all the time. This overwrites all other publications to this topic. That is why DO_SET_SERVO is not working.

I modified "vmount" module so that it would publish only if one of the actuator values were changed by RC. In other cases it stays silent.

Second, I have found that the formula, which translates PWM value from DO_SET_SERVO command parameters to -1..1 range for uORB, does not match the one which translates it back.
[Original formula:](https://github.com/PX4/Firmware/blob/c997159e32f3870c7fd3202877324b76a62ea610/src/modules/navigator/mission_block.cpp#L433) `actuators.control[(int)item.params[0]] = 1.0f / 2000 * -item.params[1];`
[Formula, which translates value back](https://github.com/4ert/Firmware/blob/397522d3813924380c209984b47b05bf743c3037/src/lib/pwm_limit/pwm_limit.cpp#L211): `effective_pwm[i] = control_value * (max_pwm[i] - min_pwm[i]) / 2 + (max_pwm[i] + min_pwm[i]) / 2;`
[New formula](https://github.com/4ert/Firmware/blob/397522d3813924380c209984b47b05bf743c3037/src/modules/navigator/mission_block.cpp#L440): `actuators.control[(int)item.params[0]] = (float)(((float)item.params[1] - (PWM_DEFAULT_MAX + PWM_DEFAULT_MIN) / 2)/((PWM_DEFAULT_MAX - PWM_DEFAULT_MIN) / 2));`

I need to discuss two questions about the formula: 
- to make it work properly we need to get actual "max_pwm[i]" and "min_pwm[i]" into navigator module. I have found a [way to get them](https://github.com/PX4/Firmware/blob/c997159e32f3870c7fd3202877324b76a62ea610/src/drivers/px4fmu/fmu.cpp#L1678), but I don't understand how to use it correctly
- when I tested mission with DO_SET_SERVO command, servo works nice only with 1, 3 and 4 aux outputs. The second one for some reason outputs into first. I think there is something wrong with casting here: `(int)item.params[0]`

I have tested everything with 1.7.3 Firmvare (px4fmu-v2_default), but did not save the flight log.
I will test the last master in a few days.

### CODE REVIEW

**Comment by dagar** [comment]
There are a few problems with this PR, but let's take a step back first.

How do people want/expect DO_SET_SERVO to even work?
screen shot 2018-08-24 at 18 55 07

Which servo does it correspond to? What's supposed to happen in the not entirely unlikely scenario that that PWM channel is already used for something?

What's the real use case for DO_SET_SERVO? Would we be better implementing a couple higher level commands? payload, gripper, etc

If the answer is still DO_SET_SERVO then the right place to implement that command is in the px4io (MAIN pwm) and/or px4fmu (AUX pwm) drivers. Those drivers are the consumers of actuator_controls_{0, 1, 2, 3} and work directly with PWM values.

**Comment by LorenzMeier** [comment]
@4ert We need to separate the different actuator groups for good to make this easier. Could you join the PX4 dev call this week?
https://dev.px4.io/en/contribute/#dev_call

**Comment by 4ert** [comment]
- **How do people want/expect DO_SET_SERVO to even work?**
In our case we want to release a cargo by the mission command. The cargo is locked by the servo which is connected to one of the AUX outputs. We want to use DO_SET_SERVO command to send a PWM signal (parameter 2) to the AUX output from paramter 1.
- **Which servo does it correspond to?**
[As we can see now](https://github.com/PX4/Firmware/blob/bbc0c28c2c07743e489a338677e449a28ab5fd74/src/modules/navigator/mission_block.cpp#L436) the Navigator publish DO_SET_SERVO values to actuator_controls_2 topic. This control group is used to rule gimbal:
image
- **What's the real use case for DO_SET_SERVO? Would we be better implementing a couple higher level commands? payload, gripper, etc**
I think when you use DO_SET_SERVO command - you just want to send an exactly PWM to external servo connected to your controller. If you want to rule gimbal - you will use DO_MOUNT_CONTROL, if you have any flight control mechanizm connected to the AUX - you will want to use some more convenient commands for this.
- **If the answer is still DO_SET_SERVO then the right place to implement that command is in the px4io (MAIN pwm) and/or px4fmu (AUX pwm) drivers. Those drivers are the consumers of actuator_controls_{0, 1, 2, 3} and work directly with PWM values.**
So, I just made a little repair into an existing WORKING mechanizm. For now, Navigator module publishes into an "actuator_controls_2" topic and the px4fmu driver gets values from it and sends to the servos. There's just two things which discourage the process: the vmount driver spamming with its own values to the topic and the formula which translates data wrong. If you switch vmount off ("vmount stop" command into a console) and correct the formula - DO_SET_SERVO will work as expected. And don't forget to load a mixer for AUX outputs.

- **What's supposed to happen in the not entirely unlikely scenario that that PWM channel is already used for something?**
I think, this question is up to the one who builds and sets up the specific device. If you connects some critical stuff to the AUX - edit mixers or just don't use DO_SET_SERVO.

**Comment by 4ert** [comment]
Made a flight, the log is here: https://logs.px4.io/plot_app?log=8fb644ab-1fe4-449a-9b0f-c4656fdae029#Nav-Actuator-Outputs-AUX

**Comment by 4ert** [comment]
@LorenzMeier my speaking english is not very good but I could try to join the devcall

**Comment by maitham1** [comment]
@kpetrykin  I'm currently trying to get this to work I've used your commit. So I have my Pixhawk connected to a servo and I'm trying to get the servo to move within the mavproxy shell by running servo set 1 1000. However the message I keep getting back is that the command was acknowledged but is unrecognised (result:3) . I can get the servo moving using nuttx shell, but I really want to be able to send a mavlink command to set the servo pwm is there any way of doing this?

**Comment by hamishwillee** [comment]
@maitham1 It looks like the  MAV_CMD_DO_SET_SERVO is **set in missions** and handled here: 
https://github.com/PX4/Firmware/blob/master/src/modules/navigator/mission_block.cpp#L424
(FYI @bkueng  this is related to https://github.com/Dronecode/DronecodeSDK/issues/533)

I can't find the message being handled outside of missions. While that does not mean it isn't, the fact that you're getting "unrecognised" is indicative. 

There is quite a bit of discussion above about this. @dagar did the devcall come to any conclusions? Is there a short term recommendation on how people should approach this?

**Comment by hamishwillee** [comment]
@dagar regarding https://github.com/PX4/Firmware/pull/10320#issuecomment-415903772 (your questions) there are some good points there. Below are "in my opinion". 

> Which servo does it correspond to? 

Shouldn't this be defined at the MAVLink/message level by a convention? How about 1-n are the MAIN outputs as labeled on board, and n upwards are the AUX ports, if present? 

> What's supposed to happen in the not entirely unlikely scenario that that PWM channel is already used for something?

IMO things screw up - it is up to the user of this tool to manage contention. See real use case below. 

Do we actually manage contention otherwise? ie does the system check that we don't have multiple control group inputs assigned to the same output?

> What's the real use case for DO_SET_SERVO? 

The real use case is probably the hardware we haven't thought about. Someone has some magic hardware that they want to drive, and a free port. They just want to be able to plug in that hardware and send it a command via MAVLink. They don't want to care about mixers. They are happy to manage contention themselves -  ie they know that nothing else is connected to the port, and if they screw up they screw up.

> Would we be better implementing a couple higher level commands? payload, gripper, etc

We currently have [First Payload](http://dev.px4.io/en/concept/mixing.html#control-group-6-first-payload) which is just a parachute. Yes we should probably define something for a gripper. Not sure it will address the above use case.

I've read http://dev.px4.io/en/concept/mixing.html and I am not 100% confident that my understanding of how these work is complete. I think that control groups are implemented as UORB topics that something can set (ie a controller). A mixer defines what actuators are set and their values based on these inputs. 

So essentially you create a control group so that you can arbitrarily map a specific **type** of command to a physical output. For example to use a parachute you write a handler for it in MAVLink that sets the appropriate control group UORB topic. "Something" in the architecture then takes the mapping in the mixer file and based on that topic input sets the appropriate PWM output. Is that about right?

This is good because your system does not need to know what plugs into the output to implement a parachute or gripper (say). But it does mean that you need a mixer.

Question: Are mixer's additive? Ie I have an airframe which uses the main outputs. I add a parachute. Do I need a completely new mixer file, or can I add my mixer just for my parachute?

You could implement this as a servo control group(s). But would be better if the mapping was transparent (ie no specific mixer required).

**Comment by kpetrykin** [comment]
@maitham1 this PR is generally about mission's DO_SET_SERVO command.
It looks like if you want to pass it through mavlink it would not be handled.
You may experiment with writing your own handler somewhere here: https://github.com/PX4/Firmware/blob/039221fa93303a6840a45c3f8a72580aaaf2d74c/src/modules/mavlink/mavlink_receiver.cpp#L527
Or you may assign an rc trigger for your servo and try to override it with mavlink message, but it is not a good way.
And what do you want to do? What is your case?

**Comment by maitham1** [comment]
@kpetrykin Thanks for getting back to me. I want to simply change pwm output from a script. 
Currently I thought this would be possible via sending the MV_CMD_DO_SET_SERVO using pymavlink, 
it doesn't seem to be implemented, unless i'm missing something (which is highly likely as this is all new to me) but I'm open to other ways?

**Comment by kpetrykin** [comment]
@maitham1 so what is your goal of using servo? What you try to do with this?
And from what you send MAV_CMD_DO_SET_SERVO using pymavlink? Onboard computer?

**Comment by maitham1** [comment]
@kpetrykin I would like run certain tests change servo positions, its a static test so nothings flying. I just want the ability to set servos to specific angles and motors to specific speeds within a python script. I don't intend to use it for flying. Its just for testing.

Sending MAV_CMD_DO_SET_SERVO using pymavlink!

**Comment by kpetrykin** [comment]
So, @dagar, @LorenzMeier - what's with this PR? What could i do to improve it?

**Comment by tubeme** [comment]
Hey @kpetrykin Can you share your mixer that you are using for the AUX channel? I'm trying to follow yur route but cannot make the mixer properly maybe.

**Comment by kpetrykin** [comment]
@tubeme, sure, it's simple:

```
M: 1
O:      10000  10000      0 -10000  10000
S: 2 0  10000  10000      0 -10000  10000

M: 1
O:      10000  10000      0 -10000  10000
S: 2 1  10000  10000      0 -10000  10000

M: 1
O:      10000  10000      0 -10000  10000
S: 2 2  10000  10000      0 -10000  10000

M: 1
O:      10000  10000      0 -10000  10000
S: 2 3  10000  10000      0 -10000  10000
```
To make it work:

- Place a mixer into a /etc/mixers/pass.aux.mix on your pixhawk's SD card
- Create /etc/extras.txt with the folowing command: `mixer load /dev/pwm_output1 /fs/microsd/etc/mixers/pass.aux.mix`

**Comment by GaoGeolone** [comment]
@kpetrykin How to make it work, bro?

**Comment by bys1123** [comment]
Is there any new update?

**Comment by GaoGeolone** [comment]
@kpetrykin I think I have already make it work, thank you~I just want to trigger my servo at a certain position. And by making a change to the AUXMIXER pass file , as well as modifying the Formula in Mission_block.cpp.

**Comment by JamesChooWK** [comment]
Hi @kpetrykin , I want to follow what you have done the flight for example takeoff, go to a waypoint and drop a cargo. Now, I am trying to follow and write a same mixer that you provide. But there are some questions that I want to ask:

Q1) Why do we create a "extrats.txt" file  with a command line "mixer load /dev/pwm_output1 /fs/microsd/etc/mixers/pass.aux.mix" ?
Q2) Where do we place this "extrats.txt" file ? same folder as our mixer file?
Q3) How can we upload the mixer and this "extrats.txt" file into our Pixhawk's SDcard? via QGC?
Q4) If QGC is needed, do we need to place these two file into our Firmware before uploading it? 

Sorry for asking these silly questions. Thanks.

**Comment by hamishwillee** [comment]
@JamesChooWK The Extras.txt is documented here: https://dev.px4.io/master/en/concept/system_startup.html#customizing-the-system-startup

It is used for system startup customisations - basically you're adding the mixer at runtime rather than as part of the firmware build. This is much easier for examples, testing,  and when you're doing something that only applies to your setup. 

You can copy the files onto the card using whatever mechanism you like - ie File explorer on windows. The files need to be present on the SD card before booting PX4. Again, they are not part of firmware, but are loaded as though they were.

**Comment by JamesChooWK** [comment]
@hamishwillee Thanks for answering my questions.  I manage to upload the mixer and Extras.txt file into MicroSD card. 

But when I tried to push a DO_SET_SERVO command to pixhawk using mavros services("mavros/mission/push") by assigning "command=183", it return this error (" WP: upload failed: command is not supported")

I am not sure whether I use the DO_SET_SERVO in ("mavros/mission/push") correctly or I have to do it in ("mavros/cmd/command") or I have to use mavlink ?

I am using MAVROS and PX4 native flight stack.

**Comment by hamishwillee** [comment]
@JamesChooWK Did you incorporate this PR? It has the code that is supposed to support  DO_SET_SERVO

**Comment by JamesChooWK** [comment]
@hamishwillee  I am sorry I do not incorporate this PR, but I will do it. If I uses the new code, does it means that I have to build the firmware and load to pixhawk or I can copy the files and paste it into the SDcard like the mixer?
I'm sorry to ask so many questions, I'm a newbie to these sort of things.

**Comment by hamishwillee** [comment]
@JamesChooWK So the point of the PR is that the message doesn't work on PX4 right now (as far as I know - I'm guessing based on what I see here).
So yes, you will have to build PX4 firmware with the changes in this code and upload it as "custom firmware". There are conflicts between the changes and master branch, so you might need to do some coding to integrate them.

Also note this PR did not get accepted yet - so there is no guarantee that even if you do this it will work.

**Comment by JamesChooWK** [comment]
@hamishwillee  I will try to amend the code and build the firmware, Thanks for the time answering my questions. Cheers.

**Comment by kpetrykin** [comment]
@JamesChooWK this PR does not contain code to accept DO_SET_SERVO from external sourses, it's about command from mission.
If you want to use external call of this command, you need to add a code to process a corresponding mavlink message.

**Comment by JamesChooWK** [comment]
@hamishwillee  I will try to amend the code and build the firmware, Thanks for the time answering my questions. Cheers.

**Comment by kpetrykin** [comment]
@JamesChooWK you could just build the branch: https://github.com/kpetrykin/Firmware/tree/make_do_set_servo_working
And don't code at all for integration.

**Comment by JamesChooWK** [comment]
@Kpetry
Many thanks to reply my questions, I will download and try on a coming flight test.

**Comment by julianoes** [comment]
What's the state here? Would be nice to get this in.

**Comment by kpetrykin** [comment]
@julianoes I need to check what's going on with servos on 1.9.1

**Comment by kpetrykin** [comment]
I rebased my commits to the last master, but I still need to perform some flight tests.
And also fix int-float conversions.

**Comment by kpetrykin** [comment]
I found that we need to publish to different actuator_control groups depending on vmount enable or not. Maybe in some other cases too.

**Comment by kpetrykin** [comment]
I rewrote the code, so now DO_SET_SERVO is being written to [Control Group #3](http://dev.px4.io/master/en/concept/mixing.html#control-group-3-manual-passthrough) because it is (as far as I can see) a default group to control AUX'es. At least at "Generic Quadcopter".
I changed an "rc_update" module to make it publish to "actuator_controls_3" topic only if inputs have been changed. It prevents from jamming other publishers.
Also I added a processing of DO_SET_SERVO command to mavlink_receiver so it is possible to send it from QGC via [such a custom widget](https://gist.github.com/kpetrykin/a4b26c666047881f5d0698155ff4df8c), for example.

**Comment by bys1123** [comment]
Looks like maybe you "git add" all files not just you manually changed files, so there are lots Conflicting.

**Comment by kpetrykin** [comment]
Rebased to the last master

**Comment by bys1123** [comment]
Thanks, but SITL test is failed, seems the drone can't fly well after these change.
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-10320/16/pipeline

**Comment by kpetrykin** [comment]
Is it possible to see the log of this failed "mc_safe_landing"?

**Comment by kpetrykin** [comment]
It looks like there is a problem in obstacle avoidance system:
`WARN  [FlightTaskUtility] Obstacle Avoidance system failed, loitering`

**Comment by bys1123** [comment]
@kpetrykin It's works! I guess you can remove [WIP] on the title now.
Can you help review this, thanks! @bkueng

**Comment by kpetrykin** [comment]
@bkueng what about a review?

**Comment by bys1123** [comment]
@dagar

**Comment by suraj2596** [comment]
This is a great thread. Just to confirm, @kpetrykin's code will now allow users to command the PWM on any AUX and MAIN pins through MAVROS outside a mission? Or are there any caveats/constraints I should be aware of? Thanks!

**Comment by kpetrykin** [comment]
@suraj2596, no, my code is only about 4 AUX'es (not MAIN outputs) which could be controlled through [Control Group #3](http://dev.px4.io/master/en/concept/mixing.html#control-group-3-manual-passthrough).
I made the following logic:

- DO_SET_SERVO command to the "first" servo will be sent to the 5th channel in Control Group 3 (aux 1)
- "Second" servo will be sent to 6th channel (aux 2)
- "Third" will be sent to 7th (aux 3)
- And "fourth" will be sent to 4th ("flaps" or "mode switch")

**Comment by bkueng** [comment]
Sorry for the long discussion here, but I think the architectural questions are still open.

The first problem I see is that the [MAV_CMD_DO_SET_SERVO](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_SET_SERVO) message is not well-defined, and not generic enough: it suggests the instance specifies the hardware pin, but there is no way to distinguish different outputs (MAIN vs AUX). It also directly specifies PWM, which is not future-proof.

It suggests that it is applied on the lowest level, bypassing everything, including mixer. This is not great for several reasons (conflicts and safety for instance). Only from a user-perspective it is easy to use.

So I prefer a solution that goes through the mixer. There we have different options:
- adding a new actuator control group
- using an existing one. The closest one I see as well is `Control Group #3` (implemented here). I would however implement it differently: rc_update is the only publisher (besides MAVLink via set_actuator_control_target). So we can handle `MAV_CMD_DO_SET_SERVO` commands in `rc_update`, and do fine-grained deconfliction/switching between sources in there (and maybe switch via parameter).
Since most airframes already configure RC passthough, no mixer changes from a user would be required.
Overall it is also quite simple to implement.

Drawbacks with that is that there are different scalings applied, so it might be better to add a new mavlink command using normalized values. Then the PWM config params can be used to configure limits.

Thoughts?

**Comment by suraj2596** [comment]
Future proof

Hey @bkueng,

I understand your perspective on conflicts and user safety. Going through this thread and other forums, it looks like some users, being aware of the fact that things could go south, want the ability to set the PWMs on pins for doing something additional.

Especially the research community where we do all kinds of bizarre things like mounting arms, grippers and what not. And in my case, the ability to control the ESCs through MAVROS like @kpetrykin mentioned [here](https://github.com/PX4/Firmware/pull/10320#issuecomment-419041625)

And Pixhawk is a beautiful piece of hardware with great firmware and community support, except when it comes to PWMs :P Currently. there is a small window through which a user can control the PWM(should pass safety checks, should be inside a mission, etc). Their motivation to do so could be something I haven't completely understood yet but doesn't fit the needs of many.

To conclude, we need more documented ways to set the DO_SET_SERVO command.

**Comment by Katawann** [comment]
Hi @kpetrykin, 
Thanks for the great work !

If I use this PR I will be able to control the servo output using the command MAV_CMD_DO_SET_SERVO ? Or it is just in for mission ?

before I try you PR I would like to make sure if it's what I need. My use case is a drone for spraying crops. The pump is controlled by a servo output (on/off with RC passthrough yet) but I need to control this servo with a companion computer

**Comment by kpetrykin** [comment]
Hello, @Katawann!

Yes, with this PR you could control your servo with MAV_CMD_DO_SET_SERVO command.

**Comment by suraj2596** [comment]
@kpetrykin have you tested the rate at which pwm can be commanded? If it's high, I'm planning to use it for commanding ESCs directly.

**Comment by kpetrykin** [comment]
Hello, @suraj2596!

No, I haven't tested the system that way. 
But I think it could be possible.

**Comment by coderkalyan** [comment]
@bkueng @kpetrykin what's the progress on this, anything I can do to help?

**Comment by hamishwillee** [comment]
There is no progress on this. 

1.  I think we should completely revisit the MAVLink message as discussed by @dagar  in https://github.com/PX4/Firmware/pull/10320#issuecomment-415903772 
    - Currently the message is just an id, but there is no way to tell the mapping to a particular output - main pwm, aux pwm, uavcan, whatever. Doesn't matter if you're playing with hardware, but to have repeatable results in missions this has to be very clear. 
    - Would be good to be able to query what servos can be set.
    - Arguably you should never be just setting a servo in a message. You should be setting a particular payload (say, a gripper) and the flight stack should map to the hardware and/or tell you that it isn't supported.

2. If we do support servos, then we should evaluate the suggestion by @bkueng : https://github.com/PX4/Firmware/pull/10320#issuecomment-561119536

@mrpollo @bkueng this looks to me like something that has rotted a bit long. Do you think you guys could progress it in the dev call? 

We could certainly get help from people to work on this but the core team need to provide direction on how we want it to work. i.e. do we provide messages for more payloads via mavlink? Do we support this generic case, and if so how?

**Comment by coderkalyan** [comment]
@hamishwillee just a thought - I posted a message in the #mavlink channel on the Slack, about an idea I had for a "payload protocol". Here it is for reference:

Hey guys, just an idea - now that we have an updated gimbal protocol which includes a gimbal manager, what would you guys think about adding a payload protocol with a payload manager? This would abstract out managing payloads so autonomous missions don't have to manually set control groups and/or servo PWM values? I was thinking this could include standard payload commands such as parachute control, controlling an actuator that releases a payload, flying the UAV to a place where payload can be dropped/activated (there are already messages for this, but they are strewn about), and maybe support for controlling a motorized winch? High level messages could be sent to the manager, which could connect to different payloads - servos, winch controller, parachute. Preferably, we would also have some sort of extensibility layer or maybe even just passthrough to be able to add custom payload configurations? 

What do you think?

**Comment by hamishwillee** [comment]
@coderkalyan I commented on slack. In summary, probably not. But I don't want to discuss it here because I really really don't want people to lose track of https://github.com/PX4/Firmware/pull/10320#issuecomment-600898657

**Comment by hamishwillee** [comment]
@bkueng Who would I have to kill to get an implementation of this on your job queue? Yet another query on how to do this on slack today.

**Comment by coderkalyan** [comment]
@hamishwillee I'd be willing to take a look at this if someone could give me a couple pointers as to what needs to be done!

**Comment by coderkalyan** [comment]
Ok, I'm going to create a new PR that just maps the servo instance number from DO_SET_SERVO to actuator_group_6. It will still require the mixer to be setup as shown in https://dev.px4.io/master/en/concept/custom_mixer_payload.html, so there isn't any bypassing mixer or related weird junk.

**Comment by hamishwillee** [comment]
@coderkalyan I'm going to connect you do Beat. Wait before starting. Just composing my thoughts. .

**Comment by hamishwillee** [comment]
@bkueng We have a volunteer to work on this ^^^ @coderkalyan . Can you outline the solution you propose for this - or would it be best for you guys to set up a meeting or discuss in the dev call?

The architectural issue [you raised above](https://github.com/PX4/Firmware/pull/10320#issuecomment-561119536) is that [MAV_CMD_DO_SET_SERVO](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_SET_SERVO) isn't really fit for purpose.

This has two fields, and two problems:
- servo instance number - it is not clear how these map to the physical hardware/bus - ie MAIN, AUX, UAVCAN
- pwm value. - This only works if your system uses PWM values, and you know the range. 

We can make a best effort to clarify that message better - e.g. we could state that that instance values of 1-8 map to MAIN and 9-16 map to AUX. UAVCAN not supported.

Ultimately though, we should probably create a new message. Any thoughts on how we would do that? I'd be tempted by

- bus (enum) 0: MAIN PWM, 1 AUX PWM, 2 UAVCAN, 3 ...
- instance number in bus (uint), indexed  from1 - whatever
- Value: A scaled range from -100 to +100% that can be indicated as "invalid". Perhaps a float with NaN indicating "ignore".

**Comment by coderkalyan** [comment]
@hamishwillee @bkueng I agree that a new message would be far less ambiguous, and allow a more flexible method of control. Maybe something on the lines of MAV_CMD_DO_SET_ACTUATOR or such, since this applies not just to servos but to generic auxiliary actuators (anything thats not part of main flight control and is not already part of its own setup, like gimbal). Just a few considerations that I'm bringing to the table:
1. > 0: MAIN PWM

    Should control of the MAIN ports be allowed? I guess that there are use cases for that, but it seems like a very hazardous thing to do.
2. I don't think we want to bypass the mixers/control groups. On that note, should the command be restricted to a specific hard-coded control group (like #6 payload) or do we give the user more flexibility in that regard? I'm worried giving too much flexibility might leak implementation details but maybe not.
3. Following up from the previous point, does the bus need further specification? Such as which control group, or details about what the published UAVCAN message should look like?
4. What happens if the user wants to control 2 or more actuators at "exactly" the same timing, possibly as part of a more complex payload where 2 servos have to be synchronized? The cleanest solution I can think of to solve this problem is to have an (optional) field be a "cookie", so that the user could setup/queue multiple actuator controls in multiple messages, then trigger them all at once.
5. I do want to keep in mind that we don't want to go outside the scope of the original intent - to make DO_SET_SERVO work. However, there are more complex payload actions that could require more messages - i.e. the queuing system mentioned above, or precise timed offsets for different actuators (this isn't just in theory, btw; my use case's payload would probably use one or more of these features). Again, I should probably just focus on implementing a single actuator control message for this PR. But if anyone has any thoughts on these more advanced features, I'd love to hear them.

Side note: I am actually quite interested in being able to use UAVCAN to control my actuators. It didn't come to mind before @hamishwillee brought it up, but in my use case, even with a PWM value (which is currently mapped to a mixer connected to an RC controller) I have another microcontroller on the receiving end which is reading the PWM values and deciding what to do, so UAVCAN seems like a good choice. I haven't used UAVCAN before though, so any clarification/pointers on how this would work are appreciated!

**Comment by hamishwillee** [comment]
@coderkalyan I'm keeping quite until @bkueng has a chance to talk. My 2 bits though:
1. I hadn't thought what it would be called, but MAV_CMD_DO_SET_ACTUATOR sounds reasonable.
1. My preference is that we allow any output to be touched in the message, but the system reject a command that sets an output that already has any assigned mixer outputs. Don't know if that is possible.

**Comment by bkueng** [comment]
Awesome, thanks @coderkalyan. I imagine something like this:
- a new mavlink command, MAV_CMD_DO_SET_ACTUATOR_AUX:
  -  param1: aux1 [-1,1], nan=ignore
   - param2: aux2 [-1,1], nan=ignore
   - ...
- it specifically controls the AUX channels in `Control Group #3`. So it goes through the mixer, and thus can be used for UAVCAN as well for example. And by using group 3, we simplify the setup, as most mixers already have it configured, so most users can just use it.
  This means it's handled together [with RC](https://github.com/PX4/Firmware/blob/master/src/modules/rc_update/rc_update.cpp#L531), and needs deconfliction. I imagine as a parameter:
  - auto: use the last changing input: this allows to send a mavlink command, but to override later via RC and vice versa.
  - RC only: ignore mavlink commands
  - mavlink only: ignore RC

You're limited to 3 channels, but I think that is enough for the majority of the use-cases. Also I think if you need more advanced logic, you're better off adding some code to handle that specifically.

Let me know if you have questions, you can also ping me on slack directly.

**Comment by coderkalyan** [comment]
Thanks for the clarification @bkueng! Seems reasonable, I'll get to work.

**Comment by hamishwillee** [comment]
Hi @coderkalyan ,
Just for my interest, how is this coming along [now](https://github.com/mavlink/mavlink/pull/1414) you have the new [MAV_CMD_DO_SET_ACTUATOR](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_SET_ACTUATOR) message?

**Comment by coderkalyan** [comment]
@hamishwillee It was brought to my attention that my PR for DO_SET_SERVO was in conflict with another open PR that @dayjaby is working on. However I haven't had a chance to look at what exactly is conflicting and sort that out yet.

**Comment by hamishwillee** [comment]
Thanks. I hope you can resolve this with @dayjaby and move forward!

**Comment by LorenzMeier** [comment]
Thanks for your earlier contribution. Unfortunately as the project has overall evolved quite a bit, this change doesn't apply any more. Closing stale pull requests like this one is part of us working aggressively to bring down the PR review time so that we will be able to merge or reject PRs in the future in a much more timely fashion.

**Comment by coderkalyan** [comment]
FYI @kpetrykin #16758 *should* cover the same intention as this PR.

**Comment by ahmedfarouk99** [comment]
@kpetrykin @hamishwillee @bkueng 
here is my setup:
1-i'm using f450 generic quad-rotor with pixhawk-4 and px4 firmware
2-i'm using aux pwm instead of main to decrease letancy according to px4 documentation
3- i connected my 4 motors to first 4 pwm aux pins
4-  i changed parameter to use actuator tab instead of motor tab and i assigned the 4 motors to pwm aux (1-4)
5- i tested my f450 and everthing works great
6- i need to use an external servo, so i assigned it to pwm aux pin-5 and 5v external battery
7- i added servo-1 in the actuator tab as pwm aux-5
8- once i added this servo , it appears in the scroller tab next to my 4 motors used ,and i'm able to manually control the 4 motors and the servo through the scroller to check if they are working good, and all of them were working good
9- i needed to assign servo-1 used to rc channel 5 , so i modified " rc_map_aux5=channel 5" ,but when i used rc channel 5 , nothing happened....
can anyone help me please...
thanks in advance

**Comment by hamishwillee** [comment]
@ahmedfarouk99 YOu have necrobumped and old closed issue. I don't look at those. If you have a technical support issue, ask on the support forums. If you have a bug, raise your own bug report. You should try  MAV_CMD_DO_SET_ACTUATOR instead though, it works.

**Pull request closed without merging**
