### PR TITLE
EKF2: constant position aiding

### PR DESCRIPTION
**Pull request by bresch**
### Solved Problem
When on a catapult, the vehicle might need to throttle up before triggering the catapult. This makes the "at rest" flag false (and this is correct) and the ekf goes into inertial dead-reckoning if no other aiding source is active. 

### Solution
Since we know that the vehicle doesn't move while on a catapult, tell the ekf that that the vehicle stays at a constant position. The EKF can then start a "valid" fake position fusion. Then, if a valid fake position is fused and that we expect to have airspeed fusion in air, the local position can remain valid too.

### Changelog Entry
For release notes:
```

New parameter: -
Documentation: -
```

### Test coverage
unit test

### CODE REVIEW

**Comment by haumarco** [comment]
Do we need _constant_pos_ and _vehicle_at_rest_?
Why dont we include the _constant_pos_ condition in the land detector and make _at_rest_ also dependent on the _launch_detection_state_?

**Comment by bresch** [comment]
> Why dont we include the constant_pos condition in the land detector and make at_rest also dependent on the launch_detection_state?

Because when the vehicle is armed and throttling up on a catapult it's not exactly at rest; it shakes and fusing the zero gyro updates or zero velocity updates could be harmful

**Review by haumarco — APPROVED** [review]

**Comment by dagar** [comment]
Overall looks good, but why do we need both `valid_fake_pos` and `constant_pos`? To be honest `valid_fake_pos` sounds like a oxymoron.

**Comment by bresch** [comment]
> Overall looks good, but why do we need both valid_fake_pos and constant_pos? To be honest valid_fake_pos sounds like a oxymoron.

`constant_pos` is an input status while `valid_fake_pos` is when the fusion is active. I called it `valid_fake_pos` because it's using all the functions of `fake_pos` and the same aid_src message. I agree that the name sounds a bit weird but maybe the best option would be to change the name "fake pos" to something else (constant position?).

**Comment by bresch** [comment]
I'll merge it as it works nicely in practice but we can still discuss about the name and I'll be happy to change it.

**Comment by dagar** [comment]
Yes renaming to "constant position" (and "constant height") sounds much clearer.

**Pull request merged**
