### PR TITLE
update world_magnetic_model to latest

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Review by Sidzeppelin95 — DISMISSED** [review]

**Comment by Sidzeppelin95** [comment]
hygrometer*

**Comment by junwoo091400** [comment]
Just curious, I couldn't find relevant workflow / Jenkins for this update. Do you have a custom script? How can we validate that this new change is valid?

Also, how come is the commit coming from the @PX4BuildBot :exploding_head:

**Comment by mcsauder** [comment]
The WMM (world magnetic model) is updated every 5 years. However, it seems to be changing much more rapidly in the past decade even though it is still being reported as updated every 5 years: https://www.ncei.noaa.gov/products/world-magnetic-model

This is actually something worth paying attention to.

**Review by mcsauder — APPROVED** [review]

**Comment by dagar** [comment]
> Just curious, I couldn't find relevant workflow / Jenkins for this update. Do you have a custom script? How can we validate that this new change is valid?
> 
> Also, how come is the commit coming from the @PX4BuildBot exploding_head

Jenkins is updating a lot of these things regularly, ensuring submodules are pointed to the tip of a branch, WMM updated, different things with board configs, etc. http://ci.px4.io/job/PX4_misc/

Updating the world magnetic model this often is unnecessary, but it's no work on our part and I like to keep it close enough that the diff is declination table is tiny.

**Comment by junwoo091400** [comment]
> Jenkins is updating a lot of these things regularly, ensuring submodules are pointed to the tip of a branch, WMM updated, different things with board configs, etc. http://ci.px4.io/job/PX4_misc/

Ooh interesting! I can tell that the Jenkins code however doesn't live in the PX4-Autopilot repository. Could we maybe document this mechanism (where the Jenkins is configured & how it gets triggered, etc) in this PR?: https://github.com/PX4/PX4-user_guide/pull/2284

**Comment by dagar** [comment]
> > Jenkins is updating a lot of these things regularly, ensuring submodules are pointed to the tip of a branch, WMM updated, different things with board configs, etc. http://ci.px4.io/job/PX4_misc/
> 
> Ooh interesting! I can tell that the Jenkins code however doesn't live in the PX4-Autopilot repository. Could we maybe document this mechanism (where the Jenkins is configured & how it gets triggered, etc) in this PR?: [PX4/PX4-user_guide#2284](https://github.com/PX4/PX4-user_guide/pull/2284)

As much as possible I don't put any of the actual logic in Jenkins, it's just running a script that any of us can, but doing it automatically every night. For example for WMM it's simply running `fetch_noaa_table.py` (https://github.com/PX4/PX4-Autopilot/blob/main/src/lib/world_magnetic_model/fetch_noaa_table.py) in the `src/lib/world_magnetic_model/` directory and if there's any diff it pushes a branch.

Jenkins has access to things like PX4Buildbot git credentials (so it can push these branches), and more recently the NOAA service started requiring a key.

**Comment by junwoo091400** [comment]
> As much as possible I don't put any of the actual logic in Jenkins, it's just running a script that any of us can, but doing it automatically every night.

Yep, makes sense. Thanks for the clarification! However, so are these scripts somehow stored in the server only (not in this repository or anywhere else) :thinking: 

Any reason why we have https://github.com/PX4/PX4-Autopilot/blob/main/Jenkinsfile, and that script in the server separately?

**Pull request merged**
