### PR TITLE
new Ignition Gazebo simulator architecture

### PR DESCRIPTION
**Pull request by dagar**
- much simpler direct interface using Ignition Transport 
 - in tree models and worlds
 - control allocation output configuration, no more magic actuator mapping to mavlink and back
 - currently requires no custom Gazebo plugins (keeping things as lightweight and simple as possible)

Co-authored-by: Jaeyoung-Lim <jalim@ethz.ch>

``` Console
$ make px4_sitl_ign ignition_x3
```

``` Console
$ make px4_sitl_ign ignition_x4
```

### CODE REVIEW

**Comment by julianoes** [comment]
How do I install the requirements? Are there binaries, or did you build it yourself and install system-wide?

**Comment by julianoes** [comment]
I needed this change:

```
diff --git a/src/modules/ignition_simulator/CMakeLists.txt b/src/modules/ignition_simulator/CMakeLists.txt
index c16cadb56c..53e083cd68 100644
--- a/src/modules/ignition_simulator/CMakeLists.txt
+++ b/src/modules/ignition_simulator/CMakeLists.txt
@@ -35,8 +35,8 @@ add_compile_options(-frtti -fexceptions)
 #add_compile_options(-fexceptions)
 
 # Find the Ignition_Transport library
-find_package(ignition-transport10 QUIET REQUIRED OPTIONAL_COMPONENTS log)
-set(IGN_TRANSPORT_VER ${ignition-transport10_VERSION_MAJOR})
+find_package(ignition-transport8 QUIET REQUIRED OPTIONAL_COMPONENTS log)
+set(IGN_TRANSPORT_VER ${ignition-transport8_VERSION_MAJOR})
 
 px4_add_module(
        MODULE modules__ignition_simulator
```

Then it failed missing `ign`.

```
SITL ARGS
sitl_bin: /home/julianoes/src/upstream/PX4-Autopilot/build/px4_sitl_ign/bin/px4
debugger: none
program: ignition
model: x4
world: empty
src_path: /home/julianoes/src/upstream/PX4-Autopilot
build_path: /home/julianoes/src/upstream/PX4-Autopilot/build/px4_sitl_ign
Ignition Gazebo
/home/julianoes/src/upstream/PX4-Autopilot/Tools/sitl_run.sh: line 202: ign: command not found
gmake[4]: *** [platforms/posix/CMakeFiles/ignition_x4.dir/build.make:70: platforms/posix/CMakeFiles/ignition_x4] Error 127
gmake[3]: *** [CMakeFiles/Makefile2:64273: platforms/posix/CMakeFiles/ignition_x4.dir/all] Error 2
gmake[2]: *** [CMakeFiles/Makefile2:64280: platforms/posix/CMakeFiles/ignition_x4.dir/rule] Error 2
gmake[1]: *** [Makefile:26891: ignition_x4] Error 2
make: *** [Makefile:230: px4_sitl_ign] Error 2
```

I'm on Linux Mint 21 (based on Ubuntu 22.04).

**Comment by dagar** [comment]
I'll update it to be more flexible with the ignition transport version.

**Comment by henrykotze** [comment]
Is there a roadmap for getting Ignition Gazebo up and running as the default sim? Or a list for todo's for getting it up and running?

**Comment by Jaeyoung-Lim** [comment]
@henrykotze https://github.com/PX4/PX4-Autopilot/issues/20046

**Review by Jaeyoung-Lim — APPROVED** [review]

**Comment by dagar** [comment]
I have a lot more I'd like to do here, but I think this is good enough to get in and then continue incrementally.

**Pull request merged**
