### PR TITLE
NuttX 10.3+ upgrade

### PR DESCRIPTION
**Pull request by dagar**
Co-authored-by: Peter van der Perk <peter.vanderperk@nxp.com>

### CODE REVIEW

**Comment by dk7xe** [comment]
Tests have been executen on R6 rover with NXP FMUK66
https://logs.px4.io/plot_app?log=1875fb1a-9112-474d-a795-4d7f5ab50077
https://review.px4.io/plot_app?log=4b2750c8-481b-4fe7-b509-f1aba15722cf
https://review.px4.io/plot_app?log=8762d40b-67b2-48f2-9af7-b087168dd250

**Comment by dagar** [comment]
Thanks for the testing @dk7xe

**Comment by dagar** [comment]
A big piece this is still missing is @davids5's network monitor changes in NuttX-apps.
https://github.com/PX4/NuttX-apps/commit/0d06c1cb836e597d5c54728963e6f412b21775ff

**Comment by PetervdPerk-NXP** [comment]
David wrote
> The first one may be now supported. I was not willing to do IPV6.
So it might be already fixed in upstream we only need to test it then.

**Comment by dk7xe** [comment]
Test today with ID10 testdrone with Pixhawk4 FMU, 2nd GPS on UCANS32K146 (dronecan)
https://logs.px4.io/plot_app?log=4bc2705c-86d5-4988-a2d0-5508b9c8ce21
https://logs.px4.io/plot_app?log=646f1cd0-c2f8-4fed-b50c-f0274893407a

**Comment by dk7xe** [comment]
> David wrote
> 
> > The first one may be now supported. I was not willing to do IPV6.
> 
> So it might be already fixed in upstream we only need to test it then.

Ethernet i can test on the R6 test rover if you can provide me the FW again @PetervdPerk-NXP

**Comment by davids5** [comment]
netman has to be tested in fall back mode

**Comment by PetervdPerk-NXP** [comment]
@davids5 I've just backported your netmon changes since it applied (mostly) cleanly. 
So I think we're pretty much done, unless someone wants to go over something?

**Comment by davids5** [comment]
Ok I have tested this on V2, V5, V5X and V6X - it looks to be OK with the changes I pushed. 
@dagar we do need to get the `px4_firmware_nuttx-10.4.0+` version labels dropped and make sure the `ver` command reports the correct value from the .version file

**Review by davids5 — DISMISSED** [review]

**Review by PetervdPerk-NXP — APPROVED** [review]

**Comment by davids5** [comment]
@PetervdPerk-NXP Would you please have a look at the raspberrypi_pico build.

**Comment by PetervdPerk-NXP** [comment]
@davids5 Raspberry Pi Pico got some major breaking driver changes in upstream which needs to be replicated in the PX4 raspberry pico board definition. Maybe the original author of the board can fix them afterwards.

**Review by PetervdPerk-NXP — APPROVED** [review]

**Comment by AlexKlimaj** [comment]
It looks like this isn't working on the cannodes. Stuck in a boot loop.
```
NuttShell (NSH) NuttX-10.2.0
nsh> ERROR [PX4_MTD] failed to locate spi bus
ERROR [PX4_MTD] mtd failure: -6 bus 2 address 0 class 1
nsh: sysinit: fopen failed: No such file or directory
nsh: set: command not found

NuttShell (NSH) NuttX-10.2.0
nsh>
```

**Review by AlexKlimaj — CHANGES_REQUESTED** [review]
Appears to not work on cannodes. Stuck in bootloop.

**Comment by PetervdPerk-NXP** [comment]
```
NuttShell (NSH) NuttX-10.2.0
nsh> ERROR [PX4_MTD] failed to locate spi bus
ERROR [PX4_MTD] mtd failure: -6 bus 2 address 0 class 1
nsh: sysinit: fopen failed: No such file or directory
nsh: set: command not found

NuttShell (NSH) NuttX-10.2.0
nsh>
```

NuttX brings in many kconfig default changes looking at that output I think set command got disabled.
Could you try to disable CONFIG_NSH_DISABLE_SET symbol?

Regarding version number I think this is solved by pushing the NuttX tags to the PX4/NuttX repo.
@davids5 do you know more about this mechanism?

**Comment by AlexKlimaj** [comment]
> ```
> NuttShell (NSH) NuttX-10.2.0
> nsh> ERROR [PX4_MTD] failed to locate spi bus
> ERROR [PX4_MTD] mtd failure: -6 bus 2 address 0 class 1
> nsh: sysinit: fopen failed: No such file or directory
> nsh: set: command not found
> 
> NuttShell (NSH) NuttX-10.2.0
> nsh>
> ```
> 
> NuttX brings in many kconfig default changes looking at that output I think set command got disabled. Could you try to disable CONFIG_NSH_DISABLE_SET symbol?
> 
> Regarding version number I think this is solved by pushing the NuttX tags to the PX4/NuttX repo. @davids5 do you know more about this mechanism?

It doesn't look like CONFIG_NSH_DISABLE_SET is enabled on any of the builds.

**Comment by PetervdPerk-NXP** [comment]
>It doesn't look like CONFIG_NSH_DISABLE_SET is enabled on any of the builds.

When I run `make ark_cannode menuconfig` and search for `NSH_DISABLE_SET`
It says it's enabled, thus you've to disable the `NSH_DISABLE_SET` key so that the `set` command is available.
Yeah it's confusing but that's unfortunely how the NuttX config works

**Comment by davids5** [comment]
@AlexKlimaj - did the resolve all your issues?

**Comment by AlexKlimaj** [comment]
> @AlexKlimaj - did the resolve all your issues?

I think it did. I can't speak for other manufacturers cannodes though. They are probably not functional.

**Comment by PetervdPerk-NXP** [comment]
I tried to catch as most of the boards configs automatically through some regexes but it could still be that some are missed.

**Comment by davids5** [comment]
@dagar - v5 stack check is now running

**Comment by AlexKlimaj** [comment]
@dagar 
Current main on the ARKV6X, ARK GPS, and ARK Flow.
https://review.px4.io/plot_app?log=427353c5-6d71-43a5-9c2a-c5b3da6c3fc4

This PR rebased on current main. Same setup.
https://review.px4.io/plot_app?log=3bd7feec-3f4d-4497-acb0-d4e0be1ba72c

**Comment by AlexKlimaj** [comment]
https://review.px4.io/plot_app?log=590cca04-5afa-4d6e-8763-4a655dc0da26

**Comment by davids5** [comment]
> https://review.px4.io/plot_app?log=590cca04-5afa-4d6e-8763-4a655dc0da26

Any Issues or comments?

**Comment by AlexKlimaj** [comment]
> > https://review.px4.io/plot_app?log=590cca04-5afa-4d6e-8763-4a655dc0da26
> 
> Any Issues or comments?

Nothing seems different from current main. @dagar can inspect the perf counters to see if anything stands out.

**Review by AlexKlimaj — APPROVED** [review]

**Comment by dk7xe** [comment]
@dagar - Daniel when can we expect that being merged?

**Comment by dagar** [comment]
> @dagar - Daniel when can we expect that being merged?

Still verifying a few things, but I'll bring it in early this week if there are no surprises.

**Comment by dk7xe** [comment]
Thank you!

**Comment by dk7xe** [comment]
> > @dagar - Daniel when can we expect that being merged?
> 
> Still verifying a few things, but I'll bring it in early this week if there are no surprises.

Hi - @dagar - Daniel, any update on that? ..and be aware of the guy in front of your door ;)

**Comment by dagar** [comment]
Finally bringing this in, thanks everyone.

**Comment by dagar** [comment]
We missed that `raspberrypi_pico_default` is broken, is anyone in a position to get it updated/fixed quickly?

**Comment by vxj9800** [comment]
> > We missed that `raspberrypi_pico_default` is broken, is anyone in a position to get it updated/fixed quickly?
> 
> @vxj9800 I would image you would be best suited for this 🤔

Sure. I'll take a look at it.

**Comment by vxj9800** [comment]
> We missed that `raspberrypi_pico_default` is broken, is anyone in a position to get it updated/fixed quickly?

@dagar A quick fix so far is to add an empty "Make.defs" file at PX4-Autopilot/boards/raspberrypi/pico/nuttx-config/src/Make.defs since the build system is looking for this file for some reason. I am not sure why this is the case since the build system does not need this file for other boards. Please let me know if you have any comments on how to resolve this issue permanently.

**Pull request merged**
