### PR TITLE
The PX4 cannode bootloader resurrection 

### PR DESCRIPTION
**Pull request by davids5**
This makes the uavcan bootloader that was added back in tree functional.

Place the image on SD card in `/fw` folder 
image

uavcan start
uavcan start fw

plug in GPS. 

This is what the lights mean.

---------------------------------------------LED  --  R  ------       G  -------      B     (blink freq in Hz)
image

### CODE REVIEW

**Comment by dagar** [comment]
There's an issue getting stuck in the bootloader, but we can go through it tomorrow.

Overall things are working though (GPS, magnetometer, barometer).

``` Console
update: 1s, num topics: 10
TOPIC NAME          INST #SUB RATE #Q SIZE
sensor_baro            0    1   73  1   32
sensor_gps             0    1    5  1  104
sensor_mag             0    1   97  4   48
```

``` Console
nsh> work_queue status

Work Queue: 2 threads                        RATE        INTERVAL
|__ 1) wq:SPI1
|   |__ 1) ms5611                         97.7 Hz        10233 us
|   \__ 2) rm3100                         97.7 Hz        10235 us
\__ 2) wq:uavcan
    \__ 1) uavcannode                    207.3 Hz         4823 us (10000 us)
```

``` Console
nsh> top
 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE FD
   0 Idle Task                  305936 92.166   192/  512   0 (  0)  READY  3
   1 hpwork                          0  0.000   332/ 1268 249 (249)  w:sig  3
   2 lpwork                          0  0.000   852/ 1620  50 ( 50)  w:sig  3
   3 init                            0  0.000  1524/ 2612 100 (100)  w:sem  3
   4 wq:manager                      0  0.000   420/ 1260 255 (255)  w:sem  3
  22 top                           105  1.479  1468/ 4084 237 (237)  RUN    3
  12 gps                            23  0.320   932/ 1684 205 (205)  READY  4
  14 wq:SPI1                       198  2.721   856/ 2340 253 (253)  w:sem  3
  18 wq:uavcan                     228  3.113  2092/ 3004 236 (236)  READY  3

Processes: 9 total, 4 running, 5 sleeping, max FDs: 12
CPU usage: 7.63% tasks, 0.20% sched, 92.17% idle
Uptime: 326.422s total, 305.937s idle
nsh>
nsh> free
             total       used       free    largest
Umem:       119584      44816      74768      74656
Prog:       524288     524288          0          0
```

**Review by dagar — APPROVED** [review]

**Comment by mrpollo** [comment]
Are all the TODOs from #16360 addressed by this PR? are there any unlisted next-steps?

**Comment by davids5** [comment]
> Are all the TODOs from #16360 addressed by this PR? are there any unlisted next-steps?

Good point - they are what we are working on and should be moved here.

**Comment by gitfishup** [comment]
@davids5 Could you please tell me how to update the CAN GPS firmware?

**Comment by davids5** [comment]
@gitfishup 
```
make cuav_can-gps-v1
make cuav_can-gps-v1_canbootloader 
```
You will have to use a JTAG and install the bootloader first.

The from the build directory copy `org.cuav.can-gps-v1-1.0-0.1.xxxxxxx.uavcan.bin` to the folder as described  at the top of this PR https://github.com/PX4/PX4-Autopilot/pull/16554#issue-554552563 at to were to place the file.

Until there is some more refracting done* you can follow the information above.

*There is [this PR](https://github.com/PX4/PX4-Autopilot/pull/16583) that allows you to just place the bin file (org.cuav.can-gps-v1-1.0-0.1.b422da45.uavcan.bin) in the root directory of the SD card.  I will rebase that now.

**Comment by LorenzMeier** [comment]
@davids5 Sounds like it needs further discussion.

**Comment by LorenzMeier** [comment]
@gitfishup The instructions from David will allow you to get to a working result immediately. We're looking into ways to support existing products as well of course.

**Comment by gitfishup** [comment]
@LorenzMeier Thanks,I am going to try.
@davids5 As your said, i checkout to pr-uavcan-binfiles
make cuav_nora_default
make cuav_can-gps-v1
make cuav_can-gps-v1_canbootloader 

Using a JTAG and install the bootloader first.The start address is 0x8000000.
Placing the bin file (org.cuav.can-gps-v1-1.0-0.1.7756ef51.uavcan.bin) in the root directory of the SD card.
Then，can gps seems meet some errors about updating fw.

https://user-images.githubusercontent.com/69180601/106084137-b4025480-6158-11eb-969f-a3802a041a5d.mp4

**Comment by gitfishup** [comment]
@davids5  And , When i make  cuav_can-gps-v1_canbootloader  ,an error occurred while compiling.
platforms/nuttx/src/px4/common/srgbled/srgbled.cpp:104:12: error: subscripting array declared 'register' [-Werror=extra]

**Comment by davids5** [comment]
@gitfishup - Thank you for testing. I am make several changes of the next few days and we can then retest.

**Comment by gitfishup** [comment]
@davids5 Are we ready to retest?

**Comment by LorenzMeier** [comment]
Yes, please test master.

**Comment by davids5** [comment]
@gitfishup - yes on master placing the `xxxx-yyyy.uavcan.bin` file on the root of the SD card is all you have to do. It will be moved and renamed.

**Comment by gitfishup** [comment]
@davids5 @LorenzMeier .  Thank you for your time!
I retested the master firmware, including the GPS firmware.I found several problems:

1. Firmware Upgrade Issues
CUAVV5+: It can update GPS firmware successfully
CUAVx7pro,Nora: can update GPS firmware 

2. safetybutton does't work;
    The led next to safetybutton does's work;

3.using nora and x7pro: When power on , the gps's buzzer  sounds strange.
And , plug in SD card and without pluing in SD card , that sounds different .

4. the speed of upgrading gps firmware seems a bit slow ,about 2 minutes.

5. CAN interface 2 can't use to upgrade gps firmware.

**Comment by davids5** [comment]
> @davids5 @LorenzMeier . Thank you for your time!
> I retested the master firmware, including the GPS firmware.I found several problems:
> 
> 1. Firmware Upgrade Issues
>    CUAVV5+: It can update GPS firmware successfully
>    CUAVx7pro,Nora: can update GPS firmware
> 2. safetybutton does't work;
>    The led next to safetybutton does's work;

@dagar was this implemented?

> 
> 3.using nora and x7pro: When power on , the gps's buzzer sounds strange.
> And , plug in SD card and without pluing in SD card , that sounds different .
> 

SD card is needed at boot time by UAVCAN it can not be plugged in after boot.

> 1. the speed of upgrading gps firmware seems a bit slow ,about 2 minutes.

It is rate limited on purpose.

> 2. CAN interface 2 can't use to upgrade gps firmware.

Firmware upgrade is only ever done over CAN1.
> 
> By the way, When i make cuav_can-gps-v1_canbootloader ,an error occurred while compiling.
> platforms/nuttx/src/px4/common/srgbled/srgbled.cpp:104:12: error: subscripting array declared 'register' [-Werror=extra]

Thanks I will fix that.

**Comment by gitfishup** [comment]
> @davids5 @LorenzMeier . Thank you for your time!
> I retested the master firmware, including the GPS firmware.I found several problems:
> 
> 1. Firmware Upgrade Issues
>    CUAVV5+: It can update GPS firmware successfully
_>    **CUAVx7pro,Nora: can update GPS firmware**_
> 2. safetybutton does't work;
>    The led next to safetybutton does's work;
> 
> 3.using nora and x7pro: When power on , the gps's buzzer sounds strange.
> And , plug in SD card and without pluing in SD card , that sounds different .
> 
> 1. the speed of upgrading gps firmware seems a bit slow ,about 2 minutes.
> 2. CAN interface 2 can't use to upgrade gps firmware.
> 
> By the way, When i make cuav_can-gps-v1_canbootloader ,an error occurred while compiling.
> platforms/nuttx/src/px4/common/srgbled/srgbled.cpp:104:12: error: subscripting array declared 'register' [-Werror=extra]

@davids5 @dagar @LorenzMeier 
Sorry ,I make a mistake here .
          CUAVx7pro,Nora: **_can NOT_**  update GPS firmware.
And by the way,was  safetybutton  implemented?

**Comment by davids5** [comment]
> @davids5 And , When i make cuav_can-gps-v1_canbootloader ,an error occurred while compiling.
> platforms/nuttx/src/px4/common/srgbled/srgbled.cpp:104:12: error: subscripting array declared 'register' [-Werror=extra]
> 
> I can only remove register.

@gitfishup  this is fixed in this PR https://github.com/PX4/PX4-Autopilot/pull/16947

**Comment by gitfishup** [comment]
> > @davids5 And , When i make cuav_can-gps-v1_canbootloader ,an error occurred while compiling.
> > platforms/nuttx/src/px4/common/srgbled/srgbled.cpp:104:12: error: subscripting array declared 'register' [-Werror=extra]
> > I can only remove register.
> 
> @gitfishup this is fixed in this PR #16947
Thanks, This is OK . 
I use NEO v2pro for test.
And , the firmware update speed is much faster.That 's great.

**Comment by davids5** [comment]
> > > @davids5 And , When i make cuav_can-gps-v1_canbootloader ,an error occurred while compiling.
> > > platforms/nuttx/src/px4/common/srgbled/srgbled.cpp:104:12: error: subscripting array declared 'register' [-Werror=extra]
> > > I can only remove register.
> > 
> > 
> > @gitfishup this is fixed in this PR #16947
> > Thanks, This is OK .
> > I use NEO v2pro for test.
> > And , the firmware update speed is much faster.That 's great.

The app is built to the Neo 3 Pro HW. Are the schematics identical?  If not we need to duplicate the board files and rename both the projects. @dagar FYI

**Comment by gitfishup** [comment]
> > > > @davids5 And , When i make cuav_can-gps-v1_canbootloader ,an error occurred while compiling.
> > > > platforms/nuttx/src/px4/common/srgbled/srgbled.cpp:104:12: error: subscripting array declared 'register' [-Werror=extra]
> > > > I can only remove register.
> > > 
> > > 
> > > @gitfishup this is fixed in this PR #16947
> > > Thanks, This is OK .
> > > I use NEO v2pro for test.
> > > And , the firmware update speed is much faster.That 's great.
> 
> The app is built to the Neo 3 Pro HW. Are the schematics identical? If not we need to duplicate the board files and rename both the projects. @dagar FYI

@dagar @davids5 The NEO V2 Pro and NEO 3 Pro are just the difference between the M8N and M9N, other hardware is the same.

**Comment by davids5** [comment]
> @dagar @davids5 The NEO V2 Pro and NEO 3 Pro are just the difference between the M8N and M9N, other hardware is the same.

OK. Good to know. I tested it with a an FMUv5 and it updated and ran. 

So @dagar the Safety switch and LED need to be supported on both GPS types.

@dagar have you tested the upgrade on any on H7 boards?

**Comment by AlexKlimaj** [comment]
Tested this yesterday on the ARK Flow. In my case, the main app builds as "80-0.1.4092f873.uavcan.bin". I copy it to the root of the sd card, and it gets copied to ufw folder and renamed "80.bin".

**Pull request merged**
