### PR TITLE
boards: spracing h7extreme add alternate IMU icm42688p

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by hydra** [comment]
@dagar Yes, as noted via Slack this would allow an updated PCB revision that uses the ICM42688P sensor instead of the supply-chain-limited ICM20602.

@Igor-Misic If you have a moment can you review this change and approve?

**Comment by hydra** [comment]
Not sure of the sensor support in PX4, but it might be worth adding the following pin compatible sensors:

* ICM42605

The following gyros are also footprint compatible when the PCB is designed appropriately (as per my SPRacingH7RF PCB)

* LSM6SDRX
* LSM6DSO
* LSM6DSO32
* BMI270

**Comment by dagar** [comment]
> Not sure of the sensor support in PX4, but it might be worth adding the following pin compatible sensors:
> 
> * ICM42605
> 
> The following gyros are also footprint compatible when the PCB is designed appropriately (as per my SPRacingH7RF PCB)
> 
> * LSM6SDRX
> * LSM6DSO
> * LSM6DSO32
> * BMI270

We have a driver for the icm42605. https://github.com/PX4/PX4-Autopilot/tree/master/src/drivers/imu/invensense

I should also add one for the Bosch BMI270, although I don't have a board with it yet.

**Review by Igor-Misic — APPROVED** [review]
Looks good to me. 
I would also suggest adding this line
`*drivers__imu__invensense__icm42688p.a:*(.text* .rodata*)`
here:
https://github.com/PX4/PX4-Autopilot/blob/pr-spracing_imu/boards/spracing/h7extreme/nuttx-config/scripts/script.ld#L162
for driver to run at RAM.

**Comment by arguelle** [comment]
> 
> We have a driver for the icm42605. https://github.com/PX4/PX4-Autopilot/tree/master/src/drivers/imu/invensense
> 
> I should also add one for the Bosch BMI270, although I don't have a board with it yet.

@dagar I just uploaded firmware to Holybro's Kakute H7 Mini. Everything seems fine, except the IMU is not being detected. It looks like Holybro has swapped over to using BMI270 for newer versions (v1.3) of the board.
Do you think adding a driver for the BMI270 may fix this problem? How difficult would it be? I am new to this. My approach would essentially be to read through the BMI055/BMI088 code and attempt to reverse-engineer.

**Comment by arguelle** [comment]
> > > We have a driver for the icm42605. https://github.com/PX4/PX4-Autopilot/tree/master/src/drivers/imu/invensense
> > > I should also add one for the Bosch BMI270, although I don't have a board with it yet.
> > 
> > 
> > @dagar I just uploaded firmware to Holybro's Kakute H7 Mini. Everything seems fine, except the IMU is not being detected. It looks like Holybro has swapped over to using BMI270 for newer versions (v1.3) of the board. Do you think adding a driver for the BMI270 may fix this problem? How difficult would it be? I am new to this. My approach would essentially be to read through the BMI055/BMI088 code and attempt to reverse-engineer.
> 
> I don't currently have hardware to test, but I can put a driver together together pretty quickly, or I'd be happy to point you in the right direction if you're interested. I've heard the BMI270 is decent.

If you can put together a driver, that would help a ton!
In addition, any resources you provide regarding driver development are highly appreciated. There are plenty of interested students at my university right now.

**Comment by dagar** [comment]
Please ping me on PX4 slack and we can try to get something working soon.

**Comment by vincentpoont2** [comment]
@dagar We can send you the Kakute H7 v2 with the BMI270 if you need hardware.

**Pull request merged**
