### PR TITLE
Mag calibration refactor

### PR DESCRIPTION
**Pull request by jkflying**
**Describe problem solved by this pull request**
The mag calibration routines were pretty messy, with a fair amount of repeated code, some accidental bugs introduced that recently had to be fixed, etc.

**Describe your solution**
* Add unit tests
* Share the outer loop and convergence criteria for the sphere and ellipsoid fit
* Don't pass millions of parameters into functions, use a struct

**Test data / coverage**
Unit tests! Including one using real data

### CODE REVIEW

**Comment by dagar** [comment]
We need to give this a quick try on NuttX and check the stack usage.

**Comment by dagar** [comment]
We'll need to test this on NuttX and likely adjust the stack. Can all of this old matrix code be purged now? https://github.com/PX4/PX4-Autopilot/blob/master/src/lib/mathlib/math/matrix_alg.cpp

**Review by bresch — DISMISSED** [review]

**Comment by jkflying** [comment]
> Can all of this old matrix code be purged now?

Yes! Unfortunately I don't think it will save us any flash since the linker was removing it already, but nice to have a negative balance to lines of code for the PR despite lots of tests and test data added :-)

**Review by LorenzMeier — APPROVED** [review]

**Comment by MikeCharikov** [comment]
@jkflying 

Hi!

Looks like min_radius = 0.2 may be too large for some places in South America. 

```
int lm_mag_fit(const float x[], const float y[], const float z[], unsigned int samples_collected, sphere_params &params,
	       bool full_ellipsoid)
{

	const int max_iterations = 100;
	const int min_iterations = 10;
	const float cost_threshold = 0.01;
	const float step_threshold = 0.001;

	const float min_radius = 0.2;
	const float max_radius = 0.7;
```

image

We will try to change it to 0.15 and report the result

**Pull request merged**
