### PR TITLE
bootloader: Move chip specific things under chip specific folders

### PR DESCRIPTION
**Pull request by jlaitine**
- move systick.c under chip specific sources
- move do_jump into chip specific main.c as arch_do_jump
- wrap flash writes to "arch_flash_write" and implement in chip specific main.c
- add bootloader TOC check

Signed-off-by: Jukka Laitinen <jukkax@ssrc.tii.ae>

Please use [PX4 Discuss](http://discuss.px4.io/) or [Slack](http://slack.px4.io/) to align on pull requests if necessary. You can then open draft pull requests to get early feedback.

**Describe problem solved by this pull request**
A clear and concise description of the problem this proposed change will solve.
E.g. For this use case I ran into...

**Describe your solution**
A clear and concise description of what you have implemented.

**Describe possible alternatives**
A clear and concise description of alternative solutions or features you've considered.

**Test data / coverage**
How was it tested? What cases were covered? Logs uploaded to https://review.px4.io/ and screenshots of the important plot parts.

**Additional context**
Add any other related context or media.

### CODE REVIEW

**Review by davids5 — CHANGES_REQUESTED** [review]
As discussed, it would be good to mirror `platforms/nuttx/src/px4/` as  `platforms/nuttx/src/bootloader/arch/`

**Comment by jlaitine** [comment]
I moved the file into a directory structure, mirrored from platforms/nuttx/src/px4/ . Let's see if it still builds for all targets.

Should I add the security (signature check) support into this same PR?

**Comment by davids5** [comment]
> Should I add the security (signature check) support into this same PR?

Let do the reorg, then add the security.

**Comment by jlaitine** [comment]
I'll need some help with the errors, I don't understand them and also can't re-produce;
I tried to build cuav_x7pro_default locally, and it builds fine. But in CI this gives me:


-- ccache enabled via symlink (/usr/lib/ccache/arm-none-eabi-g++ -> /usr/bin/ccache)
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.5", minimum required is "3") 
-- build type is MinSizeRel
-- PX4 ECL: Very lightweight Estimation & Control Library v1.9.0-rc1-567-g85f5a93
CMake Error at platforms/nuttx/src/bootloader/stm/stm32h7/CMakeLists.txt:34 (add_subdirectory):
  The source directory

    /__w/PX4-Autopilot/PX4-Autopilot/platforms/nuttx/src/bootloader/stm/stm32_common

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/__w/PX4-Autopilot/PX4-Autopilot/build/cuav_x7pro_default/external/Build/bootloader_firmware/CMakeFiles/CMakeOutput.log".
See also "/__w/PX4-Autopilot/PX4-Autopilot/build/cuav_x7pro_default/external/Build/bootloader_firmware/CMakeFiles/CMakeError.log".
[32/1344] Generating nuttx/include/nuttx/config.h, nuttx/include/nuttx/version.h
ninja: build stopped: subcommand failed.
make: *** [Makefile:221: cuav_x7pro_default] Error 1

**Comment by TSC21** [comment]
@dinomani FYI

**Comment by davids5** [comment]
> I'll need some help with the errors, I don't understand them and also can't re-produce;
> I tried to build cuav_x7pro_default locally, and it builds fine. But in CI this gives me:
> 
> -- ccache enabled via symlink (/usr/lib/ccache/arm-none-eabi-g++ -> /usr/bin/ccache)
> -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.5", minimum required is "3")
> -- build type is MinSizeRel
> -- PX4 ECL: Very lightweight Estimation & Control Library v1.9.0-rc1-567-g85f5a93
> CMake Error at platforms/nuttx/src/bootloader/stm/stm32h7/CMakeLists.txt:34 (add_subdirectory):
> The source directory
> 
> ```
> /__w/PX4-Autopilot/PX4-Autopilot/platforms/nuttx/src/bootloader/stm/stm32_common
> ```
> 
> does not contain a CMakeLists.txt file.
> 
> -- Configuring incomplete, errors occurred!
> See also "/__w/PX4-Autopilot/PX4-Autopilot/build/cuav_x7pro_default/external/Build/bootloader_firmware/CMakeFiles/CMakeOutput.log".
> See also "/__w/PX4-Autopilot/PX4-Autopilot/build/cuav_x7pro_default/external/Build/bootloader_firmware/CMakeFiles/CMakeError.log".
> [32/1344] Generating nuttx/include/nuttx/config.h, nuttx/include/nuttx/version.h
> ninja: build stopped: subcommand failed.
> make: *** [Makefile:221: cuav_x7pro_default] Error 1

The failure is in the nested build `make cuav_x7pro_bootloader`

image

**Comment by jlaitine** [comment]
> The failure is in the nested build `make cuav_x7pro_bootloader`
> 
> image

Thanks, my  bad. I forgot  the "git add" the file... :)

**Comment by jlaitine** [comment]
I think this is ready for review; I cannot test on stm32h7 board though, as I don't have any. So if anyone is willing to try this on some stm32h7 board, it would be appreciated.

The reasoning for this change is that I am working on a Microchip Polarfire based board (risc-v), and I needed to generate a bootloader for that. So the structure is needed in order to support other than stm32 or arm based HW.

**Comment by jlaitine** [comment]
Added another commit, which is not just re-org, but related my current work; on a 64 bit platform converting uint32_t into pointers and back just won't do. So I have changed those addresses represented by uint32_t into uintptr_t. This doesn't change anything on stm platform though, since uintptr_t is 32 bits on that as well.

I thought that this fits well into this same PR

**Comment by jlaitine** [comment]
Is the CI stuck somehow? The tests are not completing...

**Review by davids5 — APPROVED** [review]
@jlaitine Looks god to me. I restarted CI, let't see how it feels....

**Pull request merged**
