### PR TITLE
- FCv1 DMA optimiziation for 2Mbit UART

### PR DESCRIPTION
**Pull request by modaltb**
- disable unused SPI3 DMA
- enable USART2 RX/TX, UART5/6 TX, UART4 RX

### Solved Problem
When using 2Mbit UART speeds to ESC over USART2 on FCv1, we had a lot of CRC errors and found we can resolve with these DMA optimizations.

### Solution
- disable SPI3 DMA (unused)
- enable USART2 RX/TX, UART5/6 TX, UART4 RX

### Test coverage
- This change has been in the field for some time on our custom branch

### CODE REVIEW

**Review by dagar — APPROVED** [review]

**Comment by m4v3r** [comment]
Hello,
with this commit my TELEM3 port on a VOXL Flight stops working.
I have a UBLOX M9 chip connected on that UART and the GPS stops showing up after this update, working fine again once flashed back to a previous commit.
I tried playing around with the baudrate and devices to no avail.
best regards

**Comment by dagar** [comment]
It's likely the DMA map, @modaltb let's review in detail tomorrow.

**Comment by modaltb** [comment]
Hi @m4v3r @dagar , let me revert this change...  we use it on a 1.12 branch for a project and it was reported success but apparently causes issues....

**Comment by dagar** [comment]
It looks like UART2 TX DMA conflicts with timer 4 (used for dshot on upper channels).

You either need to remove Timer4 DMA (boards/modalai/fc-v1/src/timer_config.cpp) or disable UART2 TX DMA.

https://github.com/PX4/PX4-Autopilot/blob/c31867f104abc4fde1a771d8b21295326f1fba87/boards/modalai/fc-v1/src/timer_config.cpp#L50

**Pull request merged**
