### PR TITLE
Create 13030_mugin_vtol

### PR DESCRIPTION
**Pull request by BanthaRage**
This is modified code from Fun Cub Quad code to use with a Mugin VTOL craft.

### CODE REVIEW

**Comment by cmic0** [comment]
@BanthaRage is this a WIP ? The default parameters values are identical to the [Fun cub VTOL](https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/airframes/13005_vtol_AAERT_quad) 

FYI @sfuhrer @RomanBapst

**Comment by BanthaRage** [comment]
The parameters are the same as the Fun Cub Quad but this code opens up more Mains for the Mugin VTOL.  Also I reference the new mixers needed to make this work.

**Comment by sfuhrer** [comment]
@BanthaRage for which Mugin VTOL (size) is that new airframe config (plus the corresponding mixers in https://github.com/PX4/Firmware/pull/12706 and https://github.com/PX4/Firmware/pull/12707) for? And have already flown with it? It so, could you maybe share a log file such that we can see if your set parameters are good or if they need some further tuning?

**Comment by BanthaRage** [comment]
@sfuhrer I will update the code with the proper documentation of the correct vehicle name.  We are trying to apply this to a Mugin-4 4720mm.  It has a VTOL system with a 2-stroke gas powered engine (hence why we need additional servos to control the gas engine).  We are flying it today using the Fun Cub Quad configuration so I may be able to get you the log from today.  We did a hover test yesterday and everything was looking good.

**Comment by BanthaRage** [comment]
@sfuhrer here are the logs from our recent test flights. 

https://drive.google.com/drive/folders/1WVb6QDg97H1rBPxdmU8tukfpqtS2YWSi?usp=sharing

**Comment by sfuhrer** [comment]
@BanthaRage thanks for sharing the flight log. The logs you shared with me only cover hover flights, is that correct? Also, I noticed that your hover motors were saturating during almost all of the flight..how was the flight performance? It doesn't look too good from the logs. Could it be that the vehicle is a bit too heavy for the hover motors/props you're using? 

I'll also ping @RomanBapst. We're happy to help you to improve your setup/tuning, so reach out if you have any questions. I would prefer to have some better tuning and nicer flights before we merge this config.

**Comment by sfuhrer** [comment]
@BanthaRage other question: what do the servo1-3 you specify in the config file correspond to? I guess for the engine it's just the throttle and chocke, right? Do you have the fixed-wing gas engine actually running with px4 or were you till now more focused on the hovering?

**Comment by sfuhrer** [comment]
@TachyonZZ 
I've taken a look at the new flight logs you provided. Here a couple of things that I see:
- The magnetometer readings are disturbed a lot by the current for the hovering motors. Here's the plot: 
image
The magnetic norm should be about factor 3 smaller. Do you have the compass (I guess you're using one that's together with the GPS) closer than 10cm to some power cables? Then put more distance in between. 
- Motors 1 and 2 (front right, rear left) seem to be saturated very often, so there seems to be some yaw control authority problem.
image 
Can you check if all your motors are slightly tilted towards the outside (i.e. rotated some degrees around positive x axis for motors 1 and 4, negative for 2.3). And also that they're turning in this direction:
image
- You need much more than half throttle to lift off. Your motors/props seem to be decent for this size of vehicle, should only need about half throttle to life up. So there for me clearly is some hardware problem. Are you sure that your battery provides enough power? And could you maybe try some flights with a lighter setup, e.g. with a removed fixed-wing motor? 
- ESC calibration shouldn't be a big thing, the one from QGC should work for all of them at the same time. What it does is giving 2000us, then you have to plug in the battery, and when you done that it goes to 1000us. AfsIk this is the same procedure for all ESC. You could do the same with a normal RC receiver/transmitter: Connect the ESC to the throttle port on the receiver, go to full throttle, connect the battery, go to min throttle, done. 
- Yes, a taranis for some initial testing is probably the way to go. We do the same.

**Comment by TachyonZZ** [comment]
@sfuhrer 
Thanks for your analysis of the logs. I've got another one here and a video that corresponds to it. We moved the flight computer forward about 22cm and implemented some other magnetic interference mitigation and got the mag interference down considerably. 

The battery is a 12s 12,000mAh that claims to be capable of 100c discharging, so it ought to support max performance of our motor/prop combination. 

We also remounted all of the motors and put a combination of silicon and foam tape under them to help with vibration. 

We removed the wings for this test which amounts to about 4kg of mass total. 

The craft tried to pitch over forward upon reaching about half throttle as can be seen in the video. The logs indicate it sensed an aft pitching moment that it was responding to. In the 3d view of the online log viewer the behavior matches the video nearly identically. 

Couple of theories... We did not apply any offset correction in the firmware when we relocated the FC. Previously It was sitting atop the forward end of the fuel tank, right on the CG, for this test it was moved forward 22cm and also down 13cm to the floor of the craft. I did not think this could cause such a miscalculation of rotation but perhaps I was wrong. In my experience with smaller quads FC/CG co location is wise, but being off by 10% or so just increases the FCs workload but it should figure it out. Am I thinking about this incorrectly with a very large craft? 

Another theory is that the IMUs are physically damaged by running the gas motor during testing with the craft clamped down. The vibration in during these static tests is tremendous, and I believe our damping for the FC is woefully inadequate. Obviously the gas motor was not running during this test however that flight controller had endured about a half hour of violent vibration during gas motor run up tuning. We've got several spare Cube Blacks to test this.

If you wouldn't mind taking a look at this log and the video, (as well as the 3d video created by the log) we'd really appreciate it. 

Thanks again

https://drive.google.com/open?id=1mVZpz0eI8lVU-fcZZEVmAyQ-wBOpz43S

**Comment by sfuhrer** [comment]
@TachyonZZ 
Sorry for your crash, hope there was not too much damage.

About your two theories: The position of the FC shouldn't be too much of a problem, plus you can change the parameters EKF2_IMU_POS_[X,Y,Z] to account for it. And to test if the FC is damaged I guess replacing wouldn't be a bad thing. 

What I've seen:
- the gyro noise is tremendous. As you have very big and slow spinning props, I would reduce the cutoff frequency for the filter --> set MC_DTERM_CUTOFF and IMU_GYRO_CUTOFF to 20 Hz each
- the tuning of the rate loops is maybe too loose, make it more aggressive
- increase the time constants of the attitude loop to make it less aggressive and thus to account for the mugins size compared to the Funcub or a default multicopter. So MC_PITCH_P, MC_ROLL_P, MC_YAW_P

Also consider to improve the mounting of the FC to add some vibration damping. I'm not an expert on this though. How is it mounted now? Maybe a picture would help.

Maybe it's best if you start with the parameter settings from the next biggest VTOL config there is on PX4, which is the Babyshark (12kg MTOW). https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/airframes/13014_vtol_babyshark

Keep me posted of your progress!

**Comment by semihyildirim** [comment]
@sfuhrer hi,
We have also work on Mugin2 VTOL frame. I have also logs that they are hover tests on multi-rotor mode. The plane flight sometimes greatuflly but sometimes it flights that there is no GPS support. The plane can not execute waypoints. We had 2 flights. one of them was good and one of them was bad. Also We flight today and the plane did not store flight logs. Could you analyse the logs? 
We did not change any parameter on px4 but flight performances was not the same. In manual mode We flight smoothly but flights are unstable on mission mode. The plane flight like no gps support on ekf. GPS sat count are always 17 18. 

This log has good flight. There  was no problem on flight:
https://drive.google.com/open?id=1-q7eX-dGx6igBHfEpAdMZmwpbD8iufyJ

This log was very  bad flight: 
https://drive.google.com/open?id=1z83Qv0Pw0OnfLCcw8_Seo9qIupLY5LTV

**Pull request closed without merging**
