### PR TITLE
Mavlink check transmit buffer before send

### PR DESCRIPTION
**Pull request by dagar**
- partially addresses #10389

### CODE REVIEW

**Comment by dagar** [comment]
@PX4/testflights this needs testing, but we should sort out your radio issues first.

Scenarios to test and review (from logs).

1. SiK radio with and without mavlink RADIO_STATUS working 
   - https://github.com/PX4/Firmware/issues/10358
2. SiK radios with and without flow control physically connected

Enable logging from boot so that the log contains the initial parameter and mission sync. Then do a short flight so we can see how the mavlink module responds (gracefully degrading or not).

**Comment by LorenzMeier** [comment]
Looks good to me, we just need to make sure we're not missing side effects. @bkueng Could you please also have a look?

**Comment by dagar** [comment]
We'll need to check the worst case mavlink packet size (largest + signing) that we'd like to support.

**Comment by santiago3dr** [comment]
couple flights on a pixracer (v4)
https://logs.px4.io/plot_app?log=bd9b756e-495e-4cfb-8936-4df94e3bb0dd
https://logs.px4.io/plot_app?log=290eed2d-7124-415c-a9cc-a79bdbbd024b

unable to establish proper connection; probably a hardware issue with SiK radio

**Comment by dagar** [comment]
As discussed offline, @santiago3dr's telemetry radios seem to have a severe problem unrelated to this PR. We'll reconvene for testing once there's a stable baseline.

**Comment by santiago3dr** [comment]
got the new telemtry radios which are getting good range.
did a range test on master 39221f
https://logs.px4.io/plot_app?log=809addb6-df5a-4d30-bd54-c619292c73e9
https://logs.px4.io/plot_app?log=9225eeca-4886-4ff5-adf9-393c768a151a

ran the same range test on this pr and rtl kept getting rejected; disconnected telemtry radio and still not able to engage rtl
https://logs.px4.io/plot_app?log=43e6ccdf-8ad2-46fb-951d-70ffe2d03ab9

@dagar thoughts?

**Comment by dagar** [comment]
@santiago3dr RTL failed because you didn't have a valid home position.

I've rebased the PR on master, could you try again?

**Comment by LorenzMeier** [comment]
@santiago3dr Could you re-test? Thanks!

**Comment by santiago3dr** [comment]
mixed results
https://logs.px4.io/plot_app?log=6273d7fb-eb7c-4d45-9c5b-128d057b6d0b
had difficulty maintaining connection and loading parameters

https://logs.px4.io/plot_app?log=6daf5df5-88b2-4ecb-b7d4-acbb4402ad91
great connection; better connection than with master

same test and environment on master cfac2ccfor comparison:
https://logs.px4.io/plot_app?log=0cd4d221-887e-4109-86e1-30c8c9ed6d69

**Comment by dagar** [comment]
@santiago3dr your radio RSSI looks much better, but in all of your logs mavlink is still reporting flow control disabled.
How is the radio wired? Check RTS/CTS.

image

**Comment by dagar** [comment]
Well that's unfortunate. We have some other ideas that will help, but nothing immediate. This is all kind of secondary to this PR though.

@dogmaphobic FYI

**Comment by dagar** [comment]
@santiago3dr could you try newer QGC daily? With only telemetry connected take a look at "Loss rate"  under Settings -> Mavlink.

image

**Comment by santiago3dr** [comment]
capture

stable 1~2% loss rate

**Comment by LorenzMeier** [comment]
@dagar What's your conclusion here?

**Comment by dagar** [comment]
> @dagar What's your conclusion here?

That this change is probably fine, but only addresses a subset of the many problems. I'll open another issue.

**Comment by dagar** [comment]
Likely worth dropping this PR and starting again, but tagging @MaEtUgR @jkflying for historical reference.

**Comment by LorenzMeier** [comment]
Closing as stale.

**Pull request closed without merging**
