### PR TITLE
Fix Return issue to landing pattern

### PR DESCRIPTION
**Pull request by moreba1**
fix this issue:
https://github.com/PX4/PX4-Autopilot/issues/16299

when we have "land start" after a survey drone can not return to landing pattern.

### CODE REVIEW

**Comment by dagar** [comment]
I don't quick follow. Did you see within the if statement it's accessing missionitem_prev.lat, etc? What is the missionitem_prev in your case?

**Comment by moreba1** [comment]
missionitem_prev is MAV_CMD_DO_SET_CAM_TRIGG_DIST 0 .

**Comment by dagar** [comment]
Can you share your mission (image or .mission file)? `DO_LAND_START` is only a marker, it needs to have a position waypoint before it.

**Comment by moreba1** [comment]
https://docs.qgroundcontrol.com/master/en/PlanView/pattern_fixed_wing_landing.html
for fixedwing:
This pattern creates three mission items:
    DO_LAND_START - If you abort a landing it sends DO_GO_AROUND to the vehicle, which then causes the mission to return to this point and try to land again.
    NAV_LOITER_TO_ALT - Start point for landing
    NAV_LAND - End point for landing

**Comment by moreba1** [comment]
image

**Comment by moreba1** [comment]
[plan.zip](https://github.com/PX4/PX4-Autopilot/files/5717482/plan.zip)

**Comment by moreba1** [comment]
> Can you share your mission (image or .mission file)? `DO_LAND_START` is only a marker, it needs to have a position waypoint before it.

If this pull request merged it doesn't need to waypoint before DO_LAND_START.

**Comment by DonLakeFlyer** [comment]
Seems pretty broken to me. DO_LAND_START should work wherever you place it and whatever is in front of it in mission commands.

**Comment by Antiheavy** [comment]
> Can you share your mission (image or .mission file)? `DO_LAND_START` is only a marker, it needs to have a position waypoint before it.

why does it need a position waypoint BEFORE it?  It's the position waypoint(s) AFTER the Do_Land_Start that is import.

**Comment by moreba1** [comment]
@dagar  @sfuhrer

**Comment by moreba1** [comment]
fixed here https://github.com/PX4/PX4-Autopilot/commit/12875f7869ac547116119ba0fcad7fe3251ae27a

**Pull request closed without merging**
