### PR TITLE
px4_fmu-v6c Move I2C 4 to External

### PR DESCRIPTION
**Pull request by davids5**

### CODE REVIEW

**Comment by davids5** [comment]
see https://github.com/PX4/PX4-Autopilot/issues/19943#issue-1313411705

**Comment by ryanjAA** [comment]
This works but breaks airspeed (ms4525do) working. Calibration works but then airspeed doesnt show up - tested this on this pr and then on main.

**Comment by davids5** [comment]
> This works but breaks airspeed (ms4525do) working. Calibration works but then airspeed doesnt show up - tested this on this pr and then on main.

@ryanjAA - Please post the parameter and the output from boot on the console.

**Comment by ryanjAA** [comment]
Just left town for a bit. I have one with me but no airspeed. Let me see see if I have a jtag probe and will look.

**Review by vincentpoont2 — APPROVED** [review]
Tested, please merge @dagar @davids5

**Pull request merged**
