### PR TITLE
Enable loading third mixer when using UAVCAN for main mixer

### PR DESCRIPTION
**Pull request by RicardoM17**
**Describe problem solved by this pull request**
This PR enables a third mixer to be loaded onto an airframe which could be used for example when UAVCAN is enabled as in this case the main mixer is used on one of the Can ports and as such it "frees" up one of the PWM ports.

**Describe your solution**
When using UAVCAN ESC the output_channel is `actuator_outputs.1`  when there's no aux mixer, and `actuator_outputs.2` when there is (or at least it should be, see issue raised in #16414). My approach is to then load a third mixer in the now empty `actuator_outputs.0` channel. 

By setting `EXTRA_MIXER_MODE` on the airframe file + selecting an .aux mixer on `MIXER_EXTRA` then 3 mixers can be loaded at the same time. 2 on PWM and 1 one UAVCAN. As it stands it allows to use the motors on UAVCAN and then 8 servos on AUX for example + theoretically 8 on this new Extra outputs (still to be tested).

I didn't push any airframes with this in place but the only thing required to test it is to

Enable UAVCAN by setting `UAVCAN_ENABLE` to `3`. Possibly disable `COM_ARM_CHK_ESCS` if in a bench test.

Add these lines to an airframe file to be used:

```
set MIXER_EXTRA tilt_quad
set PWM_EXTRA_OUT 1234

set EXTRA_MIXER_MODE 1
```

 Arm and check the log.

**Test data / coverage**
Full testing on master is being blocked by #16414 . That being said the new mixer is being successfully loaded into actuator_outputs.00 as can be seen here:

image

https://logs.px4.io/plot_app?log=2342662f-df96-43e1-957e-e6865adbec99

This has also been tested quite a lot more on our forked version of PX4 where the issue mentioned above is not present (forked ~April 2020).  In this log it can be seen flying with 3 mixers loaded. The third mixer that goes on actuator_outputs.00 has no actuator attached, so this is not a definitive test.

https://logs.px4.io/plot_app?log=cbcae7d2-8627-4cbf-a997-f6302a352a83

image

**Other Notes**

This is just the first approach that I did and got it working on our PX4 version. To be full tested first #16414 has to be fixed.

I'm bringing this PR up for review already so that people can provide feedback. Once I have the OK for the initial approach 
I can clean it up and make it more robust (also with the given feedback). Things that I know already that can/should be reviewed/changed:

- Naming: There's MAIN, AUX, and then for this third mixer I named it EXTRA. Since it won't be used by most people I think changing to AUX1 and AUX2 would be more confusing than needed. But here I am completely open to changes. Also it uses .aux.mix files. Not sure if it's worth it to have mixer.extr.mix files or something. Probably too complicated.
- Right now it is enabled with a param set in the airframe file. IMO it should also have some way of blocking the loading of this third mixer if UAVCAN is not set (for example looking at the value of `UAVCAN_ENABLE`), as I believe if that's not the case it will just overwrite the main mixer (not tested yet). 
- Creation of the relevant parameters like `PWM_EXTRA_MAXi` etc For the first approach I just went with the same ones as the AUX channels to test it but I'm aware that it can't be like this.
- ? (Issues raised by feedback).

Thanks and I look forward to your suggestions/questions/feedback.

P.s. this further breaks flight review when it comes to UAVCAN outputs. Probably worth it to check that out at some point.

### CODE REVIEW

**Comment by dagar** [comment]
This looks fine, although I'd ultimately like to find a cleaner way to do it without all the duplication. I'll have to free up some flash before bringing this in.

**Comment by LorenzMeier** [comment]
Could you please rebase on master so we get a reading on flash space?

**Comment by RicardoM17** [comment]
Yap @LorenzMeier I can do that. If both of you are also ok with the naming then I'll also add the missing parameters as I mentioned in the description. Not sure if that also influences the flash space or not.

In the meantime @dagar if you could have a look at #16414 that would be great, as it is blocking this PR anyway (and it should hopefully be a separate fix).

**Comment by RicardoM17** [comment]
@LorenzMeier @dagar I rebased and also added the `PWM_EXTRA` parameters. Apologies for the delay, I was (still am) on holiday and it was hard getting on a computer.

A small note. All parameters are `PWM_EXTRA_XXX` just like the `AUX` parameters. However due to its size it was not possible to have `PWM_EXTRA_DISARMED` so I changed it to `PWM_EXTRA_DISARM` . I felt it was better than having `PWM_EXT_XXX` which isn't that obvious but like I said before I'm not 100% happy with the naming scheme so if you have a better suggestion do let me know.

Flash space seems to be ok with the rebase. I tested this and it seems to be ok even with 8 channels.

image

Log: https://logs.px4.io/plot_app?log=20decfae-f37e-4a73-8327-878d660ad1dd

**Pull request merged**
