### PR TITLE
logger: restart on file write error

### PR DESCRIPTION
**Pull request by bkueng**
This can also happen if the maximum file size is reached.

### CODE REVIEW

**Comment by lvanasse** [comment]
Hi @bkueng ! I started testing this PR yesterday, and I've let my PX4 ran all night and this morning when I checked the log, I didn't have any. Which was the behaviour before testing with this PR. 

I assume you've tested it, but I was wondering if you've done long endurance test like I did?

**Comment by bkueng** [comment]
Yes I tested the error case, but not specifically an endurance test. Do you happen to have the console output (or `dmesg`)?

**Comment by lvanasse** [comment]
You mean console out or `dmesg` of when the logger module fails? If that's the case, it's a bit hard to catch since, the bug happens only after maybe a couple of hours (3-5 hours). I was testing a custom module, and had it in verbose more, so it was logging a lot, but now with the logger stopping to log I'll try to reduce as much as possible the logging in the console output and replace it with the logger instead.

I'll try to have something by the end of the day.

**Comment by lvanasse** [comment]
@bkueng sadly, after 5 hours, the logger stopped logging, and I didn't see anything in the `dmesg`. I'll turn on the `DBGPRINT` in the logger module and restart the test. Also, maybe it's an issue where the SD card is full and just can't log anymore. But if that's the case, there should be an error message coming from the logger module.

**Comment by lvanasse** [comment]
I spoke too fast, I don't think there's a way for the `DBGPRINT` to be enabled in the module. There's error with the `struct mallinfo` because it's from POSIX, but doesn't seem to be present in NuttX

**Pull request merged**
