### PR TITLE
fix micro_hal.h for STM32F1

### PR DESCRIPTION
**Pull request by christianrauch**
The file `stm32f1/include/px4_arch/micro_hal.h` guarded against `CONFIG_STM32_STM32F4XXX` which likely is supposed to be `CONFIG_STM32_STM32F1XXX` for the STM32 F1 and not F4.

### Solved Problem
This fixes a compilation error on STM32 F1 targets.

### CODE REVIEW

**Review by bkueng — COMMENTED** [review]
`STM32_STM32F1XXX` does not exist, only `STM32_STM32F10XX`. Where and which error do you get?

**Comment by christianrauch** [comment]
I cannot reproduce the concrete issue now. I think it was that `PX4_BBSRAM_SIZE` was not defined. But since `STM32_STM32F1XXX` is not defined too, the original issue must have been resolved in a different way.

What is the purpose of checking `CONFIG_STM32_STM32F4XXX` in the stm32f1 source file? It appears counterintuitive to me.

**Comment by bkueng** [comment]
> What is the purpose of checking CONFIG_STM32_STM32F4XXX in the stm32f1 source file? It appears counterintuitive to me.

That's a good point. It's a left-over when it was still combined. We can also just remove it.

**Comment by christianrauch** [comment]
> > What is the purpose of checking CONFIG_STM32_STM32F4XXX in the stm32f1 source file? It appears counterintuitive to me.
> 
> That's a good point. It's a left-over when it was still combined. We can also just remove it.

Alright. I just went ahead and removed that part.

**Review by bkueng — APPROVED** [review]

**Pull request merged**
