### PR TITLE
Enable motor controls for tailsitter VTOLs in fixed wing mode (enable Quad Tailsitters)

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
## Describe problem solved by this pull request
For tailsitter VTOLs, motors are not used for attitude control in fixedwing mode. This is because of the distinction between control surfaces and motor controls being enabled / disabled depending on whether the vehicle is in fixed wing or multicopter mode.

## Describe your solution
This commit enables motor controls in fixed-wing mode for tailsitters. This is enabled when `VT_FW_DIFTHR_EN` is enabled on a tailsitter. This is needed for enabling control surface-less quad tailsitters (https://github.com/PX4/PX4-Autopilot/issues/19747)

## Describe possible alternatives
This feels like a hack and would be great if we can discuss how bad this hack is :sweat_smile:  @sfuhrer @tstastny 

IMHO, it would be better if this comes implicitly from the geometry of the control allocation framework. However, vehicle geomtetry doesnt seem to propagate back to vtol_att_control. We could probably do something like "Lock motor attitude control in fixedwing mode" as we do for control surfaces in fixedwing mode. However not sure how control surfaces and motors should be allocated if they are both available. 

## Test data / coverage
Tested in SITL Gazebo, with the control surfaces disabled for the quadtailsitter
```
make px4_sitl gazebo_tailsitter
```
- Flight log: [log](https://review.px4.io/plot_app?log=a616da7f-0020-4533-b983-10229f3dcb4a)
  - Note that the position and attitude controllers were not retuned, and therefore the tracking performance is quite bad. If this PR seems to be a good way to support quad tailsitters, I will add a gazebo model dedicated for quad tailsitters and retune the vehicle

## Additional context
- Fixes https://github.com/PX4/PX4-Autopilot/issues/19747

### CODE REVIEW

**Comment by sfuhrer** [comment]
With that proposal it would be no longer possible to use on e.g. a quad tailsitter with elevons the elevons for fixed-wing roll and pitch control and the differential thrust for yaw, right? 
Maybe it's necessary to have that still. For it something like here https://github.com/PX4/PX4-Autopilot/commit/17a020c6a53949aa665dd1e0258cfc519b00ff2a (as part of the [testing branch](https://github.com/PX4/PX4-Autopilot/commits/pr-enable-quad-tailsitter-diff-thrust-main) I created some time ago) may be needed.
And yes I feel there should be some sort of feedback from the allocator to the controller with the actuator setup - or we push harder for the unified rate controller and move all the allocation customization to the control allocation module.

**Comment by Jaeyoung-Lim** [comment]
> Maybe it's necessary to have that still. For it something like here https://github.com/PX4/PX4-Autopilot/commit/17a020c6a53949aa665dd1e0258cfc519b00ff2a (as part of the [testing branch](https://github.com/PX4/PX4-Autopilot/commits/pr-enable-quad-tailsitter-diff-thrust-main) I created some time ago) may be needed.

So, as far as I understand, this would be basically adding a parameter to enable differential thrust for each axis, did I understand this correctly?

**Comment by Jaeyoung-Lim** [comment]
@sfuhrer Addressed review comments on latest commit

- Flight log: [https://review.px4.io/plot_app?log=1ca59547-51a1-4a9f-9f0e-34ecf2e882d1]

**Comment by Jaeyoung-Lim** [comment]
Airspeed seems to get invalid after transition:
image

**Review by sfuhrer — APPROVED** [review]
Looks like the right iterative step for me to start enabling control surface less tailsitters without big controller reworks. Next up for me would be to remove the dual controller setup - especially with a plane that uses the same actuators in hover and fixed-wing there should be no controller switch necessary.

**Comment by Jaeyoung-Lim** [comment]
@sfuhrer Thanks!

**Comment by aoberai** [comment]
Has this been tried on physical hardware like the SWAN K1? Would it be able to couple both elevons and differential thrust for control authority--or just one or the other? 

Planning on using this on a drone in a couple weeks, just want to know if I can bank on it working or if more work needs to be done first.

Thanks

**Comment by sfuhrer** [comment]
> @Jaeyoung-Lim @sfuhrer Has this been tried on physical hardware like the SWAN K1? Would it be able to couple both elevons and differential thrust for control authority--or just one or the other?
> 
> Planning on using this on a drone in 2 weeks, just want to know if I can bank on it working or if more work needs to be done first. (Mentions that the solution was a bit of a hack so not sure what that means performance wise)

No hasn't been tried on a real drone yet. There is an ongoing effort to add proper simulation for it in https://github.com/PX4/PX4-Autopilot/pull/20558.
Likely more work to be done. Check out the state of the simulation, and if you're satisfied with how it flies try it out on the real one, that would give us valuable feedback.

And about using both elevons and MC for control: never had it in hind to combine the two, but it may work, and you should be able to quite easily bench test it to be sure.

**Comment by aoberai** [comment]
I see, I assumed the PR being merged might mean it is fully ready. In that case just to confirm, PX4 for sure works with quadrotor tailsitter with elevons (without thrust differential) as a back up for now?  If that is correct, I can still probably use it but otherwise I would have to switch over to a software like Ardupilot which does this well but has significantly worse gazebo simulation support which would be unfortunate. 

I will look into the simulation efforts going on and pitch in if I can.

**Comment by sfuhrer** [comment]
>PX4 for sure works with quadrotor tailsitter with elevons

I unfortunately don't have a quad tailsitter with elevons to try it out, but as the gazebo model is such a vehicle I'm fairly confident that it works.

**Pull request merged**
