### PR TITLE
New HW revision version format and manifest in EEPROM

### PR DESCRIPTION
**Pull request by Igor-Misic**
Starting this PR upstream so we can continue development and dialog on how to make this into the upstream repository. 

A little bit of background story about this PR:
- this pr brings a new format for the Hardware version and revision
example for fmu-v5x board is from V5X{0-a}{0-a} to new format V5X{xxx}{xxx}
Another feature is to use `/mtd/mft ` as a place that keeps manifest information. For now, it is only a placeholder for `hw_ext_ver` but it could be extended in the future. 

Here I am asking PX4 architects to take time and write down what is still missing and how should we continue from here.

### CODE REVIEW

**Comment by davids5** [comment]
I will be able to work through this on the the week of 3/7.

**Comment by davids5** [comment]
@Igor-Misic Sorry this took so long. Yikes almost 60 day behind! see https://github.com/PX4/PX4-Autopilot/pull/19575

**Comment by Igor-Misic** [comment]
Rebased and merge conflict fixed
image

**Comment by Igor-Misic** [comment]
@davids5 can we merge this?

**Review by davids5 — APPROVED** [review]
@Igor-Misic - I would say it looks ready. Did all the changes I had in https://github.com/PX4/PX4-Autopilot/pull/19575 come in?

**Comment by Igor-Misic** [comment]
> Did all the changes I had in https://github.com/PX4/PX4-Autopilot/pull/19575 come in?
yes, everything is part of this commit [5833d2b](https://github.com/PX4/PX4-Autopilot/pull/19084/commits/5833d2ba8d53180cc8f82f270645e349993b642a)
I've updated some boards that changed in the meantime.

**Comment by Igor-Misic** [comment]
> What HW have you tested it on?

px4_fmu-v5x

**Comment by davids5** [comment]
Seeing this touches all the HW, we need the test rack and other boards to pass. What H7, F4 and F7 targets do you have?

**Comment by Igor-Misic** [comment]
> Seeing this touches all the HW, we need the test rack and other boards to pass. What H7, F4 and F7 targets do you have?

I have CUAV Nora with H7, Pixracer with F4, and Skynode with F7. I'll test with each of them one more time. 
Now I see that fmu-v5 didn't pass the last rebasing. I'll check that.

**Comment by Igor-Misic** [comment]
@davids5 I solved the build issue for a private variant of fmu-v5
From the impacted version, I only have **fmu-v5x** board. At commit [5833d2b](https://github.com/PX4/PX4-Autopilot/pull/19084/commits/5833d2ba8d53180cc8f82f270645e349993b642a) I merged only diffs, so if everything was working for you it will works here as well. 
I think it is better if we merge this now, every merge conflict in the future will increase the chance of error.

**Comment by Igor-Misic** [comment]
> This needs to be updated as well: https://github.com/PX4/PX4-Autopilot/blob/ae7253777cd130ef8d7f44977f5cdecb50a6107c/boards/px4/fmu-v5x/init/rc.board_sensors#L8=. Can you do a grep for `hwtypecmp` and check if there's more such instances?

This sneaked in after rebasing. I've rebased it again and checked all `hwtypecmp`, it was only that one. Thanks!

**Review by bkueng — APPROVED** [review]
Getting this in to avoid further rebase conflicts. Thanks everyone.

**Pull request merged**
