### PR TITLE
VTOL: trigger RC override only if sticks are moved in hover flight.

### PR DESCRIPTION
**Pull request by sfuhrer**
This PR is an option to fix https://github.com/PX4/Firmware/issues/13061

### CODE REVIEW

**Comment by dagar** [comment]
This is getting really convoluted. I don't have any immediate ideas to simplify it, but maybe we should carry a fairly detailed comment so that `is_fixed_wing` doesn't accidentally disappear in a future refactor.

**Comment by dagar** [comment]
I suppose RC override could ignore the throttle channel.

**Comment by sfuhrer** [comment]
> I suppose RC override could ignore the throttle channel.

Also thought about that, I agree. Should we still bring in the changes proposed here as well?

**Comment by dagar** [comment]
> > I suppose RC override could ignore the throttle channel.
> 
> Also thought about that, I agree. Should we still bring in the changes proposed here as well?

Whichever you prefer.

So then the question is does it make sense to drop throttle from RC override consideration entirely or only in this case.

**Comment by sfuhrer** [comment]
> e question is does it make sense to drop throttle from RC override consideration entirely or only in this case.

I would vote for getting this PR in, and see if we still need to disable throttle for some cases.

**Comment by MaEtUgR** [comment]
> I suppose RC override could ignore the throttle channel.

I assume that would not be intuitive in certain situations since e.g. in multicopter Land or RTL on the final approach people might pull up again if it's landing too fast or in the wrong location.

**Comment by MaEtUgR** [comment]
This got fixed in https://github.com/PX4/PX4-Autopilot/pull/15495

**Pull request closed without merging**
