### PR TITLE
[WIP] commander: accel calibration updates

### PR DESCRIPTION
**Pull request by dagar**
- use online Welford mean to gather clean readings per orientation
 - reset if movement during per side data gathering 
 - invert full matrix to determine calibration
 - store and use off diagonal calibration scale factors (undecided if this is worth keeping)
 - detect invalid rotations (and soon auto correct like mag)
 - accel quick calibration (commander calibrate accel quick) assume vehicle is aligned with gravity and adjust offsets immediately

### CODE REVIEW

**Comment by NicolasM0** [comment]
I am not sure this is the correct place to share this but as you are working on accel calibration improvement and I was thinking to rework this calibration but hadn't time for that, here are my thought:

This calibration uses the assumption that the imu is at the perfect position for each side.
I think that, if there is an orientation error, the effect for:
- scales diagonal, the error should be something like 1-cos(angle error) so be very little for little errors but would increase for larger errors
- scales off-diagonal, the error should increase with sin(angle error) so linearly for little errors
- offsets, as scales diagonal

So, For scale diagonal and offset, it is ok if the user is doing it correctly (but depends on the position precision). I think for off-diagonal, it should not be ok.

I was thinking of using a spherical (or maybe elliptic) regression as for magnetometer with a known radius (g). This would remove the position assumption (sides would still be useful to be sure we have a good repartition of data on the spere).

I have dug into this because the accelerometer calibration didn't seem very precise and repeatable (not easy to have a precise position with our vehicle) and a client had an issue where he was unable to recalibrate. His accel calibration was so bad that the tilt error prevents the calibration to detect the correct positions.
I have been able to reproduce this bad state by rotating 180deg an autopilot during the "hold still" calibration phase (when the calibration duration was longer).

Resetting previous calibrations before doing a new one should allow recovery from such a bad state.

**Comment by dagar** [comment]
Thanks @NicolasM0, I actually considered using the same mechanism as magnetometer calibration, but wasn't sure about relying on clean accel data acquisition from user movement. Have you seen this used successfully before? I had actually considered merging accel+mag (+gyro) calibration into the existing mag calibration structure for various reasons (including auto setting rotations correctly). @bresch any thoughts on trying this for accel cal?

Could you give this branch a try to see if it improves your results relative to master? It's based on this ST application note.
https://www.st.com/resource/en/application_note/dm00119044-parameters-and-calibration-of-a-lowg-3axis-accelerometer-stmicroelectronics.pdf
The debugging is still enabled if you want to see intermediate output printed to the console.

> His accel calibration was so bad that the tilt error prevents the calibration to detect the correct positions.

This might be a small separate issue worth tackling. We currently use a calibrated vehicle body frame acceleration (vehicle_acceleration) to detect each side. Perhaps in calibration we should only rely on raw sensor data within the calibration routines to prevent any weird edge cases where you somehow ended up with a calibration so bad it's impacting your ability to re-calibrate.

> Resetting previous calibrations before doing a new one should allow recovery from such a bad state.

The way the sensor pipeline is now structured we can always consume full raw data from the sensors and the calibration is applied downstream. This was we can keep any existing calibration and only change it after the new one completes successfully (and we like it more).

**Comment by NicolasM0** [comment]
> Have you seen this used successfully before? 
Yes, I used that for accelerometers calibration in my previous job. I also implemented it in factory calibration.
I think it is more robust to user manipulation that the current method but we may have to reject measurement if the imu is not still enough (large changes in accel or not low enough gyro)

> Could you give this branch a try to see if it improves your results relative to master? 
Will do

**Comment by NicolasM0** [comment]
For sphere regression, I was thinking of using data from still phases and not from rotation.

I tested this branch and could not find a difference from master in use. Calibration result teems close to those from1.12.1

**Comment by dagar** [comment]
> I tested this branch and could not find a difference from master in use. Calibration results seem close to those from 1.12.1

Thanks for testing.

> For sphere regression, I was thinking of using data from still phases and not from rotation.

So gather data with the current accel cal workflow or with more points? Do you want to join the dev call this week or ping me on slack to discuss? I think I could hack together an initial version relatively quickly if there's enough interest in this to coordinate on testing, validation, etc.

**Comment by dagar** [comment]
Continued in https://github.com/PX4/PX4-Autopilot/pull/18166.

**Pull request closed without merging**
