### PR TITLE
[v1.15] boards: add Septentrio GNSS drivers to 6C, 6X, 6X-RT

### PR DESCRIPTION
**Pull request by julianoes**
It's confusing that the new Septentrio driver is not part of PX4 6C and 6X. Let's see if we can squeeze it in.

FYI @vincentpoont2 

Backport of #23833.

### CODE REVIEW

**Comment by PetervdPerk-NXP** [comment]
@julianoes could you update v6xrt as well to match v6x?

**Comment by vincentpoont2** [comment]
> @julianoes could you update v6xrt as well to match v6x?

When we did our test, the rt is the only one that has the Septentrio selection in the GPS protocol. Not exactly sure why.

**Comment by julianoes** [comment]
> When we did our test, the rt is the only one that has the Septentrio selection in the GPS protocol. Not exactly sure why.

It shouldn't have it for v1.15. It's gone, so you're somehow looking at something cached or outdated.

**Comment by julianoes** [comment]
> could you update v6xrt as well to match v6x?

Done.

**Comment by julianoes** [comment]
@dagar are the board checks not running for thie v1.15 release branch?

**Comment by julianoes** [comment]
@dagar I guess I just have to merge it to see what happens?

**Pull request merged**
