### PR TITLE
FMUK66 Decrease telnetd ram usage

### PR DESCRIPTION
**Pull request by PetervdPerk-NXP**
**Describe problem solved by this pull request**
FMUK66 with RTPS enabled is running into RAM issues.

**Describe your solution**
Disabled NETDB DNS to save on ram usage
Telnet daemon decrease max sessions from 8 to 1
Telnet daemon decrease stack size since we only accommodate a single client.
Telnet client decrease stack and I/O buffer sizes

**Describe possible alternatives**
Maybe try to decrease I2C/SPI WQ stack sizes to save RAM or other resources

**Test data / coverage**
Tested on FMUK66

**Additional context**
One known issue, when running top on the telnet session and press CTRL + C to stop cause the telnet session to lockup

### CODE REVIEW

**Comment by dagar** [comment]
Mirror this across all the fmuk66 defconfigs?

**Review by dagar — DISMISSED** [review]

**Comment by PetervdPerk-NXP** [comment]
> Mirror this across all the fmuk66 defconfigs?

Good point, added these changes to the socketcan config as well

**Comment by dagar** [comment]
I was also thinking keep `nxp_fmuk66-e` and `nxp_fmuk66-v3` as closely in sync as possible.

**Comment by dagar** [comment]
We can do another pass to align them.

**Pull request merged**
