### PR TITLE
px4_fmu-v6x:Add Holybro Pixhawk Jetson Baseboard ver 0x100

### PR DESCRIPTION
**Pull request by davids5**
@vincentpoont2 @mrpollo This is the code that needs to be checked ones the BASE has had its ID set.

### CODE REVIEW

**Comment by vincentpoont2** [comment]
@mrpollo please merge

**Comment by vincentpoont2** [comment]
@dagar can we merge this?

**Review by dagar — APPROVED** [review]

**Comment by vincentpoont2** [comment]
@davids5 @julianoes Can we backport this to 1.14?

**Comment by vincentpoont2** [comment]
@dagar @davids5 Can we backport this to 1.14?  I tried to do it but there are conflicts.
@julianoes  also tried backport it but unsure how to resolve this conflict, said that looks like the system has been refactored.

**Comment by julianoes** [comment]
The configuration seems different in 1.14. I don't know how it works, so I can't backport it.

**Comment by davids5** [comment]
@julianoes can you elaborate on what the issues of push a branch for review - conflicts and all.

**Pull request merged**
