### PR TITLE
[Board Support] PilotPi distributing update

### PR DESCRIPTION
**Pull request by SalimTerryLi**
**Describe problem solved by this pull request**
Update the most recent version of board configuration.

**Describe your solution**
- QMC5883l mag enabled
- fixedwing script
- other fix.

### CODE REVIEW

**Review by dagar — APPROVED** [review]

**Comment by mrpollo** [comment]
@SalimTerryLi What is a PilotPi?

**Comment by SalimTerryLi** [comment]
> 
> 
> @SalimTerryLi What is a PilotPi?

Hi
It is a hardware design aims to run PX4 natively on RPi. Document here: https://docs.px4.io/master/en/flight_controller/raspberry_pi_pilotpi.html
Note that I just finished the very first step of manufacturing the hardware and documents will be updated in a few days.

**Comment by s175217** [comment]
@SalimTerryLi  I meet two pilotpi questions: A:"pcm9685_pwm_out start'' could not work on IIC1 by using the codes of 1.13.I try the pcm9685 too(0x40 is OK),maybe the problem is that /dev/pwm_output0 does not exist in Pi4B. B:"mpu6500 start -s" in spi0.0 mode could not  work,I try mpu9250(0x70 is OK) and mpu9250_i2c start -s(ox68 is OK) ,all return -1. MY phonenumber is 18351454190.其他的IIC传感器和GPS我都试了没问题，只有这两个过不去，我没有用这个扩展版https://docs.px4.io/master/en/flight_controller/raspberry_pi_pilotpi.html

**Comment by SalimTerryLi** [comment]
> @SalimTerryLi I meet two pilotpi questions: A:"pcm9685_pwm_out start'' could not work on IIC1 by using the codes of 1.13.I try the pcm9685 too(0x40 is OK),maybe the problem is that /dev/pwm_output0 does not exist in Pi4B. B:"mpu6500 start -s" in spi0.0 mode could not work,I try mpu9250(0x70 is OK) and mpu9250_i2c start -s(ox68 is OK) ,all return -1. MY phonenumber is 18351454190.其他的IIC传感器和GPS我都试了没问题，只有这两个过不去，我没有用这个扩展版https://docs.px4.io/master/en/flight_controller/raspberry_pi_pilotpi.html

Sorry for the inconvenience brought by my pca9685_pwm_out driver. It's known to be broken since recent PWM architecture change, but I haven't found time to integrate it properly. Will do it this month to ensure the usability, with my best effort.

mpu9250 is just too 'old' so that I finally decided to replace it with newer icm4xxxx. Sorry but I cannot provide any useful help here

**Comment by s175217** [comment]
@SalimTerryLi I just couldn't believe that,the second problem is because of  a "," in your /scumaker/pilotpi/src/spi.cpp {{initSpiDev(24688p,0),initSpiDev(24605,0), } the last ","?WHY?Now imu start -s succeses.
Please give me some cookies about the change of PWM arch, Pi2B does and 4B does not,thanks very much.

**Comment by s175217** [comment]
@SalimTerryLi ADD:the driver "pcm9685" before your "pcm9685_pwm_out",I cancle the #/nutty/clock.h,Now it's successful.

**Comment by s175217** [comment]
@SalimTerryLi 2FAULTS:9685WRAPPER::CDEV{NULLptr},NULL must be char ; RUN( ){ STATE::INIT : if else LOGIC FAULT}

**Pull request merged**
