### PR TITLE
v5_stackcheck: disable CONFIG_DRIVERS_TONE_ALARM

### PR DESCRIPTION
**Pull request by sfuhrer**
v5_stacktest is above the flash limit. 

I'm not fully in the loop what this build is for, but with disabling the DRIVER_TONE_ALARM it passes again. Is it okay to exclude that from the build?

### CODE REVIEW

**Comment by sfuhrer** [comment]
@MaEtUgR fyi

**Review by MaEtUgR — APPROVED** [review]
I also don't know what it's used for. From the name presumably to start all things at once and see if there's any RAM problem? Is tone alarm part of this? Should we instead kick out some other driver that's not part of the test?

**Comment by dagar** [comment]
It's a build of px4_fmu-v5 with NuttX CONFIG_ARMV7M_STACKCHECK enabled. It's somewhat helpful for catching stackoverflows before they lead to a more subtle failure, but due to the guards it adds the resulting build can be much slower with different stack usage, so it's not necessarily representative.

**Comment by dagar** [comment]
It's useful in the sense that if the px4_fmu-v5_stackcheck build can boot and run successfully (a stackoverflow with cause a hardfault) then the regular builds will almost certainly have sufficient stack allocations.

**Pull request merged**
