### PR TITLE
standard vtol deprecated parameter update

### PR DESCRIPTION
**Pull request by frede791**
### Solved Problem
When launching the standard VTOL I found that an error would pop up suggesting that parameter `FW_L1_PERIOD` has not been found. This parameter is deprecated but still present in the airframe file for the standard VTOL. 

### Solution
Rename the parameter to its new name: `NPFG_PERIOD`

### Context
Before:
Screenshot from 2023-11-03 15-20-36

After:
image

### CODE REVIEW

**Comment by dagar** [comment]
FW_L1_PERIOD -> NPFG_PERIOD

**Comment by frede791** [comment]
So update rather than remove...

**Comment by frede791** [comment]
@dagar Anything else that needs to be done here?

**Comment by frede791** [comment]
@dagar Can this be merged?

**Review by dagar — APPROVED** [review]

**Comment by dagar** [comment]
There's a merge conflict.

**Review by dagar — APPROVED** [review]

**Pull request merged**
