### PR TITLE
Linux mint 21.3 support

### PR DESCRIPTION
**Pull request by asifpatankar**
### Solved Problem
When executing ubuntu.sh script on Linux Mint 21.3 (based on Ubuntu 22.04), the script failed to recognize the OS and install correct dependencies, particularly for Java and Gazebo Garden.

### Solution
- Added Linux Mint 21.3 detection to ubuntu.sh
- Set Java version 11 for Linux Mint 21.3 compatibility
- Configured Gazebo Garden installation using Ubuntu Jammy repositories for Linux Mint 21.3

### Changelog Entry
For release notes:
```
Bugfix: Added Linux Mint 21.3 support to ubuntu.sh installation script
Documentation: No changes needed
```

### Test coverage
- Tested on Linux Mint 21.3
- Successfully installed all dependencies including Java 11 and Gazebo Garden
- Before/After screenshots showing successful Java installation attached

### Context
The changes ensure proper detection of Linux Mint 21.3 and installation of correct dependencies, allowing PX4 development environment setup on Linux Mint 21.3 systems. Screenshots show successful Java installation after the modifications.

The modifications maintain compatibility with existing Ubuntu installations while adding support for Linux Mint 21.3 users.
Before_JRE
After_JRE

### CODE REVIEW

**Comment by mrpollo** [comment]
It looks like there's something wrong with your branch, can you please clean it up so we can review?

**Comment by Perrrewi** [comment]
You can try to rebase to resolve it. I was unable to test it, but according to the documentation gz-harmonic should work on Linux mint 21.3. I put some links here: https://github.com/PX4/PX4-Autopilot/pull/24089

**Comment by asifpatankar** [comment]
I'll give harmonic as well try to remake a branch.

**Comment by Perrrewi** [comment]
Thanks for https://github.com/PX4/PX4-Autopilot/pull/24100, can we close this (#24097 ) PR?

**Comment by MaEtUgR** [comment]
It looks like https://github.com/PX4/PX4-Autopilot/pull/24100 is the successor to this pr. If not please reopen and rebase the branch.

**Pull request closed without merging**
