### PR TITLE
Update submodule libcanard to latest Wed May 19 00:39:11 UTC 2021

### LINKED ISSUE #163: Inf / NaN handling
NuttX currently has in some cases issues with printing INF / NaN values (prints a lot of zeros or RAM content). This is not a PX4 Firmware issue, but still needs to be addressed soon, as more and more code is contributed where developers are not aware that they need to work around this by testing with isfinite() the value of the float/double before printing it.

### PR DESCRIPTION
**Pull request by dagar**
- libcanard in PX4/Firmware (ffe9f8a942c8e4330b30f35130aad64876f47505): https://github.com/UAVCAN/libcanard/commit/55938c51cf7da3096679933302693c9dae7a2b33
    - libcanard current upstream: https://github.com/UAVCAN/libcanard/commit/38796831f9083c0f0674319543d8d10813429eb5
    - Changes: https://github.com/UAVCAN/libcanard/compare/55938c51cf7da3096679933302693c9dae7a2b33...38796831f9083c0f0674319543d8d10813429eb5

    3879683 2021-05-18 Pavel Kirienko - Add canardRxAccept2(), fix #163 (#164)

### CODE REVIEW

**Comment by PetervdPerk-NXP** [comment]
LGTM

**Comment by JacobCrabill** [comment]
FYI @PetervdPerk-NXP the build failures look real: https://github.com/PX4/PX4-Autopilot/pull/17608/checks?check_run_id=2746029941#step:7:838

**Comment by JacobCrabill** [comment]
Was just a bad variable name (`_port_id` vs. `port_id`) - fixed now.

**Comment by JacobCrabill** [comment]
Is this now just completely out of date / redundant?  Can probably close it.

**Comment by PetervdPerk-NXP** [comment]
It's out of date, I've updated the submodule in another PR already it seems, we can close this one.

**Pull request closed without merging**
