### PR TITLE
magnetometer allow setting initial calibration from magnetometer bias if available

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by bresch** [comment]
>> That's really cool. I tried the PR on my bench setup and it seems to work as expected. However, I have a few remarks:
>> a user would not be aware of that feature if there is no feedback on QGC
>>They could indirectly through mavlink sys status flags, QGC sensor setup status, or potentially the overall system ready.

> Did you have anything in mind? I'm not a fan of STATUSTEXT messages.

Well, best would be to have a "quality progress bar" in the calibration tab showing the fitness status of each axis. Then the user could click on "save current estimated bias" when happy with the quality level.
Is it possible to send that data to QGC without having to create a new mavlink message?

**Comment by dagar** [comment]
I've updated `SENS_MAG_AUTOCAL` to be disabled by default.

**Comment by ryanjAA** [comment]
I’m not sure I understand. If initial mag calibration isn’t done, where does the mag bias come from? The ekf2?

Trying to understand this a bit more and how to use it.

**Comment by dagar** [comment]
> I’m not sure I understand. If initial mag calibration isn’t done, where does the mag bias come from? The ekf2?
> 
> Trying to understand this a bit more and how to use it.

This is using the new mag bias estimator that works on the ground. https://github.com/PX4/PX4-Autopilot/pull/18327

**Comment by ryanjAA** [comment]
@dagar Oh that is cool!

So neat. It is reliable enough for a fixed wing takeoff?

This is great!

**Comment by dagar** [comment]
> So neat. It is reliable enough for a fixed wing takeoff?
>

It really depends on the vehicle specifics. If you take a look at an existing good clean mag calibration and the scale factors are very close to 1 then this is likely sufficient. At the end of every good flight any ekf2 estimated magnetometer bias will be factored back into the mag cal, so it's automatically improving over time.

Please keep in mind that the full 6 orientation mag cal nice is probably always going to produce the superior calibration.

**Comment by dagar** [comment]
Merging with `SENS_MAG_AUTOCAL = 0` as the default until the parameter system concerns can be addressed.

**Pull request merged**
