### PR TITLE
SIH: ellipsoidal earth

### PR DESCRIPTION
**Pull request by bresch**
requires https://github.com/PX4/PX4-Autopilot/pull/24034

### Solved Problem
I needed a simulation environment on an ellipsoidal world to test https://github.com/PX4/PX4-Autopilot/pull/23854 .

### Solution
Run SIH in an ECEF coordinate system with a WGS84 Earth model and convert the output to the usual global (lat/lon/alt) and local tangent plane frame.
The objective is to test the robustness of the EKF by changing the Earth spin rate and radius to exaggerate the non-inertial accelerations measured when navigating on an ellipsoidal environment.

### Changelog Entry
```
New parameter: -
TOTO: mention this in the SIH documentation
```

Testing:
- [x] quad short distances
- [x] quad long distances
- [x] fixedwing (requires https://github.com/PX4/PX4-Autopilot/pull/24034)
- tailsitter -> sim is also broken in `main`, will fix it after this is merged

### CODE REVIEW

**Comment by bresch** [comment]
Thanks for the tests @romain-chiap . FW sim failed because I forgot to commit some fixes in the other PR (https://github.com/PX4/PX4-Autopilot/pull/24034/commits/76e9cf88267cd9f4deebaa7089160b5a6b6518da). I added it and rebased this one on top; could you give it a try again please?

**Comment by romain-chiap** [comment]
Thanks, so I tried again SITL quadx and airplane: they both work fine.

I was able to reach 230km with the airplane, then I got 
```
ERROR [vehicle_magnetometer] MAG #0 failed:  TIMEOUT!	
WARN  [health_and_arming_checks] Preflight Fail: High Accelerometer Bias
WARN  [health_and_arming_checks] Preflight Fail: No valid data from Compass 0
```
image

I still have the same problems on HITL: quadx can fly in altitude but not in position, FW is unstable at takeoff.

**Comment by bresch** [comment]
> I get a Preflight Fail: height estimate not stable, then it's working

I found the issue and fixed it here: https://github.com/PX4/PX4-Autopilot/pull/24050

**Comment by bresch** [comment]
>  was able to reach 230km with the airplane, then I got 
ERROR [vehicle_magnetometer] MAG #0 failed:  TIMEOUT!	
WARN  [health_and_arming_checks] Preflight Fail: High Accelerometer Bias
WARN  [health_and_arming_checks] Preflight Fail: No valid data from Compass 0

Hmm, I'm wondering where this is coming from. I flew 400km at Mach 1 without issues with the quadcopter model (without drag). Did you run the sim for a really long time?

**Comment by romain-chiap** [comment]
> Hmm, I'm wondering where this is coming from. I flew 400km at Mach 1 without issues with the quadcopter model (without drag). Did you run the sim for a really long time?

I flew at 12 m/s with the airplane for about 7min. I ran the STIL as fast as possible (PX4_SIM_SPEED_FACTOR=1000), which was about x44 on my laptop.

**Review by haumarco — DISMISSED** [review]

**Comment by bresch** [comment]
@haumarco had it working, could you comment on that please?

**Comment by haumarco** [comment]
@romain-chiap 
I used this PR as a basis:
https://github.com/PX4/PX4-Autopilot/pull/24034

and then changing HIL_ACT_REV to 1 also made it work.

**Comment by romain-chiap** [comment]
On HITL fmu-f5 it works with HIL_ACT_REV=0 and doesn't work with HIL_ACT_REV=1. 
As I understand on your setup it works with HIL_ACT_REV=1 and not with HIL_ACT_REV=0. Which setup did you use?

Can we implement something that works on all platforms? Something designed for the control allocation module?

**Pull request merged**
