### PR TITLE
drivers/imu/invensense: store offset registers on configure, trigger reset on any change

### PR DESCRIPTION
**Pull request by dagar**
- fix for https://github.com/PX4/PX4-Autopilot/issues/17804

@NicolasM0 could you use this branch for your next attempted reproduce?

### CODE REVIEW

**Comment by NicolasM0** [comment]
Here is a log with this patch: https://drive.google.com/file/d/1ppwDihhE5WGVh48Qdf4ExwcuvfBYGLIA/view?usp=sharing
The issues have not been reproduced !

acc_int_dt_patch

**Comment by NicolasM0** [comment]
With 1.12-beta5 on the same CUAV v5+ unit, I had : https://drive.google.com/file/d/1SzOaOcWYg99Y-BOUoyc_pKfHt1Gutokz/view?usp=sharing
acc_int_dt_1 12

**Comment by NicolasM0** [comment]
But now I have a lot of switches bewteen sensors: 
1 12_patch_sensor_selection

**Comment by NicolasM0** [comment]
BMI055 gyro and accel integration time is also not very stable bit not sure if it is an issue as it kept within certain boundaries

**Comment by dagar** [comment]
> The issue has not been reproduced !

That's good to hear, I'll update the PR so that it can be merged (debug off) and next we'll look at the integration edge cases (bmi055).

> But now I have a lot of switches between sensors:

I would say that's actually not too many switches over something like three and a half hours, but let's take a closer look.

> BMI055 gyro and accel integration time is also not very stable bit not sure if it is an issue as it kept within certain boundaries

The BMI055 is really a separate accel and gyro, and annoyingly the output data rates are slightly different from each other.

`INFO  [vehicle_imu] 2 - Accel ID: 4259850, interval: 2474.5 us (SD 162.1 us), Gyro ID: 4325386, interval: 2503.7 us (SD 4.6 us)`

I'll see if I can update the IMU integration code to be more accommodating of the jitter in the BMI055 output.

**Comment by NicolasM0** [comment]
> I would say that's actually not too many switches over something like three and a half hours, but let's take a closer look.

I rised this point just because it seems different from what I have seen before this patch. 
on 1.12-beta5
1 12_estimator_selection

on this branch
1 12_patch_estimator_selection

I didn't know if switches have to be expected in normal operartion. I will have a look on estimator selection.

Thank you these prompt replies and solutions !

**Comment by dagar** [comment]
@NicolasM0 I have a few minor IMU integration improvements in https://github.com/PX4/PX4-Autopilot/pull/17817. Separately I can also improve a few things at the driver level to tolerate any occasional jitter (3 IMUs fighting on the same SPI bus).

**Review by NicolasM0 — APPROVED** [review]

**Comment by dagar** [comment]
@NicolasM0 I suspect this PR is what changed the selection performance you noticed. 
https://github.com/PX4/PX4-Autopilot/pull/17699

In particular the selection logic here handling the initialized test ratio case. https://github.com/PX4/PX4-Autopilot/blob/9d3e18dbe10700a13f3048f2807dc4b1a62eee62/src/modules/ekf2/EKF2Selector.cpp#L285-L303

In your log I can see the combined_test_ratio for a certain instance briefly jumping to 1, but the log doesn't seem to have caught why.

Screenshot from 2021-06-29 09-49-55

Screenshot from 2021-06-29 09-50-58

A log with `estimator_status` at a higher rate might show us what's happening.

I don't think this is necessarily a problem as its only occasionally switching from one healthy instance to another, but I'd still like to figure out what's going on.

**Comment by dagar** [comment]
I suspect it's the baro innovation test ratio getting too close to 0.

Screenshot from 2021-06-29 10-10-34

**Comment by dagar** [comment]
Possible solution (unverified).
 - https://github.com/PX4/PX4-Autopilot/pull/17820
 - https://github.com/PX4/PX4-ECL/pull/1020

**Comment by NicolasM0** [comment]
I have made a new log of 5.5h on this branch with estimator_status at the maximal rate but I did not have any switch (apart at the beginning). 
This time, BMI055 has been selected and kept.

The main difference is that I did not have a gps this time. Maybe pos or vel test ratio is the cause...
I can make a new log with gps tomorrow.

**Comment by dagar** [comment]
> I have made a new log of 5.5h on this branch with estimator_status at the maximal rate but I did not have any switch (apart at the beginning).
> This time, BMI055 has been selected and kept.
> 
> The main difference is that I did not have a gps this time. Maybe pos or vel test ratio is the cause...
> I can make a new log with gps tomorrow.

Thanks for the update. I would see if https://github.com/PX4/PX4-ECL/pull/1020 + https://github.com/PX4/PX4-Autopilot/pull/17820 makes a difference in the GPS case.

**Comment by NicolasM0** [comment]
> Thanks for the update. I would see if [PX4/PX4-ECL#1020](https://github.com/PX4/PX4-ECL/pull/1020) + #17820 makes a difference in the GPS case.

Here is the new log with GPS plugged in, on this branch without [PX4/PX4-ECL#1020](https://github.com/PX4/PX4-ECL/pull/1020) + #17820 with estimator_status logged at full rate: https://drive.google.com/file/d/18bohotO2B8qaGFdq6Un8gz2oBmjIZkD9/view?usp=sharing

There are switches : 
1 12_patch_estimator_selection_2

hgt_test_ratio is sometimes equal to 0 and switches happen at these instants.
So you were right and your patch in ECL should fix that.

**Pull request merged**
