### PR TITLE
[Board Support] Rename AirPi2 to PilotPi, and add more options

### PR DESCRIPTION
**Pull request by SalimTerryLi**
Done.

1. Rename AirPi2 to PilotPi
2. Add aarch64 toolchain
3. Add support for ARM64 target
4. aarch64 docker and CI build test
5. move IST8310 onto internal I2C bus

### CODE REVIEW

**Comment by SalimTerryLi** [comment]
@dagar I want to reduce those redundant cmake configs with only toolchain differs. Any idea?

**Comment by dagar** [comment]
> @dagar I want to reduce those redundant cmake configs with only toolchain differs. Any idea?

What's the use case, wanting the same board config to build with either 32 and 64 bit? How do you want to decide?

**Comment by SalimTerryLi** [comment]
> > @dagar I want to reduce those redundant cmake configs with only toolchain differs. Any idea?
> 
> What's the use case, wanting the same board config to build with either 32 and 64 bit? How do you want to decide? 

https://github.com/PX4/px4_user_guide/pull/848

Here is corresponding docs. User should decide the architecture based on what OS they want to use.

**Comment by dagar** [comment]
You could try having a single `arm-linux-gnueabihf-gcc` toolchain that first looks for aarch64, but can otherwise fall back. 

It's a little sloppy if there are any cases where 32 vs 64 is going to bite you, but I suspect for PX4 on Linux we'll be able to get away with it.

**Comment by SalimTerryLi** [comment]
@dagar It's ready. Please review it.

**Review by dagar — APPROVED** [review]

**Pull request merged**
