### PR TITLE
RM3100 self-test procedure revision

### PR DESCRIPTION
**Pull request by spiderkeys**
**Describe problem solved by this pull request**
We have been experiencing intermittent failures with RM3100 initialization, wherein the BIST sometimes fails due to the STATUS register's DRDY bit not being set after firing off the POLL command. In this event, the current code fails the BIST outright. Beyond that, after reading through the BIST section of the datasheet, there are a few additional checks/actions that need to be taken to ensure that the results of the self-test are valid and that the BIST mode is exited upon completion.

**Describe your solution**
This PR addresses these issues in the following ways:
1. Adding some basic retry logic in the event that the DRDY bit was not upon checking the first time.
2. The results of the test are only valid if STE is set in the results, so this check is performed.
3. After the test is complete, BISTmode should be exited. It is unclear from the datasheet if there is any explicit automatic exit of BIST mode, so this takes the precautionary action of explicitly clearing STE, such that future POLL commands do not unintentionally trigger additional self-tests. I've seen this done in some reference drivers elsewhere, as well as seen it not done at all. There shouldn't be any harm, so I felt it was worth adding in.

**Test data / coverage**
I've tested this on a Matek H743 Wing. Since adding the logic, I have not failed any BIST tests, and with some temporary logging, I have observed instances where the check_measurement() method indicates the POLL result is not ready, which then triggered the retry logic and led to a successful test. Subscribing to the sensor_mag uorb topic, the output of the sensor appears reasonable.

### CODE REVIEW

**Comment by dagar** [comment]
As discussed ideally we don't want these drivers sleeping at all (in a work queue thread), but for now can we just keep the time to a minimum?

**Comment by spiderkeys** [comment]
@dagar just took a pass through the code and did some benchmarking/testing of a few things.

First, the initial sleep + collection that was originally in the driver doesn't seem to be necessary anymore, since my new code performs validity checks to make sure the BIST STE bit is set when reading the results after a poll. I removed this code and tested on a couple boards, finding no issues.

Next, I benchmarked the entire BIST process. On average, for a properly function sensor that passes the test, the new total duration is between 1.7 to 2.5 ms. Though the BIST is triggered by issuing a poll when using the STE bit in the command, it seems it does not take a full collection period (default config sets this at ~7ms/150Hz) for the DRDY bit to get set.

Lastly, I reduced the overall retry window to 20ms (two poll periods, though even this does not seem to be necessary), and reduced the retry delays to 500us.

Worst case for this function (when a device fails to complete the BIST) should now be down to 20-25ms, roughly the same as the original code. Interestingly, I do have one RM3100 in my stock that exhibits this behavior and never completes the BIST, while my other units always succeed in the 1.7-2.5ms period. A total duration measurement on this failing unit came out to 19ms fairly consistently.

Overall, the happy path should now be ~18ms faster than the original code now, since it is possible to traverse it with zero sleeps, only blocking for the duration of the I2C transactions. I have captured a trace of this, included below.

Screenshot from 2022-02-20 18-38-27

**Comment by spiderkeys** [comment]
Thinking about it a little more, the retry `usleep` isn't actually necessary at all, so I've removed it. The total time for my BIST non-completing board is still ~19-21ms, it just gets more test attempts now without the 500us sleep.

**Comment by dagar** [comment]
CI failure is the CUAV x7pro on the test rack which has an internal rm3100. http://px4-jenkins.dagar.ca:8080/blue/organizations/jenkins/PX4-Autopilot/detail/PR-19207/5/pipeline/122
Screen Shot 2022-02-20 at 10 41 11 PM

**Comment by spiderkeys** [comment]
Interesting. I added a bit of code just now to pritn the REVID of the sensor, to see if there was some difference between my working and non-working boards, but they both return 34.

Reading through the HSHAKE register functions, I might be able to get some more information about what is happening. On my non-working board, the STATUS register reads continuously return 0x21 (no DRDY bit, and the other bits are described as indeterminate/to-be-ignored).

I'll see if HSHAKE can help dig into the differences between my boards, which may provide some insight on this cUAV failure.

**Comment by spiderkeys** [comment]
After running some experiments with both my local failing board and the CI cUAV board, these are my observations:

1. The HSHAKE register default values for DRC0 and DRC1 are 1, which mean that the DRDY bit will be automatically cleared upon any register write operations or data measurement reads, respectively. This means that the POLL command clears DRDY each time it is written in the retry cycle, ultimately leading us to never complete.
2. The cUAV board has the RM3100 connected via SPI, vs my boards which are I2C. My guess is that the SPI operations block for much less time than the I2C transactions my boards are using, leading to a situation where DRDY is not set, so it actually triggers the retry logic. Without the automatic DRDY-clearing disabled, this basically continuously aborts the BIST. For I2C boards, the blocking transactions are likely slowing things down enough that DRDY is set by the first time it is checked.
3. My local problematic I2C board appears to truly be failing the BIST, in that it never sees DRDY go high, no matter how long I wait, even when simplifying the BIST process to the basic elements of CONFIG->POLL->SLEEP(100ms+)->CHECK_DRDY->READ_RESULTS. 

If anyone else has an I2C RM3100 laying around, it would be interesting to see if this new BIST process works for them consistently.

All of that said, the CI tests now seem to be passing, and I get consistently good results with a few of my I2C boards, and consistent failures from one of them.

**Review by dagar — APPROVED** [review]

**Pull request merged**
