### PR TITLE
boards/px4: enable flow control on CDCACM

### PR DESCRIPTION
**Pull request by julianoes**
**Describe problem solved by this pull request**

This enables flow control on CDCACM for the px4 boards which fixes a problem where HITL would stall.

The stall could happen if the hardware would be a bit too slow in keeping up with the incoming messages. Often, this happened on arming because the logger would take some time to log all parameters right at the beginning.

The stall would then not recover due to NuttX bug where the rx interrupt would not be restored correctly and instead only a slower watchdog would release the next read. This watchdog takes 200ms which means it's hard to impossible to get out of the situation without restarting sim and/or PX4.  For more information about the issue, see:
https://github.com/apache/incubator-nuttx/pull/3633

**Describe your solution**

As a workaround, until that bug is fixed, and because it makes sense anyway, I propose to enable FLOWCONTROL for the serial via USB.

**Describe possible alternatives**
As an alternative we could just reduce the [watchdog time](https://github.com/PX4/NuttX/blob/px4_firmware_nuttx-10.0.0%2B/drivers/usbdev/cdcacm.c#L80).

**Test data / coverage**
Bench testing was done for fmu-v4.

FYI @davids5

### CODE REVIEW

**Comment by dagar** [comment]
Any downsides? I'd prefer we do it everywhere by default to keep things in sync.

**Comment by dagar** [comment]
I would do it by NuttX architecture. If it's been validated on fmu-v4 (stm32f4), fmu-v5 (stm32f7), and fmu-v6 (stm32h7) then we might as well ripple it across all boards using those chips.

**Comment by dagar** [comment]
I've made the change across all the other boards. I believe we only need to worry about the same basic test per NuttX architecture (stm32f4, f7, h7, etc). I'll check a few more boards tomorrow like kinetis, but so far so good (fmu-v5, v4, etc).

**Comment by julianoes** [comment]
Great, thanks @dagar!

**Comment by julianoes** [comment]
@dagar what can I do to push this forward?

**Review by LorenzMeier — DISMISSED** [review]

**Comment by LorenzMeier** [comment]
Given the API layering in NuttX I think the test coverage you have is sufficient on the board.

**Comment by julianoes** [comment]
@dagar as discussed on the dev call this does **not** need to be merged before the release because we have the NuttX backport to fix HITL: https://github.com/PX4/NuttX/commit/94f9653326a115962c0ccabcaf898a7f754b7afa.

**Comment by julianoes** [comment]
@dagar or @davids5 if you think we still want this, I can rebase it and get it in, otherwise I'll close it.

**Comment by davids5** [comment]
> @dagar or @davids5 if you think we still want this, I can rebase it and get it in, otherwise I'll close it.

If the root cause was fixed in NuttX and part of the PX4 build now. The value proposition of this PR depends on it performance gain.  Do we have any metrics?

**Comment by julianoes** [comment]
@dagar we might as well activate it and see how it goes? If there are no complaints, it should not be worse, right?

**Comment by dagar** [comment]
> @dagar we might as well activate it and see how it goes? If there are no complaints, it should not be worse, right?

I gave it a quick test and didn't see anything different. It's an additional code path that hasn't been heavily tested that might not provide any benefit. That being said, I have no objection. Rebase and let's give it a try?

**Pull request merged**
