### PR TITLE
[dds] microdds_client: rename to uxrce_dds_client

### PR DESCRIPTION
**Pull request by beniaminopozzan**
This draft PR renames the current `microdds_client` module to **xrcedds_client** and unify the notation.

| | old version | new version |
|-|-|-|
| module name | `microdds_client` | **`xrcedds_client`** |
| strings / comments about the module | non consistent | **XRCE-DDS Client** |
| menuconfig option | `MODULES_MICRODDS_CLIENT` | **`MODULES_XRCEDDS_CLIENT`** | 
| module parameters group name | `Micro XRCE-DDS` | **XRCE-DDS Client** |
| module parameters name prefix | `XRCE_DDS_` | `XRCE_DDS_` |
| module class name | `MicroddsClient` | **`XrceddsClient`** |
|`init.d/rcS` whenever the module is mentioned | `microdds` | **`xrcedds`** |

First step for #21383 

If there are no objections to the new naming then the next step will be to update the documentation.

~~The PR depends on #21375 as it touches the microdds_client module.~~

*Note*:
As the submodule `Micro-XRCE-DDS-Client` has been moved due to the renaming, to safely move to the PR branch the following commands should be used

```sh
make distclean
git checkout pr-microdds_client-to-xrcedds_client
git submodule update --init --recursive
```

## Test
Tested in SITL and on Pixhawk v6x

### CODE REVIEW

**Comment by dagar** [comment]
Let's split `xrcedds` into `xrce_dds` or `xrce-dds` to avoid confusion?

**Comment by beniaminopozzan** [comment]
@dagar , like this?

| | old version | new version - updated in bold |
|-|-|-|
| module name | `microdds_client` | **`xrce_dds_client`** |
| strings / comments about the module | non consistent | XRCE-DDS Client |
| menuconfig option | `MODULES_MICRODDS_CLIENT` | **`MODULES_XRCE_DDS_CLIENT`** | 
| module parameters group name | `Micro XRCE-DDS` | XRCE-DDS Client |
| module parameters name prefix | `XRCE_DDS_` | `XRCE_DDS_` |
| module class name | `MicroddsClient` | `XrceddsClient` |
|`init.d/rcS` whenever the module is mentioned | `microdds` | `xrcedds` |

I just changed the module name and the menuconfig option. I picked `_` instead of `-` as it seems the convention across all other modules.

**Comment by TSC21** [comment]
@beniaminopozzan I don't think this makes sense. Micro XRCE-DDS Client is a library, and not necessarily the application that runs on the FMU. The `microdds_client` follows the approach that was taken with `micrortps_client` with Fast-RTPS: Fast-RTPS is a library implementation of OMG RTPS protocol.

**Comment by TSC21** [comment]
If we are talking about consistency, then I would call it `uxrce_dds_client` then.

**Comment by beniaminopozzan** [comment]
Thanks @TSC21 for the suggestion!
I personally don't have a strong preference between the possible solutions, but I see your point to not confuse the library with the application using it. I think the main consistency issue is not between library and application, but between actual source code and documentation, where microdds and XRCE-DDS are mixed, and source code and parameters, as the module is named `microdds_client` but all parameters are in the form `XRCE_DDS_*`.

In v1.13 the microRTPS doc page was called **RTPS/DDS Interface: PX4-Fast RTPS(DDS) Bridge** while now it is **XRCE-DDS (PX4-FastDDS Bridge)**.

So, second proposal:

| | old version | new version |
|-|-|-|
| module name | `microdds_client` | **`uxrce_dds_client`** |
| strings / comments about the module | non consistent | **UXRCE-DDS Client** |
| menuconfig option | `MODULES_MICRODDS_CLIENT` | **`MODULES_UXRCEDDS_CLIENT`** | 
| module parameters group name | `Micro XRCE-DDS` | **UXRCE-DDS Client** |
| module parameters name prefix | `XRCE_DDS_` | `UXRCE_DDS_` |
| module class name | `MicroddsClient` | **`UxrceddsClient`** |
|`init.d/rcS` whenever the module is mentioned | `microdds` | **`uxrcedds`** |
| main doc page name | XRCE-DDS (PX4-FastDDS Bridge) | **uXRCE-DDS (PX4-micro XRCE-DDS Bridge)**|

That said, also going full `microdds_client` is a possibility, third proposal:

| | old version | new version |
|-|-|-|
| module name | `microdds_client` | `microdds_client` |
| strings / comments about the module | non consistent | **microdds_client** |
| menuconfig option | `MODULES_MICRODDS_CLIENT` | `MODULES_MICRODDS_CLIENT` | 
| module parameters group name | `Micro XRCE-DDS` | **Micro DDS Client** |
| module parameters name prefix | `XRCE_DDS_` | **`MICRO_DDS_`** |
| module class name | `MicroddsClient` | `MicroddsClient`|
|`init.d/rcS` whenever the module is mentioned | `microdds` | **`microdds_client`** |
| main doc page name | XRCE-DDS (PX4-FastDDS Bridge) | XRCE-DDS (PX4-FastDDS Bridge) |

---

The initial solution (`xrce_dds_client`) was proposed to start a common naming convention based on the protocol used. In that way adding and distinguishing between new bridges based on different protocols would have been easier.

Anyway, about the SEO for searchability of the docs #21383, searching `microdds` already shows all relevant resources: MicroROS, micro XRCE-DDS and PX4 doc

**Comment by TSC21** [comment]
> Thanks @TSC21 for the suggestion! I personally don't have a strong preference between the possible solutions, but I see your point to not confuse the library with the application using it. I think the main consistency issue is not between library and application, but between actual source code and documentation, where microdds and XRCE-DDS are mixed, and source code and parameters, as the module is named `microdds_client` but all parameters are in the form `XRCE_DDS_*`.
> 
> In v1.13 the microRTPS doc page was called **RTPS/DDS Interface: PX4-Fast RTPS(DDS) Bridge** while now it is **XRCE-DDS (PX4-FastDDS Bridge)**.
> 
> So, second proposal:
> 
> old version	new version
> module name	`microdds_client`	**`uxrce_dds_client`**
> strings / comments about the module	non consistent	**UXRCE-DDS Client**
> menuconfig option	`MODULES_MICRODDS_CLIENT`	**`MODULES_UXRCEDDS_CLIENT`**
> module parameters group name	`Micro XRCE-DDS`	**UXRCE-DDS Client**
> module parameters name prefix	`XRCE_DDS_`	`UXRCE_DDS_`
> module class name	`MicroddsClient`	**`UxrceddsClient`**
> `init.d/rcS` whenever the module is mentioned	`microdds`	**`uxrcedds`**
> main doc page name	XRCE-DDS (PX4-FastDDS Bridge)	**uXRCE-DDS (PX4-micro XRCE-DDS Bridge)**
> That said, also going full `microdds_client` is a possibility, third proposal:
> 
> old version	new version
> module name	`microdds_client`	`microdds_client`
> strings / comments about the module	non consistent	**microdds_client**
> menuconfig option	`MODULES_MICRODDS_CLIENT`	`MODULES_MICRODDS_CLIENT`
> module parameters group name	`Micro XRCE-DDS`	**Micro DDS Client**
> module parameters name prefix	`XRCE_DDS_`	**`MICRO_DDS_`**
> module class name	`MicroddsClient`	`MicroddsClient`
> `init.d/rcS` whenever the module is mentioned	`microdds`	**`microdds_client`**
> main doc page name	XRCE-DDS (PX4-FastDDS Bridge)	XRCE-DDS (PX4-FastDDS Bridge)
> The initial solution (`xrce_dds_client`) was proposed to start a common naming convention based on the protocol used. In that way adding and distinguishing between new bridges based on different protocols would have been easier.
> 
> Anyway, about the SEO for searchability of the docs #21383, searching `microdds` already shows all relevant resources: MicroROS, micro XRCE-DDS and PX4 doc

I think the main point of decision is if we want to leverage an implementation that is ours (the PX4 client) vs advertising eProsima's library. Nothing against the 2nd, but we did a bit more than just consuming a library. So calling it Micro DDS for me is actually nice. But up to you guys - unfortunately I haven't been taking an active role on this matter, but I am quite happy that what I presented on the PX4 and ROS World talks is actually coming to reality :D Really happy to see the result of all of this and thanks all for the good work!

**Comment by dagar** [comment]
> I think the main point of decision is if we want to leverage an implementation that is ours (the PX4 client) vs advertising eProsima's library. Nothing against the 2nd, but we did a bit more than just consuming a library. So calling it Micro DDS for me is actually nice.

It's about calling it what it is actually is and not being overly generic, ideally in a way that's consistent in all our usage and passes the google test.

There are also people exploring zenoh-pico integration that might lead to yet another "micro DDS" solution that can peacefully coexist as a completely separate thing.

**Comment by hamishwillee** [comment]
FWIW from a readability point of view I find it easier when related things have similar names. The problem here is that we use dds everywhere - both in fastrtps-dds and xrce-dds. So to me the naming thing that catches my eye is XRCE (vs dds). I would prefer a name that includes xrce in it. microdds_client is perhaps the worst of all worlds from this perspective.

Of the ones above, maybe uxrce_dds_client.

I'm not sure whether we need to show it is more than just the eProsima DDS client. But if we do what name would capture the fact that the client implements all that uorb pub/sub stuff? I can't think of one that makes much sense.

Are the parameters all truly generic? I.e. would we use the same parameters in an alternative implementation? If so then I think `XRCE_DDS_` makes sense for generic things that would be used by every implementation, and perhaps if there are some that just configure this particular module, they should follow the module naming convention we choose.

**Comment by beniaminopozzan** [comment]
Taking into account your suggestions, this is the second version:

| | old version | new version (second proposal) |
|-|-|-|
| module name | `microdds_client` | **`uxrce_dds_client`** |
| strings / comments about the module | non consistent | **UXRCE-DDS Client** |
| menuconfig option | `MODULES_MICRODDS_CLIENT` | **`MODULES_UXRCE_DDS_CLIENT`** | 
| module parameters group name | `Micro XRCE-DDS` | **UXRCE-DDS Client** |
| module parameters name prefix | `XRCE_DDS_` | `UXRCE_DDS_` |
| module class name | `MicroddsClient` | **`UxrceddsClient`** |
|`init.d/rcS` whenever the module is mentioned | `microdds` | **`uxrce_dds`** |
| main doc page name | XRCE-DDS (PX4-FastDDS Bridge) | **uXRCE-DDS (PX4-micro XRCE-DDS Bridge)**|

If it is accepted, I'll start updating the documentation :)

**Comment by hamishwillee** [comment]
Works for me! Like anything it is a compromise, but it's a pretty good one.

**Comment by beniaminopozzan** [comment]
The documentation PR https://github.com/PX4/PX4-user_guide/pull/2483 is ready, therefore this can be fully reviewed now!

As it will cause quite a big change once merged I suggest to

1. Merge it.
2. Announce it on Discord #ROS channel and in the forum so that everyone who uses the renamed modules in `main` will not be caught off guard.
3. Check that all links in the updated docs are working.
4. Merge the docs.
5. Announce it on Discord

**Comment by hamishwillee** [comment]
Sounds good. You could announce intent and plan merge for Monday.

**Review by mrpollo — APPROVED** [review]
thanks @beniaminopozzan let's finally get this in!

**Comment by mrpollo** [comment]
⚠️⚠️⚠️Let's merge the Docs PR (https://github.com/PX4/PX4-user_guide/pull/2483) once this PR goes in.⚠️⚠️⚠️

**Comment by mrpollo** [comment]
🎉 thanks @beniaminopozzan 

I successfully tested using networking and serial, param names and client names seem to be updated and commands/params working well

**Pull request merged**
