### PR TITLE
drivers/uavcan: subtree merge last working libuavcan (preserving history)

### PR DESCRIPTION
**Pull request by dagar**
Upstream libuavcan was broken and then marked deprecated. This pull request fully absorbs the libuavcan submodule (renamed libdronecan to deconflict) up to our last good working commit and all commit history is kept.

Other than fixing the regression introduced in https://github.com/PX4/PX4-Autopilot/pull/23113 the goal here is to put us in a much better position to easily evolve the library as needed now that we have full control.

Fixes https://github.com/PX4/PX4-Autopilot/issues/23727

### CODE REVIEW

**Comment by mrpollo** [comment]
scared

**Comment by julianoes** [comment]
@dagar will this break CubeID? I guess I can check.

And how does this relate to https://github.com/dronecan/libcanard? Should we move over to that one?

**Comment by julianoes** [comment]
@dagar you're right, Remote ID still works. I tested both CubePilot CubeID and the Holybro's AP_Periph based remote ID.

**Review by AlexKlimaj — APPROVED** [review]
Looks like this is working. Tested parameters through QGC, firmware dating from the FC, and sensor data from an ARK Flow.

**Comment by dagar** [comment]
This also saves about 3kB of flash.

Thanks everyone.

**Pull request merged**
