### PR TITLE
Septentrio v1.15 backport cleanup

### PR DESCRIPTION
**Pull request by mrpollo**
The previous PR #23386 broke the release branch due to unintentional file overwrites. Hopefully, this PR captures the intention and the functionality.

We need Septentrio to verify this PR builds, flashes, and works before merging.

cc @chiara-septentrio, @flyingthingsintothings

### CODE REVIEW

**Comment by hamishwillee** [comment]
Note, does this imply a need for docs backport @flyingthingsintothings ?

**Comment by flyingthingsintothings** [comment]
Yes, the documentation for v1.15 would have to be updated with the same changes that were made to the main documentation.

**Comment by chiara-septentrio** [comment]
It's probably my fault, it built correctly but the difference in files might not have been updated when making the pull request and I didn't think to check more than the difference I saw on the web interface. So sorry for that.

**Comment by julianoes** [comment]
I've added the commits from  #23415 as well.

**Comment by bresch** [comment]
v1.15 having issues with septentrio config: https://github.com/PX4/PX4-Autopilot/issues/23714#issuecomment-2370671684

**Comment by mrpollo** [comment]
Thanks for the report @bresch I will take a look

**Comment by mrpollo** [comment]
This pr was cherry-picked by @dagar no longer needed so I am closing

**Pull request closed without merging**
