### PR TITLE
PX4IO: Bind if not armed

### PR DESCRIPTION
**Pull request by LorenzMeier**
DSM binding was disabled before if safety was off, which on a lot of multicopters is today the default. The logic is now checking instead for wether the system is armed.

Tested with SPM9645 receiver on commandline and via QGC.

### CODE REVIEW

**Review by dagar — APPROVED** [review]

**Comment by dagar** [comment]
The other missing thing we should add is acknowledging the `vehicle_command`. https://github.com/PX4/PX4-Autopilot/blob/b77bd97d962405f2cda7059a684f3a3116974315/src/drivers/px4io/px4io.cpp#L957-L961

**Comment by dagar** [comment]
FYI @mcsauder

**Comment by dagar** [comment]
I gave this a quick try on a CUAV v5+, but it's still not going into bind mode.

### QGC initiated
``` Console
nsh> WARN  [load_mon] px4io low on stack! (296 bytes left)
WARN  [load_mon] px4io low on stack! (296 bytes left)
INFO  [px4io] Binding DSM-X8 RX
```

### command line
``` Console
nsh> px4io bind dsmx8
INFO  [px4io] Binding DSM-X8 RX
```

The Spektrum satellite never goes into bind (lights blinking), but this same physical setup works if I bind externally first.

I'll have to dig into this later.

**Comment by LorenzMeier** [comment]
Do you have the schematics?

**Comment by dagar** [comment]
> Do you have the schematics?

Only what's online. https://github.com/cuav/hardware/tree/master/V5_Autopilot/V5%2B

**Comment by dagar** [comment]
It looks like the FMU side rc driver (rc_update) is still starting, but not actively doing anything. 

Screenshot from 2020-12-30 11-16-36

**Comment by LorenzMeier** [comment]
That's the difference to FMUv5 - it is not running there.

**Comment by dagar** [comment]
It's a distraction, no change in px4io binding with `rc_update` removed from the build. It should still be fixed though.

**Comment by LorenzMeier** [comment]
Maybe it is - look at the latest change.

**Comment by LorenzMeier** [comment]
Merging based on @dagar's earlier review.

**Pull request merged**
