### PR TITLE
NuttX stm32f7:sdmmc defer invalidate until after DMA completion

### PR DESCRIPTION
**Pull request by dagar**
PX4/NuttX PR https://github.com/PX4/NuttX/pull/170

 - fixes https://github.com/PX4/PX4-Autopilot/issues/18672

### CODE REVIEW

**Comment by dagar** [comment]
The existing `tests file` (re-enabled in this PR) is failing intermittently. We should see if it's related.
Screenshot from 2021-11-21 16-56-19
http://px4-jenkins.dagar.ca:8080/blue/organizations/jenkins/PX4-Autopilot/detail/pr-nuttx-stm32f7_sd_fix/3/pipeline/540

**Comment by davids5** [comment]
@dagar What are there 11 changes in nuttx?

**Comment by davids5** [comment]
@dagar OK I see you are bringing other work not on master.  (can we bring  then in on it's own)?

I reviewed the H7 and it is structured very differently. I also ran test on it and it if only fails when the disk is really full.
```
nsh> ERROR [logger] write failed errno:28 (No space left on device), retrying
ERROR [logger] write failed (28)
INFO  [logger] closed logfile, bytes written: 4289462272

nsh> df
  Block    Number
  Size     Blocks       Used   Available Mounted on
     0          0          0           0 /bin
   512        630        630           0 /etc
 32768     242304     242304           0 /fs/microsd
     0          0          0           0 /proc
nsh>
```

I want to look at a few things then I will upstream the F7 changes.

**Comment by dagar** [comment]
The other NuttX changes have gone in separately.

**Comment by dagar** [comment]
Hard fault on px4_fmu-v5_debug running sd_bench. http://px4-jenkins.dagar.ca:8080/blue/organizations/jenkins/PX4-Autopilot/detail/pr-nuttx-stm32f7_sd_fix/4/pipeline/343
Screen Shot 2021-11-22 at 6 22 55 PM

**Comment by davids5** [comment]
> Hard fault on px4_fmu-v5_debug running sd_bench. http://px4-jenkins.dagar.ca:8080/blue/organizations/jenkins/PX4-Autopilot/detail/pr-nuttx-stm32f7_sd_fix/4/pipeline/343 Screen Shot 2021-11-22 at 6 22 55 PM

@dagar Looking at this now. I can not even get to a command prompt the load is so high

**Comment by davids5** [comment]
@dagar let's get https://github.com/PX4/PX4-Autopilot/pull/18699 in then repoint and retest this.

**Comment by dagar** [comment]
> @dagar let's get #18699 in then repoint and retest this.

#18699 merged and this PR has been rebased on master.

**Comment by davids5** [comment]
@dagar Nuttx Change merged upstream and here this PR repointed to PX4 Nuttx tip

**Comment by dagar** [comment]
For now I've removed the Jenkins changes that fail the overall build if mkfatfs doesn't succeed.

**Comment by dagar** [comment]
We still need to get mkfatfs working everywhere and debug the intermittent px4_fmu-v5_debug hard fault, but in general this seems to have fixed things on stm32f7.

**Comment by davids5** [comment]
@dagar - I am working on mkfatfs fs now....

**Pull request merged**
