### PR TITLE
New motor failure detection + dynamic motor de-allocation

### PR DESCRIPTION
**Pull request by potaito**
**Goals of this PR:**
- Automatically detect motor problems based on ESC telemetry (DShot or UAVCAN / VESC)
- On failure, automatically remove the failed motor from the Control Allocation effectiveness matrix
- Distinguish between failed motors and changes of the airframe configuration. I.e. keep track of the failed motors and "remember" the original airframe configuration and effectiveness.

**What about the existing engine failure check?**
Removed! It relied solely on the *total* battery current consumed, which works for a single-engine fixed-wing, but does not work for multirotors. The reason is that it would not allow us to distinguish between 4 motors all at 50%, and 2 motors at 100% plus 2 motors at 0% to make a very simple example.

However, the idea of checking for motor failures based on expected current consumption per throttle level was re-used in this PR's approach.

**How are motor failures detected?**
Currently two types of failures are detected:
1. The ESC current is (much) lower than what it is expected to be based on this ESC's throttle level. This allows to detect when motor phase wires are removed or a propeller falls off completely. 
2. ESC telemetry times out. This allows to detect when the ESC power supply or signal is completely lost or the ESC's IC damaged in some way.

**Hardware tests that were done**
Experimented with VESCs and their telemetry under different failure cases. The RPM turned out to be useless **for determining motor failures**. For example, when removing two of the three motor phase wires while the motor is spinning, the estimated RPM would remain at the setpoint, while it would start to jitter more (increased variance). It did not go to 0! The only reliable value in the esc report turned out to be the current consumed, which is measured and not estimated.

**Content of this PR**
- The old "engine failure" check was removed from commander
- The notion of an engine failure was also removed from navigator and OSD drivers and VTOL controllers
- The motor failure detection algorithm was added to commander's FailureDetector
- Commander is aware of motor failures, and based on a new parameer it will either not react at all, loiter, land in place or execute RTL.
- ControlAllocator listens to the failure_detector messages and has its own logic to remove failed motors from the effectiveness. Can be turned off via parameter.
- Added motor failure injection handling to the mavlink simulator
- SITL tests were added for simple control allocation tests with MAVSDK. The SITL model used is the **typhoon_h480** hexarotor. Issues I encountered here is that even without control allocation the drone remains fairly stable when killing one of the six motors. Only after killing two motors the drone fails to maintain attitude and altitude.

**TODO**
- Failure injections outside of SITL are not supported yet, because nothing in PX4 is listening to the failure injection commands.

### CODE REVIEW

**Comment by potaito** [comment]
This was tested in SITL, and then I had to rebase heavily, so this will need to be tested again.

**Comment by Jaeyoung-Lim** [comment]
> SITL tests were added for simple control allocation tests with MAVSDK. The SITL model used is the typhoon_h480 hexarotor. Issues I encountered here is that even without control allocation the drone remains fairly stable when killing one of the six motors. Only after killing two motors the drone fails to maintain attitude and altitude.

@potaito I think this is due to the yaw torque authority available in the motors of the typhoon_h480. Have you tried decreasing it to a realistic value? (https://github.com/PX4/PX4-SITL_gazebo/blob/2cf56d0bf8a9119cadc1a44d20d641ab24a6a42d/models/typhoon_h480/typhoon_h480.sdf.jinja#L1173) Probably might be worth decreasing it so that this can be tested properly

**Comment by potaito** [comment]
> > SITL tests were added for simple control allocation tests with MAVSDK. The SITL model used is the typhoon_h480 hexarotor. Issues I encountered here is that even without control allocation the drone remains fairly stable when killing one of the six motors. Only after killing two motors the drone fails to maintain attitude and altitude.
> 
> @potaito I think this is due to the yaw torque authority available in the motors of the typhoon_h480. Have you tried decreasing it to a realistic value? (https://github.com/PX4/PX4-SITL_gazebo/blob/2cf56d0bf8a9119cadc1a44d20d641ab24a6a42d/models/typhoon_h480/typhoon_h480.sdf.jinja#L1173) Probably might be worth decreasing it so that this can be tested properly

That's a good point, thanks! I'll take a look :)

**Review by bkueng — APPROVED** [review]
Looks good, can you rebase?

**Comment by potaito** [comment]
@bkueng 
> Looks good, can you rebase?

Done!

I'd rather merge this now and improve the SITL tests later, according to @Jaeyoung-Lim's suggestion. The current SITL test implementation is not causing any harm though.

**Comment by potaito** [comment]
Thanks @bkueng :smile: !!!!

**Pull request merged**
