### PR TITLE
NuttX apps with REJECTED commit

### PR DESCRIPTION
**Pull request by davids5**

### CODE REVIEW

**Review by LorenzMeier — APPROVED** [review]

**Comment by LorenzMeier** [comment]
We need to fix the checks / flash space.

**Comment by sfuhrer** [comment]
> We need to fix the checks / flash space.

The standard VTOL check fails. When I run the test locally they pass though - do we understand why this happens already?
image

**Comment by davids5** [comment]
@LorenzMeier - this is odd. master was already pointing to that branch in apps from when you merged the IP PR. I merged that commit to the px4 nuttx 10.0. Then repointed master via this PR.

**Comment by davids5** [comment]
> We need to fix the checks / flash space.

Are we ready for this https://github.com/PX4/PX4-Autopilot/issues/16415 ?

**Pull request merged**
