### PR TITLE
[WIP] Rover controller refactor

### PR DESCRIPTION
**Pull request by junwoo091400**
## Describe problem solved by this pull request
This started out as testing the #18317, but I ended up doing a lot of side refactoring to improve code readability and update comments / parameter definitions. This is not directly related to improving the PR, and was an initial step I took since I thought the code was pretty messy and unreadable in the beginning.

Also there's new airframe file like the one for the RC speed boat I am testing this on, which shouldn't make it to the `main` branch anyways (since we are only going to support generic geometries from now on).

## Describe your solution
A clear and concise description of what you have implemented.

## Describe possible alternatives
A clear and concise description of alternative solutions or features you've considered.

## Test data / coverage
How was it tested? What cases were covered? Logs uploaded to https://review.px4.io/ and screenshots of the important plot parts.

## Additional context
Add any other related context or media.

### CODE REVIEW

**Comment by junwoo091400** [comment]
Rebased on `main`

**Review by Jaeyoung-Lim — COMMENTED** [review]
I understand that it is tempting to fix everything at once, but would it be possible to prioritize on getting https://github.com/PX4/PX4-Autopilot/pull/18317 in with the current state and we separate the refactoring with the rate controller PR? Note that the current rover PR have already gone through a recent refactor (https://github.com/PX4/PX4-Autopilot/pull/16847) and is still not in a good state. 

Since people have been already using the current state of the rover position controller we should not try to break it for other people while we move forward for boats. 

If we combine refactoring with the added rate control it will be hard to verify whether the behavior is consistent with the previous state. I think it would be much easier to review if we separate refactoring and feature additions.

**Comment by junwoo091400** [comment]
image

Initial rate control SITL test shows good progress. All the PID values are 0 and only the feed-forward was enabled.
1. With full differential thrust, vehicle hardly reaches the yaw rate setpoint of +/- 1.0 rad/s.
2. Feedforward gain of 1.5 is too big (e.g. with 1 rad/s rate command, we don't want to command actuator control of 1.5 :wink:)

**Comment by junwoo091400** [comment]
> I understand that it is tempting to fix everything at once, but would it be possible to prioritize on getting #18317 in with the current state and we separate the refactoring with the rate controller PR? Note that the current rover PR have already gone through a recent refactor (#16847) and is still not in a good state.

Yes I understand :crying_cat_face:, that's why I am now adding marginal commits like [this one](https://github.com/PX4/PX4-Autopilot/pull/19957/commits/ac64deb3c9029fa3f51df1b748ce4d60d6030fea) so that I can extract only the rate control related commits out of this PR and get it merged.

This PR is mostly a reflection of this branch I am testing the boat on that shows the progress / overall changes, and as you mentioned it would be easier if I separate this into the rate control improvement PR + refactor PR! Which I am hoping to do so with marginal commits :smirk:

**Comment by junwoo091400** [comment]
image

Velocity based torque control output scaling has been added. Work in progresszzzz!

**Comment by junwoo091400** [comment]
Screenshot from 2022-07-28 14-29-01

Yaw rate acro mode seems to work kinda ok-ish on a real vehicle. Few things that I adjusted during the test:
1. Setting the `GND_RATE_MAX` to a sane value is important. On the first test, having 1.5 rad/s as the max rate, and hence making that the yaw rate setpoint completely saturated the acuator control for yaw. Therefore on this test I set it to **0.5 rad/s**, after observing that vehicle often has yaw rate of around 0.5 ~ 1.0 rad/s during the turn.
2. Adjusted the `GND_RATE_FF`, and this alone seemed to control the boat just fine actually! (Maybe since it's a catamaran vehicle, the water surface damping is more prevalent)
3. Enabled the `GND_RATE_P`, which gave some active control in acro mode, but didn't notice a big difference in performance increase.

Also, for now acro and manual mode feels pretty much the same (maybe it should be?), but glad to have the first real life test! :tada: 

Other notes:
* Yaw control is more aggressive on the right turn command, due to the rudder having asymmetric angle on min/max control input (right rudder command is ~45 degrees, as left rudder command gives only ~25 degrees deflection). Probably needs to be mitigated by modifying the hardware, but this is also noticable from the log (on manual control, right turns reach 1.0 rad/s easily, but left turns are around 0.6 rad/s maximum)
*

**Comment by junwoo091400** [comment]
Rebased on https://github.com/PX4/PX4-Autopilot/pull/20082

**Comment by junwoo091400** [comment]
Removed un-removed `RoverRateControl` files :sweat:

**Pull request closed without merging**
