### PR TITLE
Consolidate coverage upload

### PR DESCRIPTION
**Pull request by jkflying**
**Describe problem solved by this pull request**
Currently the coverage info is uploaded from a completely separate runner, this pulls it into an option from running from the basic 'check' matrix. Also, in some conditions the VTOL models (particularly tailsitter) didn't track the corridor between waypoints well in multirotor mode.

**Describe your solution**
1: Upload the coverage info from the unit and functional tests via the regular matrix of checks
2: drastically increase the radius so we don't have false positives from the SITL tests.

**Other comments**
We need to also get the coverage info from ECL and Matrix, so that we have a realistic idea of where we are missing coverage. Also, it would be great to have a way to view the coverage separately between SITL and unit testing, since the SITL testing doesn't actually check the accuracy of 99% of the code it runs.

### CODE REVIEW

**Comment by dagar** [comment]
I don't recall why it was done separately in the first place.

**Review by dagar — DISMISSED** [review]
Good to go from my perspective once CI is happy.

**Comment by LorenzMeier** [comment]
Could you please also check the other CI failures? E.g. test_coverage fails. And it might be worth syncing with @sfuhrer on the other fixed wing related instances?

**Comment by jkflying** [comment]
Yep test_coverage is broken because the test_coverage_genhtml target isn't available... definitely something strange going on there

**Comment by jkflying** [comment]
I'll be honest, I don't understand the intricacies of how you could extend CTest targets with the `SETUP_TARGET_FOR_COVERAGE()`... I've worked around it for now, but this stuff should be consolidated, I suspect the `make tests_coverage` has been broken for a long time

**Comment by jkflying** [comment]
The MAVROS fixed wing tests are also failing but that is unrelated

**Pull request merged**
