### PR TITLE
calibration params: avoid using NaN as default

### PR DESCRIPTION
**Pull request by bkueng**
NaN is not supported by JSON, and leads to parsing failure in QGC.

 - fixes https://github.com/PX4/PX4-Autopilot/issues/18095

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I'm not seeing a corresponding change where a check for == NaN is being changed to a check for == -1000. Was this used anywhere?

**Comment by bkueng** [comment]
I believe they're not used yet.

**Comment by dagar** [comment]
> Was this used anywhere?

Not yet, it's going to be used when the heater is present to ensure the calibration is appropriate.

It's also in place so we can casually monitor calibration changes as a function of temperature over time. If it appears to be consistent (and worthwhile) we can then extend the calibration system to keep multiple calibrations at different temperatures and build up a simple profile over time (aka poor man's temp cal).

**Comment by dagar** [comment]
How about we keep the NAN internally and only expose the magic value (-1000) to the parameter system? https://github.com/PX4/PX4-Autopilot/commit/57e50631c31f3c2b883785cf4e96023fe7899fac

**Comment by bkueng** [comment]
I tend towards not having extra logic around that, but I don't mind too much.

**Pull request merged**
