### PR TITLE
boards: enable early MPU reset on any board potentially not using the PX4 bootloader

### PR DESCRIPTION
**Pull request by dagar**
As a precaution we should perform the early MPU reset on all boards that potentially use a bootloader we don't control.

@taileron possibly related to https://github.com/PX4/PX4-Autopilot/pull/18709#issuecomment-983731982.

### CODE REVIEW

**Comment by dagar** [comment]
In a lot of cases this is a waste of time, but it only costs 88 bytes so I think we're safer doing it.

Screenshot from 2021-12-01 10-52-16

**Comment by taileron** [comment]
seems to have nothing to do with it, the current master also makes the same error with the bootloader from january 21.
INFO  [parameters] BSON document size 4731 bytes, decoded 4731 bytes
Board architecture defaults: /etc/init.d/rc.board_arch_defaults
INFO  [dataman] data manager file '/fs/microsd/dataman' size is 362560 bytes
Loading airframe: /etc/init.d/airframes/13012_convergence
INFO  [uavcan] Node ID 1, bitrate 1000000
WARN  [px4io] check CRC failed: -22, CRC: 3984471609
[PX4IO] using firmware from /etc/extras/px4_io-v2_default.bin
[PX4IO] bad sync 0xff,0xff
[PX4IO] bad sync 0xff,0xff
[PX4IO] bad sync 0xff,0xff
[PX4IO] bad sync 0xff,0xff
[PX4IO] bad sync 0xff,0xff
[PX4IO] bad sync 0xff,0xff
[PX4IO] bad sync 0xff,0xff
[PX4IO] bad sync 0xff,0xff
[PX4IO] bad sync 0xff,0xff
[PX4IO] bad sync 0xff,0xff
[PX4IO] bad sync 0xff,0xff
[PX4IO] bad sync 0xff,0xff
[PX4IO] bad sync 0xff,0xff
[PX4IO] bootloader not responding
[PX4IO] using firmware from /etc/extras/px4_io-v2_default.bin
[PX4IO] bad sync 0xff,0xff
[PX4IO] bad sync 0xff,0xff
[PX4IO] bad sync 0x10,0x12
[PX4IO] bootloader not responding
ERROR [px4io] error updating PX4IO - check that bootloader mode is enabled
INFO  [tune_control] Stopping playback...
PX4IO not found
Board sensors: /etc/init.d/rc.board_sensors
ms5611 #0 on SPI bus 1
WARN  [SPI_I2C] icm20608g: no instance started (no device on bus?)
icm20602 #0 on SPI bus 1 rotation 8
mpu9250 #0 on SPI bus 1 rotation 8
Starting Main GPS on /dev/ttyS3
Starting MAVLink on /dev/ttyS1
INFO  [mavlink] mode: Normal, data rate: 20000 B/s on /dev/ttyS1 @ 921600B
ERROR [mixer] can't open /dev/pwm_output0

ERROR [mixer] failed to load mixer
ERROR  [init] Failed loading mixer: /fs/microsd/etc/mixers/vtol_convergence.main.mix
ekf2 [1133:100]
ERROR [vtol_att_control] can't open /dev/pwm_output0
INFO  [airspeed_selector] Airspeed estimation invalid    
INFO  [logger] logger started (mode=all)

NuttShell (NSH) NuttX-10.2.0

**Comment by dagar** [comment]
Thanks @taileron. To confirm, are you only changing the FMU bootloader or the IO as well?

**Comment by taileron** [comment]
currently it´s only the FMU bootloader which is really a different one flashed by SWD. 
(a few blocks and it´s size are completely different)
IO is still one that´s a few months old. shall I try that as well? 
Out of the box that fs had the IO bootloader from AP in my case it is definitely a PX4 one flashed I can bring it back to the AP one if that helps. 
I can try to bring all bootloaders to a status like mro would sell it now ...

**Comment by taileron** [comment]
Unfortunately, I made a mistake during the tests and always took the GPS function as a criterion, since it does not start with RX DMA. Then I noticed that in defconfig the UART RXDMA=Y was written in capital letters and that is interpreted by PX4 as "n".
So all different boot loaders don´t solve the X2.1-777 u(s)art dma issue. With the prebuilt master the uart dma still doesn't work.

**Pull request merged**
