### PR TITLE
ROMFS: add motor assignment to holybro x500

### PR DESCRIPTION
**Pull request by bkueng**

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
So with mine I had to switch to dshot300 for the protocol before it would fully work correctly. Without that one of my motors wouldn't spin up at the same time as the others.

But in reality I'm just poking around in the dark here. I'm a hardware moron. You'd have to ask the Holybro folks what is correct. Although mine is working now I don't know if I have it set to what it really should be.

**Comment by bkueng** [comment]
I'd be surprised if PWM didn't work, but if we can use dshot, even better. According to the [docs](https://docs.px4.io/main/en/frames_multicopter/holybro_x500_pixhawk4.html#assembly) it's the FMU outputs.
Can you show your param diff? `param show-for-airframe`

**Comment by danielhonies** [comment]
If this is updated, I'd recommend also updating the docs for the v2 version: https://docs.px4.io/main/en/frames_multicopter/holybro_x500v2_pixhawk6c.html
https://docs.px4.io/main/en/frames_multicopter/holybro_x500V2_pixhawk5x.html
Right now it says "Assign actuator functions to outputs to match your wiring." Probably add a note there to make clear it's preconfigured. Also if we move to dshot we should check if the old x500 comes with dshot capable ESCs.

**Comment by DonLakeFlyer** [comment]
Mine are like this. Nut keep in mind I don't know what I'm doing:
```
param set-default PWM_AUX_FUNC1 101
param set-default PWM_AUX_FUNC2 102
param set-default PWM_AUX_FUNC3 103
param set-default PWM_AUX_FUNC4 104
param set-default PWM_AUX_MIN1 1100
param set-default PWM_AUX_MIN2 1100
param set-default PWM_AUX_MIN3 1100
param set-default PWM_AUX_MIN4 1100
param set-default PWM_AUX_TIM0 -4
```

Originally when not using dshot I had to bump the min pwm to 1100 to get them to spin. Not sure if that's needed with dshot.

**Comment by danielhonies** [comment]
@DonLakeFlyer in master we only have the X500 V2 though. However I just tested it and can confirm that the old one also supports dshot as well.

**Comment by danielhonies** [comment]
@bkueng afaik FMU usually doesn't support dshot? So update the docs to connect them to AUX?

**Comment by danielhonies** [comment]
@DonLakeFlyer the min pwm is not needed with dshot. The actuators page actually removes that setting once you switch to dshot.

**Review by mrpollo — APPROVED** [review]
thanks @bkueng

**Comment by vincentpoont2** [comment]
@bkueng Thank for the PR. 
However, I want to point out most existing user are probably using X500 v2 with the I/O PWM Out (Main PWM) because the I/O PWM Out was the default for all Quad airframe prior to [the purging of the mixing stystem ](https://github.com/PX4/PX4-Autopilot/commit/cac9c51ac87741e214df55747ec445d00fe8fd9f)that was made in 1.14. 

If we change it to FMU PWM Out as default for this airframe now, there will be users that will be confused on why their quad don't work when they update to 1.14. 

What is the reason that we remove these from [rc.mc_defaults?](https://github.com/PX4/PX4-Autopilot/blob/main/ROMFS/px4fmu_common/init.d/rc.mc_defaults), it looks the reason users are having issue with motor not spinning when armed is because of the PWM_Main_Min being too low? 

in 1.13, we have these as default.
`param set-default PWM_MAIN_MAX 1950`
`param set-default PWM_MAIN_MIN 1075`
`param set-default PWM_MAIN_RATE 400`

**Comment by bkueng** [comment]
I don't mind changing but then we also need to change the docs: https://docs.px4.io/main/en/frames_multicopter/holybro_x500_pixhawk4.html#assembly

The PWM_MIN is currently being addressed in https://github.com/PX4/PX4-Autopilot/pull/21513

**Comment by vincentpoont2** [comment]
@bkueng Can we change it back so that when existing user flash 1.14, they would not run into issue with this?

> I want to point out most existing user are probably using X500 v2 with the I/O PWM Out (Main PWM) because the I/O PWM Out was the default for all Quad airframe prior to [the purging of the mixing stystem ](https://github.com/PX4/PX4-Autopilot/commit/cac9c51ac87741e214df55747ec445d00fe8fd9f)that was made in 1.14.
>If we change it to FMU PWM Out as default for this airframe now, there will be users that will be confused on why their quad don't work when they update to 1.14.

cc @julianoes

**Comment by bkueng** [comment]
Yes, can you update the documentation?

**Comment by vincentpoont2** [comment]
@bkueng thanks! Yes. Will do after the change.

**Pull request merged**
