### PR TITLE
[WIP]: move "Follow Me" out of navigator to flight_mode_manager

### PR DESCRIPTION
**Pull request by dagar**
This is the next little piece on the long road to unified flight mode handling and turning navigator into a simple "mission manager".

 - follow navigator navigation state moves entirely into a flight task (flight mode)
 - position_setpoint_triplet remove velocity and yawspeed setpoints (now position only)

TODO
 - fully test FOLLOW

### CODE REVIEW

**Comment by potaito** [comment]
This is awesome Daniel, thanks for doing this! Particularly the reduced number of fields in `msg/position_setpoint.msg`

**Comment by dagar** [comment]
> This is awesome Daniel, thanks for doing this! Particularly the reduced number of fields in `msg/position_setpoint.msg`

Thanks @potaito, any suggestions for testing? I need a simple test case to work through the remaining details and ensure there are no regressions.

**Comment by potaito** [comment]
I can test it in simulation. Got a python script with a moving target. Is there any other test that we need @dagar ?

**Comment by potaito** [comment]
Hm just tried with jmavsim and the drone did not move after takeoff: https://logs.px4.io/plot_app?log=764e59d1-a728-4aa9-b744-8f8c95bbdc06

And here's the same simulation with current master, where the drone is moving: https://logs.px4.io/plot_app?log=be67163b-dd12-4836-97fd-53004f4946ed

The script I used for simulating is this one: https://gist.github.com/potaito/f6a1d92a813e0ababf908f37d5aed7f6 
Just need `pip3 install mavsdk`

**Comment by dagar** [comment]
> Hm just tried with jmavsim and the drone did not move after takeoff: https://logs.px4.io/plot_app?log=764e59d1-a728-4aa9-b744-8f8c95bbdc06

I should have been more clear, this is the bulk of the move with a few key pieces of logic still missing before it will actually work. 

https://github.com/PX4/PX4-Autopilot/blob/7f4fbc102c60ad6da1130edd036ba44d6486e880/src/modules/flight_mode_manager/tasks/AutoFollowMe/FlightTaskAutoFollowMe.cpp#L215-L219

My next step was figuring out how to effectively test in simulation so I could fill in the remaining TODOs.

**Comment by potaito** [comment]
Right, the PR even says "draft" :sweat_smile: 
The script I posted above is simply using mavSDK to publish the FOLLOW_TARGET mavlink message for a simulated target.

**Comment by dagar** [comment]
> Right, the PR even says "draft" 
> The script I posted above is simply using mavSDK to publish the FOLLOW_TARGET mavlink message for a simulated target.

Thanks that's exactly what I needed. I'll finish this once v1.12 is out the door.

**Comment by potaito** [comment]
Closing in favour of https://github.com/PX4/PX4-Autopilot/pull/18026

**Pull request closed without merging**
