### PR TITLE
NuttX with Fix DATA timeout

### PR DESCRIPTION
**Pull request by davids5**
~~Just for testing~~

Re-pointed to merged NuttX back ports

### CODE REVIEW

**Comment by LorenzMeier** [comment]
What is the next step here - wait for the backport?

**Comment by davids5** [comment]
Testing the latest commits

**Comment by bkueng** [comment]
I let this run for a bit and didn't see any timeouts anymore.

**Comment by davids5** [comment]
> Merged - can you repoint?

Done

**Pull request merged**
