### PR TITLE
navigator_main: improve geofence approach user warning

### PR DESCRIPTION
**Pull request by MaEtUgR**
## Describe problem solved by this pull request
@leonardosimovic was suggesting improved wording so I opened a pr.

## Describe possible alternatives
We need an in-depth revision but in the meantime improved wording doesn't hurt.

## Test data / coverage
Not specifically tested. As far as I can see it doesn't exceed the maximum length for the message so it should work.

### CODE REVIEW

**Review by mcsauder — APPROVED** [review]

**Comment by dagar** [comment]
Maybe the warning should be sent with mavlink_log_warning instead of mavlink_log_critical?

https://github.com/PX4/PX4-Autopilot/blob/1141ec71de1be6f76216050eed11655fb9e93089/src/modules/navigator/navigator_main.cpp#L878

**Comment by bkueng** [comment]
I'm already changing this in https://github.com/PX4/PX4-Autopilot/pull/20172

**Comment by junwoo091400** [comment]
Yep this part was removed in the PR beat mentioned: https://github.com/PX4/PX4-Autopilot/pull/20172/files#diff-b0f4afafd2913feb330ba2f0d33d857255face127274b7bb70ec00c12a65fbc1L846

Closing for now, but feel free to bring it up again! @MaEtUgR

**Comment by MaEtUgR** [comment]
This was covered with https://github.com/PX4/PX4-Autopilot/pull/20172

**Pull request closed without merging**
