### PR TITLE
Murata SCH16T IMU driver

### PR DESCRIPTION
**Pull request by dakejahl**
Driver for the 6 DoF Murata SCH16T IMU
(full datasheet not publicly available)
https://www.murata.com/en-us/products/sensor/gyro/overview/lineup/sch16t

**Highlights from the datasheet**
- ±300 °/s calibrated angular rate measurement range.
- ±8g acceleration measurement range
- Redundant digital accelerometer channel with up to ±26g dynamic range
- Options for output interpolation and decimation
- Data Ready output
- SafeSPI v2.0 interface (20-bit out-of-frame)

**TODO**
- [x] Implement Control Register map for validating configuration (**required**)
- [x] At startup sometimes it repeatedly fails to validate sensor status and continuously restarts. Eventually starts up cleanly.
- [ ] Add parameters for settings: decimation, range, and sensitivity
- [ ] Test without DRDY
- [x] Check COMP_ID and ASIC_ID to match chip version

**Decimation Factor 8, DRDY @1475Hz, ±300 °/s gyro, ±80 m/s² accel**
```
|__ 5) wq:SPI6         
|   \__ 1) sch16t                          1502.2 Hz          666 us
```
**SPI 6 @2Mhz (15% CPU @ 1500Hz)** 
```
1202 wq:SPI6                        31 15.561   860/ 2368 248 (248)  w:sem  4
```
**Gyro**
```
Instance 3:
 sensor_gyro
    timestamp: 784015870 (0.001138 seconds ago)
    timestamp_sample: 784015456 (414 us before timestamp)
    device_id: 5963826 (Type: 0x5B, SPI:6 (0x00))
    x: 0.00110
    y: -0.00100
    z: 0.00030
    temperature: 29.11000
    error_count: 0
    clip_counter: [0, 0, 0]
    samples: 1
```
**Accel**
```
Instance 3:
 sensor_accel
    timestamp: 775162062 (0.000797 seconds ago)
    timestamp_sample: 775161674 (388 us before timestamp)
    device_id: 5963826 (Type: 0x5B, SPI:6 (0x00))
    x: 0.04093
    y: 0.00156
    z: 9.91844
    temperature: 29.10000
    error_count: 0
    clip_counter: [0, 0, 0]
    samples: 1
```
**sch16t status**
```
INFO  [SPI_I2C] Running on SPI Bus 6
sch16t: reset: 2 events
sch16t: bad register: 0 events
sch16t: bad transfer: 0 events
sch16t: CRC8 bad: 0 events
sch16t: Frame bad: 0 events
sch16t: DRDY missed: 1 events
```

image

### CODE REVIEW

**Comment by bresch** [comment]
Hmm, 8g of accel range, I hope you have a good vibration isolation mount...

**Comment by dakejahl** [comment]
> Redundant digital accelerometer channel with up to ±26g dynamic range

The datasheet guarantees +/- 8G on ACC3 but has the electrical headroom for +/-26G. I guess we'll find out once we test fly it.

I've modified the driver to use ACC3. This should be in a good state for testing and review.

**Comment by AlexKlimaj** [comment]
Just did a quick test hop in the office. Data looks decent but the gyro clipping messages are annoying.
https://review.px4.io/plot_app?log=10f570a2-89f7-4696-8ea5-bb79e320d72f

**Comment by AlexKlimaj** [comment]
Clipping warning is gone now.

https://review.px4.io/plot_app?log=b57a5d15-40e8-4068-bd74-d1287d7e32af
https://review.px4.io/plot_app?log=b57a5d15-40e8-4068-bd74-d1287d7e32af
https://review.px4.io/plot_app?log=edc21310-bb70-414a-be63-a610e61f1ce9
https://review.px4.io/plot_app?log=30d566dc-3f8b-4ffa-acdf-1ed0c634705f

**Review by dagar — APPROVED** [review]

**Pull request merged**
