### PR TITLE
[BACKPORT release/1.15] tools/bootloader: add force-erase option and add bootloader version 

### PR DESCRIPTION
**Pull request by julianoes**
Backport of: https://github.com/PX4/PX4-Autopilot/pull/22777
And fixups: https://github.com/PX4/PX4-Autopilot/pull/23174
And updated target list: #23234

Best to be rebased cleanly so that the git hash embedded in the bootloader makes sense and points to the actual branch.

### CODE REVIEW

**Comment by julianoes** [comment]
Ok, that's fine with me. Let me know when I should rebase it.

**Comment by davids5** [comment]
> Ok, that's fine with me. Let me know when I should rebase it.

@julianoes - Please rebase

**Comment by julianoes** [comment]
@davids5 hang on, I need to add the commits from: #23234.

**Review by davids5 — APPROVED** [review]
LGTM @dagar - pleas have a look

**Pull request merged**
