### PR TITLE
boards: stm32f7 run gyro_fft by default

### PR DESCRIPTION
**Pull request by dagar**
Let's see what this would cost.

### CODE REVIEW

**Comment by dagar** [comment]
Looks like it would be about 5% for the primary is an 8 kHz gyro.

Screen Shot 2021-03-14 at 9 06 20 PM

What do you think @bkueng?

**Comment by dagar** [comment]
Down slightly to ~4.2% with the last push (f1882b303bbcb6631826d9ae669).

**Review by bkueng — APPROVED** [review]
Let's collect some data then.

**Comment by bkueng** [comment]
Just realizing on my KakuteF7 2khz setup, CPU is already maxed out even w/o fft enabled:
```
 PID COMMAND                   CPU(ms) CPU(%)  USED/STACK PRIO(BASE) STATE FD
   0 Idle Task                    4484  0.145   268/  512   0 (  0)  READY  3
   1 hpwork                          0  0.000   332/ 1268 249 (249)  w:sig  3
   2 lpwork                          0  0.000   332/ 1620  50 ( 50)  w:sig  3
   3 init                            0  0.000  2140/ 2932 100 (100)  w:sem  3
   4 wq:manager                      0  0.000   420/ 1260 255 (255)  w:sem  5
 346 mavlink_rcv_if0                31  0.413  3244/ 4668 175 (175)  w:sem  6
  28 dataman                         0  0.000   788/ 1204  90 ( 90)  w:sem  4
  30 wq:lp_default                   3  0.046   924/ 1700 205 (205)  w:sem  5
 176 wq:hp_default                  49  0.641  1204/ 1900 237 (237)  w:sem  5
 182 wq:SPI4                      1309 17.098  1468/ 2340 250 (250)  w:sem  5
 184 wq:I2C1                         8  0.112   760/ 2340 246 (246)  w:sem  5
 210 wq:nav_and_controllers        741  9.690  1260/ 2164 242 (242)  w:sem  5
 211 wq:rate_ctrl                 2265 29.537  1468/ 1924 255 (255)  w:sem  5
 216 commander                     103  1.403  1292/ 3220 140 (140)  w:sig  5
 225 mavlink_if0                   490  6.049  1780/ 2428 100 (100)  READY  6
 250 frsky_telemetry               144  1.853   876/ 1324 104 (104)  w:sem  5
 271 mavlink_if1                   311  3.820  1684/ 2340 100 (100)  w:sig  4
 285 wq:UART3                       46  0.605   724/ 1404 231 (231)  w:sem  5
 293 mavlink_rcv_if1                33  0.436  3148/ 4668 175 (175)  w:sem  4
 294 wq:INS0                       384  5.032  1052/ 6004 241 (241)  w:sem  5
 307 navigator                       0  0.013  1108/ 1772 105 (105)  w:sem  6
 328 wq:SPI2                       235  2.984   612/ 2340 252 (252)  w:sem  5
 337 logger                        297  3.885  2804/ 3644 230 (230)  w:sem  4
 340 log_writer_file               832 11.580   604/ 1172  60 ( 60)  READY  4
 347 mavlink_shell                   0  0.000  1084/ 2028 100 (100)  w:sem  3
 354 top                            80  1.036  1964/ 4084 237 (237)  RUN    3

Processes: 26 total, 4 running, 22 sleeping, max FDs: 12
CPU usage: 96.24% tasks, 3.62% sched, 0.14% idle
DMA Memory: 5120 total, 1536 used 1536 peak
Uptime: 59.452s total, 4.484s idle
```

And running low on RAM with gyro fft:
```
INFO  [logger] [logger] /fs/microsd/log/sess295/log001.ulg
ERROR [logger] Can't create log buffer
nsh> free
             total       used       free    largest
Umem:       219312     190528      28784      27488
```

**Comment by LorenzMeier** [comment]
Do you have UAVCAN enabled? I don't see it in top, but just making sure..

The other bit is SPI DMA - try increasing the buffer for SPI4 to 4K because to me the 17% load seems too high: https://github.com/PX4/PX4-Autopilot/blob/master/boards/px4/fmu-v5x/nuttx-config/nsh/defconfig#L218-L230

**Comment by dagar** [comment]
> Just realizing on my KakuteF7 2khz setup, CPU is already maxed out even w/o fft enabled:

The first thing that comes to mind is that KakuteF7 has `CONSTRAINED_FLASH` set, which means things like the rate controller and sensor pipeline aren't being compiled at -O2. I would try removing that and instead stripping out SYSTEMCMDS (listener is enormous).

https://github.com/PX4/PX4-Autopilot/blob/a5151f92ea9db548f939741436e3154d947eb974/boards/holybro/kakutef7/default.cmake#L10

The other small piece to keep in mind is that our load measurements (when top is running) are actually fairly expensive, probably around 5% (taxed across all tasks/threads). PX4 is faster when you aren't looking at it...

I believe the biggest area for improvement at this point will be optimizing dshot, mixers, and output modules in general.

**Comment by dagar** [comment]
> And running low on RAM with gyro fft:
> 
> ```
> INFO  [logger] [logger] /fs/microsd/log/sess295/log001.ulg
> ERROR [logger] Can't create log buffer
> nsh> free
>              total       used       free    largest
> Umem:       219312     190528      28784      27488
> ```

@bkueng the default FFT length (IMU_GYRO_FFT_EN) is fairly large at this point to capture good data for review. Very likely for racing setups it's going to need to be considerably shorter in order to get the latency down between peak frequency detection in the FFT and actually updating gyro notch filters.

I would try lowering IMU_GYRO_FFT_EN to 256, 128, etc. I believe Betaflight only uses 32. I'm hoping we're going to be able to have multiple very narrow notches, but we'll need to find a good trade off between latency, cpu load, and frequency bucket granularity.

**Comment by dagar** [comment]
> > And running low on RAM with gyro fft:
> > ```
> > INFO  [logger] [logger] /fs/microsd/log/sess295/log001.ulg
> > ERROR [logger] Can't create log buffer
> > nsh> free
> >              total       used       free    largest
> > Umem:       219312     190528      28784      27488
> > ```
> 
> @bkueng the default FFT length (IMU_GYRO_FFT_EN) is fairly large at this point to capture good data for review. Very likely for racing setups it's going to need to be considerably shorter in order to get the latency down between peak frequency detection in the FFT and actually updating gyro notch filters.
> 
> I would try lowering IMU_GYRO_FFT_EN to 256, 128, etc. I believe Betaflight only uses 32. I'm hoping we're going to be able to have multiple very narrow notches, but we'll need to find a good trade off between latency, cpu load, and frequency bucket granularity.

One last comment here for the `gyro_fft` module and flash, if we can settle on a small handful of FFT lengths then I can manually include them and drastically decrease the flash requirements.

 - `gyro_fft` currently requires > 70 kB of flash, but I can get it down to 10-20 kB if we only have a couple FFT lengths.

**Pull request merged**
