### PR TITLE
mavlink: streams/COMMAND_LONG don't send internal vehicle_commands

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Review by AlexKlimaj — APPROVED** [review]
This is working.

**Review by julianoes — COMMENTED** [review]
Hang on. Why are we sending COMMAND_LONG as a stream? Aren't we handling commands in https://github.com/PX4/PX4-Autopilot/blob/master/src/modules/mavlink/mavlink_command_sender.cpp ?

**Comment by dagar** [comment]
> Hang on. Why are we sending COMMAND_LONG as a stream? Aren't we handling commands in https://github.com/PX4/PX4-Autopilot/blob/master/src/modules/mavlink/mavlink_command_sender.cpp ?

The stream is passing it off to mavlink command sender.

https://github.com/PX4/PX4-Autopilot/blob/487502fa07aea31e88dd19df3ab50b3e0a4d9701/src/modules/mavlink/streams/COMMAND_LONG.hpp#L89

**Comment by julianoes** [comment]
Oh, it's good to read :facepalm:.

**Review by julianoes — APPROVED** [review]

**Pull request merged**
