### PR TITLE
uorb subscriber get oldest generation in queue

### PR DESCRIPTION
**Pull request by AlexKlimaj**
@ShawnFeng0

### CODE REVIEW

**Comment by ShawnFeng0** [comment]
The logic here is modified by me.
You can't get the oldest data in the first place, the generation is an unsigned that can overflow, but we don't know when it will overflow (it becomes 0 after 0xffffffff), and we shouldn't assume that PX4 won't run for long.

**Comment by dagar** [comment]
> `generation` is an `unsigned` type that can overflow. If it overflows, we cannot guarantee to get the oldest data at initialization. Getting the latest data on initialization ensures that initialization behavior is always consistent.

Per uORBDeviceNode we could separately track if we've had at least _queue_size publications.

**Comment by ShawnFeng0** [comment]
> > `generation` is an `unsigned` type that can overflow. If it overflows, we cannot guarantee to get the oldest data at initialization. Getting the latest data on initialization ensures that initialization behavior is always consistent.
> 
> Per uORBDeviceNode we could separately track if we've had at least _queue_size publications.

Yes, but every time you publish a message you need to execute a few more lines of code.
Do new subscribers really need old messages?

**Comment by AlexKlimaj** [comment]
Could we just update this behavior for messages with a queue? Leave the old behavior for messages without a queue.

**Comment by ShawnFeng0** [comment]
> Could we just update this behavior for messages with a queue? Leave the old behavior for messages without a queue.

Messages without queues themselves don't suffer from this problem.

**Comment by ShawnFeng0** [comment]
I think it's reasonable that new subscribers will start processing new messages when they get them.
Do new subscribers really need old messages?

If our purpose is the reliable transmission of messages (such as executing commands from ground stations), the existing uorb mechanism cannot do it, and it cannot be done by simply retrieving old messages.


By the way, are there any plans for uorb to support reliable data transfer?

**Pull request closed without merging**
