### PR TITLE
ekf2: add verbose print status (moved out of DEBUG_BUILD)

### PR DESCRIPTION
**Pull request by dagar**
image

image

### CODE REVIEW

**Review by bresch — APPROVED** [review]

**Comment by dagar** [comment]
Looks like it'll need to be disabled in the flash constrained builds.

**Comment by dagar** [comment]
FYI this is nearly 3 kilobytes of flash (surprisingly). I'll need to adjust some builds to squeeze it in.

**Comment by dagar** [comment]
On second thought I'll turn this off by default in kconfig, but enable it in px4_sitl.

For anything other than px4_sitl this needs to be enabled in kconfig (eg `make px4_fmu-v6x_default boardguiconfig`.

image

**Comment by bresch** [comment]
> FYI this is nearly 3 kilobytes of flash

wow, that hurts...

**Pull request merged**
