### PR TITLE
Enable lockstep scheduler for replay

### PR DESCRIPTION
**Pull request by Danmou**
**Describe problem solved by this pull request**
EKF2 replay doesn't log the majority of messages.

**Describe your solution**
I enabled the lockstep scheduler for replay. This change was already introduced [here](https://github.com/PX4/PX4-Autopilot/pull/15137/files#diff-5a8a2eccdfd390a06d96f666712b761e62fef9f6a9c53f688cb0bdb576c400b0) but (accidentally, I think) reverted [here](https://github.com/PX4/PX4-Autopilot/pull/15743/files#diff-5a8a2eccdfd390a06d96f666712b761e62fef9f6a9c53f688cb0bdb576c400b0).

### CODE REVIEW

**Comment by dagar** [comment]
For actual EKF2 replay lockstep doesn't matter because each ekf2 iteration is driven by a new `sensor_combined` publication.

Is it specifically `replay_mode=ekf2` where you're seeing the problem or are you replaying something else? https://docs.px4.io/master/en/debug/system_wide_replay.html#ekf2-replay

**Comment by Danmou** [comment]
> For actual EKF2 replay lockstep doesn't matter because each ekf2 iteration is driven by a new `sensor_combined` publication.
> 
> Is it specifically `replay_mode=ekf2` where you're seeing the problem or are you replaying something else? https://docs.px4.io/master/en/debug/system_wide_replay.html#ekf2-replay

Yes EKF2 replay. Lockstep matters because the logger can't keep up with the data from EKF.

**Comment by bkueng** [comment]
Yes lockstep is used for ekf2 replay as well.

**Comment by dagar** [comment]
Ah right, so I don't know what was intended here.

**Comment by dagar** [comment]
Ok, I think the confusion here was introduced by the kconfig changes.

@Danmou can you add `CONFIG_BOARD_LOCKSTEP=y` to `boards/px4/sitl/default.px4board` and we'll get rid of `set(ENABLE_LOCKSTEP_SCHEDULER yes)` entirely.

You can use `make px4_sitl_default boardguiconfig`.

**Comment by julianoes** [comment]
We can probably close that one?

**Pull request closed without merging**
