### PR TITLE
ekf2: selector improve status reporting

### PR DESCRIPTION
**Pull request by dagar**
- publish estimator_selector_status at minimal rate or immediately on change
 - log all estimator_selector_status updates

### CODE REVIEW

**Review by LorenzMeier — APPROVED** [review]
Awesome, immediate logging is really important.

**Comment by LorenzMeier** [comment]
@dagar Reviewed on architecture, design pattern and uORB usage. I have not reviewed the EKF2 changes line-by-line - depending on how much review you have on those, you might want to pull Beat or Mathieu in, or merge as is.

**Comment by dagar** [comment]
This is the trivial change (`estimator_selector_status` publication) broken out of https://github.com/PX4/PX4-Autopilot/pull/16518 where more review and testing would be greatly appreciated.

**Review by LorenzMeier — APPROVED** [review]

**Comment by LorenzMeier** [comment]
Could you rebase the other PR real quick so it is in its final state and ready to go in after more review and flights?

**Pull request merged**
