### PR TITLE
Added fixed to VTOL for gz

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: Alejandro Hernández Cordero <ahcorde@gmail.com>

 - I fixed the orientation of the foxtech loong 2160 model
 - update airspeed sdf

I'm able to takeoff the robot but when I transitioned to fixed wing plane something wrong is happening

vtol_fail

### CODE REVIEW

**Comment by ahcorde** [comment]
FYI @dagar @bperseghetti

**Comment by Jaeyoung-Lim** [comment]
@ahcorde I think it would be easier if we decouple the airspeed sensor data integration with the general flight control issues.

I have created a simulated airspeed sensor PX4 side in https://github.com/PX4/PX4-Autopilot/pull/21106

Would it be helpful if I try to work on the flight control issues without the gazebo airspeed sensor integration? What would be more helpful? Working on the Loong? or the standard VTOL?

**Comment by ahcorde** [comment]
thank you @Jaeyoung-Lim, I only need to merge the `gz-sim` PR https://github.com/gazebosim/gz-sim/pull/1847 to include the airspeed sensor in Gazebo. 

Anyhow working on the Loong probably makes more sense. Let me know if I can help somehow

**Comment by bperseghetti** [comment]
I feel like we are very close on getting the airspeed upstream in gz-garden. So part of me wants to uncomplicate things right now by just focusing on getting the simulation airspeed in the way we originally wanted it and then adding anything else.

**Comment by ahcorde** [comment]
@Jaeyoung-Lim  and @bperseghetti  I will ask for some reviews today, I think we can merge and release today.

**Comment by Jaeyoung-Lim** [comment]
@bperseghetti Even if the vehicle has no airspeed measurements vtol vehicles should still be able to fly successful transition maneuvers.

Therefore I still think we are mixing the two orthogonal issues together - we could have already have a flying VTOL vehicle whether or not the airspeed related changes is merged in gazebo / the airspeed change in gazebo does not solve anything regarding the problems with vtol transitions.

**Pull request merged**
