### PR TITLE
Build on NixOS

### PR DESCRIPTION
**Pull request by povik**
**Describe problem solved by this pull request**

Greetings PX4 developers. These changes make it easier to build PX4 on [NixOS](https://nixos.org/).

**Describe your solution**

I changed the interpreter in some `platforms/nuttx` scripts as `/bin/bash` does not exist on clean NixOS installation. Then I added `Tools/setup/shell.nix`, which you can supply to `nix-shell` to obtain an environment in which PX4 will have its build dependencies.

Also see [this build error I had to fix](https://github.com/PX4/PX4-Autopilot/commit/0b5ee19b6b41383e63c1e3da6b9e3b6c1cce4a81). I guess it might be because of too old an ARM GCC (9-2019-q4-major)? Should I get the `shell.nix` environment to have newer version? That's doable with some additional effort.

**Describe possible alternatives**

Well you could use container with e.g. Ubuntu, but that's not a solution I like.

**Test data / coverage**

`make px4_fmu-v5` builds and produces good binaries. Let me know if there are other targets that you want me to test.

**Additional context**

Feel free to decide against inclusion if you don't see it worth the maintenance burden.

Also I have seen that cmake will ignore if `platforms/nuttx/NuttX/tools/px4_nuttx_make_olddefconfig.sh` fails, which caused a harder-to-explain build error later on. I don't know cmake good enough to fix that, neither do I know if that's intentional.

### CODE REVIEW

**Comment by dagar** [comment]
This looks good, although I wouldn't expect `Tools/setup/shell.nix` to continue working unless we put something in place to force it. 

What I'd like to do is have all of these setup scripts directly used by the containers (https://github.com/PX4/PX4-containers/tree/master/docker) which are then used in CI.

**Comment by povik** [comment]
@dagar Should I then prepare a PR against PX4-containers and add a container testing build under `shell.nix`?

**Comment by dagar** [comment]
> @dagar Should I then prepare a PR against PX4-containers and add a container testing build under `shell.nix`?

Yes, if you're interesting in doing that I'd be happy to consider NixOS some level of "supported" for PX4 development. Once we have a baseline docker container available, then we can add something basic in github actions (https://github.com/PX4/PX4-Autopilot/tree/master/.github/workflows).

**Comment by povik** [comment]
> > @dagar Should I then prepare a PR against PX4-containers and add a container testing build under `shell.nix`?
> 
> Yes, if you're interesting in doing that I'd be happy to consider NixOS some level of "supported" for PX4 development. Once we have a baseline docker container available, then we can add something basic in github actions (https://github.com/PX4/PX4-Autopilot/tree/master/.github/workflows).

Yes, I am willing to do that. I don't know how nicely nix plays with docker but it seems it can be done. I will get back in touch once I have a Dockerfile for the baseline container.

**Review by dagar — APPROVED** [review]

**Comment by povik** [comment]
Hi @dagar. I wrote a [dockerfile like this](https://gist.github.com/povik/24e313eddff5e5b87aba35c81d196344), which you may use in CI, but after looking into github actions I propose we drop the docker image altogether and use nix directly in github actions. Because there is some overlap in what docker and nix aims to provide, the only function a prepared docker image may have is to serve as cache, having the needed /nix/store/... paths prepopulated. There is little value in such image for general users, as one may run nix-shell outside of the docker image, on the host system, and as long as nix does its job, one should obtain the same environment.

So what I propose instead is that we prepare a github workflow in which we install nix (there is [cachix/install-nix-action](https://github.com/cachix/install-nix-action), nix can be installed into conventional distributions such as Ubuntu), we fetch the /nix/store/... paths from the github actions cache if possible, and then we run nix-shell to enter the build environment, then we build the PX4 targets.

What do you say? Out of curiosity I have been tinkering with github actions and can estimate the proposed approach would use up around 540 MB of the github actions cache. I am willing to prepare such workflow, although I would like to discuss if using ccache is needed.

**Comment by povik** [comment]
Ping @dagar, in case you missed my message above.

**Pull request merged**
