### PR TITLE
[DO NOT MERGE] sitl_gazebo mavlink debug

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by dagar** [comment]
Screen Shot 2021-01-02 at 10 49 59 PM

**Comment by LorenzMeier** [comment]
I'm testing with this in parallel, but haven't found the culprit yet.

**Comment by LorenzMeier** [comment]
Interestingly enough with those latest changes the sim completely stalls on Mac OS with a real-time factor of zero.

**Comment by LorenzMeier** [comment]
Local diff I'm testing with on top:
```
diff --git a/src/gazebo_mavlink_interface.cpp b/src/gazebo_mavlink_interface.cpp
index 8507fda..2f7c184 100644
--- a/src/gazebo_mavlink_interface.cpp
+++ b/src/gazebo_mavlink_interface.cpp
@@ -491,15 +491,23 @@ void GazeboMavlinkInterface::OnUpdate(const common::UpdateInfo&  /*_info*/) {
   std::unique_lock<std::mutex> lock(last_imu_message_mutex_);
 
   if (previous_imu_seq_ > 0) {
+    unsigned waitcycles = 0;
     while (previous_imu_seq_ == last_imu_message_.seq() && IsRunning()) {
-      last_imu_message_cond_.wait_for(lock, std::chrono::milliseconds(10));
+      last_imu_message_cond_.wait_for(lock, std::chrono::milliseconds(5));
+      if (waitcycles > 5) {
+        gzerr << "waiting" << std::endl;
+      }
+      waitcycles++;
     }
   }
 
+  lock.unlock();
+
   previous_imu_seq_ = last_imu_message_.seq();
 
   // Always run at 250 Hz. At 500 Hz, the skip factor should be 2, at 1000 Hz 4.
   if (!(previous_imu_seq_ % update_skip_factor_ == 0)) {
+    gzerr << "Bailing at skip factor check" << std::endl;
     return;
   }
 
@@ -512,19 +520,20 @@ void GazeboMavlinkInterface::OnUpdate(const common::UpdateInfo&  /*_info*/) {
 
   bool close_conn_ = false;
 
-  if (hil_mode_) {
-    mavlink_interface_->pollFromQgcAndSdk();
-  } else {
-    mavlink_interface_->pollForMAVLinkMessages();
-  }
-
   // Always send Gyro and Accel data at full rate (= sim update rate)
   SendSensorMessages();
 
   // Send groudntruth at full rate
   SendGroundTruth();
 
+  if (hil_mode_) {
+    mavlink_interface_->pollFromQgcAndSdk();
+  } else {
+    mavlink_interface_->pollForMAVLinkMessages();
+  }
+
   if (close_conn_) { // close connection if required
+    gzerr << "Closing MAVLink connection" << std::endl;
     mavlink_interface_->close();
   }
 
diff --git a/worlds/empty.world b/worlds/empty.world
index 08922a0..ad9b8e9 100644
--- a/worlds/empty.world
+++ b/worlds/empty.world
@@ -33,5 +33,15 @@
       <real_time_update_rate>250</real_time_update_rate>
       <magnetic_field>6.0e-6 2.3e-5 -4.2e-5</magnetic_field>
     </physics>
+    <gui fullscreen='0'>
+      <camera name='gzclient_camera'>
+        <view_controller>fps</view_controller>
+        <track_visual>
+          <name>standard_vtol</name>
+          <use_model_name>true</use_model_name>
+        </track_visual>
+        <projection_type>perspective</projection_type>
+      </camera>
+  </gui>
   </world>
 </sdf>

```

**Pull request closed without merging**
