### PR TITLE
imu/invensense: adjust scheduling dynamically if not using data ready interrupt

### PR DESCRIPTION
**Pull request by dagar**
@danduril

### CODE REVIEW

**Comment by danduril** [comment]
The number of samples for each sensor_gyro_fifo record for the icm20602 was unvarying at 20 samples per. Perhaps the sample timestamp should actually be: timestamp_sample = _last_timestamp_sample + samples * FIFO_SAMPLE_DT? Does "local" processor time really matter more than real-time, as measured but the IMU?

**Comment by dagar** [comment]
> The number of samples for each sensor_gyro_fifo record for the icm20602 was unvarying at 20 samples per. Perhaps the sample timestamp should actually be: timestamp_sample = _last_timestamp_sample + samples * FIFO_SAMPLE_DT? Does "local" processor time really matter more than real-time, as measured by the IMU?

That could be fine as along as we're careful to not let it get too far off (reset, IMU clock difference, etc). Typically this sample timestamp is set directly from the data ready interrupt.

Note that when the gyro data is actually filtered to produce vehicle_angular_velocity the dt for each FIFO sample is used directly from the message, rather than calculated from timestamp_sample. https://github.com/PX4/PX4-Autopilot/blob/a2389652287a398df15002c8ff1770ca2a5ae029/src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp#L665

I was also planning to update the IMU integration to use the FIFO and dt as well. At that point the timestamp_sample field is mainly a convenient way to see how long the transfer took.

**Comment by danduril** [comment]
`sensor_gyro_fifo.samples`, at IMU_GYRO_RATEMAX = 400Hz, is perfect, every time: 20, for 20602, and 22 for the other two (bcs those other chips have 9kHz ODR).

`sensor_gyro_fifo.timestamp_sample` deltas still bangs between 2500uS and ~5000uS. I think that means whole sample sets get overwritten fairly frequently.
Screenshot from 2021-09-12 12-49-10

**Comment by danduril** [comment]
Good to go!

**Comment by dagar** [comment]
Thanks @danduril. I suppose that remaining jitter makes sense in this case (cube orange) given the bus utilization (4 drivers sharing SPI4) and the sensor interrupts not being connected. The only idea for further improvement I have is to try and estimate how fast the sensor is actually generating samples and try to sync up. We've probably reached the point of diminishing returns...

**Pull request merged**
