### PR TITLE
[WIP] DO_CHANGE_SPEED work across LOITER, MISSION, RTL

### PR DESCRIPTION
**Pull request by dagar**
Opening for further discussion and testing, please do not merge.

TODO:
 - review behaviour wrt VTOL transitions
 - define mission behaviour
   - debatably, the speed should be set as a property of the current mission
   - example: setting mission speed, temporarily leaving leaving mission mode, then resuming

### CODE REVIEW

**Comment by dagar** [comment]
@sanderux do you have any input here? This might be a good time to review and document your requirements (current and desired).

**Comment by dagar** [comment]
@superware

**Comment by LorenzMeier** [comment]
A quick pass looks good to me.

**Comment by sanderux** [comment]
does this work for setting cruise throttle? (disabled airspeed sensors)

**Comment by sanderux** [comment]
our use case for changing speed would be 
- from an onboard computer monitoring vehicle behavior and detecting a requirement for more speed
- custom behavior: change flight setting from efficient to performance and back
- custom behavior: Quick RTL / Bird strike avoidance

So for us it is not so much a mission setting but a way for external systems (or perhaps in the future through QGC) of defining the vehicles speed.

**Comment by julianoes** [comment]
We probably still need this.

**Comment by superware** [comment]
Hi @julianoes, can you please reopen?

**Comment by julianoes** [comment]
> Hi @julianoes, can you please reopen?

It's still open.

**Comment by LorenzMeier** [comment]
Closing as stale.

**Pull request closed without merging**
