### PR TITLE
nxp_ucans32k146:Brings in NuttX Backport for LPSPI DMA and enables it and UART DMA, Adds Probes 

### PR DESCRIPTION
**Pull request by davids5**
This Brings in  NuttX backports for s32k1 LPSI.

- It configures the nxp_ucans32k146 to use DMA on Serial and LPSPI 
- It changes the HW Handsake on RTS to be watermark (buffer) based not per char.
- It adds PROBS for debugging
- It adds support for DREADY by adding Ki gpiosetevent support

### CODE REVIEW

**Comment by davids5** [comment]
https://github.com/PX4/NuttX/pull/208 needs to come in and this repointed.

**Comment by davids5** [comment]
@dagar NuttX backports are merged and this PR has been repointed

**Comment by davids5** [comment]
@PetervdPerk-NXP - Do we need the PM fix Backported?

**Comment by PetervdPerk-NXP** [comment]
PM is only used on the BMS-772

**Pull request merged**
