### PR TITLE
[DO NOT MERGE] Test CI

### PR DESCRIPTION
**Pull request by sfuhrer**
CI for VTOLs and FW fail, but locally (at least the standard VTOL) runs smoothly.
image

### CODE REVIEW

**Comment by sfuhrer** [comment]
why?
image

**Comment by dagar** [comment]
> why?
> image

It's free.

**Comment by dagar** [comment]
Actually, that looks like it could be our fault with what's running after transition. We should do some profiling.

In general though I've seen lots of CI logs have cpu usage that look terrible, and it's what I've come to expect from free CI services.

**Comment by sfuhrer** [comment]
> Actually, that looks like it could be our fault with what's running after transition. We should do some profiling.
> 
> In general though I've seen lots of CI logs have cpu usage that look terrible, and it's what I've come to expect from free CI services.

right, I was just wondering if it being maxed out after transition could in some way be related to it failing (crashing) in the SITL CI, but not locally

**Pull request closed without merging**
