### PR TITLE
Multicopter rounded turns

### PR DESCRIPTION
**Pull request by bresch**
This creates more rounded turns in multirotor mission using l1-style guidance logic in corners.

Example of what can be done (default acc/jerk, acceptance radius of from 2m to 8m):
https://logs.px4.io/plot_app?log=616bf543-eb2f-44a8-90fa-63cc4b7795f6
DeepinScreenshot_select-area_20201211134534

- This will only change mission flights
- The drone doesn't stop at each waypoint but decelerates to make a turn at constant speed
- The turning radius is defined by the waypoint acceptance radius `NAV_ACC_RAD`
- A wide range of accelerations (`MPC_ACC_HOR`), jerk (`MPC_JERK_AUTO`) and velocities (`MPC_XY_CRUISE`) should work.
- Use [MPC_YAW_MODE](https://dev.px4.io/master/en/advanced/parameter_reference.html#MPC_YAW_MODE) "along trajectory" for a nice yaw coordinated turn

Other example:
Rounded_turns

### CODE REVIEW

**Review by jkflying — APPROVED** [review]

**Review by MaEtUgR — COMMENTED** [review]
Looks good 👍 
If you need a review you have to give me some working hours 🤷‍♂️

**Comment by aredub83** [comment]
I'm looking for help with this. I too am flying LiDAR on the AltaX. I'm no good at any coding. Anyone here willing to assist in getting my bird setup for these curved turns?

**Comment by mrpollo** [comment]
@aredub83 you should talk to FreeFly Systems, and figure out which flavor of PX4 are you currently running, and if this feature is included. If the feature is already included, they should be able to help you tune the parameters in your mission control software.

Let me know if this doesn't solve your question.

**Comment by aredub83** [comment]
> @aredub83 you should talk to FreeFly Systems, and figure out which flavor of PX4 are you currently running, and if this feature is included. If the feature is already included, they should be able to help you tune the parameters in your mission control software.
> 
> Let me know if this doesn't solve your question.

I've found another post from @arktix regarding this. It sounds like they may be working on a solution. I've emailed Freefly now and hope to have something back from them. Thanks for the reply!

**Comment by mrpollo** [comment]
Sounds good! FreeFly is a super friendly company and should be able to help you.

**Comment by muramura** [comment]
Is this feature included in the current release?
I have experienced the behavior of stopping at a WAYPOINT in version V1.13.

**Comment by dakejahl** [comment]
@muramura 
> The turning radius is defined by the waypoint acceptance radius NAV_ACC_RAD

**Comment by muramura** [comment]
@dakejahl san. Comments thanks.

I am conducting a survey flight over terrain. In this case, many waypoints are created along straight line segments.
I believe that increasing the navigation accuracy radius will cause the flight path to zigzag along those straight lines.
Is my understanding incorrect?

**Comment by dakejahl** [comment]
@muramura let's continue the discussion in a new issue. Can you open one with your questions and any flight logs you can share?

**Pull request merged**
