### PR TITLE
ekf2: fake_pos don't use fuseHorizontalPosition helper

### PR DESCRIPTION
**Pull request by dagar**
- fake_pos shouldn't update _time_last_hor_pos_fuse

### CODE REVIEW

**Comment by dagar** [comment]
If we respect that only valid aid sources update `_time_last_hor_pos_fuse`, etc later we can simplify the logic in updateHorizontalDeadReckoningstatus().

**Review by haumarco — DISMISSED** [review]
Maybe we need to with about renaming the variable to time_last_hor_pos_meas_fuse, since in theory the current timestamp should simply track the last fusion time of any kind, not only measurements

**Comment by dagar** [comment]
> Maybe we need to with about renaming the variable to time_last_hor_pos_meas_fuse, since in theory the current timestamp should simply track the last fusion time of any kind, not only measurements

I'm not sure I'm following, can you elaborate or provide a specific example?

Possibly related, in a follow up I was going to propose dropping `_time_last_hor_pos_fuse`, `_time_last_hor_vel_fuse`, etc from the reset helpers (eg resetHorizontalVelocityTo()), and then we'd have very simple checks higher level to know if something is actually active or not without worrying about getting stuck in reset cycles.

**Comment by haumarco** [comment]
> I'm not sure I'm following, can you elaborate or provide a specific example?

I was referring to the fact that the fusion of the fake position is still a horizontal-pos-fusion. Therefore, if I want to know for when the last position was fused, __time_last_hor_pos_fuse_ should be updated as well after a fake pos fusion (given the variable name). But I think its alright anyways.

**Review by haumarco — APPROVED** [review]

**Pull request merged**
