### PR TITLE
uavcan_stm32h7:can driver preserve ordering & respect timeouts on borked hardware

### PR DESCRIPTION
**Pull request by davids5**
Referring to the refernece manual:

     Tx queue operation is configured by programming FDCAN_TXBC.TFQM to 1. Messages
     stored in the Tx queue are transmitted starting with the message with the lowest message
     ID (highest priority). **In case that multiple queue buffers are configured with the same
     message ID, the queue buffer with the lowest buffer number is transmitted first**

    Tx FIFO operation is configured by programming FDCAN_TXBC.TFQM to 0. Messages
    stored in the Tx FIFO are transmitted starting with the message referenced by the get index
    FDCAN_TXFQS.TFGI. After each transmission the get index is incremented cyclically until
    the Tx FIFO is empty. The Tx FIFO enables transmission of messages with the same
    message ID from different Tx buffers in the order these messages have been written to the
    Tx FIFO

    The issue will be cancelation:

    The FDCAN supports transmit cancellation. To cancel a requested transmission from a
    dedicated Tx buffer or a Tx queue buffer the Host has to write a 1 to the corresponding bit
    position (= number of Tx buffer) of register FDCAN_TXBCR. Transmit cancellation is not
    intended for Tx FIFO operation.

    But there is nothing preventing it. This seems to indicate it will
    work. When a transmission request for the Tx buffer referenced by the get index is canceled, the
    get index is incremented to the next Tx buffer with pending transmission request and the Tx
    FIFO free level is recalculated. When transmission cancellation is applied to any other Tx
    buffer, the get index and the FIFO free level remain unchanged.

### CODE REVIEW

**Review by LorenzMeier — APPROVED** [review]

**Comment by LorenzMeier** [comment]
I've merged this because the failures are unrelated - these need to be worked through ASAP independently.

**Comment by JacobCrabill** [comment]
@davids5 is there a specific reason to switch from queue to FIFO?  Just wondering.
Good catch on adding the timeouts on setting the various control bits.

**Comment by davids5** [comment]
@JacobCrabill Yes - to maintain the ordering. 

The bootloader does a file read. The 256 byte array spans several frames. The receiver was failing the sequence number (toggle bit) was wrong. 

image

image

I imagine this is less noticeable on multi frame message that are shorter, and repeated often, but I would assume it could cause issues.

From the RM

Queue:
**In case that multiple queue buffers are configured with the same
 message ID, the queue buffer with the lowest buffer number is transmitted first**

when on is > off this causes reordering. 

The Fifo:
The Tx FIFO enables transmission of messages with the same message ID from different Tx buffers in the order these messages have been written to the Tx FIFO

**Comment by pavel-kirienko** [comment]
@davids5 Does FIFO respect CAN ID prioritization? If not, you will eventually run into inner priority inversion which may be costly for a real-time process.

**Comment by pavel-kirienko** [comment]
We just spoke with David about this. We found an error in the documentation for the new FDCAN macrocell. In the table below, where it says "FIFO order" in the rightmost column is a mistake:

Screenshot_20210323_183156

David may or may not reach out to someone in ST about this to see if there is a proper way to work around this. Barring that, it is possible to implement the same workaround in software [as we already do in the bxCAN driver](https://github.com/UAVCAN/platform_specific_components/blob/master/stm32/libcanard/bxcan/src/bxcan.c#L538-L605), but it is far from optimal because it increases the interrupt load along with transmission latency.

**Pull request merged**
