### PR TITLE
boards: Lines are arranged in ascending order

### PR DESCRIPTION
**Pull request by muramura**
### Solved Problem

None

### Solution

I add a system command.
I have learned that the line is written in ascending order.
I have learned that I, in part, am not adhering to this style.
I will change the line to ascending order.

### Alternatives

None

### Test coverage

I built with HOLYBRO DURANDAL after the change and it built successfully.

[1107/1109] Linking CXX executable holybro_durandal-v1_default.elf
Memory region         Used Size  Region Size  %age Used
        ITCM_RAM:          0 GB        64 KB      0.00%
           FLASH:     1893496 B      1920 KB     96.31%
       DTCM1_RAM:          0 GB        64 KB      0.00%
       DTCM2_RAM:          0 GB        64 KB      0.00%
        AXI_SRAM:       44804 B       512 KB      8.55%
           SRAM1:          0 GB       128 KB      0.00%
           SRAM2:          0 GB       128 KB      0.00%
           SRAM3:          0 GB        32 KB      0.00%
           SRAM4:          2 KB        64 KB      3.12%
          BKPRAM:          0 GB         4 KB      0.00%

### Context

None

### CODE REVIEW

**Comment by PetervdPerk-NXP** [comment]
Related to #20841 
One can run `make updateconfig` to do this automatically.
@dagar but we've to either check this or run this command periodically on .px4board changes.
Maybe add a CI check that checks if checked-in px4board files are the same after running `make updateconfig` and if not we indicate a fail?

**Comment by dagar** [comment]
Replaced with automatic PX4Buildbot update. https://github.com/PX4/PX4-Autopilot/pull/20869

**Comment by dagar** [comment]
Replaced with automatic PX4Buildbot update. https://github.com/PX4/PX4-Autopilot/pull/20869

**Comment by muramura** [comment]
I know I have the tools.  thank you.

**Pull request closed without merging**
