### PR TITLE
more consistent quadchute messages

### PR DESCRIPTION
**Pull request by ThomasRigi**
A minor PR to clean up the Quadchute messages that are sent over mavlink. When read out over QGC, I always found it a bit weird that some only say "Abort: xxx" whereas others say "Abort: QuadChute: xxx". With this PR I replaced the "Abort:" with a "Quadchute: " Like this, the first thing you hear voiced is Quadchute so you know faster what's going on. And most messages are now shorter.

@sfuhrer what do you think? I know it's not essential, but it's something that's been bugging me slightly for long enough and it doesn't take much to change.

### CODE REVIEW

**Comment by dagar** [comment]
Looks good from my perspective. To be honest I also wonder about dropping the "QuadChute" naming entirely, it sounds a little gimmicky. Why not just say "emergency back transition" or something?

**Comment by ThomasRigi** [comment]
"Quadchute" is shorter than "emergency back transition". ;) and you could argue that it's not really a back transition if you skip the back transition phase. (on the other hand you could also argue that any mode switch is a transition)

Personally I quite like the term Quadchute. It's catchy and easy to remember. But now that I think of it, I prefer "Quadchute" to "QuadChute", so I'm going to change this. Already a bit less gimmicky

**Comment by dagar** [comment]
> "Quadchute" is shorter than "emergency back transition". ;) and you could argue that it's not really a back transition if you skip the back transition phase. (on the other hand you could also argue that any mode switch is a transition)
> 
> Personally I quite like the term Quadchute. It's catchy and easy to remember. But now that I think of it, I prefer "Quadchute" to "QuadChute", so I'm going to change this. Already a bit less gimmicky

I'm fine with keeping it if people like it and think it's reasonably self explanatory.

**Review by dagar — APPROVED** [review]

**Review by sfuhrer — APPROVED** [review]
I agree that Quadchute is catchy for us that use the system on a regular basis, but for a default drone user it may be confusing. Plus there's a lot VTOLs out there than don't have a Quad-based hovering system (e.g. duo or tri copter), so something more generic would be nice.
I don't like the "back" in backtransition too much - but "Emergency switch to hover mode" is even longer. But that would capture the action more precisely. 

Okay to bring it in like this though as making things consistent is the first step :ok_hand:

**Comment by ThomasRigi** [comment]
"Emergency switch to MC" would be marginally shorter than "Emergency switch to hover mode". But then acronyms aren't very nice to be voiced.

**Comment by dagar** [comment]
> Plus there's a lot VTOLs out there than don't have a Quad-based hovering system (e.g. duo or tri copter), so something more generic would be nice.

Yes the lack of a quad across all VTOL types is why I started thinking the name might not be great.

**Pull request merged**
