### PR TITLE
mantis-edu: remove duplicate RC define

### PR DESCRIPTION
**Pull request by MaEtUgR**
### Solved Problem
@lyraik found this duplicate define 🧹

### CODE REVIEW

**Review by julianoes — APPROVED** [review]
Funny.

Also, we could just remove the whole board instead, right?

**Comment by dagar** [comment]
> Funny.
> 
> Also, we could just remove the whole board instead, right?

I'm not sure if there's literally any chance of it being used again.

Either way we definitely need to get to a point where we don't carry board specific hacks. 

https://github.com/PX4/PX4-Autopilot/blob/1bd65f8bebf99a20c2d31c2e78b26e3806f87ad4/src/modules/mavlink/mavlink_receiver.cpp#L2030

https://github.com/PX4/PX4-Autopilot/blob/1bd65f8bebf99a20c2d31c2e78b26e3806f87ad4/src/modules/rc_update/rc_update.cpp#L649

**Comment by julianoes** [comment]
I don't think it ever went anywhere, right? So we might as well purge it?

**Comment by MaEtUgR** [comment]
> we could just remove the whole board instead, right?

It would just render the 30 drones we just set up a few weeks ago to test main incapable of testing main. That's where the attention for this pr comes from. I'd wait a bit for them to not get used anymore.

**Comment by julianoes** [comment]
Oh, well I didn't know about that!

**Pull request merged**
