### PR TITLE
parameters: don't keep in memory if set to default

### PR DESCRIPTION
**Pull request by dagar**
This avoids unnecessarily keeping params set to default value in memory or having to export them to non-volatile storage.

### CODE REVIEW

**Comment by dagar** [comment]
Example: stock pixracer (generic quadcopter 4001) after sensor calibration

### Master
Screen Shot 2020-12-01 at 11 42 09 PM

### PR
Screen Shot 2020-12-01 at 11 41 40 PM


This avoids saving things like all the default calibration values, which in this particular case saves 1 kB of memory due to a smaller parameter array. Things like param_export and param_get are also incrementally faster.

**Review by bkueng — APPROVED** [review]
Note that this also changes the user-bahavior: a value cannot be set explicitly to default anymore.

**Comment by dagar** [comment]
> Note that this also changes the user-bahavior: a value cannot be set explicitly to default anymore.

Yes, although I'd be surprised if any actual users were knowingly doing that.

For anyone else reading this the change is that if you explicitly set a parameter back to default (or reset a parameter back to default in QGC) that parameter value is going to be stored to non-volatile memory and restore at every boot. Later if you upgrade firmware and the actual system parameter default changed you will continue to have the old (now non-default) value.

**Comment by bys1123** [comment]
How to remove an explicitly set value from memory then?

**Comment by dagar** [comment]
> How to remove an explicitly set value from memory then?

This change stops storing anything being set to default. On the next import (system boot) the param is set, but if it's set to default then nothing it stored at all.

**Pull request merged**
