### PR TITLE
[WIP] increase FMU max PWM channels to 14 for CUAV X7Pro and Nora

### PR DESCRIPTION
**Pull request by dagar**
@CUAVcaijie 

Nora support: https://github.com/PX4/Firmware/pull/14475

### CODE REVIEW

**Comment by bys1123** [comment]
Just not sure, is PX4 support camera trigger on AUX 78 now?

**Comment by dagar** [comment]
> Just not sure, is PX4 support camera trigger on AUX 78 now?

Good question. It actually could be almost anywhere, but we've tried to keep the user facing configuration simple and deconflict with the majority of mixer usage. Let me take a look at how that all fits together and see what we can do short term.

**Comment by dagar** [comment]
@CUAVcaijie do you have any preference for how this should work? 

### Options
1. 14 MAIN PWM outputs (how my x7 prototype is labelled)
2. 8 MAIN + 6 AUX (as my Nora prototype is labelled)
    - extend `pwm_out` to run multiple instances

The advantage of option 2 is it would more directly translate from the other boards that had completely separate MAIN + AUX. This will matter for things like the existing VTOL airframes that use both.

**Comment by CUAVcaijie** [comment]
> @CUAVcaijie do you have any preference for how this should work?
> 
> ### Options
> 1. 14 MAIN PWM outputs (how my x7 prototype is labelled)
> 2. 8 MAIN + 6 AUX (as my Nora prototype is labelled)
>    
>    * extend `pwm_out` to run multiple instances
> 
> The advantage of option 2 is it would more directly translate from the other boards that had completely separate MAIN + AUX. This will matter for things like the existing VTOL airframes that use both.

Thanks, I also choose option 2

**Comment by cuhome** [comment]
@dagar I tested the pr-pwm14_1 branch firmware, Generic Quadplane VTOL frame aux1~aux5 have no signal output.

**Comment by LorenzMeier** [comment]
This has been merged in parallel.

**Comment by Jozmen** [comment]
Is it going to be included in 1.11.x or we need to wait for 1.12?

**Comment by dagar** [comment]
> Is it going to be included in 1.11.x or we need to wait for 1.12?

It's a sufficiently large change it will be v1.12, but that's going to be out very soon.

**Pull request closed without merging**
