### PR TITLE
Update submodule mavlink v2.0 to latest Thu Dec 17 23:05:10 UTC 2020

### PR DESCRIPTION
**Pull request by dagar**
- mavlink v2.0 in PX4/Firmware (3600b2abfc4f209aced9540aaf9bee62fab516e2): https://github.com/mavlink/c_library_v2/commit/8f481688d70541e8f91ee8c4fc233ca70cd7fad9
    - mavlink v2.0 current upstream: https://github.com/mavlink/c_library_v2/commit/5f03134f5b2f9ed72b9e7ba21dc128dfacb03fdd
    - Changes: https://github.com/mavlink/c_library_v2/compare/8f481688d70541e8f91ee8c4fc233ca70cd7fad9...5f03134f5b2f9ed72b9e7ba21dc128dfacb03fdd

### CODE REVIEW

**Comment by dagar** [comment]
Compile failure due to spec change.

Screen Shot 2020-12-17 at 6 18 03 PM

**Comment by dagar** [comment]
FYI @mrivi @BazookaJoe1900 this build is failing because Mavlink SMART_BATTERY_INFO (http://mavlink.io/en/messages/common.html#SMART_BATTERY_INFO) serial_number is now char[16].

Please advise how you'd like to update the PX4 side. Should we store it as a string back in batt_smbus?

https://github.com/mavlink/mavlink/pull/1529

**Comment by BazookaJoe1900** [comment]
I actually have ready pr to adjest the change on mavlink. I wasn't sure how it should be done, because it must be synced with the submodule.
I made the change on mavlink side, does it sound OK?
I can push it only tomorrow

**Comment by dagar** [comment]
> I actually have ready pr to adjest the change on mavlink. I wasn't sure how it should be done, because it must be synced with the submodule.
> I made the change on mavlink side, does it sound OK?
> I can push it only tomorrow

You can open the PR with the combined change + the submodule bump.

**Comment by BazookaJoe1900** [comment]
opened 'format smart battery serial number as string on mavlink #16453' to solve the change on SMART_BATTERY_INFO

**Comment by LorenzMeier** [comment]
Outdated, merged now, thanks!

**Pull request closed without merging**
