### PR TITLE
Decouple filepaths from rcS/MTD using Kconfig rootpath

### PR DESCRIPTION
**Pull request by PetervdPerk-NXP**
Removes hardcoded filepaths allows for use of filesystem and boardspecific filelocations.

Replaces #21891

### CODE REVIEW

**Comment by davids5** [comment]
@PetervdPerk-NXP - Rebased on man and added the rest of the paths.

**Comment by davids5** [comment]
@PetervdPerk-NXP Shal we un-draft this?

**Review by davids5 — APPROVED** [review]
LGTM

**Comment by dirksavage88** [comment]
I just tested the filepath changes on the CANHUBK3 FMU and the params are there, metadata seems to work better (don't need mavlink over ethernet if telem/uart connection is good). 

Had to manually change BOARD_ROOT_PATH to '/fs/microsd' get logging to work, though

**Review by dagar — APPROVED** [review]

**Comment by sfuhrer** [comment]
If I'm not mistaken then this PR broke some CI tests: 
image

**Comment by MaEtUgR** [comment]
The module documentation CI also fails after this. Here's my suggestion to not trip the parser anymore:
https://github.com/PX4/PX4-Autopilot/pull/23499

**Comment by PetervdPerk-NXP** [comment]
@Jaeyoung-Lim can you rebase on https://github.com/PX4/PX4-Autopilot/pull/23457 that should've fixed it

**Pull request merged**
