### PR TITLE
Always trigger all cameras

### PR DESCRIPTION
**Pull request by potaito**
### Solved Problem
The camera triggering logic is currently "random" when more than one camera sending a mavlink heartbeat is connected to PX4. The trigger logic in PX4 currently stores the last camera mavlink component ID it saw a heartbeat from, and then sends trigger commands to that camera. If there are multiple cameras sending heartbeats, it is more or less random which camera gets triggered when a capture command is sent to PX4. This includes missions that have capture waypoints, or surveys that capture a photo periodically.

### Solution
This PR changes the behaviour such that always all mavlink cameras are triggered, making the photo capture process deterministic, which is the main improvement.

This changes nothing for systems that have only one camera, as it will still trigger this one camera.

The only scenario where PX4 users would be negatively affected by this change, is if somebody were to use a camera that understands mavlink, receives mavlink messages, but does not send out its own heartbeat and is therefore invisible to PX4. Before this PR, such an invisible camera would not get triggered. After this PR it will. This is a very hypothetical scenario which I hope does not exist in reality. It would also be non-compliant with the mavlink protocol to have a component participate in the mavlink network without sending its own heartbeat.

### Changelog Entry
For release notes:
Bugfix: When multiple mavlink cameras are present, they will now all be triggered by PX4

### Test coverage
Tested on real hardware

### CODE REVIEW

**Comment by potaito** [comment]
@tstastny @dagar  this is not the perfect solution, but I would argue that any deterministic solution is better than undefined behaviour :)

**Review by tstastny — CHANGES_REQUESTED** [review]
lgtm - just need to run make format

**Review by tstastny — DISMISSED** [review]

**Review by tstastny — APPROVED** [review]

**Comment by tstastny** [comment]
@dagar Any idea why we're getting this message on jenkins for cuav_x7pro and px4fmu_v4?
> Running command: 'param save'
ERROR [parameters] param_save_default: file lock failed (already locked)
ERROR [param] Param save failed (-1)

I don't think this PR would have an effect on this.. but didnt know if this was an error you were tracking already?

**Comment by tstastny** [comment]
> @dagar Any idea why we're getting this message on jenkins for cuav_x7pro and px4fmu_v4?
>
> Running command: 'param save'
ERROR [parameters] param_save_default: file lock failed (already locked)
ERROR [param] Param save failed (-1)
>
> I don't think this PR would have an effect on this.. but didnt know if this was an error you were tracking already?

ok @bkueng told me this is related to the lock free param thing

**Pull request merged**
