### PR TITLE
[BACKPORTS v1.14] 6X rev6 and rev8 as well as PAB ID and FMUM split

### PR DESCRIPTION
**Pull request by julianoes**
This backports contains:

- https://github.com/PX4/PX4-Autopilot/pull/22716
- https://github.com/PX4/PX4-Autopilot/pull/22639 (without https://github.com/PX4/PX4-Autopilot/pull/22639/commits/d3c548b351ae1e5229805dbb7001b84fcefdd780 and https://github.com/PX4/PX4-Autopilot/pull/22639/commits/7ed20ec57c2807f14f6b1e5b499bb07db0217838)
- https://github.com/PX4/PX4-Autopilot/pull/22238
- https://github.com/PX4/PX4-Autopilot/pull/22708

FYI @vincentpoont2 

It's a bit of a scary/more involved backport due to https://github.com/PX4/PX4-Autopilot/pull/22639.

### CODE REVIEW

**Review by davids5 — COMMENTED** [review]
@julianoes It looks familiar:) 
What did the conflicts look like?
Can we get a run on the test rack and full CI?

**Comment by julianoes** [comment]
>  Can we get a run on the test rack and full CI?

Sure, how? :)

From what I remember, conflicts were around the RT board not being available yet, as well as the Auterion specific power module starter and the ina_launcher.

**Comment by julianoes** [comment]
@vincentpoont2 I've tested it on my Rev6. Do you want to do any other tests?

**Comment by vincentpoont2** [comment]
> @julianoes It looks familiar:) What did the conflicts look like? Can we get a run on the test rack and full CI?

@davids5 How do we get the FMU-6XRT to be on the test rack? 
@dagar Do you have one? Can we send you one of these unit? Same address?

**Comment by davids5** [comment]
FYI @PetervdPerk-NXP

**Comment by vincentpoont2** [comment]
Tested with the following VER and REV. All sensor startup without issue. 

image

**Comment by julianoes** [comment]
Tested on CUAV and gyro/accel are correct. (Mag and baros are not available but that's a problem orthogonal to this PR, see https://discord.com/channels/1022170275984457759/1040115319508832328/1219093339954221126.

**Pull request merged**
