### PR TITLE
Added PX4 VxX Mini baseboard

### PR DESCRIPTION
**Pull request by davids5**
@vincentpoont2 this is the WIP for the mini. I need to ring out the HW 100% still

### CODE REVIEW

**Comment by vincentpoont2** [comment]
@davids5 The Mini Baseboard (VER 5 Resistor) + Holybro FMUv6X. We encountered this. 
[FMUVX-BASE-MINI-Print.txt](https://github.com/PX4/PX4-Autopilot/files/8650909/FMUVX-BASE-MINI-Print.txt)

**Comment by vincentpoont2** [comment]
@davids5 With the REV resistor, the startup was abnormal.
image

Afterward, we tested the BASE-MINI without the VER resistor, the startup was normal, so the hardware should be OK.

**Comment by vincentpoont2** [comment]
Hi @davids5, is this ready to merge?

**Comment by davids5** [comment]
@vincentpoont2 

No. It needs to be rebased and tested.  It is on my todo list.

**Comment by davids5** [comment]
@vincentpoont2 - this is ready for test with a V5X FMUM and a V6X FMUM. 
Please test with all revs of sensors for each FMUM versions

**Comment by ryanjAA** [comment]
When I use this PR (and master from yesterday) on a 6X and go to the console (within QGC daily) and I type anything in and hit enter, the 6x reboots. This is on a Mac

**Comment by mhkabir** [comment]
@ryanjAA Might be related to https://github.com/PX4/PX4-Autopilot/pull/19690. Sounds like a hardfault when starting the mavlink shell.

**Comment by ryanjAA** [comment]
Thanks! Also does it when I try and sensor cal so there are a few things to work through.

**Comment by davids5** [comment]
@ryanjAA @mhkabir https://github.com/PX4/PX4-Autopilot/pull/19724 should fix the issue. This PR will need to be rebased once that comes in.

**Comment by vincentpoont2** [comment]
> @vincentpoont2 - this is ready for test with a V5X FMUM and a V6X FMUM. Please test with all revs of sensors for each FMUM versions

@davids5 Tested working on our 5X and 6X.

**Comment by davids5** [comment]
Rebased on master

**Review by dagar — APPROVED** [review]

**Pull request merged**
