### PR TITLE
stm32h7_can: fix filter memory initialization bug.

### PR DESCRIPTION
**Pull request by duartecdias**
While testing the reception of the feedback from KDECAN ESCs in the following public branch (https://github.com/duartecdias/PX4-Autopilot/tree/pr/uavcan/kdecanProtocol), it was noted that while using standard ids, some messages were not being received from the ESCs in a random fashion for different power cycles.

Problem was tracked down to the initialization of the filters (probably they are being initialized randomly at each power cycle). After proper memset of the respective filter areas the problem went away.

Also adjusted the number of maximum filters for extended IDs to 64, according to the h7 chip datasheet.

### CODE REVIEW

**Review by davids5 — APPROVED** [review]
LGTM

**Comment by davids5** [comment]
@duartecdias please run `make check_format` and fix the style issues.

**Comment by duartecdias** [comment]
@davids5 , let me know if ok to merge (MAVROS tests failing BTW..)

**Comment by davids5** [comment]
@dagar is HW CI Down?

**Comment by davids5** [comment]
@duartecdias - MAVROS look unrelated (as it should be) but I would like to see HW CI happy first.

**Review by dagar — APPROVED** [review]

**Pull request merged**
