### PR TITLE
Preflight check call simplifications

### PR DESCRIPTION
**Pull request by MaEtUgR**
## Describe the problem solved by this pull request
It's super confusing under what conditions what preflight/arm checks are actually called in the arm state machine.

## Describe your solution
I simplified the conditions to cover mostly how it was. It's not an exact refactor but I'm pretty sure it covers all the conditions we care about. The rest was in my eyes just complexity built from historic patches.

## Test data / coverage
I quickly tested that generally preflight checks still work as expected in simulation.

## Additional context
Builds on #19764, please review that one first.

### CODE REVIEW

**Comment by dagar** [comment]
Rebased on master to resolve conflict.

**Review by dagar — DISMISSED** [review]

**Review by dagar — DISMISSED** [review]

**Comment by dagar** [comment]
There are MAVROS CI failures, I'll take a closer look tomorrow.

**Comment by MaEtUgR** [comment]
> There are MAVROS CI failures, I'll take a closer look tomorrow.

Thanks for reviewing! Let me have a look.

**Comment by MaEtUgR** [comment]
Found the stupid mistake in writing 🤦‍♂️ 
https://github.com/PX4/PX4-Autopilot/compare/a3a59d730c18237b4cf03ca4c1ccce56911e667f..3178561cd4c5a76374bde1208c97749d032b9cea

**Pull request merged**
