### PR TITLE
Support multivehicle SITL simulations for rover in gazebo

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
**Describe problem solved by this pull request**
This adds support to simulate multiple rover vehicles at once. Previously this was not easy since the rover vehicle had to be ported into xacro macros to be able to support multivehicle simulations.

**Describe your solution**
This is the result of the migration of rover models into jinja templates in https://github.com/PX4/sitl_gazebo/pull/629

**Test data / coverage**
image

**Additional context**
- This PR requires https://github.com/PX4/sitl_gazebo/pull/629 to be merged in the  PX4/sitl_gazebo submodule

### CODE REVIEW

**Comment by hamishwillee** [comment]
Does this mean I can play rocket league in Gazebo? Huzzah! YOu know what I'm going to remind you to do when this is merged :-)

**Review by TSC21 — DISMISSED** [review]
LGTM

**Comment by TSC21** [comment]
@Jaeyoung-Lim can you rebase?

**Comment by Jaeyoung-Lim** [comment]
@TSC21 Thanks for the quick review!

**Review by TSC21 — APPROVED** [review]

**Comment by hamishwillee** [comment]
Haven't checked whether you have done this or not ... but reminder on docs!

**Pull request merged**
