### PR TITLE
Ark-flow: add a simple module to populate optical_flow message's gyro…

### PR DESCRIPTION
**Pull request by Donecle**
…s with onboard gyros measurements.

**Disclaimer**
This is my first PR, it will probably contain some obvious mistakes!

Please use [PX4 Discuss](http://discuss.px4.io/) or [Slack](http://slack.px4.io/) to align on pull requests if necessary. You can then open draft pull requests to get early feedback.

**Describe problem solved by this pull request**
This PR is meant for ARK-flow, that has an IMU onboard but publishes an optical_flow message with NAN on gyro integrated values.

**Describe your solution**
It creates a simple module (named FlowGyro, had no better inspiration) that subscribes to PAW3902 optical_flow and onbaord IMU sensor_gyro messages, and publishes basically the same optical_flow message with intergated gyros instead of NAN.

**Describe possible alternatives**
Not really considered any alternative...

**Test data / coverage**
Tested it on a real ARK-Flow board, helped by the debug port. See the gyro comparison between UAV's primary IMU and ARK-Flow's IMU in the attached screenshots (took on the same flight).
It has flown a dozen of ~5 minutes without any problem.

image
image

### CODE REVIEW

**Comment by dagar** [comment]
Thanks @Donecle. There are a few minor issues with this like the module both subscribing to optical_flow and then republishing it, but the general idea is solid.

I was considering doing this in the `sensors` hub module where we have this general pattern of aggregating sensor data from multiple sources, applying any corrections/calibrations/etc and then publishing the data for estimator consumption.

I was thinking of doing something similar for optical flow where each driver would publish `sensor_optical_flow` and full rate in the sensor frame. Then a new piece in the `sensors` module would consume `sensor_optical_flow` x N, synchronize with raw gyro, and integrate the flow data (rather than the driver doing it). Then we'd publish a new `vehicle_optical_flow` message that would be the integrated optical flow + gyro in the vehicle frame suitable for consumption by the estimator. There are a few minor different for the CAN node case, but I can explain later if this otherwise sounds fine.

Thoughts?

**Comment by Donecle** [comment]
Thanks @dagar. I agree this is a much cleaner way to make it - and much more useful for PX4, since it's not ARK-Flow specific. I'll try to find time to code it.
Just a question, some flow sensors have their own gyros onboard, how would you make sure to use those ones to fill vehicle_optical_flow, instead of primary or random gyros ? There may be differences in the damping which would - slightly - change the integrated value.

**Comment by AlexKlimaj** [comment]
Hi @Donecle see this PR https://github.com/PX4/PX4-Autopilot/pull/19714

**Comment by dagar** [comment]
Finished in https://github.com/PX4/PX4-Autopilot/pull/19714.

**Pull request closed without merging**
