### PR TITLE
uxrce add manual control setpoint subscriber and battery status publisher

### PR DESCRIPTION
**Pull request by AlexKlimaj**
@bradenwagstaff is working on controlling a rover through uxrce and manual_control_setpoint is needed.

### CODE REVIEW

**Comment by beniaminopozzan** [comment]
Hi @AlexKlimaj , one extra subscriber in not an issues, but out of curiosity, why is manual_control_setpoint needed? Are the existing topics not enough?

**Comment by AlexKlimaj** [comment]
There is currently no way to do manual control in offboard mode for rovers.

**Comment by AlexKlimaj** [comment]
Switched to manual-control-input instead of manual-control-setpoint and force pushed

**Comment by beniaminopozzan** [comment]
I see, but in any case, manual control in offboard mode is not possible for any vehicle. Offboard mode is intended for controlling the vehicle without RC / manual control.

Do you want to manually control the rover from a faked RC using ROS?

**Comment by AlexKlimaj** [comment]
Yes manual control for a rover makes sense where you just want to send throttle and steering.

**Comment by beniaminopozzan** [comment]
Hey @AlexKlimaj 
Do you still want this merged?

**Comment by AlexKlimaj** [comment]
> Hey @AlexKlimaj Do you still want this merged?

Yes I think its a useful feature.

**Review by beniaminopozzan — APPROVED** [review]

**Review by beniaminopozzan — APPROVED** [review]

**Pull request merged**
