### PR TITLE
Heater: added support of inverted IMU heat controller output

### PR DESCRIPTION
**Pull request by aviaks**
Depending on the hardware implementation of the IMU heater it can be controlled with either normal (active high) or inverted (active low) pin output. 

Current implementation supports only active high IMU heat controller output. 

This pull request allows to control both active high and active low IMU heat controller hardware implementation. This can be configured with the SENS_TEMP_INVERT parameter. By default, it's set to 0 which is normal non-inverted control output (active high). When set to 1 the control output will be inverted.

### CODE REVIEW

**Review by AlexKlimaj — APPROVED** [review]
Looks good.

**Comment by dagar** [comment]
This is kind of nitpicky, but could the parameter name be a bit closer to describing what this actually does?

`SENS_TEMP_INVERT` sounds like its inverting a temperature sensor or something.

**Comment by aviaks** [comment]
@dagar I was thinking quite a bit about this and it turned out to be the most appropriate one. I think we definitely want it to start with **SENS_TEMP_** to be within the same group and then we have 6 chars left. Probably it can be changed to something like `SENS_TEMP_INVOUT` or `SENS_TEMP_REVOUT` (inverted out or reversed out). Anyway, any suggestions are welcome.

**Comment by dagar** [comment]
Thanks, `SENS_TEMP_INVOUT` sounds fine to me. I think it's important to be self explanatory given the consequences of getting it wrong.

Maybe a little late to ask, but does this even need to be runtime configurable? Isn't this a static property of the board? Are you using this with completely stock PX4?

**Comment by mcsauder** [comment]
> Thanks, `SENS_TEMP_INVOUT` sounds fine to me. I think it's important to be self explanatory given the consequences of getting it wrong.
> 
> Maybe a little late to ask, but does this even need to be runtime configurable? Isn't this a static property of the board? Are you using this with completely stock PX4?

I like your suggestion @dagar , it seems configurable per board. Here is the current for fmu-v4:  https://github.com/PX4/PX4-Autopilot/blob/f9d8c613b048f58eb3110e9af13cb3a89c4c866f/boards/px4/fmu-v4/src/board_config.h#L148

Otherwise, what do you think of `SENS_TEMP_IO_INV` ?

The changes all look good to me, I felt similarly about the naming but I am happy to defer to @dagar !  Thanks for the PR.

**Comment by aviaks** [comment]
> Maybe a little late to ask, but does this even need to be runtime configurable? Isn't this a static property of the board? Are you using this with completely stock PX4?

@dagar, thanks for the good suggestion! No, it doesn't need to be runtime and can be defined once per board. Now can be defined as a static parameter in board_config.h. 

Thanks @mcsauder!

**Comment by dagar** [comment]
> No, it doesn't need to be runtime and can be defined once per board. Now can be defined as a static parameter in board_config.h.

Then honestly, maybe we're better skipping this (as a parameter) rather than leaving the possibility open to adventurous users?

At the board level we could make it unambiguous. For example look at the macros `VDD_5V_HIPOWER_EN()` and `VDD_3V3_SPEKTRUM_POWER_EN()` and note one is active high, the other active low.

https://github.com/PX4/PX4-Autopilot/blob/d8704cee67813c1b9d5001e5094a016520d8d797/boards/px4/fmu-v5/src/board_config.h#L275-L277

**Comment by aviaks** [comment]
> Then honestly, maybe we're better skipping this (as a parameter) rather than leaving the possibility open to adventurous users?

Yes, this is even better! Thanks for the example. However, this would require adding the definition to all board_config.h files which use a heater. I did it for fmu-v5 as an example and committed. Please let me know if this looks good to you, then I can update all other board_config.h where necessary.

**Review by dagar — DISMISSED** [review]
This looks good, and even simpler. Thanks

**Comment by aviaks** [comment]
Thanks! Macros was added to board_config.h where necessary.

**Review by mcsauder — APPROVED** [review]
Looks great to me.  Nice work!

**Comment by aviaks** [comment]
Thanks Mark!

**Comment by mcsauder** [comment]
Hi @aviaks , if you rebase against current master it will run the tests again and you can also squash your commits as well.

**Comment by aviaks** [comment]
Thanks, @mcsauder! Done.

**Comment by mcsauder** [comment]
Hi again @aviaks , it looks like there is more free space in fmu-v2 with the ecl migration.  If you rebase against current master again it will probably pass checks this time.

**Comment by aviaks** [comment]
> Hi again @aviaks , it looks like there is more free space in fmu-v2 with the ecl migration. If you rebase against current master again it will probably pass checks this time.

HI @mcsauder! I checked locally and it's still failing: 

```
Memory region         Used Size  Region Size  %age Used
           flash:     1035977 B      1008 KB    100.37%
            sram:       25492 B       192 KB     12.97%
          ccsram:          0 GB        64 KB      0.00/usr/local/Cellar/gcc-arm-none-eabi/20180627/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: px4_fmu-v2_default.elf section `.data' will not fit in region `flash'
/usr/local/Cellar/gcc-arm-none-eabi/20180627/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: region `flash' overflowed by 3785 bytes
collect2: error: ld returned 1 exit status
%
ninja: build stopped: subcommand failed.
make: *** [px4_fmu-v2] Error 1
```
This is using 65745a3676e1a68126cd9137f8f606006a3a7113 (current master), merging your latest commit b588b62b497be81b7104809d8bb75afc117c9c87 didn't help either.

**Comment by mcsauder** [comment]
> HI @mcsauder! I checked locally and it's still failing:
> This is using [65745a3](https://github.com/PX4/PX4-Autopilot/commit/65745a3676e1a68126cd9137f8f606006a3a7113) (current master), merging your latest commit [b588b62](https://github.com/PX4/PX4-Autopilot/commit/b588b62b497be81b7104809d8bb75afc117c9c87) didn't help either.
Hi @aviaks , I sent you a slack DM to bring your branch up to date.  Let me know on slack if you run into issues following those instructions.

**Comment by dagar** [comment]
This is passing once rebased.

**Review by dagar — APPROVED** [review]

**Pull request merged**
