### PR TITLE
FMU-V6XRT release/1.15 backports

### PR DESCRIPTION
**Pull request by PetervdPerk-NXP**
- Increase core voltage for stability.
- DShot timing fix
- Increase mtd_param size

Also pulls in stm32h7x7xx and ethernet changes from NuttX.

### CODE REVIEW

**Comment by dk7xe** [comment]
@NXPBenjaminK fyi

**Review by davids5 — APPROVED** [review]
LGTM - @PetervdPerk-NXP Please build test V6X and V6XRT to verify

**Comment by mrpollo** [comment]
Have we tested this PR in hardware?

**Comment by dk7xe** [comment]
@davids5 

```
[1227/1229] Linking CXX executable px4_fmu-v6x_default.elf
Memory region         Used Size  Region Size  %age Used
        ITCM_RAM:          0 GB        64 KB      0.00%
           FLASH:     1960356 B      1920 KB     99.71%
       DTCM1_RAM:          0 GB        64 KB      0.00%
       DTCM2_RAM:          0 GB        64 KB      0.00%
        AXI_SRAM:       99292 B       512 KB     18.94%
           SRAM1:          0 GB       128 KB      0.00%
           SRAM2:          0 GB       128 KB      0.00%
           SRAM3:          0 GB        32 KB      0.00%
           SRAM4:          2 KB        64 KB      3.12%
          BKPRAM:          0 GB         4 KB      0.00%
[1229/1229] Creating /home/user/git/PX4-Autopilot/build/px4_fmu-v6x_default/px4_fmu-v6x_default.px4
```

```
[1290/1292] Linking CXX executable px4_fmu-v6xrt_default.elf
Memory region         Used Size  Region Size  %age Used
           flash:     2122744 B      3968 KB     52.24%
            sram:       91436 B      1280 KB      6.98%
            itcm:      243272 B       256 KB     92.80%
            dtcm:         936 B       256 KB      0.36%
[1292/1292] Creating /home/user/git/PX4-Autopilot/build/px4_fmu-v6xrt_default/px4_fmu-v6xrt_default.px4
```

**Comment by dk7xe** [comment]
> Have we tested this PR in hardware?

The changes have been flight-tested on Tuesday by me in a custom build FW on the 6X-RT.

**Comment by dk7xe** [comment]
> Have we tested this PR in hardware?

@mrpollo Yes, especially for you Ramon i have done 6 testflights today ;)
### 
Drone setup

Tarot770 frame
T-Motor MN5006 380kv
MF1604 folding props
SLS 6S1P 12000mAh lipo
NXP FMURT1176
Holybro M10 GPS (on GPS1)
DroneCAN M8N GPS (on CAN1)
FETtec ESC60Apro (on CAN1 and CAN2 as well as PWM1-4 with Dshot600 failover)
Dronebridge on TELEM1
Holybro Remote ID on TELEM2
IRC Ghost Atto duo RX
HDzero freesyle VTX v3 (MSP) on GPS2
uAvionix PingRX on ExtUART
Retracts on PWM5
Camera Pitch Servo on PWM6


First two flights were done with [pr-bp-imxrt-release/1.15](https://github.com/PX4/PX4-Autopilot/tree/pr-bp-imxrt-release/1.15)
https://logs.px4.io/plot_app?log=28da085e-e880-4fd7-921f-e16fd7710e40
https://logs.px4.io/plot_app?log=b4b4030f-afcc-4b1b-96a3-e92ff25c8421

Other four flights were done with [release/1.15](https://github.com/PX4/PX4-Autopilot/tree/release/1.15) including [920005a2359575f50b7a954768dd3b691491d298](https://github.com/PX4/PX4-Autopilot/commit/920005a2359575f50b7a954768dd3b691491d298) from @MaEtUgR 
https://logs.px4.io/plot_app?log=d2a0f50e-46d1-444e-a2e5-cfb50549d8d3
https://logs.px4.io/plot_app?log=d77eee01-f309-404f-807a-b6ea8da0706a
https://logs.px4.io/plot_app?log=29a1c0fb-0462-476b-bc97-830223d4a664
https://logs.px4.io/plot_app?log=82ba9135-0041-4d5b-a953-96d23f536144

With this flights i have also tested my HDzero VTX with the pitch servo. Unfortunately MSP is not working. Need to look into that.
https://youtu.be/Ge3ek4H4kK4

**Pull request merged**
