### PR TITLE
CubeOrange/CubeOrange+: enable bl_update

### PR DESCRIPTION
**Pull request by julianoes**
Enable bl_update to be able to update the bootloader, or change from the pre-installed ArduPilot based bootloader.

Or is there a way without `bl_update` that I don't know about?

**Changelog:**
> Give PX4 users the option to switch bootloader from APM

### CODE REVIEW

**Comment by julianoes** [comment]
@dagar in general I agree, however, there is a specific problem here.

The `reboot -b` command to stay in bootloader doesn't work with the ArduPilot bootloader because of two reasons:

1. The magic number saved in RTC backup register 0 is different. (The one for fastboot is the same though.) We can potentially improve this situation by checking for either the ArduPilot magic number or the PX4 one, and then ArduPilot could do the same.

PX4 definitions:
https://github.com/PX4/PX4-Autopilot/blob/64e90b91aaaad6be0f1baa06a5fa2ae618f559f7/platforms/nuttx/src/bootloader/stm/stm32_common/main.c#L95
https://github.com/PX4/PX4-Autopilot/blob/55563eba49f87624d7b73356ea3d421fee7ec081/platforms/nuttx/src/px4/stm/stm32_common/board_reset/board_reset.cpp#L68

ArduPilot definition:
https://github.com/ArduPilot/ardupilot/blob/4934808ba82b2287cf5605e7e4ee8b71146f7e57/libraries/AP_HAL_ChibiOS/hwdef/common/stm32_util.h#L84

2. The other problem is that ChibiOS on ArduPilot resets the RTC backup registers if the clock selected is not the same one. PX4 sets the clock to HSE but ArduPilot has it set to NOCLOCK. It's not clear why that's selected on H7 based boards. I looked into using NOCLOCK as well, at least for Cube Orange+, just to be compatible, but NuttX doesn't let you select that. It's either HSE, LSE, LSI.

So given these two issues, I thought, it might make sense to update the bootloader. However, if we actually just don't care whether the "stay in bootloader" functionality, or fastboot without 5s wait, ought to work, then we can just ignore it.

One more note: if we don't include `bl_update` then we should also not include the bootloader binary, otherwise that's a waste of flash, right?

**Comment by dagar** [comment]
Thanks for the info, sounds like maybe we should include `systemcmds/bl_update` on any board that ships with the ArduPilot bootloader. I still think we should hesitate before encouraging regular users to update the bootloader unless they actually need it.

> One more note: if we don't include bl_update then we should also not include the bootloader binary, otherwise that's a waste of flash, right?

Yes I just changed that last week. https://github.com/PX4/PX4-Autopilot/pull/21316

**Review by dagar — APPROVED** [review]

**Comment by julianoes** [comment]
> Yes I just changed that last week. https://github.com/PX4/PX4-Autopilot/pull/21316

Ah nice, I missed that.

**Comment by mrpollo** [comment]
hey @julianoes @dagar is this good to merge?

**Pull request merged**
