### PR TITLE
TECS: Fix internal state init if dt is large

### PR DESCRIPTION
**Pull request by CarlOlsson**
**Describe problem solved by this pull request**
There was a bug in TECS which made the `_dt > DT_MAX` part of [this check](https://github.com/PX4/PX4-Autopilot/blob/cec31fd68512988f1eba072e167c4b53d1d1035c/src/lib/tecs/TECS.cpp#L465-L465) never trigger since just before we call the function we limit the _dt to be max `DT_MAX` [here](https://github.com/PX4/PX4-Autopilot/blob/cec31fd68512988f1eba072e167c4b53d1d1035c/src/lib/tecs/TECS.cpp#L539-L539).

This results in the fact that the internal TECS states are not reset if a VTOL vehicle is doing a second transition to cruise

**Test data / coverage**
Tested on TECS similar to v1.10.1

### CODE REVIEW

**Review by dagar — DISMISSED** [review]

**Comment by dagar** [comment]
This reminds me we should fully untangle the state update calls in TECS.

**Comment by CarlOlsson** [comment]
@dagar yes that would be nice. I forced push an update to my last commit to fix a typo, I accidentally copied the wrong timestamp variable before, should be correct now

**Comment by sfuhrer** [comment]
Shouldn't the reset actually be triggered by [this](https://github.com/PX4/PX4-Autopilot/blob/cec31fd68512988f1eba072e167c4b53d1d1035c/src/lib/tecs/TECS.cpp#L67)?
Btw, this dt [here](https://github.com/PX4/PX4-Autopilot/blob/cec31fd68512988f1eba072e167c4b53d1d1035c/src/lib/tecs/TECS.cpp#L68) doesn't seem to have any use..

**Comment by mrpollo** [comment]
@CarlOlsson hey do you have any updates on this PR? looks like an awesome feature to get into the codebase

**Comment by CarlOlsson** [comment]
> @CarlOlsson hey do you have any updates on this PR? looks like an awesome fix to get into the codebase

I don't see anything wrong with the PR, above @sfuhrer is just pointing out that TECS is a mess, which is true but unrelated to the fix here

**Review by LorenzMeier — APPROVED** [review]

**Pull request merged**
