### PR TITLE
mc_pos_control: skip takeoff logic when in fixed wing mode

### LINKED ISSUE #14933: [VTOL] Dangerous Back Transition
@RomanBapst 

**Describe the bug**
If the drone overshoots on a back transition, it initiates a FW style U turn, which already scares me in SITL. 
image
During this manoeuver the drone isn't capable of keeping the desired pitch, leading to a large drop in altitude, which makes the drone gain speed, which makes that the back transition doesn't finish.

Additionally, there is no support of the MC motors during the back transition. I would have expected them to [ramp up](https://docs.px4.io/master/en/advanced_config/parameter_reference.html#VT_B_TRANS_RAMP).

**To Reproduce**
It's not completely trivial to reproduce and it's not always entirely equal. Here is my setup with which I found the problem:
[bad_BT.zip](https://github.com/PX4/Firmware/files/4649422/bad_BT.zip)

Firmware  v1.11.0-beta2
-Gazebo: standard_vtol (modified sdf file to have stronger motors)
-Mission: simple mission using normal Takeoff waypoint to take off in FW mode (which is why I needed a stronger motor). Interestingly enough the back transition isn't the same when replacing the Takeoff waypoint with a VTOL takeoff waypoint.
-Parameters: mostly default, need to set CBRK_VTOLARMING = 159753 to allow arming in FW mode.

**Expected behavior**
1. The MC motors should ramp up during the back transition, independent of the take off method used.
2. (Even though it's a logical consequence of using FW L1 position control) IMO the drone shouldn't do this crazy U turn during transition. I'd be in favour of force-ending the transition when you are at the desired position even if the speed is too high.

**Log Files and Screenshots**
The first two logs are both with a FW takeoff, identical setup but the direction of the U turn is different. The third log shows the mission where FW takeoff has been replaced with VTOL Takeoff. It's interesting to see that the MC motors ramp up in this case.

https://logs.px4.io/plot_app?log=241b24bb-248a-4451-a7e0-4638565f9d34
https://logs.px4.io/plot_app?log=abe58451-984d-43e9-a8ac-31308bf0d66e

https://logs.px4.io/plot_app?log=99aa4c67-3e82-47d8-95a3-105c49280e6f

**Drone (please complete the following information):**
SITL Gazebo Standard VTOL with stronger motors

**Additional context**
Position controlled transitions have been introduced here: https://github.com/PX4/Firmware/pull/14405

### PR DESCRIPTION
**Pull request by RomanBapst**
Test to see if this fixes #14933

### CODE REVIEW

**Comment by MaEtUgR** [comment]
This is likely the problem but it should just skip the takeoff ramp if you're in that vtol mode like when you're taking of stabilized. See https://github.com/PX4/Firmware/blob/master/src/modules/mc_pos_control/Takeoff/Takeoff.cpp#L49

**Comment by RomanBapst** [comment]
@MaEtUgR Thanks, can you do a PR for that?

**Comment by dagar** [comment]
Presumably we didn't need this?

**Comment by RomanBapst** [comment]
@dagar Yes, looks like this was actually not the root problem.
According to @sfuhrer [this](https://github.com/PX4/PX4-Autopilot/pull/16443) fixed it.
Closing this.

**Pull request closed without merging**
