### PR TITLE
drivers: broadcom AFBR fix close to ground false readings

### PR DESCRIPTION
**Pull request by AlexKlimaj**
This PR attempts to fix the broadcom AFBR reading false readings when very close to the ground. 

https://review.px4.io/plot_app?log=4da0db08-522e-488a-942e-369b6085f239#Nav-Distance-Sensor
https://review.px4.io/plot_app?log=10f570a2-89f7-4696-8ea5-bb79e320d72f#Nav-Distance-Sensor
https://review.px4.io/plot_app?log=290041ef-6abb-4e1f-b236-fd2363087bf5#Nav-Distance-Sensor
https://review.px4.io/plot_app?log=aaad65cd-3eff-4237-b918-b2fbaf7ffe9a#Nav-Distance-Sensor
https://review.px4.io/plot_app?log=8c5acf8d-e921-49fd-8dc2-dda2aa7444b3#Nav-Distance-Sensor

It still looks like it can get into a state when right next to the ground where it reads ~3cm.

image
image
image
https://review.px4.io/plot_app?log=8c5acf8d-e921-49fd-8dc2-dda2aa7444b3#Nav-Distance-Sensor

### CODE REVIEW

**Comment by dirksavage88** [comment]
Will short range mode switch to long range at around ~5m? I have been testing in short range mode as default for a few weeks now. The sensor seems to be reading a minimum of 6-7cm but any lower and it seems to be unreliable.

**Comment by AlexKlimaj** [comment]
> Will short range mode switch to long range at around ~5m? I have been testing in short range mode as default for a few weeks now. The sensor seems to be reading a minimum of 6-7cm but any lower and it seems to be unreliable.

Yeah that's because the current driver only uses dual frequency mode x8. This PR turns on DFM for short range. With DFM off in short range mode, below 8cm is working well.

**Comment by dirksavage88** [comment]
https://logs.px4.io/plot_app?log=68d80259-360e-4888-a246-2a5fdf34ff71

**Review by dagar — APPROVED** [review]

**Comment by dirksavage88** [comment]
broadcom

**Pull request merged**
