### PR TITLE
delete old style mode switches

### PR DESCRIPTION
**Pull request by dagar**
Having multiple ways to configure RC switches is bad for both users and developers. There are certain features that only work in one mode, but not the other, and we don't have good test coverage for either.

I suspect some people will be opposed to this, so I'm opening the PR to prompt the discussion.

**Let's figure out how to get to a single good RC configuration.** Keeping both with little to no testing is not acceptable.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@DonLakeFlyer How do you feel about this?

**Comment by hamishwillee** [comment]
FWIW, I agree this is needed. 

I guess the benefit of multiple channel mode setup is that the transmitter doesn't need to be particularly configurable. However this this was one of the hardest things I have documented ([QGC](https://docs.qgroundcontrol.com/en/SetupView/FlightModes.html)/[PX4](https://docs.px4.io/en/config/flight_mode.html)) and I'm still not sure it is something I'd ever choose to use.

**Comment by dagar** [comment]
Personally I could live with either (as long as you can use QGC to change as well), but definitely not both.

**Comment by DonLakeFlyer** [comment]
Are you talking about flight mode switch setup? The simpler 6 mode selection method versus the insane flight modes from hell flowchart setup which I can't even remember how it all works? If so, then I assume you are talking about getting rid of the crazy one?

**Comment by jgoppert** [comment]
I agree that just settling on one is best.

**Comment by tubeme** [comment]
We think that with two ways setting up flight modes selection is very complicated especially for the novice. It creates users manual complications as well.

For a long time we used the multi-channel selection vs. single channel selection because we had the option to use more than 6 modes which is a must for some professional setups.

But the single channel selection is very straight forward and much easier to grasp for the pilots if they are novice or if they come from another autopilot.

So our request is to ADD two more mode slots in the single channel selection ie 8 instead of 6 modes and remove the multi-channel selection option totally.

This way whoever wants to use 3 mode switch, 6 mode switch or a mix in their RC will be able to do it very nicely and fast with the single channel selection.

I can prepare a Template for the Taranis mix that could help the novice to set it up very fast their craft?

**Comment by sanderux** [comment]
How long has the single channel switch been in stable?

**Comment by dagar** [comment]
Only 2 years or so.

**Comment by sanderux** [comment]
Then i suppose its time. But it does seem to me like it should be in a major release, not a minor.

**Comment by tubeme** [comment]
@dagar @sanderux How about the 8 modes idea vs. 6 modes? or toggle between 6 and 8?

**Comment by hamishwillee** [comment]
Is there a theoretical limit to how many modes could be set in a channel, and on a Taranis how many switches can be mapped to  a single channel? If not, then why stop at 8?

Also, multi-channel as currently implemented is complicated, but another alternative is to support single channel as we currently have it "multiple times". Ie you select a channel, do the mapping using single channel, then you select another channel and do the same thing.

**Comment by tubeme** [comment]
@hamishwillee There is no limit on the mixing in the RCs so no problem to do it with 10 ch... but I think just 8 channels is good enough to accommodate the take off and landing.

Your idea is not possible with using multiple channels with 6 slots each because you need to introduce priorities and it is impossible to make it work nicely because of 100 corner cases. That was discussed long time ago in the git.

**Comment by dagar** [comment]
Related https://github.com/PX4/Firmware/issues/9144

**Comment by dagar** [comment]
This will be done with the px4io cleanup. https://github.com/PX4/PX4-Autopilot/pull/16444

**Comment by DonLakeFlyer** [comment]
@dagar It's unclear to me. Should the crazy complicated flight mode switch setup be removed from QGC?

**Comment by dagar** [comment]
> @dagar It's unclear to me. Should the crazy complicated flight mode switch setup be removed from QGC?

Not quite yet, but I think we'll finally be able to soon. Any concern from your side?

**Comment by DonLakeFlyer** [comment]
My only concern is that it can't go away fast enough! That whole thing makes my head hurt.

**Pull request closed without merging**
