### PR TITLE
CUAV V6X board support

### PR DESCRIPTION
**Pull request by davids5**
Continuing https://github.com/PX4/PX4-Autopilot/pull/19750 here. 

Rebased on current master.

### CODE REVIEW

**Review by bmeagher — COMMENTED** [review]
@davids5  I believe your proposed change for the RM3100 self test bug does not address the fundamental problem with the current self test implementation.  The software timeout needs to be greater than what is programmed into the RM3100 BIST register (0x33).  The current implementation sets the BW and BP bits to all 1's (the maximum value).  This equates to a timeout value of 480us (4 sleep oscillation cycles per LR timeout period and 4 LR periods for BIST) according to the latest published datasheet.  Currently, the driver is waiting 26ms (2*RM3100_INTERVAL) which is significantly longer than required.  See pull request #19583 for a proposed fix to address the RM3100 self test failures.  I’d be interested to know if my proposed changes address the RM3100 self test failures you are experiencing on your flight controller.

**Comment by davids5** [comment]
> @davids5 I believe your proposed change for the RM3100 self test bug does not address the fundamental problem with the current self test implementation. The software timeout needs to be greater than what is programmed into the RM3100 BIST register (0x33). The current implementation sets the BW and BP bits to all 1's (the maximum value). This equates to a timeout value of 480us (4 sleep oscillation cycles per LR timeout period and 4 LR periods for BIST) according to the latest published datasheet. Currently, the driver is waiting 26ms (2*RM3100_INTERVAL) which is significantly longer than required. See pull request #19583 for a proposed fix to address the RM3100 self test failures. I’d be interested to know if my proposed changes address the RM3100 self test failures you are experiencing on your flight controller.

@bmeagher - Thank you! This was not my work, just a continuation of a PR I could not write to.

@mxiaogit  Let's drop [8ea548d](https://github.com/PX4/PX4-Autopilot/pull/19819/commits/8ea548d967e1dacb5e9365c362b6167f6dd679dc) and when https://github.com/PX4/PX4-Autopilot/pull/19583 comes it will be fixed

**Comment by mxiaogit** [comment]
> > @davids5 I believe your proposed change for the RM3100 self test bug does not address the fundamental problem with the current self test implementation. The software timeout needs to be greater than what is programmed into the RM3100 BIST register (0x33). The current implementation sets the BW and BP bits to all 1's (the maximum value). This equates to a timeout value of 480us (4 sleep oscillation cycles per LR timeout period and 4 LR periods for BIST) according to the latest published datasheet. Currently, the driver is waiting 26ms (2*RM3100_INTERVAL) which is significantly longer than required. See pull request #19583 for a proposed fix to address the RM3100 self test failures. I’d be interested to know if my proposed changes address the RM3100 self test failures you are experiencing on your flight controller.
> 
> @bmeagher - Thank you! This was not my work, just a continuation of a PR I could not write to.
> 
> @mxiaogit Let's drop [8ea548d](https://github.com/PX4/PX4-Autopilot/pull/19819/commits/8ea548d967e1dacb5e9365c362b6167f6dd679dc) and when #19583 comes it will be fixed

@davids5 Yes, we can delete it.

**Comment by davids5** [comment]
@mxiaogit - I have dropped that commit and rebased on current master.

**Comment by cuhome** [comment]
@davids5 Pixhawk V6X kit will include CAN PMU Lite, can you enable Dronecan battery monitor by default?

**Comment by dagar** [comment]
You want to backport this for v1.13.1?

**Comment by davids5** [comment]
Well good news it works

**Comment by davids5** [comment]
@dagar I do not have time to do the back port do you?

**Comment by cuhome** [comment]
@dagar @davids5 This pr was not merged into the newly released 1.13.1stable, but was merged in 1.13.0master, can you please help me?
image

**Comment by julianoes** [comment]
The v1.13.2 has been released but I have no objections to a v1.13.3 once more backports like this one are in.

**Comment by mrpollo** [comment]
@julianoes we need to make sure things like this don't slip from releases, there doesn't seem to be any process for that currently

**Comment by julianoes** [comment]
I don't have the overview of all these things and what needs to be backported, sorry.

**Comment by cuhome** [comment]
@davids5 @dagar How should we deal with it?

**Comment by mrpollo** [comment]
@cuhome we are working on a point release for your hardware

**Comment by dagar** [comment]
I'm verifying things here.

**Comment by cuhome** [comment]
image
@dagar Thanks, when there is no gps positioning, the wrong altitude (>1000) (local_position_ned) appears.

**Comment by cuhome** [comment]
image

**Comment by mrpollo** [comment]
@cuhome there's a PR for this #21765

**Pull request merged**
