### PR TITLE
send safety switch status to ground

### PR DESCRIPTION
**Pull request by garfieldG**
**Describe problem solved by this pull request**
I added a bit to the health flags that will pass the safety switch status.

**Describe your solution**
Safety switch status is one of the health flags.

### CODE REVIEW

**Comment by dagar** [comment]
Doesn't this diverge from the mavlink spec?

http://mavlink.io/en/messages/common.html#MAV_SYS_STATUS_SENSOR

Screenshot from 2021-03-11 16-50-58

**Comment by LorenzMeier** [comment]
Adding the field to the system state (safety off) can make sense from a MAVLink spec perspective.

I would propose an additional approach where you add a new message like:

```
Enums:
ENUM USER_SWITCH_STATE:
0: Not present
1: MOMENTARY_OFF
2: MOMENTARY_ON
3: SWITCH_OFF
4: SWITCH_CENTER
5: SWITCH_OFF

ENUM USER_SWITCH_MAPPING
0: NONE
1: SAFETY
2: PAIRING

Message:
USER_SWITCH
uint8_t switches[8]
uint8_t switch_mapping[8]
```

This way you could enable to transmit the switch state at change and be a lot more flexible.

**Comment by garfieldG** [comment]
@LorenzMeier Thanks for your review and input!
I think the second approach is a little too much and it can be done more simply.
I think that for now, the solution I proposed is very simple and easy and you shouldn't complex it when it can be done with the addition of only one bit.
I added the pr in mavlink https://github.com/mavlink/mavlink/pull/1609 and you can see the change in this or as well/

**Comment by garfieldG** [comment]
@dagar @LorenzMeier Hi,
I changed the flag to use the

**Review by LorenzMeier — APPROVED** [review]

**Pull request merged**
