### PR TITLE
Add TCBP001TA Barometer Driver

### PR DESCRIPTION
**Pull request by bys1123**
Continue works by @zhaoxiaowei1013 #14286 

TCBP001TA docs (only have chinese version for now): [tcbp001ta baro datasheet](https://drive.google.com/open?id=1UCjF8ykhcKI8LOFJvVPqr-RtCfE-uBwH)

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Would you mind rebasing? I'm happy to merge!

**Comment by ShiauweiZhao** [comment]
> Would you mind rebasing? I'm happy to merge!

I will rebase this code in furture.

**Comment by mrpollo** [comment]
@bys1123 is this barometer available in the market? I can help rebase this PR, please confirm!

**Comment by bys1123** [comment]
https://www.infineon.com/cms/en/product/sensor/pressure-sensors/pressure-sensors-for-iot/infineon-inside/
I think it's available if contact with Cindy.chu@luqintech.com
@ShiauweiZhao Looking forward to it!

**Review by dagar — DISMISSED** [review]

**Comment by mrpollo** [comment]
This is finally ready to go! 🎉

**Comment by bys1123** [comment]
@mrpollo Thanks!
@ShiauweiZhao Seems have some new update, Please add them in a new PR. Thank you!

**Comment by mrpollo** [comment]
Thanks for your contribution @ShiauweiZhao 🙏, please submit a new PR if you have further enhancements or bug fixes planned, we will gladly help you.

**Pull request merged**
