### PR TITLE
PWM Fixes - WIP

### PR DESCRIPTION
**Pull request by davids5**
None of the test worked. Now they do....some what - There is still an order of operation issue. 

Testing with the commands listed below. 

(1)  `pwm_out mode_pwm14` only starts instance 0
```
pwm_out0 set_pwm_rate 0 0 50
group:0  mask f
group:1  mask f0
group:0  mask f
group:1  mask f0
```
(2)  `pwm rate` Only sets first instance until both are armed
```
nsh> pwm rate  -d /dev/pwm_output0  -r 400 -a
pwm_out0 set_pwm_rate 0 0 400
group:0  mask f
group:1  mask f0
group:0  mask f
group:1  mask f0
pwm_out0 set_pwm_rate ffff 0 400
group:0  mask f
group:1  mask f0
group:0  mask f
group:1  mask f0
nsh> pwm rate  -d /dev/pwm_output1  -r 400 -a
pwm_out1 set_pwm_rate 0 50 400
pwm_out1 set_pwm_rate ffff 50 400
nsh> INFO  [pwm_out] instance: 0, max rate: 2000, default: 0, alt: 400
INFO  [pwm_out] instance: 1, max rate: 800, default: 50, alt: 400
```

3) now sets mode and alow rates to be set
```
nsh> pwm -d /dev/pwm_output0 arm
nsh> pwm -d /dev/pwm_output1 arm
pwm_out1 set_pwm_rate ffff 0 400
group:2  mask f00
group:3  mask 3000
group:2  mask f00
group:3  mask 3000
nsh> INFO  [pwm_out] instance: 1, max rate: 2000, default: 0, alt: 400
```

4)
```
pwm rate  -d /dev/pwm_output0  -r 400 -a
pwm_out0 set_pwm_rate ffff 0 400
group:0  mask f
group:1  mask f0
group:0  mask f
group:1  mask f0
pwm_out0 set_pwm_rate ffff 0 400
group:0  mask f
group:1  mask f0
group:0  mask f
group:1  mask f0
nsh> pwm rate  -d /dev/pwm_output1  -r 400 -a
pwm_out1 set_pwm_rate ffff 0 400
group:2  mask f00
group:3  mask 3000
group:2  mask f00
group:3  mask 3000
pwm_out1 set_pwm_rate ffff 0 400
group:2  mask f00
group:3  mask 3000
group:2  mask f00
group:3  mask 3000
nsh> INFO  [pwm_out] instance: 0, max rate: 2000, default: 0, alt: 400
INFO  [pwm_out] instance: 1, max rate: 2000, default: 0, alt: 400
```

First commit:  Found and fixed DSHOT broke io timers. (This may need so be rippled to other arches)

Found and fixed AFU IOCLT values. It coun not have been any more broken. (Channel number like 0xffffffffa Nikes!!

added _output_mask logic to keep the restored `set_pwm_rate(pwm_alt_rate_channels_new, default_rate_min, alt_rate_max);`
from missing with groups not in it's intance.

```
pwm_out start
pwm_out mode_pwm14 
 
pwm status -d /dev/pwm_output0
pwm status -d /dev/pwm_output1
  
pwm -d /dev/pwm_output0 arm
pwm -d /dev/pwm_output1 arm

pwm rate  -d /dev/pwm_output0  -r 400 -a
pwm rate  -d /dev/pwm_output1  -r 400 -a

   
pwm rate  -d /dev/pwm_output0  -r 50 -a
pwm rate  -d /dev/pwm_output1  -r 50 -a


pwm test  -d /dev/pwm_output0  -p 1000 -a

pwm test  -d /dev/pwm_output0  -p 1234 -a

pwm test  -d /dev/pwm_output1  -p 1234 -a


pwm_out -d /dev/px4fmu test
pwm_out -d /dev/px4fmu1 test



pwm rate  -d /dev/pwm_output0  -r 0 -a

```

```
diff --git a/src/drivers/pwm_out/PWMOut.cpp b/src/drivers/pwm_out/PWMOut.cpp
index 5f513553f6..1e61e29bb0 100644
--- a/src/drivers/pwm_out/PWMOut.cpp
+++ b/src/drivers/pwm_out/PWMOut.cpp
@@ -375,7 +375,7 @@ int PWMOut::set_mode(Mode mode)
  */
 int PWMOut::set_pwm_rate(uint32_t rate_map, unsigned default_rate, unsigned alt_rate)
 {
-       PX4_DEBUG("pwm_out%u set_pwm_rate %x %u %u", _instance, rate_map, default_rate, alt_rate);
+       printf("pwm_out%u set_pwm_rate %x %u %u\n", _instance, rate_map, default_rate, alt_rate);
 
        for (unsigned pass = 0; pass < 2; pass++) {
 
@@ -402,6 +402,7 @@ int PWMOut::set_pwm_rate(uint32_t rate_map, unsigned default_rate, unsigned alt_
                                continue;
                        }
 
+                       printf("group:%d  mask %x\n", group, mask);
                        // all channels in the group must be either default or alt-rate
                        uint32_t alt = rate_map & mask;
```

### CODE REVIEW

**Comment by dgeorge83616** [comment]
Yesterday, our flight test team discovered that PWM_MAIN_MAX does not always take effect at boot. They changed rotor blades and when they armed the motors blew past the max. Subsequent troubleshooting revealed that setting parameters after boot appears to be a workaround. Might be a race condition because we've been flying the PR 16444 based code for a couple of months and only noticed the problem yesterday.

Our version is 1.12.0-beta2 plus https://github.com/PX4/PX4-Autopilot/pull/16444 at b626da8321fe7a2d43ba67df77dcfb40e7b99f58 and our own heli mixer that supports dual swash side-by-side config.
See also: https://github.com/PX4/PX4-Autopilot/pull/16444#issuecomment-791741648

**Comment by davids5** [comment]
@dagar - after we got off the call yesterday, I made some changes, that gets the multi instance implementation back to working. 

From boot

image

Zoomed in
image

Please see if it works as expected now. 
fyi @LorenzMeier 

@CUAVcaijie - Please test when back in office.

**Comment by davids5** [comment]
> Yesterday, our flight test team discovered that PWM_MAIN_MAX does not always take effect at boot. They changed rotor blades and when they armed the motors blew past the max. Subsequent troubleshooting revealed that setting parameters after boot appears to be a workaround. Might be a race condition because we've been flying the PR 16444 based code for a couple of months and only noticed the problem yesterday.
> 
> Our version is 1.12.0-beta2 plus #16444 at [b626da8](https://github.com/PX4/PX4-Autopilot/commit/b626da8321fe7a2d43ba67df77dcfb40e7b99f58) and our own heli mixer that supports dual swash side-by-side config.
> See also: [#16444 (comment)](https://github.com/PX4/PX4-Autopilot/pull/16444#issuecomment-791741648)

@dgeorge83616 - Please open an New issue for what you are reporting.

**Review by LorenzMeier — APPROVED** [review]
Reviewed line-by-line and the logic changes are exactly along the lines of what I would have expected.

**Pull request merged**
