### PR TITLE
parameters move param save to PX4 work queue and fully remove NuttX LPWORK

### PR DESCRIPTION
**Pull request by dagar**
Saves a little ram and gets us fully removed from NuttX LPWORK (https://github.com/PX4/Firmware/issues/12068). The design of the PX4 work queue is kind of in our way here, requiring an object that extends WorkItem to Run anything. We should think about getting a simple dispatch queue with a std::function equivalent in place.

### CODE REVIEW

**Comment by dagar** [comment]
For NuttX HPWORK the only remaining usage in PX4 is the `camera_capture` driver and the shutdown hooks in platforms.

**Comment by PetervdPerk-NXP** [comment]
In NuttX the network drivers also use the NuttX workqueue so I'm not sure it would be possible to completely remove the need of the NuttX workqueue. Or would it be possible in the future to utilize the PX4 work queue as well for the NuttX network drivers?

**Comment by dagar** [comment]
> In NuttX the network drivers also use the NuttX workqueue so I'm not sure it would be possible to completely remove the need of the NuttX workqueue. Or would it be possible in the future to utilize the PX4 work queue as well for the NuttX network drivers?

Thanks Peter, I actually caught that in CI after submitting the PR and then restored it for those NXP configs. What I really mean by "remove NuttX LPWORK" is that nothing within PX4 is dependent on NuttX specifics. The vast majority of modules and drivers (src/drivers) are cross platform.

**Comment by LorenzMeier** [comment]
I'm closing but not deleting the branch since this still a draft.

**Pull request closed without merging**
