### PR TITLE
[WIP] ADS1115 Driver

### PR DESCRIPTION
**Pull request by iyer-suchet**
**Describe problem solved by this pull request**
Whilst designing and implementing a power monitor module for the Pixhawk, I decided to use an ADS1115 4-channel 16-bit ADC connected via I2C. This pull request aims to add a driver for the ADS1115. 

**Describe your solution**
I found an issue ([#11755](https://github.com/PX4/Firmware/pull/11755/files)) which aimed to implement the INA226 I2C driver. I approached building the driver using the INA226.cpp as a base reference, but have since moved away from it. 
I am still very early on in the driver creation, but fixing the read/write operations should speed things up:
- There seems to be more data being read from the Configuration Register than expected. We are expecting 2 bytes of data (0xA243) but receiving 4 bytes of data, where the last byte is not acknowleged. 
reading from config reg, having sent 42A3

**Additional context**
Datasheet - 
[ADS1115.pdf](https://github.com/PX4/Firmware/files/3878599/ADS1115.pdf)

### CODE REVIEW

**Comment by LorenzMeier** [comment]
We unfortunately can’t really help in driver development when it comes to the device side. That would totally overload the team. Please ping us here when the PR is ready for review.

**Comment by iyer-suchet** [comment]
Of course, thank you for acknowledging. I was hoping other people attempting to arrive at a similar solution might be able to help out.

**Comment by SalimTerryLi** [comment]
I have already implemented such a driver for ads1115, but haven't create a pr due to the incomplete design of adc system.  How about that we firstly work out the poorly designed adc part?

**Comment by dagar** [comment]
> I have already implemented such a driver for ads1115, but haven't create a pr due to the incomplete design of adc system. How about that we firstly work out the poorly designed adc part?

@SalimTerryLi are you able to join the weekly dev call to discuss?

**Comment by SalimTerryLi** [comment]
> 
> 
> > I have already implemented such a driver for ads1115, but haven't create a pr due to the incomplete design of adc system. How about that we firstly work out the poorly designed adc part?
> 
> @SalimTerryLi are you able to join the weekly dev call to discuss?

I' m able to join next week but with poor English speaking ability. Maybe there is some challenges for me :)

**Comment by bys1123** [comment]
@SalimTerryLi I'm asking Jinger to help you.

**Comment by mrpollo** [comment]
@SalimTerryLi please join the hardware channel on Slack and ping us (@dagar @mrpollo)

**Comment by dagar** [comment]
We have an adis1115 driver in master. https://github.com/PX4/PX4-Autopilot/blob/cef3d36af2b11bf62f8a3e44965ffcf3bdd0ebdf/src/drivers/adc/ads1115/ADS1115.h#L99-L105

**Pull request closed without merging**
