### PR TITLE
mavlink: send LINK_NODE_STATUS

### PR DESCRIPTION
**Pull request by dagar**
This adds support to Mavlink for sending `LINK_NODE_STATUS`.

Screenshot from 2020-10-09 14-28-09

In the mavlink receiver I've implemented message sequence id tracking to estimate lost messages. This largely matches the logic implemented in QGC, but with only a subset of total possible system and component ids implemented (we can't afford 256 x 256 bytes).

Once QGC and other systems start broadcasting `LINK_NODE_STATUS` we can factor it into the mavlink transmit throttling (rate multiplier). This serves as congestion control at the mavlink level which is important for serial links that don't have flow control, but it's also quite useful for UDP links that degrade very poorly.

FYI @dogmaphobic @DonLakeFlyer

### CODE REVIEW

**Comment by dagar** [comment]
To really get any value for congestion control I think we'll a little more detail about the estimated drop rate between 2 particular components (eg vehicle -> GCS).

**Comment by dagar** [comment]
Shall we give this a try? We may need to ultimately do more than LINK_NODE_STATUS, but I think this will be helpful in the meantime to begin to better understand what's happening in real usage.

**Comment by dagar** [comment]
I'll split out the RX drop rate estimation and we can talk about LINK_NODE_STATUS separately.

**Comment by LorenzMeier** [comment]
Why not get this in as is? This looks good and useful. Let's address flash separately and get this in.

**Comment by dagar** [comment]
> Why not get this in as is? This looks good and useful. Let's address flash separately and get this in.

Works for me. https://github.com/PX4/PX4-Autopilot/pull/16503 was split out of this.

**Comment by dagar** [comment]
Rebased on top of https://github.com/PX4/PX4-Autopilot/pull/16503.

**Comment by LorenzMeier** [comment]
I've rebased this, should be good to go now.

**Review by LorenzMeier — APPROVED** [review]

**Pull request merged**
