### PR TITLE
Flash savings, v5 and v6x

### PR DESCRIPTION
**Pull request by dakejahl**
**Removed from v5**
CONFIG_EXAMPLES_FAKE_GPS=y
Flash Saved: **328 bytes**

CONFIG_SYSTEMCMDS_SD_BENCH=y
Flash Saved: **2560 bytes**

These are development/debugging tools, probably shouldn't be in the default config? 

**Removed from COMMON_DISTANCE_SENSOR**
select DRIVERS_DISTANCE_SENSOR_MB12XX
Flash Saved: **3400** bytes

Does anyone use this sensor? I see no mention of it in Discord and no one on the forum has asked about it since 2021.
```
boards/nxp/ucans32k146/init/rc.board_sensors
boards/ark/cannode/init/rc.board_sensors
```

### CODE REVIEW

**Review by TSC21 — APPROVED** [review]

**Comment by dagar** [comment]
I would keep `bsondump`, it's important in init both for the elusive parameter import failure, and for transitioning old factory cal data that wasn't valid bson (size record set to 0). 

https://github.com/PX4/PX4-Autopilot/blob/f646f1ba984f04e2925650f49b4e854b80ecd337/ROMFS/px4fmu_common/init.d/rcS#L126-L173

**Comment by dakejahl** [comment]
If we could reduce the amount of drivers supported in the various COMMON_* sets it would help a lot. Any EOL sensors in common for diff pressure or mag? What about all these lights drivers? We support a lot of distance sensors, any idea how we can get a sense of who regularly uses certain hardware?

**Review by TSC21 — APPROVED** [review]
I would start smaller and disable other as necessary.

**Comment by Jaeyoung-Lim** [comment]
Rather than trying to optimize the default target, shouldn't we try to divide the build targets such that it is more relevant for different use cases?

**Comment by dagar** [comment]
> Rather than trying to optimize the default target, shouldn't we try to divide the build targets such that it is more relevant for different use cases?

Yes, this is the only sustainable solution at this point.

**Pull request merged**
