### PR TITLE
add Holybro KakuteH7 support

### PR DESCRIPTION
**Pull request by bkueng**
known issues:
- flash-based params does not work on H7 (due to ECC), so params are on SD card. The last flash sector is still reserved however.
- output channel 6 does not support DShot (the implementation does not handle channel gaps)
- flashing of the 2. flash bank is much slower (around 3x), than the 1. bank for some unknown reason.
- after the BL jumps to the app, there's several seconds passing until stm32_boardinitialize() is called.

### CODE REVIEW

**Comment by dagar** [comment]
> flash-based params does not work on H7 (due to ECC), so params are on SD card. The last flash sector is still reserved however.

FYI I've been considering moving flash based parameters to littlefs as well (https://github.com/PX4/PX4-Autopilot/pull/18958).
The backing RAM for the erase sector is kind of expensive, but seems to scale well enough for each architecture (eg 128K H7, 32K F7, etc). If anything the hard part will be handling the transition.

**Review by dagar — APPROVED** [review]

**Comment by bkueng** [comment]
Does it work with a single page as well?

**Comment by dagar** [comment]
> Does it work with a single page as well?

I still have to work through how to use the H7 flash (ECC, etc), but at the moment I don't see why it won't work with a single flash sector. There's a bit of a hole to be aware of when the entire flash sector needs to be erased (consider with wearleveling), but I think we can either live with it or use another flash sector as a backup (where necessary).

**Comment by mrpollo** [comment]
@bkueng which bootloader target did you use for the KakuteH7?

**Comment by bkueng** [comment]
`make holybro_kakuteh7_bootloader`

**Comment by vincentpoont2** [comment]
@bkueng Sorry, how can I build the bootloader HEX file like [this one ](https://docs.px4.io/v1.12/en/flight_controller/kakutef7.html#px4-bootloader-update), with make holybro_kakuteh7_bootloader, I only get the .bin & .px bootloader files.

**Comment by bkueng** [comment]
You can use ` arm-none-eabi-objcopy -Oihex file.elf file.hex` to convert the file. We can add that to the build if you like.

**Comment by vincentpoont2** [comment]
> You can use ` arm-none-eabi-objcopy -Oihex file.elf file.hex` to convert the file. We can add that to the build if you like.

@hanyang2013212 Any chance you can share the bootloader HEX file directly so I can included in a kakute H7 PX4 doc?

**Pull request merged**
