### PR TITLE
PX4 IO: Retry upgrades of IO

### PR DESCRIPTION
**Pull request by LorenzMeier**
This adds robustness to system timing and bad link. I've tested this on a normal setup. Needs testing on more problematic setup.

### CODE REVIEW

**Review by dagar — DISMISSED** [review]

**Comment by dagar** [comment]
Let's see what happens on the test rack.

**Comment by dagar** [comment]
Screenshot from 2021-02-18 13-03-35



Screenshot from 2021-02-18 13-02-51

**Comment by dagar** [comment]
To be clear, it's probably not any worse

**Comment by LorenzMeier** [comment]
It looks like the updater might be leaking FDs, let me see..

**Pull request merged**
