### PR TITLE
delete drv_baro.h, drv_mag.h, drv_range_finder.h and purge UAVCAN CDev usage

### PR DESCRIPTION
**Pull request by dagar**
UAVCAN changes need a closer look. This started as a simple change to get CDev out of PX4Barometer/PX4Magnetometer/PX4RangeFinder, but pulling the thread eventually gutted UAVCAN CDev usage as well.

### CODE REVIEW

**Comment by JacobCrabill** [comment]
I think this all looks good.  The only potential issue I would see with the UAVCAN changes is that `ioctl()`'s were previously used for calibration (see differential_pressure), but I think this still works - just requires a reboot to reload the offset (calibration) parameter.  No other side effects come to mind.

**Comment by JacobCrabill** [comment]
I'd like to get this combined with https://github.com/PX4/PX4-Autopilot/pull/16409

Would you like me to try combining the two in one of these PRs?

**Comment by dagar** [comment]
> The only potential issue I would see with the UAVCAN changes is that ioctl()'s were previously used for calibration (see differential_pressure), but I think this still works

It's still using the parameter directly, and as soon as we free up some flash I'm going to handle it entirely downstream in `sensors` like everything else.

**Comment by dagar** [comment]
I did this on a whim a few months ago in an attempt to complete the CDev purge, but never tested it. I'll give it a review and test, but any other quick sanity testing would be appreciated. Basically any existing UAVCAN usage still producing the corresponding uORB data within PX4 should be sufficient.

**Comment by JacobCrabill** [comment]
Just did one quick check; with a Pixhawk 4 + 2 Here3 GPS units, I correctly get 2 magnetometers bridges created, but only get one GNSS.
image
I did check with a Babel - the 2nd GPS is indeed publishing valid gnss.Fix2 messages.

**Comment by JacobCrabill** [comment]
Resolved the dual-GPS issue - I don't know why (I specifically had a PR last year enabling multiple GNSS publications), but a restriction allowing only a single GNSS channel to be published was in the UavcanGnssBridge class.  I simply removed that.  All seems to be working now.

**Comment by dagar** [comment]
Thanks @JacobCrabill

**Pull request merged**
