### PR TITLE
nxp_mr-canhubk3:fmu use Serial DMA

### PR DESCRIPTION
**Pull request by davids5**
This is for testing and will be repointed after backports are done.

### CODE REVIEW

**Comment by dk7xe** [comment]
Hi David, did the first test drives with the R6 Rover
https://review.px4.io/plot_app?log=11e76ab2-68eb-4674-a093-8d02809c58f2
and
https://review.px4.io/plot_app?log=562986c5-6493-4aef-b69d-64a973b79239

**Comment by dk7xe** [comment]
Hi @davids5 
some more logs driving outdoors. Unfortunately GPS error has been too high being between the buildings. Therefore no possibility to test any mission.
3) https://logs.px4.io/plot_app?log=eb3977cd-684d-4120-a9c3-b5f94a926fb9
4) https://logs.px4.io/plot_app?log=8a5f1e0b-3254-4b38-ac5a-6c58aa6e052c
5) https://logs.px4.io/plot_app?log=dba90ce5-75f0-4d49-94c0-0864ba8f9c10
6) https://logs.px4.io/plot_app?log=5c65410a-366c-4ade-b777-e17a151dcdd1

HW Setup:
R6 rover with MR-CANHUBK3 acting as FMU
MR-T1ETH8 T1 ethernet switch
NavQ (i.MX8M-mini) connected via ethernet to CANHUBK3
2nd Pixhawk4 GPS connected via UCANS32K146 to CAN0 of CANHUBK3
BMS772 connected to CAN0 of CANHUBK3 (but not yet enabled in SW)

**Comment by dk7xe** [comment]
@davids5 may you be able to merge https://github.com/PX4/PX4-Autopilot/pull/20805 into pr-k3-serial-dma please?! that would help me continuing testing the K3. Thank you!

**Comment by davids5** [comment]
@dk7xe - This is merged so @PetervdPerk-NXP can rebase his PR

**Pull request merged**
