### PR TITLE
AVL Automation

### PR DESCRIPTION
**Pull request by frede791**
This is a tool that can be used to generate advanced lift drag plugin parameters automatically using AVL. Rather than having to create .avl files yourself, pass them to AVL, read out the correct parameters and place them in the Advanced Lift Drag plugin, this tool will do all that for you and generate a complete advanced_lift_drag plugin sdf containing all necessary parameters for any vehicle. All that is required is to specify what the physical geometries of the vehicle are. The scripts are adaptable enough to support a self-selected number of control surfaces. 

I am looking to improve the README.md, clean up the code more, and provide a sketch of the required physical measurements in order to help the user understand what is actually required.

### CODE REVIEW

**Comment by frede791** [comment]
@Jaeyoung-Lim Please check the parameter assignment if you can using AVL.

**Comment by dagar** [comment]
Given this is all self contained within `Tools/simulation/gz/tools/avl_automation` it's safe to merge and continue working incrementally in main.

**Review by dagar — APPROVED** [review]

**Comment by frede791** [comment]
@dagar bigger issue is that the advanced lift drag plugin still hasn't been merged by the reviewers over at gz-sim and until that's not done, this tool does not really have any use.

**Comment by dagar** [comment]
> @dagar bigger issue is that the advanced lift drag plugin still hasn't been merged by the reviewers over at gz-sim and until that's not done, this tool does not really have any use.

That's fine, we'll get there.

**Pull request merged**
