### PR TITLE
mavsdk_tests: add VTOL mission tests

### PR DESCRIPTION
**Pull request by julianoes**
This adds VTOL mission tests based on a QGC .plan mission imported using the MAVSDK MissionRaw plugin.

### CODE REVIEW

**Comment by dagar** [comment]
One failure. https://github.com/PX4/PX4-Autopilot/pull/17332/checks?check_run_id=2270846461

Screenshot from 2021-04-05 12-48-18

**Comment by dagar** [comment]
Timeout, I'll try restarting. https://github.com/PX4/PX4-Autopilot/pull/17332/checks?check_run_id=2275586757

Screenshot from 2021-04-06 10-22-32

**Comment by julianoes** [comment]
@dagar noo, it looks like you cancelled it 15mins before it was done and would have spit out the output! That's why I left it running...

**Review by dagar — APPROVED** [review]

**Comment by julianoes** [comment]
> @dagar noo, it looks like you cancelled it 15mins before it was done and would have spit out the output! That's why I left it running...

Nevermind, you're right, it was just the timeout.

**Pull request merged**
