### PR TITLE
[WIP]: uavcannode (v1) testing branch

### PR DESCRIPTION
**Pull request by dagar**
For testing UAVCAN v1 (libcanard) with NuttX SocketCAN on the NXP rddrone-uavcan146 board.

 - https://github.com/PX4/NuttX/pull/96
 - https://github.com/PX4/NuttX-apps/pull/5

With Peter's libcanardv1 example. https://github.com/PetervdPerk-NXP/nuttx-apps-testing/tree/libcanardv1/examples/canardv1

@PetervdPerk-NXP @davids5

### CODE REVIEW

**Comment by dagar** [comment]
Updated NuttX, NuttX-apps, and rebased on current master.

**Comment by dagar** [comment]
Compile failure in px4_fmu-v5_default (has networking support).

``` Console
[321/1334] Generating nuttx/net/libnet.a
FAILED: cd /home/dagar/git/Firmware/build/px4_fmu-v5x_default/NuttX/nuttx && find net -type f -name *.o -delete && make -C net --quiet --no-print-directory all TOPDIR=/home/dagar/git/Firmware/build/px4_fmu-v5x_default/NuttX/nuttx KERNEL=y EXTRADEFINES=-D__KERNEL__
inet/inet_sockif.c:94:19: error: static declaration of 'inet_recvfrom' follows non-static declaration
 static ssize_t    inet_recvfrom(FAR struct socket *psock, FAR void *buf,
                   ^~~~~~~~~~~~~
In file included from inet/inet_sockif.c:57:0:
./inet/inet.h:286:9: note: previous declaration of 'inet_recvfrom' was here
 ssize_t inet_recvfrom(FAR struct socket *psock, FAR void *buf, size_t len,
         ^~~~~~~~~~~~~
inet/inet_sockif.c: In function 'inet_send':
inet/inet_sockif.c:1091:17: error: too many arguments to function 'psock_tcp_send'
           ret = psock_tcp_send(psock, buf, len, flags);
                 ^~~~~~~~~~~~~~
In file included from inet/inet_sockif.c:51:0:
./tcp/tcp.h:1300:9: note: declared here
 ssize_t psock_tcp_send(FAR struct socket *psock, FAR const void *buf,
         ^~~~~~~~~~~~~~
Makefile:103: recipe for target 'inet_sockif.o' failed
make[1]: *** [inet_sockif.o] Error 1
[321/1334] Generating nuttx/arch/arm/src/libarch.a
FAILED: cd /home/dagar/git/Firmware/build/px4_fmu-v5x_default/NuttX/nuttx && find arch/arm/src -type f -name *.o -delete && make -C arch/arm/src --quiet --no-print-directory all TOPDIR=/home/dagar/git/Firmware/build/px4_fmu-v5x_default/NuttX/nuttx KERNEL=y EXTRADEFINES=-D__KERNEL__
chip/stm32_ethernet.c: In function 'stm32_poll_work':
chip/stm32_ethernet.c:2383:34: error: passing argument 2 of 'devif_timer' makes integer from pointer without a cast [-Werror=int-conversion]
           (void)devif_timer(dev, stm32_txpoll);
                                  ^~~~~~~~~~~~
In file included from chip/stm32_ethernet.c:59:0:
/home/dagar/git/Firmware/build/px4_fmu-v5x_default/NuttX/nuttx/include/nuttx/net/netdev.h:544:5: note: expected 'int' but argument is of type 'int (*)(struct net_driver_s *)'
 int devif_timer(FAR struct net_driver_s *dev, int delay,
     ^~~~~~~~~~~
chip/stm32_ethernet.c:2383:17: error: too few arguments to function 'devif_timer'
           (void)devif_timer(dev, stm32_txpoll);
                 ^~~~~~~~~~~
In file included from chip/stm32_ethernet.c:59:0:
/home/dagar/git/Firmware/build/px4_fmu-v5x_default/NuttX/nuttx/include/nuttx/net/netdev.h:544:5: note: declared here
 int devif_timer(FAR struct net_driver_s *dev, int delay,
     ^~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:172: recipe for target 'stm32_ethernet.o' failed
make[1]: *** [stm32_ethernet.o] Error 1
```

**Comment by dagar** [comment]
Updated with merged NuttX changes and rebased on current master.

**Comment by dagar** [comment]
I've created a new `nxp_fmuk66-v3_socketcan` target for testing.

**Comment by PetervdPerk-NXP** [comment]
Latest commit should work correctly and is publishing a string to a UAVCAN v1 topic. To test it u can use the scripts in here https://github.com/PetervdPerk-NXP/cannode-v1-tools

**Comment by PetervdPerk-NXP** [comment]
We can now subscribe to the vehicle_gps_position uORB topic and publish a [VehicleGPSPosition.1.0.uavcan](https://github.com/PetervdPerk-NXP/cannode-v1-tools/blob/master/px4/VehicleGPSPosition.1.0.uavcan) UAVCAN v1 message.

To test this use the [print_vehicle_gps_position_topic.py](https://github.com/PetervdPerk-NXP/cannode-v1-tools/blob/master/print_vehicle_gps_position_topic.py) script to parse the output.

Re-publishing to the vehicle_gps_position uORB topic on another board is not working, because for some reason the libcanard library parser invalidates the frames I'm sending. Which has to be debugged further.

**Comment by LorenzMeier** [comment]
I'm closing this as there is a more recent PR with the same scope.

**Pull request closed without merging**
