### PR TITLE
Add Femtomes GPS Driver

### PR DESCRIPTION
**Pull request by bys1123**
Femtomes GPS Driver already merged into GpsDrivers submodule https://github.com/PX4/GpsDrivers/pull/49

This PR makes it available to use.

But for now, looks should wait until #14447 merged to avoid conflict.

@bkueng Thanks for review.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@bys1123 Don't know if you noticed, but this stalled.

**Comment by bys1123** [comment]
@hamishwillee Thanks, still waiting #14447

**Comment by bys1123** [comment]
@bkueng @dagar Do you have time check this, thanks!

**Comment by bkueng** [comment]
This looks good, can you rebase and resolve the conflicts?

**Pull request closed without merging**
