### PR TITLE
Improve offboard failsafe

### LINKED ISSUE #16534: Offboard only RC lost failsafe
**Describe problem solved by the proposed feature**
For my use case, I need a way to failsafe only on RC lost when using offboard. This is because we sometimes have issues with our RC transmitter when flying offboard and we need to be able to take over at any time otherwise the RC lost failsafe must execute.

**Describe your preferred solution**
I've got 3 proposals to address my solution in order that I desire.

1. Add a rc_lost condition to the code here: https://github.com/PX4/PX4-Autopilot/blob/04f9ada500eacf469b51b81d4575f2b7248a3021/src/modules/commander/state_machine_helper.cpp#L684

		if (status_flags.offboard_control_signal_lost) {
			if (status->rc_signal_lost) {
				// Offboard and RC are lost
				enable_failsafe(status, old_failsafe, mavlink_log_pub, reason_no_rc_and_no_offboard);
				set_offboard_loss_nav_state(status, armed, status_flags, offb_loss_act);

			} else {
				// Offboard is lost, RC is ok
				enable_failsafe(status, old_failsafe, mavlink_log_pub, reason_no_offboard);
				set_offboard_loss_rc_nav_state(status, armed, status_flags, offb_loss_rc_act);
			}

		} else if (rc_lost) {
			/* RC is lost, when required for safety */
			enable_failsafe(status, old_failsafe, mavlink_log_pub, reason_no_rc);
			set_link_loss_nav_state(status, armed, status_flags, internal_state, rc_loss_act);

		} else {
			status->nav_state = vehicle_status_s::NAVIGATION_STATE_OFFBOARD;
		}
`
2. Add another parameter to failsafe in offboard when only RC is lost.
3. Use the offboard controller to sense RC is lost then change the mode to failsafe. 

This first solution changes the existing standard that when RC is lost it should not affect any automatic modes. To keep this functionality, the rc failsafe can be set to disabled so that way it will not affect offboard, however this would remove the following use case: when the user wants rc failsafe enabled in manual modes but not in offboard for the same flight.

### PR DESCRIPTION
**Pull request by benjinne**
**Describe problem solved by this pull request**
Closes #16534 using 2nd proposal of adding a new parameter to allow for failsafe on RC only.

**Describe your solution**
Change the following:
   * When Both offboard and RC are lost, use OBL_ACT instead of OBL_RC_ACT
   * When only offboard is lost and RCL_EXCEPT is enabled use OBL_ACT instead of OBL_RC_ACT
   * When only RC is lost and RCL_EXCEPT is disabled, use NAV_RCL_ACT
Untitled

**Describe possible alternatives**
The outcomes in the table were picked by my intuition, but can change if needed.

**Test data / coverage**
All scenarios in table tested and verified using jmavsim and offboard_control example in px4_ros_com.

### CODE REVIEW

**Comment by dagar** [comment]
The table is quite helpful, I'll review this.

Any input here @Jaeyoung-Lim @bperseghetti?

**Review by julianoes — COMMENTED** [review]
I commented on small nitpicks for the MAVSDK tests part.

Other than that, I think your table make complete sense, and the implementation looks correct.
This is really well done and communicated, thanks a lot for the issue and PR!

**Review by julianoes — APPROVED** [review]

**Comment by julianoes** [comment]
The one CI error doesn't look related.
Thanks for the fixes @benjinne, that was quick.

**Comment by MaEtUgR** [comment]
My mistake that the result wasn't the most appropriate in all cases:
https://github.com/PX4/PX4-Autopilot/pull/17785/files#diff-16343101332933c8491a2460368615ae5861531c321280d0468f7be6733b8661R752

@benjinne I fully agree with your intuitive resolution of failsafe cases. Thanks so much for the contribution of the correction, the tests and the very clear description. 👍 🙏

**Comment by DiegoHerrera1890** [comment]
thank you so much! it works!!

**Comment by MaEtUgR** [comment]
@DiegoHerrera1890 Just for reference you can also change them using the QGC GUI like this: https://docs.qgroundcontrol.com/master/en/SetupView/Parameters.html on a real vehicle as well as the simulation (take care to connect to the right instance).

**Comment by benjinne** [comment]
@julianoes Hey, I'm trying to write MAVSDK tests for these cases, however there's no way to stop sending offboard setpoints abruptly. From what I see, only `_offboard->stop()` is available which changes the flight mode to hold and stops setpoints. Is there another way, or does the offboard MAVSDK plugin need another function?

**Comment by julianoes** [comment]
@benjinne I guess we need to add some functionality to MAVSDK which allows you to have more fine grained control over when the setpoint should be sent. 

I've created https://github.com/mavlink/MAVSDK/issues/1630 to collect requirements around this, please add a note about the behavior that you would like to see there.

**Pull request merged**
