### PR TITLE
platforms: px4 log build string then print (fputs)

### PR DESCRIPTION
**Pull request by dagar**
Minor change to prevent interlaced output.

### CODE REVIEW

**Review by LorenzMeier — APPROVED** [review]
Makes sense and was indeed a nuisance.

**Comment by LorenzMeier** [comment]
The CI failures seem to be real. While I could not find the root cause quickly from the pure code review, it looks like this output change might be creating real issues in the CI tests. Potentially due to now too small thread stacks. Have you tested this on HW?

**Review by LorenzMeier — CHANGES_REQUESTED** [review]
Holding the review until we understand the CI failures properly.

**Comment by mrpollo** [comment]
@LorenzMeier looks like CI is fixed, anything else needed before merging?

**Review by LorenzMeier — APPROVED** [review]

**Pull request merged**
