### PR TITLE
[WIP] uORB split topics and msg and full ROS2 compatibility

### PR DESCRIPTION
**Pull request by dagar**
**WORK IN PROGRESS**

This evolves the PX4 pub/sub system to solve a number of small short comings and do so in a way that brings us much closer to full ROS2 compatibility.

#### Problems
 - every .msg file created a corresponding topic (aka ORB_ID)
     - additional topics per .msg were added to the msg file (#TOPIC)
     - creating nested types (with no ORB_ID)
     - every board has to carry the full static set of ORB_ID topics

#### Changes
 - topics are now explicitly created per module (topic pruning per build) https://github.com/PX4/PX4-Autopilot/blob/76659ff5a68c6c01c899f908424ea04589c249d3/src/modules/navigator/CMakeLists.txt#L58-L66
 - .msg files are PascalCase (ROS2 style)
 - compatible structs are still generated (eg struct msg_s), but ROS2 style px4::msg::Msg is also available
 - very early initial ROS2 platform support (build px4 within ROS2 colcon)

#### TODO
 - [ ] fields string for nested types
 - [ ] fix fastrtps (untangle topics from messages)

### CODE REVIEW

**Comment by dagar** [comment]
Does anyone have any comment on the mechanism for establishing the static topics per PX4 build (explicitly listing publications per module)? Per module you list out the Publications (msg & topic), then the possible set of topics in that particular PX4 build is a union of all those topics across included modules. The topic name for ROS2 maps directly to the ORB_ID (eg `/vehicle_status` -> `ORB_ID(vehicle_status)`.

The location, mechanism, style, etc for doing all of this is flexible at this stage.

https://github.com/PX4/PX4-Autopilot/blob/8c88625d35c766b5099b7cec39ed9234cc01a341/src/modules/navigator/CMakeLists.txt#L58-L66

**Comment by bkueng** [comment]
My preferred way is to use the `module.yaml` file, I find string handling in cmake somewhat terrible.

**Comment by dagar** [comment]
> My preferred way is to use the `module.yaml` file, I find string handling in cmake somewhat terrible.

Sounds good to me.

**Comment by spiderkeys** [comment]
I may have missed this, but how are uORB topic instances expected to map to ROS2 topics? 

In DDS, it is possible to have key fields which are used to create separate instances (often a string or integer like `string vehicle_id`), but ROS2 does not truly support this concept in their use of DDS within the RMW. Instead, since no key fields are usually specified in ROS2 messages, each topic has a single default instance. This affects topics that have reliable QOS semantics, such as "status" topics that are published with keep-last-reliable semantics (i.e. late joiners or subscribers who missed a message can reliably be delivered the current data for that topic).

If PX4 expects to publish any multi-instance topics that have keep-last-reliable semantics only publishes updates upon changes for each instance, then there needs to be a mechanism that ensures that uORB instances get mapped to different topics. I.E. `/actuator_outputs/0`, `/actuator_outputs/1`, etc.

Unfortunately, this approach of mapping to multiple topics is counter to standard DDS best practices, which allow you to create a single datawriter/datareader for a multi-instance topic (similar to uORB). With multiple topics, users have to create datareaders/writers for each new topic, which they have to use discovery callbacks to discovery - makes code harder to scale dynamically as things like sensors, actuators, vehicles, etc expand within a system. Ideally, for systems that support instanced DDS topics, an integer key field could be inserted that maps to the uORB instance. This wouldn't necessarily negatively impact ROS2 users, since it will be mostly opaque to them, but it would provide useful semantics/APIs for DDS users.

If all topics being published by PX4 are expected to be best-effort and published periodically then most of this doesn't matter - late joiners and subscribers that miss messages will simply sync up after the next sample. There still probably needs to be some mechanism that maps uORB instances though, so subscribers/publishers can differentiate the samples.

**Comment by spiderkeys** [comment]
Follow-up question in the same vein:

I notice that this PR is removing the microRTPS agent target and replacing it with a ROS2 target. One of the advantages of the microRTPS agent right now is that it has a fairly straightforward path to modify the agent code to enable the use of standalone DDS without ROS2 requirements/dependencies, and also the ability to use some of the DDS specific features I mentioned above. 

Is the intention to completely deprecate the existing bridge approach and only support ROS2, or could it be possible to either leave it intact or make things a bit more generic and support generic pub/sub endpoints, whether they be provided by ROS2 libraries or standalone DDS libraries?

**Pull request closed without merging**
