### PR TITLE
Disable camera trigger in Return mode

### PR DESCRIPTION
**Pull request by moreba1**
https://github.com/PX4/Firmware/issues/13282

### CODE REVIEW

**Comment by Antiheavy** [comment]
I wonder if the reason the original function was not working in some RTL modes is that RTL_TYPE 1 and 2 remain in Mission Mode internally?
https://github.com/PX4/Firmware/blob/3e90cbe6868d0dfb0d1c4c72faf7dd15988cfa6c/src/modules/navigator/mission.cpp#L137-L146

Will this "unpause" function still work with this new PR?
https://github.com/PX4/Firmware/blob/3e90cbe6868d0dfb0d1c4c72faf7dd15988cfa6c/src/modules/navigator/mission.cpp#L165-L171

**Comment by moreba1** [comment]
> 
> 
> I would say that makes sense.
> 
> Have you tested it @moreba1?

No , i have not tested it .

**Comment by julianoes** [comment]
@Antiheavy you might be correct, yes.

Would be good if you could verify that this actually works correctly for you @moreba1.

**Comment by julianoes** [comment]
@moreba1 this is pending testing.

**Comment by moreba1** [comment]
@julianoes I can not test it.

**Comment by LorenzMeier** [comment]
@julianoes Could you do a quick SITL test? It looks good to me and it's easy enough to test after I fixed all the triggering logic in SITL.

**Comment by julianoes** [comment]
No, I can't test it right now but I'm ok if it is merged.

**Comment by moreba1** [comment]
> 
> 
> No, I can't test it right now but I'm ok if it is merged.

can you merge this commit ?

**Comment by julianoes** [comment]
Sorry, I wrote I would merge this but then I forgot about it.

I think the feature itself is now covered in `Mission::inactivation`:

https://github.com/PX4/PX4-Autopilot/blob/9686c81f7d089a486a8d0546f5df00609035fdbf/src/modules/navigator/mission.cpp#L171-L191

I'll close this. If you disagree, let me know!

**Pull request closed without merging**
