### PR TITLE
Posix iris stereo fix

### PR DESCRIPTION
**Pull request by canberkgurel**
**Describe problem solved by this pull request**

I typically only use the iris model for my PX4-SITL testing, lately I migrated to a new Linux machine and installed a later version of the PX4-Autopilot (following [this documentation](https://docs.px4.io/master/en/simulation/ros_interface.html)). I wanted to use the iris-stereo-camera model for an application I'm working on. In the bottom of the documentation I used, there's a short code snippet showing how the Gazebo simulation can be modified to integrate sensors publishing directly to ROS topics; to support this feature, Gazebo is launched with the appropriate ROS wrappers. I realized that the launch file ([posix_sitl.launch](https://github.com/PX4/PX4-Autopilot/blob/v1.11.2/launch/posix_sitl.launch)) that's referred in this code snippet doesn't support the iris-stereo-camera.

This wasn't working:

```
cd /path/to/PX4-Autopilot
DONT_RUN=1 make px4_sitl_default gazebo
source ~/catkin_ws/devel/setup.bash    # (optional)
source Tools/setup_gazebo.bash $(pwd) $(pwd)/build/px4_sitl_default
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)/Tools/sitl_gazebo
roslaunch px4 posix_sitl.launch vehicle:=iris_stereo_camera
```

**Describe your solution**

I've originally created [a post on discuss.px4/ROS](https://discuss.px4.io/t/error-unknown-target-unable-to-simulate-the-iris-stereo-camera-model/21180) to find out what the problem is. I spent a little more time digging it. I found [the script printing the error message](https://github.com/PX4/PX4-Autopilot/blob/97ab8277ed16a548ee2c933c3c56b6360b2d145b/ROMFS/px4fmu_common/init.d-posix/rcS#L49) that I was receiving. I noticed that the `platforms/posix/cmake/sitl_target.cmake` excludes the iris-stereo-camera. I fixed the problem with the modifications I made in this PR. The branch I'm trying to merge works with the posix_sitl.launch file when used as it is stated in the [documentation](https://docs.px4.io/master/en/simulation/ros_interface.html). 

**Describe possible alternatives**

`posix_sitl.launch` is documented as the plain SITL launch script that needs to be used to run the simulation wrapped in ROS. There's no other alternative to use posix_sitl.launch and iris_stereo_camera as far as I know. However, it's possible to use the iris-stereo-camera with [px4.launch](https://github.com/PX4/PX4-Autopilot/blob/v1.11.2/launch/px4.launch). My intention here is to fix the problem in the posix_sitl.launch as it appears to be the preferred method.

**Test data / coverage**

I ran the code snippet I've provided above and confirmed that it was working by monitoring the published topics via `rostopic list`, viewed the images published via `rosrun image_view ...`, and ensured that the camera_info topic contained the camera specs modeled in the [stereo_camera.sdf](https://github.com/PX4/PX4-SITL_gazebo/blob/0da08f0333cd14c08a9545c6ba7ddfc18706398f/models/stereo_camera/stereo_camera.sdf) file. 

**Additional context**

- OS: Ubuntu 18.04.5 LTS
- Gazebo version: Gazebo 9.16.0
- ROS version: Melodic
- Firmware version: 1.11.2

### CODE REVIEW

**Review by Jaeyoung-Lim — CHANGES_REQUESTED** [review]
Thank you for the contribution,

- Can you check the conflicts and rebase this PR?
Seems like the base branch is outdated therefore the diff includes a lot more than you intent to merge

- Also, adding `iris_stereo_camera` as a make target or adding an airframe config is not the correct way to handle your use case. Rather, you need to handle the launchfile where the airframe config name and the sdf model names can be defined separately.

**Comment by canberkgurel** [comment]
@Jaeyoung-Lim 

> Seems like the base branch is outdated therefore the diff includes a lot more than you intent to merge

I've been using Firmware v1.11.2. So, I made the changes in there, I think all of the additional commits are the ones submitted between v1.11.2 and the current master branch.

> Can you check the conflicts and rebase this PR?

I'll rebase as requested. 

> Also, adding iris_stereo_camera as a make target or adding an airframe config is not the correct way to handle your use case. Rather, you need to handle the launchfile where the airframe config name and the sdf model names can be defined separately.

Having not understood why it isn't the correct way, I know what you're suggesting is an alternative solution that also solves the problem. So, I'll undo the changes I made and fix the launch file. (It might be easier to create a separate PR for this.)

**Comment by canberkgurel** [comment]
Argh! Rebasing cause me to solve some merge conflicts that deviated my PR away from its intended purpose; I'm closing this one, I'll open a new one.

**Comment by canberkgurel** [comment]
@Jaeyoung-Lim 

If I change 

    
    <arg unless="$(arg interactive)" name="px4_command_arg1" value="-d"/> 
    <arg     if="$(arg interactive)" name="px4_command_arg1" value=""/>  
    <node name="sitl" pkg="px4" type="px4" output="screen"  
         args="$(find px4)/ROMFS/px4fmu_common -s etc/init.d-posix/rcS $(arg px4_command_arg1)" required="true"/>  

in posix.launch with 

    
    <include file="$(find px4)/launch/px4.launch">
        <arg name="vehicle" value="$(arg vehicle)"/>
    </include>

this solves the problem. Is this what you have suggested as the correct way?

**Comment by LorenzMeier** [comment]
I'm sorry, but would you mind rebasing it again?

**Comment by canberkgurel** [comment]
@LorenzMeier I originally modified `platforms/posix/cmake/sitl_target.cmake` and `ROMFS/px4fmu_common/init.d-posix/10017_iris_stereo_camera`. These modifications solved the problem I mentioned about in the original post. Unfortunately, my original modifications got entangled with some other commits that weren't part of my original PR. Can someone help me remove the unintended commit out of my PR? I've just learned about rebasing from an online tutorial, I can indeed re-do it if you think that'll solve the problem!

**Comment by canberkgurel** [comment]
It looks like the main branch is very dynamic, files are changing very quickly. There've been some merge conflicts since I opened the PR. We need to act quickly if we want to merge this in. So, please give me some guidance on how to remove some of the commits out of my PR, and how to solve the new merge conflicts.

**Comment by Jaeyoung-Lim** [comment]
@canberkdurmus Adding the `iris_stereo_camera` airframe is not the right solution for your problem. 

The correct solution for your use case it to use `iris` for https://github.com/PX4/PX4-Autopilot/blob/f6eae085978d7a11483156b5d4e461c875b46729/launch/mavros_posix_sitl.launch#L14 and use the `iris_stereo_camera` sdf file in https://github.com/PX4/PX4-Autopilot/blob/f6eae085978d7a11483156b5d4e461c875b46729/launch/mavros_posix_sitl.launch#L16

Please let me know if you have issues using the model this way. I am closing this PR for since it doesn't seem applicable to solve your problem.

**Comment by canberkdurmus** [comment]
Hi, @Jaeyoung-Lim I am not the right Canberk, he is @canberkgurel. Not a problem of course 😄

**Comment by canberkgurel** [comment]
@Jaeyoung-Lim You tagged the wrong person. In the original post, I've clearly stated that `roslaunch px4 posix_sitl.launch vehicle:=iris_stereo_camera` doesn't work w/o the modification I've committed. I've already tested setting `vehicle` to `iris_stereo_camera`, if that was working I wouldn't have created this PR in the first place. When I set `vehicle=iris_stereo_camera`, the `sdf` variable is equal to `$(find mavlink_sitl_gazebo)/models/iris_stereo_camera/iris_stereo_camera.sdf`. You're suggesting me to use the `mavros_posix_sitl.launch` file instead of `posix_sitl.launch`. I checked the contents, the only difference is that in the former, mavros is launched in addition to everything else in the `posix_sitl.launch`.

**Comment by Jaeyoung-Lim** [comment]
@canberkdurmus Oh, very sorry about that. 

> In the original post, I've clearly stated that roslaunch px4 posix_sitl.launch vehicle:=iris_stereo_camera doesn't work w/o the modification I've committed.

I am quite doubtful about this statement. I am using in other projects sdf models that don't have an airframe config (exactly your usecase) and this works. In your PR, you also added a make target for the `iris_stereo_camera` which isn't related to starting models with ROS. 

What I am saying applies also for `posix_sitl.launch`

you just need to leave
```
    <arg name="vehicle" default="iris"/>
```
as it is and set the sdf path as
```
    <arg name="sdf" default="$(find mavlink_sitl_gazebo)/models/iris_stereo_camera/iris_stereo_camera.sdf"/>
```

**Comment by ADI201998** [comment]
> @canberkdurmus Oh, very sorry about that.
> 
> > In the original post, I've clearly stated that roslaunch px4 posix_sitl.launch vehicle:=iris_stereo_camera doesn't work w/o the modification I've committed.
> 
> @canberkgurel I am quite doubtful about this statement. I am using in other projects sdf models that don't have an airframe config (exactly your usecase) and this works. In your PR, you also added a make target for the `iris_stereo_camera` which isn't related to starting models with ROS.
> 
> What I am saying applies also for `posix_sitl.launch`
> 
> you just need to leave
> 
> ```
>     <arg name="vehicle" default="iris"/>
> ```
> 
> as it is and set the sdf path as
> 
> ```
>     <arg name="sdf" default="$(find mavlink_sitl_gazebo)/models/iris_stereo_camera/iris_stereo_camera.sdf"/>
> ```
> 
> or if you want to do it as you are launching by command line
> 
> ```
> roslaunch px4 posix_sitl.launch vehicle:=iris sdf:=<path_to_sdf>
> ```


So I ran the command `roslaunch px4 mavros_posix_sitl.launch vehicle:=iris sdf:=~/PX4-Autopilot/Tools/simulation/gazebo-classic/sitl_gazebo-classic/models/iris_depth_camera/iris_depth_camera.sdf`.
I was able to see a white cube in gazebo, which I'm assuming is the stereo camera.

But when I run rostopic list, I dont see any topic related to depth image.

But when i replace `iris_depth_camera` with `iris_fpv_cam`, I can see topics for rgb image.

**Pull request closed without merging**
