### PR TITLE
ci: update image tags

### PR DESCRIPTION
**Pull request by coderkalyan**
The images appear to be built and tagged/uploaded now.

### CODE REVIEW

**Comment by coderkalyan** [comment]
Well, the uavcanv1 targets are working now, but the mission test stopped working...

**Comment by TSC21** [comment]
Can you please also update the Jenkins ones?

**Comment by coderkalyan** [comment]
@TSC21 I just updated the Jenkinsfile, is that all I need to do? Also, I've kept the mavros mission tests on an older version to see if they run successfully, since I was getting CI issues.

**Comment by TSC21** [comment]
> @TSC21 I just updated the Jenkinsfile, is that all I need to do?

You are missing the ones here: https://github.com/PX4/PX4-Autopilot/tree/master/.ci

> Also, I've kept the mavros mission tests on an older version to see if they run successfully, since I was getting CI issues.

This is usually not a good idea because we might end-up in a situation where 1. we are using out-of-sync tooling in comparison to our development systems 2. we loose track of which tags we are using in all containers (because ones are using a tag, others are using another), and now you can quickly do it with a search and replace in your IDE.
The issue is apparently in `px4tools`, so the best is to fix the source of the problem.

**Comment by TSC21** [comment]
@coderkalyan solution for https://github.com/PX4/PX4-Autopilot/pull/17476/checks?check_run_id=2461600147#step:10:250: add `control==0.8.4` and wherever Python2 pip packages are being installed. The problem is that the `@` (at) operator, used for matrices multiplications, was only introduced in numpy for Python 3.5.

**Comment by coderkalyan** [comment]
@TSC21 I'll send another PR to PX4-containers to fix the regression for now (with that version freeze) but I question whether that is a good idea in the long run, why and where are we using python2 in the first place? Is it due to ROS not working well with python3?

**Comment by coderkalyan** [comment]
https://github.com/PX4/PX4-containers/pull/295

**Comment by TSC21** [comment]
@coderkalyan you should be able to update the tags to `2021-04-29` now.

**Pull request closed without merging**
