### PR TITLE
[RFC] Commander failsafe state machine rewrite

### PR DESCRIPTION
**Pull request by bkueng**
I was working on preflight check reporting with the events interface and wanted to check how it could fit into the whole structure. So I came up with this:
commander drawio

The basic idea is that the arming/health checks do the GCS reporting, prevent all or individual modes from arming, and can set flags that are then used in the failsafe state machine (the checks run and report during arming as well).
This PR is about implementing the failsafe state machine part.

### Failsafe state machine
- As one of the basic requirements, there needs to be a way to generate user documentation from the code.
  I ended up using Emscripten, which allows to compile the C++ code directly to webassembly and run it in the browser. So any possible failsafe combination can be checked directly, and the logic corresponds 1:1 to what runs on the vehicle.
  This allows to implement arbitrary logic in the C++ code.
  At the same time it is very convenient for development (testing and debugging) as well.
  The condition flags are extracted from the msg file directly, and there's a minimal parameter storage. The accessed parameters are added to the UI (using the parameter json metadata).
  The implementation of this PR can be tested under https://logs.px4.io/plot_app/static/failsafe_test/index.html.
   Use `make run_failsafe_web_server` to build & run it locally.
- The implementation is split into a generic framework (base class) and class that implements the actual checks (this could be vehicle-specific).
  - The framework maintains a set of active actions and an action becomes active when a condition is triggered. Action can have additional settings (e.g. if user takeover is allowed). The selected failsafe is then the most severe active action.
    So it's well-defined what happens when multiple failsafes trigger.
	Then there's fallbacks to the next option, should the desired failsafe not be available.
  - clear condition: by default, when the failure condition clears, the vehicle goes back into the user intended mode. An action can change this to e.g. clear only on disarming or on mode switch.
  - user takeover: the default behavior is when an action is triggered, the vehicle first goes into Hold for N seconds (configurable, and disabled for N=0), with a user notification. During that time the user cannot take over. After that the action is triggered and the user can take over by switching into any mode or moving the sticks.
  - `can_run`: this is a bitset for each mode if it can be executed (basically what `main_state_transition` currently does). This is used by the failsafe state machine for mode fallback. We probably need more granularity here later on (e.g. which modes require position).
  - The behavior generally matches closely what we have now, apart from generically handling multiple failsafes. It can generally be changed as we need it.
- state machine inputs: minimal state (armed, vehicle type, user intended mode, user takeover request, etc), `vehicle_status_flags` (conditions) and param configuration
- output: failsafe action (if any), updated user intended mode
- Not everything is done yet, for testing I implemented the core of the existing failsafe state machine, `set_nav_state`, user takeover and a few other things.
- I'm also suggesting to change the lockdown action to disarm.

Feedback is welcome, also unexpected or unintended behavior (there's generally various details that can be done one way or another).
Thanks to @KonradRudin  & @MaEtUgR  for testing & support.

Screenshot of the web sim:
image

### CODE REVIEW

**Comment by ThomasDebrunner** [comment]
@bkueng The only compile flag that was offending was `no-rtti`. I added a hack to remove that for the failsafe_test target.

**Comment by julianoes** [comment]
@bkueng wow, nice.

So I'm just thinking about the relationship between pre-arm checks and the failsafe state machine. Given failsafes are reset when disarmed this basically means that we have need to match the pre-arm checks somewhat with the state machine, right?
One thing that seems to be missing there right now are the battery checks, e.g. you can arm with low battery.

And that's one state input missing currently, the battery state, right?

I tried the web example but don't get any console output. I assume it's currently broken?

**Comment by bkueng** [comment]
> Given failsafes are reset when disarmed this basically means that we have need to match the pre-arm checks somewhat with the state machine, right?

Exactly, for that reason the arming checks also set the flags for the failsafe logic, so that you're sure arming is prevented when a condition is set, and then in flight the failsafe logic can trigger any action it wants (it can also do nothing). That means it's slightly more work to add a new condition, but you automatically get the logic right, including proper user reporting.

> One thing that seems to be missing there right now are the battery checks, e.g. you can arm with low battery.
> And that's one state input missing currently, the battery state, right?

Correct. In the new structure it would be:
- arming check for battery: does user reporting & sets flag(s)
- failsafe check using the flag(s)

A limitation here is that currently only bool flags are supported (for the web generator). Not sure if it's worth adding enum support, but it's possible, and could be done later as well.

> I tried the web example but don't get any console output. I assume it's currently broken?

Not that I'm aware of. Are there any browser console messages?

**Comment by julianoes** [comment]
> Are there any browser console messages?

There are none :thinking:.

**Comment by bkueng** [comment]
Completed in #20172

**Pull request closed without merging**
