### PR TITLE
Update uavcan bootloader to use new appdes and support non complaint nodes

### PR DESCRIPTION
**Pull request by davids5**

### CODE REVIEW

**Comment by davids5** [comment]
DNM This is getting the FW on the node but not running it yet.

**Comment by davids5** [comment]
@dagar - making progress. The AppDes and CRC's are now All good. I added the watchdog (we need to pet it in the app when booted by da'kine) The boot is not clean HW wize and DMA is hanging. 
```
I still need to work though the node_id handoff.
```

**Comment by davids5** [comment]
OK this is booting and running. I still need to work though the node_id handoff.

**Comment by davids5** [comment]
OK this is booting and running the node_id handoff has been resolved! 

@dagar please test. You can use the uavcan gui but for the  non px4 bootloader ensure you rename the bin to uavcan.bin (or shorter)

**Comment by davids5** [comment]
@dagar I will continue to rework the fw server. Do you want that work done here or shall we get this in and do a separate PR?

**Comment by davids5** [comment]
@dagar All the FS rework is done. Much simpler uavcan PR is https://github.com/PX4/libuavcan/pull/5

**Review by dagar — APPROVED** [review]

**Comment by dagar** [comment]
Minor build failures addressed and libuavcan submodule updated.

**Review by dagar — APPROVED** [review]

**Pull request merged**
