### PR TITLE
px4_fmu-v6x:Add Rev 4 Sensors

### PR DESCRIPTION
**Pull request by davids5**
Added rev 4 sensors.

image

### CODE REVIEW

**Comment by davids5** [comment]
@vincentpoont2 - Please tests. 

Also please verify that the CS1 was used with Drdy2 and not CS2 with Drdy2

**Comment by vincentpoont2** [comment]
> @vincentpoont2 - Please tests.
> 
> Also please verify that the CS1 was used with Drdy2 and not CS2 with Drdy2

Will test confirm ASAP.

**Comment by vincentpoont2** [comment]
> @vincentpoont2 - Please tests.
> 
> Also please verify that the CS1 was used with Drdy2 and not CS2 with Drdy2

Confirmed CS1 is with DRDY2.

**Comment by vincentpoont2** [comment]
@davids5 
Same v6X board and PR Artifact firmware:

With REV3 hardware - no issue.
With REV4 hardware - the IO chip cannot be recognized (see error message below)
 
image

**Comment by vincentpoont2** [comment]
@davids5 
Same v6X board and PR Artifact firmware:

With REV3 hardware - no issue.
With REV4 hardware - the IO chip cannot be recognized (see error message below)
 
image

**Comment by vincentpoont2** [comment]
@davids5 Artifact FW tested on REV4 hardware, all sensors were started & recognized. No issue.

We will do flight test later this week.

**Review by vincentpoont2 — DISMISSED** [review]

**Comment by vincentpoont2** [comment]
@davids5 With this Artifact FW, we are having issue calibrating the IMU. It would be stuck in this screen.  
42670-p

- If we use stable v6x firmware (doesn't start ICM42670-P), no issue 
- If we removed the ICM42670-P , no issue.

Debug port would show the following:
42670-p Debug

I remember @dagar mentioned the ICM 42670-p  PX4 driver needed some changes. Would that the cause of this issue? Do you need HW in hand to resolve this?

**Comment by davids5** [comment]
@vincentpoont2 Please post the IMU Layout of Rev3, and Rev4 with DOF and chips Identified.

**Comment by davids5** [comment]
@vincentpoont2 Rotation set per above. Please retest

**Comment by vincentpoont2** [comment]
> @vincentpoont2 Rotation set per above. Please retest

@davids5 Still having calibration issue with the latest Artifact. 
image

**Comment by davids5** [comment]
@vincentpoont2 - Thanks to @dagar the ICM42670 is now working. Please re-test. I will finish the HW validation and this will be good to come in.

**Comment by vincentpoont2** [comment]
> @vincentpoont2 - Thanks to @dagar the ICM42670 is now working. Please re-test. I will finish the HW validation and this will be good to come in.

Great. Will test and report back.

**Comment by vincentpoont2** [comment]
@davids5 Tested calibration and flight, everything was normal. 
https://logs.px4.io/plot_app?log=f44be906-d7d5-45fd-ad53-d2cfbb21da63

**Review by vincentpoont2 — APPROVED** [review]
Tested working.

**Review by dagar — APPROVED** [review]

**Pull request merged**
