### PR TITLE
boards: add support for Matek H743 Slim V3 (ICM42688P IMUs)

### PR DESCRIPTION
**Pull request by korigod**
### Summary
IMUs were replaced in V3 revision of Matek H743 Slim with 2x ICM42688P, the same way as in Mini V3 (#21926). The proposed configuration should work with all revisions of Matek H743 Slim board, was tested on V3.

### Changelog Entry
For release notes:
```
Matek H743 Slim: add support for V3 board
```

### CODE REVIEW

**Review by dagar — APPROVED** [review]
This seems fine, I just wish there was a way to deal with the versioning explicitly instead of playing games trying to start sensors and see what sticks.

**Comment by korigod** [comment]
> This seems fine, I just wish there was a way to deal with the versioning explicitly instead of playing games trying to start sensors and see what sticks.

I agree. In case of these Matek boards the only way to determine which version is it, as I understand, is to poll the sensors anyway.

I saw DS-019, the idea with voltage divider is nice, but the number space is so small, and adding not only the divider but also an EEPROM is extra money and space. Some MCUs have OTP memory, it would be natural to store the revision info there, however H74x indeed doesn't have it and it's quite MCU-specific. Any option to store the revision is much better than not having it at all, of course.

**Comment by svpcom** [comment]
@korigod Hi, I have a strange issue with H743 Slim v3 -- first two pwm outputs (S1 and S2) works, but S3 and S4 - doesn't. With px4 firmware then doesn't output signal to esc. With ardupilot all works fine. Do you have similar experience with this board?

**Comment by svpcom** [comment]
Behavior is the same with both dshot and pwm:

```
nsh> dshot status
INFO  [dshot] Outputs initialized: yes
INFO  [dshot] Outputs used: 0x3f
INFO  [dshot] Outputs on: yes
dshot: cycle: 145327 events, 2373029us elapsed, 16.33us avg, min 15us max 91us 0.890us rms
INFO  [mixer_module] Param prefix: PWM_MAIN
control latency: 145330 events, 21650292us elapsed, 148.97us avg, min 142us max 287us 3.104us rms
INFO  [mixer_module] Switched to rate_ctrl work queue
Channel Configuration:
Channel 0: func: 101, value: 0, failsafe: 0, disarmed: 0, min: 109, max: 1999
Channel 1: func: 102, value: 0, failsafe: 0, disarmed: 0, min: 109, max: 1999
Channel 2: func: 103, value: 0, failsafe: 0, disarmed: 0, min: 109, max: 1999
Channel 3: func: 104, value: 0, failsafe: 0, disarmed: 0, min: 109, max: 1999
Channel 4: func:   0, value: 0, failsafe: 0, disarmed: 0, min: 109, max: 1999
Channel 5: func:   0, value: 0, failsafe: 0, disarmed: 0, min: 109, max: 1999
Channel 6: func:   0, value: 0, failsafe: 0, disarmed: 0, min: 109, max: 1999
Channel 7: func:   0, value: 0, failsafe: 0, disarmed: 0, min: 109, max: 1999
Channel 8: func:   0, value: 0, failsafe: 0, disarmed: 0, min: 109, max: 1999
Channel 9: func:   0, value: 0, failsafe: 0, disarmed: 0, min: 109, max: 1999
Channel 10: func:   0, value: 0, failsafe: 0, disarmed: 0, min: 109, max: 1999
Channel 11: func:   0, value: 0, failsafe: 0, disarmed: 0, min: 109, max: 1999
nsh> 
```

**Pull request merged**
