### PR TITLE
WIP NXP Backports to release/1.14 

### PR DESCRIPTION
**Pull request by davids5**
This is a WIP of backporting  the 1170 to  release/1.14

### CODE REVIEW

**Comment by davids5** [comment]
@wating on https://github.com/PX4/PX4-Autopilot/pull/23021

**Comment by davids5** [comment]
@dk7xe Please Fly this and compare to main

**Comment by davids5** [comment]
@dagar is there a way to get this through full CI and the test HW platform?

**Comment by dk7xe** [comment]
@davids5 i have just build the current main as well as pr-bp-release/1.14 for px4_fmu-v6xrt_default target.
With some luck i can test today still, otherwise it will be Monday.

**Comment by dk7xe** [comment]
@davids5 did 4 tests with one of our testdrones

**Log(s)**

Test1 - https://logs.px4.io/plot_app?log=9feca61c-ceda-4914-8633-cbf27bfe8ac8
Test2 - https://review.px4.io/plot_app?log=b356d0e3-7d58-4f35-9334-f2908640f6a8
Test3 - https://review.px4.io/plot_app?log=e2eab954-512a-4870-ae06-2ae4b6123751
Test4 - https://review.px4.io/plot_app?log=553ad471-8929-448a-867c-7e48f75046d2

**Observations**
Critical - At Test2 LPwork low stack warning. At test4 hardfault due to Lpwork resulting in crash.
Critical - High vibrations during all flights, switch to 3 blade props needed
Critical - avionics power low error constantly. Measurement seems to be too low. Workaround by setting CBRK. Was ok before on same HW with PX4 main
USB connection is very unreliable. Lost-regained-lost-regained 

Testdrone is a Holybro S500 frame with T-Motor MN3110-26 470kv and (lousy) 12" Props. 5S battery, UWB board connected to GPS2 port. Ethernet port connected via T1ADAPT to NavQplus T1 port. 433MHz telemetry on TELEM1, KW45 BT radio on TELEM2. FETtec 4in1 45A ESC connected to AUX1-4 running DShot600.
[ID18_Pixhawk6X-RT_PX4-1v14_20240506_param.zip](https://github.com/PX4/PX4-Autopilot/files/15226240/ID18_Pixhawk6X-RT_PX4-1v14_20240506_param.zip)

**Comment by dk7xe** [comment]
@davids5 all PR's related to 6X-RT bugfixes from https://github.com/PX4/PX4-Autopilot/pulls?page=1&q=author%3APetervdPerk-NXP from Oct 2023 onwards that were merged should be included. and maybe also some open ones.
@PetervdPerk-NXP any suggestions?

On LPSTACK: we are running our own custom PX4 version based on PX4 main from 8dae9905aa4ac294dca9eead9459cfddb9094072 with PX4_STACK_ADJUSTED(12000),

**Comment by dk7xe** [comment]
Agree. How to deal with the lpstack issue? May you increase it? I'm at the rc- model  airfield. Prepared for testing right away.

**Comment by davids5** [comment]
I think the low stack message may be a redherring. The error I saw was unexpected isr. It is in `imxrt_txpoll` in the Ethernet driver. 
@PetervdPerk-NXP - Does this ring a bell?

**Comment by davids5** [comment]
Closing in favor of 1.15 - but 1.15 will need some commits.

[33d6453](https://github.com/PX4/PX4-Autopilot/pull/23071/commits/33d6453d7fdc0a7218cb5e34c4b42b9ea34c3a9f)
[42e2e0c](https://github.com/PX4/PX4-Autopilot/pull/23071/commits/42e2e0cd0ac08e4c9313003f6020990ef83ae2bf)
[ba18b09](https://github.com/PX4/PX4-Autopilot/pull/23071/commits/ba18b09b1e763cdf1187b9d7a0e504d01caefb55)

and I2C launcher

**Pull request closed without merging**
