### PR TITLE
VTOL: Add options for spoiler and flaps during backtransition

### PR DESCRIPTION
**Pull request by sfuhrer**
Requires https://github.com/PX4/PX4-Autopilot/pull/19329

Deploy flaps and/or spoilers during a backtransition for some extra breaking and aerodynamic stability. Was originally part of https://github.com/PX4/PX4-Autopilot/pull/19329, but needs first proof that it actually has a significant effect on transition time most of all.

### CODE REVIEW

**Comment by ThomasRigi** [comment]
Hi @sfuhrer is this PR functionally ready to be tested ? I know it's outdated, but I think I was able to port it just fine to v1.13. It's something I'm very keen on testing if we can limit the gained altitude during BT with spoilerons. Our drone climbs way too much during back transitions and for now we don't have ESCs that are capable of reverse thrust (we want to change ESCs for the next iteration). So adding spoilerons to dissipate energy is our "easiest best guess".

**Comment by sfuhrer** [comment]
> Hi @sfuhrer is this PR functionally ready to be tested ? I know it's outdated, but I think I was able to port it just fine to v1.13. It's something I'm very keen on testing if we can limit the gained altitude during BT with spoilerons. Our drone climbs way too much during back transitions and for now we don't have ESCs that are capable of reverse thrust (we want to change ESCs for the next iteration). So adding spoilerons to dissipate energy is our "easiest best guess".

Very outdated yeah, and actually most of what this PR is about is already in by now. The extra things required to have spoilers during transitions is though very light weight, so should be easy to adapt to the latest firmware and test. 
Very curious for the outcome - tbh I don't expect too much of a difference, unless you have huge deflections.. but would be cool if you can prove otherwise! In which case we can totally revive this PR and bring it in.

**Comment by sfuhrer** [comment]
@ThomasRigi did you get to test this? Do you find it useful? I'm not that sure anymore, the breaking effect resp. the less-lift-affect we got out of using ailerons as spoilers were very low, and very few VTOLs have dedicated spoilers.

**Comment by ThomasRigi** [comment]
I did test it, and we kept it in our branch because it doesn't hurt to have it, but yeah the effects weren't very noticeable on our drone... 

https://github.com/PX4/PX4-Autopilot/pull/21135 gave us a more significant improvement.

**Comment by sfuhrer** [comment]
Okay closing this then, as it in the long term hurts maintainability to have lots of these low effect features in the code base.

**Pull request closed without merging**
