### PR TITLE
Remove include <log.h> from defines.h

### PR DESCRIPTION
**Pull request by pussuw**
## Describe problem solved by this pull request
The reason for this is that log.h includes drv_hrt.h which sucks in half the project's include files with it, which causes strange build issues

## Describe your solution
Limit the scope that is sucked in by defines.h

## Describe possible alternatives
Leave it as is, and try to fix the circular inclusion issues case-by-case

## Test data / coverage
fmuv5, CI

## Additional context
I'll put this on offer here and utilize upstream CI to see if there are still files that do not compile. If this change is deemed unnecessary / breaking I'll abandon it.

### CODE REVIEW

**Comment by dagar** [comment]
Did you see the CI failures?

Screenshot from 2022-09-23 09-25-34

**Comment by pussuw** [comment]
> Did you see the CI failures?
> 
> Screenshot from 2022-09-23 09-25-34

Thanks, yes I fixed a few of them, I'll fix the rest next week. It's quite hard for me to build all the targets locally, so I need to use CI to tell me what's broken.

**Comment by dagar** [comment]
> Thanks, yes I fixed a few of them, I'll fix the rest next week. It's quite hard for me to build all the targets locally, so I need to use CI to tell me what's broken.

Not a problem, it's there to be abused.

**Comment by pussuw** [comment]
I think the build errors caused byt this PR are now fixed. There seems to be some persistent build error with fmuv5:
../../platforms/common/uORB/uORBManager.cpp: In static member function 'static int uORB::Manager::orb_ioctl(unsigned int, long unsigned int)':
../../platforms/common/uORB/uORBManager.cpp:123:85: error: cannot call member function 'int uORB::Manager::orb_exists(const orb_metadata*, int)' without object
  123 |     data->ret = uORB::Manager::orb_exists(get_orb_meta(data->orb_id), data->instance);

This does not occur locally for me.

**Comment by pussuw** [comment]
Regression by:
https://github.com/PX4/PX4-Autopilot/pull/20274

The prototype was changed from static to non-static:
	static int  orb_exists(const struct orb_metadata *meta, int instance);
	int  orb_exists(const struct orb_metadata *meta, int instance);

For me the reason for this is not immediately obvious from the PR, so I don't really know how it should be fixed.

**Review by bkueng — APPROVED** [review]

**Pull request merged**
