### PR TITLE
add XRCE DDS client

### PR DESCRIPTION
**Pull request by bkueng**
This adds [eProsima's XRCE DDS bridge](https://github.com/eProsima/Micro-XRCE-DDS-Client) in order to bridge uORB to DDS.

#### Notes
- on stm32f7 with 58KB/s TX rate, the CPU load is 4.5%. Seems quite high.
- some of the microRTPS build infra is re-used (urtps_bridge_topics.yaml), which will need some cleanup.
- during testing I experienced an uncaught exception in the agent (terminate called after throwing an instance of 'eprosima::fastcdr::exception::NotEnoughMemoryException').
- when running via serial: pinging the agent after an FMU reboot does not work reliably
- I also did not see a reliable way to re-init the client when the agent restarts

#### Serialization
CDR serialization code is directly generated from .msg files and templates instead of using [XRCE-DDS Gen](https://github.com/eProsima/Micro-XRCE-DDS-Gen). This has some advantages:
- Reduced flash overhead: e.g. for vehicle_odometry, Micro-XRCE-DDS-Gen adds 1.4KB flash whereas in this PR, the extra flash for the serialization method is 400B.
- Reduced build dependencies (no java and gradle required) and complexity
- Faster build

The only caveat is that the `ucdrBuffer` is accessed directly (somewhat internal API).

#### Tested
- both publishing and receiving topics
- sitl via UDP
- v5x via UDP
- v5 via serial
- tested against recent master of [Micro-XRCE-DDS-Agent](https://github.com/eProsima/Micro-XRCE-DDS-Agent), and [micro-ROS-Agent](https://github.com/micro-ROS/micro-ROS-Agent)

#### TODO
- [x] support nested topics
- [ ] instead of using xml to setup the agent, use the binary interface

Overall I'm not yet convinced [to go with XRCE](https://docs.google.com/document/d/1-tnmt9owBEzkdMhAysgvroKxV4RPT2JiaR2xIm7DSiU/edit#), but with this it's in a state where we can test it further.

@spiderkeys @pablogs9

### CODE REVIEW

**Comment by spiderkeys** [comment]
Trying to figure out how to get this built, but am running into an issue around what seems to be an improperly generated expected size for a static assertion check for certain message types:
```
PX4-Autopilot/build/matek_h743-slim_default/uORB/ucdr/vehicle_trajectory_waypoint.h:28:40: error: static assertion failed: size mismatch
   28 |  static_assert(sizeof(topic.waypoints) == 0, "size mismatch");
      |                ~~~~~~~~~~~~~~~~~~~~~~~~^~~~
```
The uORB input generated code for `vehicle_trajectory_waypoint_s` is:
```c++
	uint64_t timestamp;
	uint8_t type;
	uint8_t _padding0[7]; // required for logger
	struct trajectory_waypoint_s waypoints[5];
```
Whereas the generated ucdr code has a size of 0 for the waypoints field:
```c++
bool ucdr_serialize_vehicle_trajectory_waypoint(const vehicle_trajectory_waypoint_s& topic, ucdrBuffer& buf)
{
	if (ucdr_buffer_remaining(&buf) < 9) {
		return false;
	}
	static_assert(sizeof(topic.timestamp) == 8, "size mismatch");
	memcpy(buf.iterator, &topic.timestamp, sizeof(topic.timestamp));
	buf.iterator += sizeof(topic.timestamp);
	buf.offset += sizeof(topic.timestamp);
	static_assert(sizeof(topic.type) == 1, "size mismatch");
	memcpy(buf.iterator, &topic.type, sizeof(topic.type));
	buf.iterator += sizeof(topic.type);
	buf.offset += sizeof(topic.type);
	static_assert(sizeof(topic.waypoints) == 0, "size mismatch");
	memcpy(buf.iterator, &topic.waypoints, sizeof(topic.waypoints));
	buf.iterator += sizeof(topic.waypoints);
	buf.offset += sizeof(topic.waypoints);
	return true;
}
```
Looking at `actuator_outputs`, which also has an array field, the size values are correct (output = 16*4 = 64), so I'm wondering if  the difference is that the field in the trajectory message is a struct array, rather than a primitive array.
https://github.com/PX4/PX4-Autopilot/blob/317b56c1d26792606281c9814086dea3545038da/msg/templates/ucdr/msg.h.em#L85

**Comment by spiderkeys** [comment]
Got things replicated on my side using the Matek H743 Wing. Seeing 2% CPU usage on this board.

Configured the serial link to run at 1MBaud (required minor tweak to allowed bauds in microdds_client).
```
 712 microdds_client               144  2.099  6684/ 7904  96 ( 96)  READY  5

Processes: 30 total, 5 running, 25 sleeping
CPU usage: 24.80% tasks, 0.71% sched, 74.48% idle
DMA Memory: 5120 total, 1024 used 1536 peak
Uptime: 73.551s total, 56.700s idle
nsh> microdds_client status
INFO  [microdds_client] Running, connected
INFO  [microdds_client] Payload tx: 25868 B/s
INFO  [microdds_client] Payload rx: 0 B/s
```
Topics are showing up as expected in RTI Admin Console (and using only single Participant/Pub/Sub entities, which is good):
Screenshot from 2022-03-14 10-48-29

**Comment by spiderkeys** [comment]
On the DDS/ROS2 side of things, users ultimately need to convert the .msg files to .idl files via `rosidl_adapter`. There is a convenient script for this:
```sh
ros2 run rosidl_adapter msg2idl.py px4/msg
```
However, there are two issues with the current formatting of the message files:
1. ROS2 requires that the filenames conform to upper camel case
2. Once this is done, the references to nested types in the messages (like trajectory_waypoint waypoints[5]) need to be updated to match the same upper camel case.

I wrote a quick python script that does the first step and manually corrected the 4-5 cases of nested type usage, which satisfied `rosidl_adapter msg2idl.py`

From there, I can now use the IDL type definitions in both pure DDS or ROS2.

**Comment by spiderkeys** [comment]
Unfortunately, there seems to be some kind of delta between the CDR representation of the type being published by the MicroXRCEAgent on behalf of the client, as neither RTI Admin Console, nor example code generated via fastrtps-gen are able to match their datareaders with the type published by the agent:

Screenshot from 2022-03-14 12-12-41

**Comment by spiderkeys** [comment]
Unfortunately, even after the above changes, the types are still mismatching. I've taken steps to ensure that the type names, module names, and CDR fields are matching on both sides, but there still seems to be some delta.

@bkueng as part of your testing, did you validate ROS2/DDS-side communications to the Agent? If so, can you share your steps?

**Comment by spiderkeys** [comment]
Found the issue: when using topic references in the client (via XML as an example followed by this branch), the agent must have full type descriptions available in a reference file on the other side:
https://micro-xrce-dds.docs.eprosima.com/en/latest/agent.html#creation-mode-agent

This makes the full typecode/typeobject information available to the XRCE Agent, such that it can properly match with other DDS/ROS2 processes.

**Comment by spiderkeys** [comment]
I've now confirmed communication on the DDS side with both FastDDS and CycloneDDS. ConnextDDS is reporting that it is successfully matching, but samples don't seem to get delivered from XRCE Agent when requested by a Connext Datareader. Not sure what is going on here yet. Maybe XCDR vs XCDR2 settings.

**Comment by bkueng** [comment]
Thanks for checking @pablogs9.

> In fact, by using this approach you are not taking into account the alignment requirements of the CDR standard and you are not using the fragmentation mechanisms provided by Micro XRCE-DDS.

Alignment is considered, and the message size is below the MTU, or rather I used the best-effort streams, and we're only using little-endian systems, thus I don't see a problem here. Can you be specific what you think is problematic?

> In order to avoid 'eprosima::fastcdr::exception::NotEnoughMemoryException' you will need to add <historyMemoryPolicy>PREALLOCATED_WITH_REALLOC</historyMemoryPolicy> to the Datawriter XML. You can find more details [here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/eprosimaExtensions.html#memorymanagementpolicy).

My concern here is reliability: if some (corrupt) data can cause an uncaught exception (crash), it is a problem.

> In order to use the ping functionality to ensure reconnection you will need to use uxr_ping_agent() when there is no established session and uxr_ping_agent_session() when you have an already available session. We can provide examples here if you need.

`uxr_ping_agent_session` is a blocking call, is there a method to continue sending data?

**Comment by pablogs9** [comment]
> Alignment is considered, and the message size is below the MTU, or rather I used the best-effort streams, and we're only using little-endian systems, thus I don't see a problem here. Can you be specific what you think is problematic?

Not sure if your [alignment calculation](https://github.com/PX4/PX4-Autopilot/pull/19326/files#diff-725f5431e8bc2939bfb6657c9b32e85e0b481117713510cd38821c0f2a705cadR33) is taking into account the CDR standard, check [Micro CDR](https://github.com/eProsima/Micro-CDR/blob/1c712a08cf5571af0435bf1d881075e813c09513/src/c/common.c#L183) or [Fast CDR](https://github.com/eProsima/Fast-CDR/blob/0b5efc087877804ec3075ef2310d4aadda39e88b/include/fastcdr/Cdr.h#L3492)

> My concern here is reliability: if some (corrupt) data can cause an uncaught exception (crash), it is a problem.

Corrupt data should not raise any uncaught exception that ends in a crash, but if you detect any case where it happens we will fix it ASAP.

> uxr_ping_agent_session is a blocking call, is there a method to continue sending data?

There is not an active API for doing ping in a non-blocking manner. A workaround can be: `uxr_ping_agent_session(&session, 0, 1);` and then check `session->on_pong_flag != NO_PONG_STATUS;`. In any case, we are completely open to extending our APIs to your need and maybe creating a `uxr_ping_agent_check_status()` or even a callback approach, let's discuss this.

**Comment by pablogs9** [comment]
Possible fix for Fast DDS & RTI Connext issue here: https://github.com/eProsima/Fast-DDS/pull/2580

Once it is merged we will update the Micro XRCE-DDS Agent

**Comment by bkueng** [comment]
> But, maybe as mentioned https://github.com/eProsima/Micro-XRCE-DDS-Agent/issues/307 if XCDR2 is expected, the max alignment is 4 B instead of 8 B ([page 148 OMG standard](https://www.omg.org/spec/DDS-XTypes/1.3/PDF))v

Noted.

> There is not an active API for doing ping in a non-blocking manner. A workaround can be: uxr_ping_agent_session(&session, 0, 1); and then check session->on_pong_flag != NO_PONG_STATUS;. In any case, we are completely open to extending our APIs to your need and maybe creating a uxr_ping_agent_check_status() or even a callback approach, let's discuss this.

Ok, I'm directly checking for `check session->on_pong_flag` for now, which is working. Ideally there would be an API to detect an agent restart, as a quick agent restart could be missed using a ping.

**Comment by pablogs9** [comment]
> Noted.

According to what we have been talked [here](https://github.com/eProsima/Micro-XRCE-DDS-Agent/issues/307) there should not be any alignment error in your implementation. Probably the issue cames from https://github.com/eProsima/Fast-DDS/pull/2580

> Ok, I'm directly checking for check session->on_pong_flag for now, which is working. Ideally there would be an API to detect an agent restart, as a quick agent restart could be missed using a ping.

Let us know which kind of API would fit your requirements and we will make a proposal.

**Comment by bkueng** [comment]
This is getting ready to merge (I can change from xml to binary later, mostly a flash optimization).

> Let us know which kind of API would fit your requirements and we will make a proposal.

I just realized I can also check for `PONG_IN_SESSION_STATUS`, so explicitly exposing the pong result would be enough (`pong_status_t uxr_latest_pong_status(uxrSession* session)`).

**Pull request merged**
