### PR TITLE
Remove relaying of maximum altitude through land detector

### PR DESCRIPTION
**Pull request by MaEtUgR**
**Describe problem solved by this pull request**
After https://github.com/PX4/PX4-Autopilot/pull/15020 the land detector is just copying the maximum altitude parameter to the uORB message and publishing it regularly with the `vehicle_land_detected` topic.

**Describe your solution**
I'm using the parameter directly in the two places that access it namely the multicopter position controller and the mission block in navigator. This is just one iteration and the parameter should probably be consolidated with `GF_MAX_VER_DIST` like it's description writes.

**Test data / coverage**
I did not test this yet.

### CODE REVIEW

**Review by ThomasDebrunner — DISMISSED** [review]

**Comment by ThomasDebrunner** [comment]
Will do some testing

**Comment by ThomasDebrunner** [comment]
Tested in SITL, all seems to behave the same as before.

**Comment by dagar** [comment]
Move `LNDMC_ALT_MAX` out of the land detector and migrate the parameter if you think anyone was actually using it?

**Comment by MaEtUgR** [comment]
> Move LNDMC_ALT_MAX out of the land detector and migrate the parameter if you think anyone was actually using it?

I'd do that when we revamp geofence because it fits there. So this step is just to simplify things a bit and then I'd move the logic to have a geofence ceiling. There are probably only very few users right now.

**Pull request merged**
