### PR TITLE
New target mamba f405 mk2

### PR DESCRIPTION
**Pull request by taileron**
**Describe problem solved by this pull request**
two tries to start i2c mpu9250 now seem to work perfectly
flies now perfect even with gps and wifi telemetry

### CODE REVIEW

**Comment by taileron** [comment]
adapted folder structure diatone_mamba-f405-mk2

can the names in board.h and firmware.prototype be changed without further side effects?

**Comment by taileron** [comment]
flight tests again successful (stab, acro, alt, pos, rtl)

**Review by dagar — DISMISSED** [review]

**Comment by taileron** [comment]
Still flies perfectly with today's Master, but with the following #18625 limitations that have nothing to do with the Target.
The pass through mode of the MPU9250 still needs some sleeps in the sensor-init, which I will remove by an additional query. As soon as a HMC5883 is found, the MPU9250/AK8963 with it´s delays can be simply not started.

**Review by dagar — APPROVED** [review]

**Comment by dagar** [comment]
> how can I delete that based branch ... to reduce confusion :-)

I'm not following, can you point me at what you're talking about?

**Comment by taileron** [comment]
it´s more a github issue, I only want to get managed to delete the New-Target-Mamba-F405-MK2 branch cause the best variant is merged now.

**Pull request merged**
