### PR TITLE
Msg docs

### PR DESCRIPTION
**Pull request by hamishwillee**
This PR allows auto generation of docs for Uorb - graphs and messages.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@TSC21 This generates basic UORB docs (@bkueng did the framework and I have added a parser). The first non-empty comment line at the top of the message, if present, becomes the message description.
Pages render with the message title, description, source link, and content of the message. It looks like this:

image

A README top level is also generated, which lists the messages in alphabetic order, along with the message description if one exists. It looks like this:
image

Any suggestions/are you OK with this? E.g. are the headings OK etc etc.

If you want a richer syntax for markup as suggested by Beat in this [discussion with ROS here](https://discourse.ros.org/t/structured-metadata-for-message-files/20965), that can be done, but you'll need to specify what you want.

**Comment by dagar** [comment]
The top level Jenkins (ci.px4.io) is currently down, do you want to move this to GitHub Actions?

**Comment by bkueng** [comment]
@dagar do you have an ETA when it's back? Or should we just move it right away?

**Comment by dagar** [comment]
> @dagar do you have an ETA when it's back? Or should we just move it right away?

It's back now. http://ci.px4.io/blue/organizations/jenkins/pipelines

**Comment by junwoo091400** [comment]
Amazing!

**Pull request merged**
