### PR TITLE
vfr_hud: fix throttle display for FW

### PR DESCRIPTION
**Pull request by sfuhrer**
### Solved Problem
https://discord.com/channels/1022170275984457759/1022186266957201480/1156786412729933824

### Solution
Also check thrust in x for FW.

### Changelog Entry
For release notes:
```
Bugfix: Fix  throttle display in VFR_HUD mavlink message
```

Has to be ported to 1.14.

### CODE REVIEW

**Review by tstastny — COMMENTED** [review]
Wait so we dont actually know which value is currently being commanded? this is just taking the max of three different possibilities? where is it blended for VTOL? is there a final throttle message published somewhere that would be a better thing to subscribe to here?

**Comment by ryanjAA** [comment]
👍👍

**Comment by sfuhrer** [comment]
>Wait so we dont actually know which value is currently being commanded? this is just taking the max of three different possibilities? where is it blended for VTOL? is there a final throttle message published somewhere that would be a better thing to subscribe to here?

For VTOL the max() only has en effect in the transition phase. If you like it more I can also do a if(FW) vs if (MC).

>final throttle message published somewhere that would be a better thing to subscribe to here?

There is no "throttle" message, no. It's 3D thrust, which is duplicated for VTOL.

**Comment by tstastny** [comment]
> For VTOL the max() only has en effect in the transition phase. If you like it more I can also do a if(FW) vs if (MC).

i guess it's been this way for some time with the max. your call.

**Comment by sfuhrer** [comment]
@tstastny I've changed it and now calculate the magnitude of the 3D thrust setpoints. For VTOL the logic stays the same in that the larger of MC thrust or FW thrust is displayed.

**Review by tstastny — APPROVED** [review]
ok

**Comment by ryanjAA** [comment]
Tested in sitl.  👍

**Pull request merged**
