### PR TITLE
Add typhoon h480 support to gazebo multiple sim

### PR DESCRIPTION
**Pull request by bbworld1**
This commit adds support for the typhoon_h480 model for the gazebo_sitl_multiple_run.sh script. This will allow multiple typhoon_h480 models to run in the simulator at the same time.

Literally just adds typhoon_h480 to SUPPORTED_MODELS.

Depends on [this sitl_gazebo PR](https://github.com/PX4/PX4-SITL_gazebo/pull/655) being merged.

### CODE REVIEW

**Review by Jaeyoung-Lim — CHANGES_REQUESTED** [review]
Could you maybe rebase and include the latest master of sitl_gazebo?

**Comment by bbworld1** [comment]
Done.

**Comment by bbworld1** [comment]
apologies, didn't update sitl_gazebo submodule. **now** it should work.

**Review by Jaeyoung-Lim — APPROVED** [review]
Thanks!

**Comment by mzahana** [comment]
Hi @bbworld1  @Jaeyoung-Lim 

Can this work with ROS? i.e. using
```
roslaunch px4 multi_uav_mavros_sitl_sdf.launch vehicle:=typhoon_h480
```

I am not able to check this with `v1.11.2` because I am not able to successfully compile `v1.11.2` in the first place, but just wanted to confirm if it works with ROS too.

Thanks

**Comment by Jaeyoung-Lim** [comment]
@mzahana Probably not with sitl_sdf.launch but it was enabled with https://github.com/PX4/PX4-Autopilot/pull/15938/files

**Comment by mzahana** [comment]
@Jaeyoung-Lim  Thanks, but it does not seem to be available for `v1.11.2`, no?

**Comment by Jaeyoung-Lim** [comment]
@mzahana Have you checked if it is included?

**Comment by mzahana** [comment]
@Jaeyoung-Lim  I checked and 
* the changes in `single_vehicle_spawn.launch `  https://github.com/PX4/PX4-Autopilot/pull/15938 are not available in px4 `v1.11.2` although it was before the release time
* the changes in the typhoon jinja model (https://github.com/PX4/PX4-SITL_gazebo/pull/655) are not available in px4 `v1.11.2`, since it was done after the release
* the changes in  `jinja_gen.py` in `sitl_gazebo` (https://github.com/PX4/PX4-SITL_gazebo/pull/634) are also not in px4 `v1.11.2`  although it was before the release time

I also adapted all the above changes to px4 `v1.10.1`. It worked fine with the iris jinja model, but when I try with the typhoon model, they run in Gazebo except that the gimbals rotate crazily; I tried to debug, but and I am still not sure why.

**Comment by Jaeyoung-Lim** [comment]
@mzahana Okay, then probably post a separate issue, since it is unrelated to this PR

It doesn't matter the date that it was commited, since release are not simply took from the master on that date.

**Pull request merged**
