### PR TITLE
[DO NOT MERGE] CI SITL lockstep debug (work queue lockstep component)

### PR DESCRIPTION
**Pull request by dagar**
### CI history
1. 4/4 SITL Tests Passed
2. 4/4 SITL Tests Passed
3. 4/4 SITL Tests Passed
4. 4/4 SITL Tests Passed
5. 2/4 SITL Tests Passed (very first tests failed, mavsdk or mavlink starved? `[mavlink] Operation timeout`)
    - https://github.com/PX4/PX4-Autopilot/pull/16479/checks?check_run_id=1640689991
    - https://github.com/PX4/PX4-Autopilot/pull/16479/checks?check_run_id=1640690002
6. 4/4 SITL Tests Passed
7. 4/4 SITL Tests Passed
8. 4/4 SITL Tests Passed
9. 3/4 SITL Tests Passed (very first test failed, mavsdk or mavlink starved? `[mavlink] Operation timeout`)
    - https://github.com/PX4/PX4-Autopilot/pull/16479/checks?check_run_id=1640860035
10. 4/4 SITL Tests Passed
11. running...

### CODE REVIEW

**Comment by dagar** [comment]
Not perfect, but this appears to drastically lower the failure rate.

**Comment by LorenzMeier** [comment]
Same here: 
Screen Shot 2021-01-03 at 22 59 18

State is:

- PX4 SITL responsive
- Gazebo completely paused, but UI reponsive
- None of the Gazebo-side instrumentation has triggered (which is odd - we should at least be getting a timeout error on that side)

**Comment by LorenzMeier** [comment]
I'm seeing that Gazebo SITL can get into an endless loop in ```void MavlinkInterface::pollForMAVLinkMessages()``` - I'm testing a dirty fix to verify, then it's time to clean up that function. It looks architecturally wrong to me.

**Comment by LorenzMeier** [comment]
More test data: in the remaining corner case the simulation get's stuck on waiting for autopilot output: 
Screen Shot 2021-01-04 at 11 49 51

**Comment by dagar** [comment]
Still more to do here, but closing the debugging PR.

**Pull request closed without merging**
